### ISSUE TITLE
Default theme - back of cards should not be totally white 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1001]
When the name-less theme is selected, the back of the card is white, so when it turns over, there is nothing to be seen. Should have some sort of outline or shading, so that the bacm of the card can be seen.

![image](https://user-images.githubusercontent.com/16290361/116415635-e4ca5680-a839-11eb-9f13-245e510506ab.png)

**Comment by dakom** [comment]
to keep it consistent with all the other functionality, it should be a predefined image. 

assigning to @dani-ji though it's really an issue for Gali

**Comment by dakom** [comment]
Once the image is provided, feel free to re-assign to me for implementation
