### ISSUE TITLE
Block leaving step 1

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1008]
Should happen not just when hitting `done` but also when hitting `preview`, `continue`, and the other circle buttons

**Comment by dani-ji** [comment]
@dakom to confirm this would apply to other to steps as well, ie user cannot jump step 1 to 3 unless they've already completed 2, correct?

**Comment by dakom** [comment]
That's a [different issue](https://github.com/ji-devs/ji-cloud/issues/1007)

Here it's not really about skipping steps, but rather, that leaving step 1 is blocked in numerous ways (e.g. the preview button too)

**Comment by dani-ji** [comment]
@dakom My apologies
