### ISSUE TITLE
(TBD) Signed URLS for Additional Resources

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1015]
additional resources are files that get uploaded directly to storage. They are associated with a jig

jigs would have something like `Vec<AdditionalResourceId>` or `Vec<Url>`

because we aren't implementing any security checks on this, we can increase the file size limit drastically and let the user upload files directly

the ux flow could be something like:

1. Get signed url for uploading
2. Upload to url
3. Call backend API to finalize and associate this url with the jig

**Comment by izik1** [comment]
Limit: 5 MiB
