### ISSUE TITLE
Google Sign In: Sign Up Step 1: Format "need to select" like "Can't be empty"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#1018]
**Describe the bug**
Error text for leaving blank field for "i am over 18" does not match style. It should match style for "Can't be empty" error text on the same page:
- red text
- sentence case (ie "Need" instead of "need")
- match font size ("need to select" looks like it might be larger than "Can't be empty")
- position left align under the field ?

**To Reproduce**
1. Go to Sign Up Step 1
2. Click on "Continue" button without clicking "i am over 18"
3. See error (black text instead of red)

**Expected behavior**
I expect the error text to be red.

**Screenshots**
![001_Google_SignUpStep1_RequiredFields](https://user-images.githubusercontent.com/74170693/117030957-22156500-acce-11eb-94b5-4d08b0def412.png)

**Additional context**
NA

**Comment by esteels** [comment]
"need to select" error text for "I have read..." checkbox on Sign Up Step 2 is similarly formatted to error text for leaving blank "I am over 18" check box. Both should be corrected as described above. 

(not sure how this works behind the scenes, but maybe there's a way to fix the formatting of error text for checkboxes in all instances instead of treating each of these as individual cases?)

![002_Google_SignUpStep2_RequiredFields](https://user-images.githubusercontent.com/74170693/117032624-a0263b80-accf-11eb-985b-b47bdad51d96.png)

**Comment by dakom** [comment]
Discussed with @corinnewo , current UI is fine
