### ISSUE TITLE
Google Sign In: Sign Up Step 3: match UI (layout and colors)

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#1022]
**Describe the bug**
The checklist for age groups does not look correct. Elements are not spaced properly and crowded. Please correct formatting.

**To Reproduce**
1. Go to Sign Up Step 3
2. See crowded checklist

**Expected behavior**
I expect the checklist for age groups to look less crowded/to have proper padding. 
See https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f6234ff1142517b9a42f468

**Screenshots**
![003_Google_SignUpStep3_Checklist](https://user-images.githubusercontent.com/74170693/117034645-8685f380-acd1-11eb-9544-a9fc12ae3082.png)

**Additional context**

**Comment by dakom** [comment]
Updated Zeplin, note it's vertical columns: https://zpl.io/2jqW5dO
