### ISSUE TITLE
Image Search Component - Filter by tag (internal)

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1032]
Need ability to add a Vec<TagId> to the component which is used to power internal filters

An example is when displaying backgrounds for Poster... if the user chose "Comics" at start, then we'll need to filter by those TagIds

This is being tracked in the flowcharts here: https://github.com/ji-devs/ji-cloud-flowcharts/issues/6

**Comment by dakom** [comment]
Once this is done, we need to supply it carefully based on each unique situation (see google doc)

**Comment by dakom** [comment]
This is currently blocked on https://github.com/ji-devs/ji-cloud/issues/1391
And non-optimal until https://github.com/ji-devs/ji-cloud/issues/1086

**Comment by MendyBerger** [comment]
@dakom is this resolved already?

**Comment by dakom** [comment]
Yes, I believe so... closing the issue
