### ISSUE TITLE
Create: My Recent JIGS: "You're not authorized" error

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#1042]
**Describe the bug**
I run into a "You're not authorized" error when I try to change any of the fields in the "My Recent JIGS" section of the page. See issue #1041 

**To Reproduce**
1. Go to Create landing page. Encounter initial error (see #1041) + click ok to view page.
2. Click in Search field OR click dropdown menu and change My Recent JIG settings.
3. See error "You're not authorized" notification

**Expected behavior**
I expect to be able to use the fields to search and change My Recent JIGs setting without getting an error. 

**Screenshots**
![021_Create_Create1_SearchNotAuthorized](https://user-images.githubusercontent.com/74170693/117602409-a2005c80-b11e-11eb-8d66-db090bfce023.png)

**Additional context**
NA.

**Comment by dani-ji** [comment]
added to #1041
