### ISSUE TITLE
WYSIWYG - blur callback

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1047]
Needed so the Transform knows when to hide/show the click layer

**Comment by dakom** [comment]
Actually - it's not really about the events... it's about having callbacks on the component level. Will update the title

**Comment by dakom** [comment]
Discussed on zoom - new plan:

1. state creation will accept an `on_blur` callback, and stash it for later use

2. internally, a blur event is caught. it does *not* call `on_blur` right away. Rather, it creates (and holds) a new `Timeout` which will fire that callback when the timeout ends. The timeout should be very low, a few milliseconds (this should be configurable as an easy-to-find `const`)

3. internally, certain things can cancel that `Timeout`. For now, we're thinking just adding one click event to the editor controls container will be enough. We may tweak this to improve UX later (e.g. in the case where they click between controls, should that _really_ cancel...)

Effectively this means that the outside is only notified of `blur` when it's _really_ blurred (i.e. they exited the wysiwyg widget completely), not when it was blurred for the sake of clicking an editor control.

**Comment by MendyBerger** [comment]
Ended up not doing the whole timer thing, I saw that the blur event has a `relatedTarget` property that points to the newly focused element, so I used that instead
