### ISSUE TITLE
anchored overlay should not have the overlay, should just be used for anchoring

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1051]
currently the anchored-overlay is doing 3 things:

1. showing the grey background full-screen
2. listening for click events on that background for dismissing the entire element
3. anchoring one element to another

we should have a stronger separation of concerns here, especially since in most cases where the elements are anchored the background isn't even shown. Suggestion:

1. Make this *only* about anchoring elements and listening for clicks outside those elements (if possible)
2. Separately, where we need the visual full-screen overlay (such as modals), have an element to do that

Note that there is currently a bunch of positioning logic in tooltip.ts and tooltip.rs ... we might want to separate that into generic positioning instead of "tooltips", but not for now, the use case here is for more specific things, i.e. where we don't need to re-position based on proximity to a container.

Once this change is made, perhaps it should be renamed to something like `anchored-container`

**Comment by MendyBerger** [comment]
Didn't end up renaming since the component still overlays, it just doesn't overlay the whole page
