### ISSUE TITLE
Refactor elements into primitives

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1052]
Our core elements are currently doing too much. For example - the text element has to re-dispatch change events.

Much better would be to have a set of primitives, which do not have any styling other than what's absolutely necessary, and then we slot these in to containers which add additional styling, html, etc.

Note that once we do this, we may be able to use third-party primitives instead of building our own. In some cases this probably worth it (i.e. `select`), in other cases it's probably not due to the native html being robust and simple enough (i.e. `text`) and in other cases we may not be able to rely on the third party to solve what we really need (i.e. `tooltips`)

Therefore, each primitive will need to be assessed on a case-by-case basis to decide whether we do it in-house, directly native, or use a third party.

Since we are using web components we should be able to use different third-parties if we really need to, but we should try to avoid that.

**Comment by MendyBerger** [comment]
This has been done to some extent, closing for now but feel free to reopen
