### ISSUE TITLE
Style of the jiggling text

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1060]
The style of the label for the jiggling texts needs to be tweaked:
![image](https://user-images.githubusercontent.com/16290361/117978403-1ced9100-b332-11eb-81f4-829c8b2f3081.png)

1. Rounded Corners
2. Space between end of text and the hyper link 'don't show again'
3. The space between the button and the bottom edge of the popup should be more like the zeplin
https://zpl.io/2ygrvGG 

Zeplin: 
![image](https://user-images.githubusercontent.com/16290361/117978632-6211c300-b332-11eb-8ef3-326c344d50e1.png)

**Comment by chayaml** [comment]
Still needs updating
![Screen Shot 2021-09-02 at 3 38 53 PM](https://user-images.githubusercontent.com/78186896/131905823-3a1e724b-2cb1-42bf-83fa-009924fe17c7.png)

**Comment by dakom** [comment]
Yes, the issue is still open :)

However, let's limit the scope of this issue to these inner content changes:

> Space between end of text and the hyper link 'don't show again'
> The space between the button and the bottom edge of the popup should be more like the zeplin
https://zpl.io/2ygrvGG

I've opened a separate issue for tooltips as a whole which will need much more work: https://github.com/ji-devs/ji-cloud/issues/1512
