### ISSUE TITLE
Create: Landing page: Layout for template buttons is crowded

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#1063]
**Describe the bug**
Display/layout of template buttons is crowded.

**To Reproduce**
1. Go to https://jicloud.org/jig/edit/gallery
2. Click on "See all templates" 
3. Scroll down to see vertical stack of templates
4. See crowded layout of template buttons

**Expected behavior**
I expect to be able to see 4 buttons in a horizontal row per Zeplin sketch:
https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/60535ee14215c73d9ca624c4 

**Screenshots**
![020_Create_Create1_ButtonSize](https://user-images.githubusercontent.com/74170693/118222448-a645b600-b44d-11eb-975e-021bcb774b2e.png)

**Additional context**
Possible issues include:
- "Create a New JIG" text too large
- buttons too large 
- My window too small? I'm viewing in a Macbook pro 13 inch though, and I don't think that's the case

**Comment by dani-ji** [comment]
@esteels this is due to your window size
