### ISSUE TITLE
Create: Landing Page: Correct filter appearance for "My Recent JIGS"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#1064]
**Describe the bug**
Filter appearance for "My Recent JIGS" does not match Zeplin sketch. 

**To Reproduce**
1. Go to https://jicloud.org/jig/edit/gallery
2. Click on filter dropdown menu, "Show all my JIGS"
3. See green check mark, which does not match visual from Zeplin: https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/60535ea1b721491b920f068f 

**Expected behavior**
I expect a blue check mark to indicate selected filter per Zeplin sketch: https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/60535ea1b721491b920f068f 

**Screenshots**
![022_Create_Create1_VisualSelect](https://user-images.githubusercontent.com/74170693/118223099-d477c580-b44e-11eb-8d5f-7705f3965636.png)

**Additional context**
NA

**Comment by MendyBerger** [comment]
Resolved in a572fb5494c736603ddc37575018e5df324e74e8
