### ISSUE TITLE
Create: Landing Page: Change Jigs to JIGS in filter dropdown menu

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#1065]
**Describe the bug**
One of the options for the filter dropdown menu says "Show published Jigs" instead of "Show published JIGS"

**To Reproduce**
1. Go to https://jicloud.org/jig/edit/gallery 
2. Click on filter dropdown menu
3. See error, "Show published Jigs" as second dropdown option.

**Expected behavior**
I expect Jigs to say JIGS

**Screenshots**
![022_Create_Create1_VisualSelect](https://user-images.githubusercontent.com/74170693/118223584-a0e96b00-b44f-11eb-87de-161627f36fd9.png)

**Additional context**
I'm mostly leaving text corrections for second pass of QA, but wanted to add this one as I follow up to issue #1064

**Comment by MendyBerger** [comment]
Resolved in 27a79198a53a2a70eebc0a9197b6464ba9289c3d
