### ISSUE TITLE
Add last edited to jig

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1066]

**Comment by rrcwang** [comment]
`Jig` metadata currently has an `updated_at` field. Is this similar to what you'd like or would this just be for jig drafts #898 ?

**Comment by MendyBerger** [comment]
In [this](https://github.com/ji-devs/ji-cloud/blob/sandbox/shared/rust/src/domain/jig.rs#L128)? Don't see `updated_at`

**Comment by rrcwang** [comment]
Ahh I was mistaken, you're absolutely right.
