### ISSUE TITLE
improve wysiwyg output renderer so that it matches wysiwyg editor

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1081]
There are some cases where it isn't quite matching. Specifically, adding a combination of color changes, size changes, and wrapping, causes an extra space between letters (not sure which of those is the culprit, but latest detective work says colors particularly mess things up)

**Comment by MendyBerger** [comment]
Fixed in 59964d361451d988e47eb46df7f244246a1114af
