### ISSUE TITLE
Jig 4-digit code mapping

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1083]
We need to create a mapping between a unique 4-digit numerical code, and unique jig ID's

Each unique mapping should expire after a certain amount of time (currently 2 weeks), after which point it may be recycled

The 4-digit numerical codes should be somewhat randomized

So on one foot, we need endpoints to:

1. Given a JigId, create a new JigCode
2. Given a JigCode, get a JigId (or fail)

**Comment by dakom** [comment]
There needs to be more metadata associated with this. So expanding on 1 and 2 it is more like the following (names are up to you @rrcwang , these are just hints to the intention):

1. Given JigPlayerSessionCreateRequest, create new JigPlayerSession in the db, return JigPlayerSessionResponse
2. Given a JigPlayerSessionGetRequest, return the associated JigPlayerSession for that given code

where:

JigPlayerCodeCreateRequest and JigPlayerSession contain:

* jig_id: JigId
* direction: [TextDirection](https://docs.sandbox.jicloud.org/crate/shared/domain/jig/enum.TextDirection.html)
* display_score: bool
* track_assessments: bool
* drag_assist: bool

JigPlayerSessionResponse and JigPlayerSessionGetRequest contain only the 4-digit code

**Comment by dakom** [comment]
Just to clarify a bit, the UX experience is that the teacher wants to share a jig but with settings which are really part of the player, not the jig itself.

To take an example it's kinda like sharing a youtube video with a given start time. Doesn't affect the video itself, just part of the shared url.

In this case we can't do it via a URL (the students all come to the same homepage and just enter their code), so we need to track this in the DB

**Comment by dakom** [comment]
@rrcwang - I updated the above to break `JigPlayerSettings` into it's own struct. This is needed to keep this in sync with https://github.com/ji-devs/ji-cloud/issues/1229

**Comment by rrcwang** [comment]
Resolved, see docs: https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/jig/player/index.html
