### ISSUE TITLE
text editor should accept a signal of ThemeId

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1090]
Currently, the text editor accepts a `ThemeId`, however the ThemeId for modules is often dynamic.

the editor does provides a method to imperatively change that, via `set_theme()`, but I think it's much cleaner if the state creation accepts a Signal of ThemeId and then handles the changes internally. Something like this could work (after adding `theme_id_reactor: AsyncLoader` to `State`):

I didn't want to add it myself because I'm not totally sure how the current `theme_id: Mutable<ThemeId>` is used everywhere and if this is enough to cover all the requirements properly:

```
impl State {
    pub fn new(theme_id_signal: impl Signal<Item = ThemeId>, value: Option<String>, callbacks: Callbacks) -> Rc<Self> {
        let theme_id_reactor = AsyncLoader::new();

        let _self = Rc::new(Self {
            theme_id_reactor,
            ...
        });

        _self.theme_id_reactor.load(theme_id_signal.for_each(clone!(_self => move |theme_id| {
            //nit - we have "ThemeChoice" and ThemeId, so set_theme_id() is a little more clear
            //than set_theme()
            _self.set_theme_id(theme_id);
            async {}
        })));

        _self

    }
}

```

**Comment by dakom** [comment]
Note - if you need the signal in multiple places, it will need to either create a Broadcaster or accept a function which generates a Signal. I think the function is simpler and cleaner, so it would be something like this (untested, might be syntax errors):

```
impl State {
    pub fn new<F, S>(get_theme_id_signal: F, value: Option<String>, callbacks: Callbacks) -> Rc<Self> 
    where
        F: Fn() -> S + Clone + 'static,
        S: Signal<Item = ThemeId> + 'static
    {
      // Get a signal
      let theme_id_signal = get_theme_id_signal();
      // Pass the generator function down somewhere else so it can be used
      let foo = FooState::new(get_theme_id_signal.clone());
    }
}
```

**Comment by MendyBerger** [comment]
I believe this was taken care of some time ago
