### ISSUE TITLE
Data on Jig not being saved

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1100]
Looks like updating Jig description and is_public is not actually being saved

**Comment by rrcwang** [comment]
Just fixed this in #1092. It's just been merged, trying pulling the latest `sandbox` commit

**Comment by MendyBerger** [comment]
Right, sorry for bothering you

**Comment by rrcwang** [comment]
Not a bother at all -- this was a bug and should've been done in the original commit #1075.
