### ISSUE TITLE
Existing text should respond to theme changes

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1108]
This requires an overhaul of how the WYSIWYG editor uses theme info. 

Currently, it renders the text and replaces styles based on the theme settings. This means that when the theme is changed, other text on the page (such as via the output renderer) is unaffected by the new theme.

Rather, changing the theme should affect all H1-P2 text, giving it the theme style. Suggestion to do that is as follows:

1. Inside of the text editor and output renderer components, these classes are defined (for all of H1-P2):

```
   .H1 {
    font-family: var(--h1-font-family);
    color: var(--h1-color);
   }

   .P2 {
    font-family: var(--h2-font-family);
    color: var(--h2-color);
   }
```

2. These CSS classes are also defined:
```
  .theme-happy-brush {
    --h1-font-family: HappyBrushFont
    --h1-color: orange
   }
   
   .theme-chalkboard {
     --h1-font-family: ChalkboardFont
     --h1-color: blue
   }
```

3. The output and editor renderer would do something like this:

```
html!("container", {
  .property_signal("theme", theme_id_signal)
})
```

4. Lastly, in order to do this, it means both renderers must take a `theme_id_signal: Signal<Item = ThemeId>`

**Comment by MendyBerger** [comment]
This has been done some time ago
