### ISSUE TITLE
Specify Jig Audio options

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1116]
Need the final list for:

* Background music
* Positive feedback
* Negative feedback

**Comment by corinnewo** [comment]
Hi david
I have asked Mitch for these sound files, but his father died this week so I I don’t have them yet. Should I give you some demo files in the meantime?

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dakom** [comment]
What we need is the list of all the options. The actual audio files can be supplied later.

If we don't know the options yet, then this issue needs to remain open until we do (and we can't implement the jig settings fully until then)

**Comment by corinnewo** [comment]
What do you mean ‘options’? File types? 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dakom** [comment]
The list of choices the user will have. Something like:

Background Music:

- Happy Loop 1
- Circus Music

Positive Audio Feedback
- Cheers
- Bells

Negative Audio Feedback
- Try Again
- Buzz

The audio files themselves can come later, but unless we know the exact list of options, we can't create all the data structures we need to implement the UI and database requirements.

**Comment by corinnewo** [comment]
So please give a choice of 5 positive, 5 negative and 5 backgrounds.  Thanks. Is this not going to be flexible at all?

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by corinnewo** [comment]
I have some music loops and sound effects from Mitch. I would like to put them into the JIG player. How to proceed?

**Comment by corinnewo** [comment]
I have put the sounds in the audio folder in dropbox

**Comment by MendyBerger** [comment]
Resolved in b7528ece244661ece57846f2272991eb218e20bc
