### ISSUE TITLE
JIG Panel

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1142]
1. When I come into a new JIG, there should be the first dark blue module space that says 'Drag activity here. Should not have to add it before I can drag the first module.
2. Settings icon for JIG needs to be repositioned (now to the left of the Preview JIG), see  https://zpl.io/2p3MMol
3. Need to do build JIG Settings

**Comment by MendyBerger** [comment]
1. resolved in aae227711e42f23fe1244d63696c165a861ebd0a

2. resolved in 909ca9ca090015c57c996b975495c06bb2dc1f30

**Comment by MendyBerger** [comment]
3. resolved in 27b8267a67766ea29d7796cab7519430e8e2b29d
