### ISSUE TITLE
Flash cards

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1144]
1. No Use Case 'Duplicate' here - only pairs that are different.
2. No button 'Add a pair' once cards have been generated.
3. In preview - should have a 'Next' button, little arrow, so that you can see the next flashcard pair. https://zpl.io/blGMW5z

**Comment by dakom** [comment]
Just some more info for implementation:

1. The mode filtering needs to be generic or at least generic on the level of card groups (it's not specific to flash cards exactly)
2. Add a pair goes in the card groups generic header, applies to all of them
3. Next button is part of the player (preview is always just a player loader - the functionality is never different between preview and play)

**Comment by corinnewo** [comment]
So these issues will be sorted out once all the card modules are done?

**Comment by dakom** [comment]
It's a combo - 

1. _mostly_ an issue of all card modules, with a setting on flashcards
2. all card modules
3. flashcards-specific
