### ISSUE TITLE
Publish - Categories not shown correctly

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1145]
1. When you choose a category that is not the root, then we need to show the whole path. We can't just show the end category.  (Checking with Gali what it should look like...)
2. When you hover over a chosen category, there should be a X to delete it. See https://zpl.io/Vk4KeYM

**Comment by MendyBerger** [comment]
Fixed in ec7dc38426cb2903496acdbfae48a5ea92537fb9
