### ISSUE TITLE
Re-send email not working

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1150]
The [Resend Flow](https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/user/struct.VerifyEmail.html#resend-verification-email) appears to not be sending the email.

This is in an environment where the initial email send (triggered via [Create](https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/user/struct.Create.html)) does work

**Comment by rrcwang** [comment]
I wasn't able to replicate this locally. I've made some changes to the profile creation flow, do let me know if this still occurs after #1161.
