### ISSUE TITLE
Verify email fails

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1151]
Error from the logs:

```
ISE while responding to request: error returned from database: duplicate key value violates unique constraint "user_email_email_key"
```

**Comment by rrcwang** [comment]
I also wasn't able to replicate this issue locally, but it should return `409 CONFLICT` if a request to verify w/ token is sent for an existing email now. Let me know if this is still happening after #1161.

You shouldn't be able to get a token for `Verify` this in the first place through `POST /v1/user`.
