### ISSUE TITLE
Image search loading UI should be self-contained

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1154]
In the image-search component, it blocks the entire screen while loading, both the initial metadata and search itself.

@corinnewo - we should have a proper UI brief from Gali, but I think for now this is a workable placeholder:

1. On first load for the required metadata, show _only_ a "Please wait..." string (because we won't have the required metadata for the filters etc.)

2. On search, the only thing that should be wiped is the results, and "Please wait..." should go there. The inputs should all be available and they will simply abort and replace the current request (this is all done automatically via AsyncLoader)

**Comment by MendyBerger** [comment]
Resolved in 0baba7107ebcc2f1128c95f3ca67b697d2c4666d
