### ISSUE TITLE
User should be prevented from doing things until the first PutProfile

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1164]
I believe they are prevented in terms of the UX flow right now, trying to login will force them to continue registration?

But they shouldn't be able to hack around that by calling APIs directly

We need to delay adding initial scopes until _after_ the initial PutProfile

**Comment by rrcwang** [comment]
This already exists as a part of [`CreateSessionResponse`](https://docs.sandbox.jicloud.org/crate/shared/domain/session/enum.CreateSessionResponse.html)
