### ISSUE TITLE
WYSIWYG: Sizing of text should not be field, as it takes focus from the text field on main screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1186]
When you change the size of a text string by typing in a size on the WYSIWYG, you lose focus on the text field on the main screen. Possible solution: use a pull-down menu with sizes in increments of 10. Then use the arrows to get to smaller/larger sizes.
Happy to discuss.

**Comment by corinnewo** [comment]
Increments of 10 starting at 10 until 160. (I know we talked about up to 100, but the H1 size in the themes can go up to 150. So this will allow for enlarging the H1 if necessary

**Comment by MendyBerger** [comment]
Fixed in 781d41e8cd3c1747d2ed8beb18c8856db563f7cf
