### ISSUE TITLE
Move ages from front of search result cards to the back, and list as age groups

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1189]
We are not going to have age ranges whatsoever. Will have list of the age groups that it is suitable for displayed on the back of the cards. 
Final age groups:

- Pre-K
- Kindergarten
- Elementary school
- Middle school
- High school

**Comment by MendyBerger** [comment]
So I think we'll need an updated design, right?

**Comment by MendyBerger** [comment]
Done in dd6c32f9c5c2d1885a879aa218a730a47c1a8b25
