### ISSUE TITLE
Media ready should be in Firestore (not Cloud Message)

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1197]
Our current implementation of media uploads uses Firebase Cloud Messaging ("FCM") to notify the client that a media file has finished processing.

This is a problem for web clients since FCM requires push notification permissions. It unfortunately requires this permission even when using the service for only focused browsers without actually needing push notifications, e.g. behind-the-scenes data messages (our use case).

Therefore, we need to migrate this layer to something which does not depend on these permissions: Firestore.

I've implemented a couple placeholder cloud functions and tested in a browser to make sure this will work. Ultimately, this issue is about replacing those cloud functions with the API server/EventArc[*]

The server should do the following:

1. When processing begins (i.e. the media is uploaded to the processing bucket), set `doc.processing = true`;
2. When processing is finished (i.e. the media is uploaded to the uploads bucket), set `doc.ready = true`;

`doc` is, in firestore terms, the document named `ID` under the `uploads` collection, where `ID` is the media id.

Here is the sample javascript for reference. This function would be set for the "processing begins" event. The "processing finished" event is identical except instead of `{processing: true}` it sets `{ready: true}`:

```
//Load the firebase admin SDK
const admin = require('firebase-admin');

//Using the firebase-admin service worker, no need for credentials
admin.initializeApp();

//Get the firestore instance
const firestore = admin.firestore();

// strips out the id
// example: *media/global/d4151e02-ebb3-11eb-b631-c7be23614ceb/*
// becomes: d4151e02-ebb3-11eb-b631-c7be23614ceb
function getId(s) {
  const prefix = `media/global/`;
  const prefixIndex = s.indexOf(prefix);
  const startIndex = prefixIndex + prefix.length;
  const endIndex = s.lastIndexOf('/');

  if(prefixIndex === -1 || endIndex === -1 || endIndex <= startIndex) {
    return "";
  }

  return s.substring(startIndex, endIndex);
}

/**
 * Triggered from a change to a Cloud Storage bucket.
 *
 * @param {!Object} event Event payload.
 * @param {!Object} context Metadata for the event.
 */
exports.main = (event, context) => {
  
  console.log(`Processing file: ${event.name}`);
  const id = getId(event.name);

  if(id === "") {
    console.warn(`couldn't get ID for file: ${event.name}`);
  } else {
    console.info(`processing ID ${id} for file ${event.name}`);
    
    const ref = firestore.doc(`uploads/${id}`);
    
    // don't totally replace the object, merge it
    ref.set({processing: true}, {merge: true})
        .then(() => console.info(`set processing to true for ${id}`));
  }
};
```

[*] note: we might ask, if the cloud functions work, why not just use that? there's 3 reasons: 1) the API server also needs to update the DB to mark finalization / push to Algolia before notifying that it's actually ready. 2) better just to keep all the logic in one place. 3) the cloud functions suffer from horrible cold start times. our API server has this problem too but it will inherently be hit more frequently when we're live, keeping it fresh

**Comment by dakom** [comment]
@rrcwang - the above doesn't take into account global vs. user libraries. We should follow the same nesting everywhere. There is currently a problem uploading images (getting a 401, see slack), but theoretically here's some updated JS code which shows the idea:

```javascript
const admin = require('firebase-admin');
admin.initializeApp();
const firestore = admin.firestore();

// strips out the metadata from cloud storage object
// example: *media/global/d4151e02-ebb3-11eb-b631-c7be23614ceb/*
// becomes: {lib: global, id: d4151e02-ebb3-11eb-b631-c7be23614ceb}
//returns null if it can't parse
function getMeta(s) {
  const lib = betweenTokens(s, "media/", "/", true);
  if(lib != "") {
    const id = betweenTokens(s, `media/${lib}/`, "/", false);
    if(id != "") {
      return {lib, id}
    }
  }

  return null;
}

function betweenTokens(s, prefix, suffix, suffixRequired) {
  const prefixIndex = s.indexOf(prefix);
  if(prefixIndex === -1) {
    return "";
  }

  s = s.substring(prefixIndex + prefix.length);
  
  const suffixIndex = s.indexOf(suffix);

  if(suffixIndex === -1) {
    if(suffixRequired) {
      return "";
    } else {
      return s;
    }
  }

  return(s.substring(0, suffixIndex))
}

/**
 * Triggered from a change to a Cloud Storage bucket.
 *
 * @param {!Object} event Event payload.
 * @param {!Object} context Metadata for the event.
 */
exports.main = (event, context) => {
  
  console.log(`Processing file: ${event.name}`);
  const meta = getMeta(event.name);

  if(meta == null) {
    console.warn(`couldn't get meta for file: ${event.name}`);
  } else {
    const {lib, id} = meta;
    console.info(`processing Lib ${lib} ID ${id} for file ${event.name}`);
    
    const ref = firestore.doc(`uploads/media/${lib}/${id}`);
    ref.set({ready: true}, {merge: true})
       .then(() => console.info(`set processing to true for ${lib}/${id}`));
  }
  
};
```

**Comment by rrcwang** [comment]
**Updated diagram:**
Instead of using Pub/Sub to signal completed processing status, the service notifies the API server directly. This then triggers the client notification and final database update. 

![ji-cloud media processing service](https://user-images.githubusercontent.com/15862033/127388896-07d707ae-3b55-4cb2-a6a4-feefea01e0f0.png)

**Comment by dakom** [comment]
great diagram! just a couple tiny nits:

* the Firestore should maintain the library path as well, so the record to update will be at `uploads/media/${lib}/${id}` where `lib` is, `global`, `user` or `web` (afaik we do _not_ store the different media types like images vs. audio in separate directories)

* the Firestore record should merge values in, so the final result should be `{processing: true, ready: true}`
