### ISSUE TITLE
Changing size - enlarge arrow does not seem to be working

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1204]
WHen I select a text box, and double click inside, and use the pull down of sizes in increments of 10, 

1. the size of the font in the text box does not change until I click and up/down arrow. Should it not respond immediately?
2. click the up arrow does not work properly, If I chose size 50 in the pulldown, then click down arrow reduces the size. The up arrow works until I reach 50, then does not go further. Should continue increasing.

![image](https://user-images.githubusercontent.com/16290361/126949455-adbf2a54-091a-4507-a00f-ded20f49502f.png)

**Comment by MendyBerger** [comment]
Fixed in 45a7ec8290741d14ed15f28c94963504825d5e54
