### ISSUE TITLE
Text box - dotted line is broken

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1215]
I'm not sure if this is connected with themes, but when you type text, change theme, then the transform box is broken (see screen capture). When you double-click to edit the text, the box is fine. But when you click out of the box, it gets broken again.

![image](https://user-images.githubusercontent.com/16290361/127145938-233baeed-5223-491f-9abe-bcb6e6fdccd0.png)

**Comment by dakom** [comment]
Might be a browser bug we'll need to work around by adding extra padding or something.

@corinnewo can we push this off into the `Future` milestone? It's the kind of thing which could take hours of fiddling around.

**Comment by corinnewo** [comment]
Yes, I think it can wait for a later milestone. But we must keep this ticket alive!
