### ISSUE TITLE
WYSIWYG: Text box fill

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1217]
When you open up the text fill, the palette of colours is half-hidden. See screen capture:
![image](https://user-images.githubusercontent.com/16290361/127146783-ff716b21-2b1f-4357-84d3-42c33fc9a4e7.png)

There is a horizontal scroll bar, but when I try and scroll right, the colour palette closes!

**Comment by MendyBerger** [comment]
Resolved in 4bd9dd88e26c65828a0ccafc71508b8fef08344c
