### ISSUE TITLE
New jigs' Cover module should have content

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1257]
The Default impl for cover data sets its inner content to Some: https://github.com/ji-devs/ji-cloud/blob/5c27da6470cab93f8a21be19c00a2ae76072082e/shared/rust/src/domain/jig/module/body/cover.rs#L19

But when new jigs are created, the cover data is null for some reason

@rrcwang if this isn't a backend issue and it's something in the module data structures in the shared crate, feel free to re-assign to me

**Comment by rrcwang** [comment]
I was not able to replicate this neither locally not on sandbox. It appears to be creating a correctly populated cover in the DB when making a new jig. If you could double check that new jigs are still creating `null` or invalid modules please update me.
