### ISSUE TITLE
Wire up the report jig button

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1263]
Blocked by #1982

**Comment by corinnewo** [comment]
@MendyBerger Is this sending the email yet? If not going to work, then we must hide for MVP.

**Comment by MendyBerger** [comment]
Might be ready for MVP

**Comment by corinnewo** [comment]
Hi @mastapegs - I understood that this was committed already, so I tried to send a report on sandbox, and it has not arrived anywhere. Also, we had spoken in LB meeting about putting the **name** of the JIG in the subject. Are you able to do this, or do we have to go to LB about it? Thanks!

**Comment by mastapegs** [comment]
@corinnewo This has now been merged :-)

**Comment by corinnewo** [comment]
Thanks @mastapegs - the email arrived at the test site! When will this be sent to the correct address - to info@jigzi.org?

**Comment by mastapegs** [comment]
@corinnewo 
The sandbox environment is defined right now to always send emails to `JiTestLB@gmail.com` while the release environment will be sending emails to `info@jigzi.org`

https://github.com/ji-devs/ji-cloud/blob/422145f4b7e09f9e18c9c225a3723da7a586d28a/shared/rust/src/config.rs#L225-L230

![image](https://user-images.githubusercontent.com/13839150/152341116-6aa3a9e6-f47e-44e0-8ccb-2fcddc292955.png)

**Comment by corinnewo** [comment]
@mastapegs Thanks for the explanation - looks fine to me!
