### ISSUE TITLE
Jig Editor: handle ModuleToJigEditorMessage::AppendModule

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1273]
Needs to append the module to the sidebar and update the iframe src

Note that it should *not* actually clone the module, that is already done, it just updates the UI (the id and kind are in the Message)

**Comment by MendyBerger** [comment]
Resolved in f086cc17

**Comment by dakom** [comment]
Re-opening - seems the iframe src isn't being updated (stays on the current module - should move to the next one)

**Comment by MendyBerger** [comment]
Next one or newly created one?

**Comment by dakom** [comment]
newly created

**Comment by MendyBerger** [comment]
Resolved in 75c39b9c4a14cf8c5e9975358692c727e81dbc3d
