### ISSUE TITLE
Fix jig player buttons

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1278]
This is a weird one!

The player buttons do not render when using the current CSS (inline-grid + place-content).

Toggling the display property in the browser dev tools makes it _permanently_ stay fine.
Toggling place-content toggles the visibility off an on

However, it seems to only be a problem in Chrome, and only in version 92.x!

**Comment by MendyBerger** [comment]
Resolved in 76b1c050a8b30c3de5124c559c9d6a52fa158d06
