### ISSUE TITLE
Profile editing - missing text in dialog for 'Subjects'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1288]
Heading and first sentence are question marks.

![image](https://user-images.githubusercontent.com/16290361/129035897-23ed0043-9969-4bd9-8067-3dc88a76402c.png)

Heading should be "Relevant Subjects"
Intro should say "Which subjects are you interested in?"

**Comment by MendyBerger** [comment]
Resolved in abd2013dbeb982df8608e87ccac393ce0d7cd14f
