### ISSUE TITLE
Profile - current menu item not reflecting current place on page

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1289]
When I click an item on the left menu, eg Teaching settings, then the right hand side jumps to the correct anchor. But the item highlighted on the menu does not match. See the screenshot: I am in **Teaching settings** on main panel, but on the left **Location** is highlighted.
![image](https://user-images.githubusercontent.com/16290361/129037530-ec069a5c-448c-45c3-8a36-d0e8acafb333.png)

**Comment by MendyBerger** [comment]
Resolved in 07896aa0
