### ISSUE TITLE
End of memory game - change icon for FIND A PAIR

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1293]
![image](https://user-images.githubusercontent.com/16290361/129042489-ac86436f-dbc0-40af-90ce-3b8483abbd7d.png)

Please update the image for FIND A PAIR at the end of all the card-based games. 
Should be
![image](https://user-images.githubusercontent.com/16290361/129042659-11b51133-ad60-4921-9fec-6152055cff70.png)

**Comment by GaliShapira** [comment]
![2](https://user-images.githubusercontent.com/88834002/129193384-06776fb6-0d47-46c6-abd7-776fc35d60e1.jpeg)

**Comment by GaliShapira** [comment]
[Clock.svg.zip](https://github.com/ji-devs/ji-cloud/files/6975317/Clock.svg.zip)
(try only)

**Comment by dakom** [comment]
works perfectly :)

**Comment by chayaml** [comment]
Find the Pair Icon updated

![Screen Shot 2021-09-02 at 3 48 31 PM](https://user-images.githubusercontent.com/78186896/131906978-74cb66f5-2469-4338-b129-235bd218a35b.png)
