### ISSUE TITLE
Jig Editor: handle ModuleToJigEditorMessage::Next

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1296]
UX note from @corinnewo: At the end of Memory Game - when I choose what to do next, should open up the JIG panel automatically. As I click the option I chose, it should progress and open the JIG panel with the current activity highlighted.

**Comment by dakom** [comment]
@corinnewo - what is supposed to happen on the last module? does it go to Publish?

**Comment by MendyBerger** [comment]
Resolved in 1572f8b2
