### ISSUE TITLE
All card games - inputting and editing the text

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1297]
Shuli was really unhappy with the way we did the editing on the cards. She wanted to be able to click CONTENT stage again and you can edit in the list, not on the cards.

Here are the notes from Ideation on 23 June 2021:

- LISTS - keeping them in place instead of making them disappear and only edit the cards:
- Shuli said that we need to be consistent, and if users go back to wizard #1, should still look the same and have the lists.
- David said we could leave the lists in place, and then change the button from DONE to UPDATE CARDS.
- List will update the cards when the button UPDATE CARDS is pressed.
- Can edit either in the list or in the cards.
- If a word is deleted in the list, then it will show up as a blank card. We could add an alert that there is a blank card.

**Comment by dakom** [comment]
@corinnewo Is this a duplicate or different than https://github.com/ji-devs/ji-cloud/issues/1125 ?

**Comment by corinnewo** [comment]
yes - it is a duplicate - sorry!
