### ISSUE TITLE
Add audio in setting and play

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1298]
Temporary files can be found at https://www.dropbox.com/home/Ji-2-0/sound%20files

**Comment by dakom** [comment]
for the sake of consistency this should use `AudioMixer`

icing on the cake - it uses the WebAudio API so we can add effects like reverb, distortion, eq, etc. if we really want to.

**Comment by MendyBerger** [comment]
Blocked by #1412

**Comment by MendyBerger** [comment]
Resolved
