### ISSUE TITLE
use thumbnail in more places

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1300]
- homepage + search results (jig image should always use cover image w/ fallback)
- jig edit gallery (jig image should always use cover image w/ fallback)
- jig edit - publish window (use cover thumbnail w/ fallback)
- jig edit sidebar (always use it, doesn't need to wait for publish)
- jig player sidebar (always use it, doesn't need to wait for publish)

Specifically, the fallbacks are:

- In the sidebars (all of them), it's always `ui/module/{kind}/thumb-placeholder.svg`
- In the jig results (all of them), it's always `ui/jig/thumb-placeholder.svg`

In terms of implementation the only difference will be that in sidebars a `fallbackKind` is set, and elsewhere it isn't

**Comment by dakom** [comment]
@GaliShapira @corinnewo TBD

**Comment by dakom** [comment]
@MendyBerger - it's approved, go for it :)

**Comment by MendyBerger** [comment]
Resolved in 3eb2aa7a

**Comment by MendyBerger** [comment]
Resolved others in db154661634dc3fb179b3700ffd910e17e694c11
