### ISSUE TITLE
Create Jig Thumbnail fallback

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1302]
In the rare case where the user needs the cover thumbnail but it hasn't been generated yet, we need a fallback image to use

One example where this can happen is they create a new jig and then immediately hit "publish" without giving the screenshot mechanism enough time to run.

(_note: this image will be placed in `ui/jig/thumb-placeholder.svg`_)

**Comment by GaliShapira** [comment]
Hi @dakom @corinnewo 
We are afraid that this will not be rear... When the teacher didnt create a cover, it will be white, and an error message appears on publish page. 
https://zpl.io/a77GrRW

**Comment by dakom** [comment]
Technically that isn't a fallback due to missing image, it's a white poster :) Same as if they created a poster, added/deleted images, changed theme, and then set background color to white.

In the publish screen we can possibly load the cover module and detect if there's any worthwhile content - but we cannot do this for all the jig results

**Comment by corinnewo** [comment]
@GaliShapira I think that this can be solved by adding the edit button, a heading 'Cover' or 'Thumbnail' and a small sentence like 'Your cover becomes your JIG's thumbnail. A good thumbnail stands out and draws attention.'
Then clicking the edit button,  will open up the cover module to edit.
Please update the zeplin and then we can assign to Mendy again.

**Comment by dakom** [comment]
Not with the [current API](https://docs.sandbox.jicloud.org/crate/shared/domain/jig/module/struct.Module.html) - but I'll open an issue so we can track `updated_at` for modules.

This would still only be directly useful for the publish page. If we want to do it for jig results in general it would build on that but be a separate issue.

**Comment by dakom** [comment]
ok I opened a couple issues so we can know whether or not the cover has ever been modified: https://github.com/ji-devs/ji-cloud/issues/1538 and https://github.com/ji-devs/ji-cloud/issues/1537

so we can assume we'll have that capability, and the graphics requirement is what to show when it _hasn't_ ever been modified.

Note - if the user goes in and makes any change at all to the cover, even just navigating in the wizard, we'll have to go with what it is. If they left their screen blank, that's life (well... if *really* necessary, we can do a deeper dive on the publish screen to check the content itself, but not on jig results)
