### ISSUE TITLE
Admin - Edit images - move NEXT and PUBLISH images to the top right corner

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1306]
When editing, the buttons (NEXT and PUBLISH) are on the bottom right, so you have to scroll down to find them. Please place these buttons on the top right corner, so they are available all the time.

Also, please have both of the buttons, so that you do not have to go Next -> Next >Next-> Publish, when perhaps you just needed to change something on the first screen.

![image](https://user-images.githubusercontent.com/16290361/129215115-4df0b91e-64fc-44f5-a666-1e747c20ac85.png)

**Comment by chayaml** [comment]
"Next" Button was not added but can easily flip through screens with:
![Screen Shot 2021-09-02 at 4 05 07 PM](https://user-images.githubusercontent.com/78186896/131908901-2b43c02d-a9fa-418c-9173-658db1ae23fb.png)

"Publish" button was added on the top right:
![Screen Shot 2021-09-02 at 3 57 59 PM](https://user-images.githubusercontent.com/78186896/131908508-4cfdd88b-0ced-47a9-8a76-d528f97449c3.png)
