### ISSUE TITLE
Admin - Edit image - Add EDIT button to the Categories panel

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1307]
At the moment, there is an EDIT button next to the General Summary panel, and that opens up the whole editing sequence. 
I think that we need an EDIT button next to the Categories panel too, that will open up the categories directly to be edited. 

At the moment, if I need to edit the category, I have to go Edit -Next -Next. This would allow me to go there directly.

![image](https://user-images.githubusercontent.com/16290361/129215862-1c5ff308-ae06-4d67-9d43-1301d756ae01.png)

**Comment by GaliShapira** [comment]
@corinnewo 
Done
