### ISSUE TITLE
Login - using google - was told to create an account

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1310]
I tried to log in using a different Google account, and I got this message:
![image](https://user-images.githubusercontent.com/16290361/129226807-6e3d27e3-be6e-476f-9afb-2ebeb08b03a4.png)

We need a designed screen telling you that you don't appear to have an account yet, and you need to create one by registering. Then have a link to the register page.

**Comment by GaliShapira** [comment]
@corinnewo 
Not sure I understand the use case:
The user tried to login via Google without creating an account? It can also happen if I try to login not with Google and I dont have an account. 
I suggest to move to Registration page, perhaps with a different title/explanation of why you got there

**Comment by GaliShapira** [comment]
@corinnewo 
 See the screen:
 https://zpl.io/anv6wqk
 
 Its similar to #1433
 Just different titles.

**Comment by MendyBerger** [comment]
Resolved in 9b057fec0
