### ISSUE TITLE
Jig Publish: Additional Resources Icons

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1316]
Although https://github.com/ji-devs/ji-cloud/issues/1315 is only for the `Future` milestone and the functionality isn't hooked up, the missing icons should be added in the meantime

**Comment by MendyBerger** [comment]
What missing icons?

**Comment by dakom** [comment]
![chrome_HnAFe4VEC3](https://user-images.githubusercontent.com/6406986/129354092-f60d8917-3c15-4044-8008-a8f6ab3a4355.png)

**Comment by MendyBerger** [comment]
@corinnewo can I please hide the whole section for now? I'm probably going to redo the whole thing from scratch anyway

**Comment by corinnewo** [comment]
Instead of hiding, I’d like to keep it visible with a note ‘Coming soon!’ 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by MendyBerger** [comment]
Resolved in c18a1a99
