### ISSUE TITLE
After publish - should go to the screen with options to share, etc

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1318]
At the moment, after clicking the  publish button, nothing happens. Should go to the end of publish screen https://zpl.io/addRN9E and each of those options should be active.

**Comment by dakom** [comment]
@MendyBerger - heads up, since `Share` exists here and elsewhere, the menu system and all the sub-windows should all be encapsulated in one component which takes `JigId` as a param and can be rendered anywhere

**Comment by MendyBerger** [comment]
Resolved in 321c6f2130ff8d51880cee428de96e9167b4989c
