### ISSUE TITLE
Jig Publish: Add popup when public is toggled

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1320]
zeplin ref: https://zpl.io/awzyOnd

**Comment by corinnewo** [comment]
Text in the popup should be:
Sharing is Caring!
Are you sure you want to keep this JIG private? Please consider sharing your JIG with the Jigzi community.

**Comment by MendyBerger** [comment]
Resolved in b32e42222ff3df732e9f1cf69232e78899e81740
