### ISSUE TITLE
Jig Publish: show number of categories

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1322]
Zeplin ref: https://zpl.io/awzyOnd

**Comment by dakom** [comment]
@GaliShapira @corinnewo - the zeplin reference says that the cutoff is based on the _visual width_ of the text.

This is doable but extremely complicated and prone to error due to the limitations of HTML

Can we instead have the rule be if there is more than 1 choice, show the first choice and then the number? i.e. it will only always ever be one choice displaying there.

**Comment by corinnewo** [comment]
Yes, that is fine. One choice and a number

**Comment by MendyBerger** [comment]
Resolved in 329f0321aaa8d233c8c30b3acda834ef8921e003
