### ISSUE TITLE
Missing small icon for Drag and Drop - collapsed JIG panel

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1326]
![image](https://user-images.githubusercontent.com/16290361/129342726-5a4f1c04-6276-4f05-8826-4eea7953f334.png)

**Comment by GaliShapira** [comment]
@MendyBerger 
See attached icon
[Drag & Drop_small.svg.zip](https://github.com/ji-devs/ji-cloud/files/7013876/Drag.Drop_small.svg.zip)

All icons are here:
https://zpl.io/V4rXdGQ

**Comment by corinnewo** [comment]
I added in the icon to dropbox
