### ISSUE TITLE
Search not finding my published JIG

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1327]
I created and published a JIG called "my first thumbnail". Then I searched for 'thumbnail' and no results were found.
![image](https://user-images.githubusercontent.com/16290361/129343026-ef277e90-7106-4f39-8631-1cbe33997648.png)

![image](https://user-images.githubusercontent.com/16290361/129342939-45bc58a5-fe37-4bd1-b238-2133399c7509.png)

**Comment by dakom** [comment]
This is actually working, but the UX is broken due to https://github.com/ji-devs/ji-cloud/issues/1338
