### ISSUE TITLE
JIG panel - when editing a JIG -  missing graphic for 'Drag activity here'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1328]
When you first create a JIG, clicking the + icon adds in the 'Drag activity here' image.
![image](https://user-images.githubusercontent.com/16290361/129343943-8d9101b5-5944-428a-b565-ef7e7693e2a3.png)

When you come back and edit, clicking the + icon simply adds a blank area. (might be after publishing)
![image](https://user-images.githubusercontent.com/16290361/129343732-740c77e6-f62b-4cff-8c60-594ca4aede0d.png)

**Comment by MendyBerger** [comment]
Resolved in 3eb2aa7a
