### ISSUE TITLE
Video carousel - missing images

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1329]
The carousel of the video is missing all the images. Images in zeplin are here: https://zpl.io/2j3G9qp

![image](https://user-images.githubusercontent.com/16290361/129344658-e1e09424-8bc0-48ec-bab1-73c85044cc95.png)

**Comment by dakom** [comment]
@corinnewo I should also change the options themselves to match https://zpl.io/2j3G9qp right?
