### ISSUE TITLE
Video - text does not appear in the preview mode

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1330]
I created a module with a video, graphic and text. When I am in preview mode, the text does not appear.
Does not appear in the thumbnail either.

With text:
![image](https://user-images.githubusercontent.com/16290361/129345918-0a9edf8c-dce7-44f6-9a9b-f95d00d4d27d.png)

Preview:
![image](https://user-images.githubusercontent.com/16290361/129345950-8fa27633-9043-4d5d-9a74-66f887dbc78d.png)

**Comment by MendyBerger** [comment]
Fixed in c909fe353bf813b1d66acc6a101401873ee7450a
