### ISSUE TITLE
Video - nothing happens after you click DONE

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1331]
After you click DONE in the preview step, you should go to the last screen, https://zpl.io/be3REZD and then to https://zpl.io/br3w5Dr.
If they press continue, should open up the JIG panel again.

**Comment by dakom** [comment]
I'm going to re-assign this to myself since I _think_ this is handled on the generic module abstraction layer. If not then I'll kick it back to @MendyBerger
