### ISSUE TITLE
Decide final module fallback image

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1336]
The [current zeplin](https://zpl.io/V4rXdGQ) shows that there is one global "activity in progress" image

However, we discussed on Zoom the possibility of instead using the module kind icon (e.g. memory game, drag and drop, etc.) and only changing the background to orange.

Needs a final decision.

In the meantime we are copy/pasting the fallback image into each folder, so that we support the capability

**Comment by GaliShapira** [comment]
@dakom 
I believe we fixed that today, and this issue can be closed.
