### ISSUE TITLE
Jig Publish: Affiliations and Ages

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1338]
Affiliations and Ages should all be selected when publishing a jig for the first time (similar to adding new images in admin)

@corinnewo tagging you to keep you in the loop. This is the reason jig searching is failing at the moment (jigs with no affiliations can't be found by a logged in user with an affiliation)

@GaliShapira this should also be updated in the Zeplin, but @MendyBerger isn't blocked on that since it's just a dropdown with the same values elsewhere.

**Comment by MendyBerger** [comment]
Resolved in 9b2a6f17

**Comment by MendyBerger** [comment]
Ages was not done

**Comment by MendyBerger** [comment]
Ages resolved in b05ef62c
