### ISSUE TITLE
Admin of images - redesign so that no need to scroll for buttons

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1341]
Editing images in the backend is very clumsy at the moment. Suggest:

1. Add an edit link to the Categories column too, so that you can go directly to the category list.
2. Create a new section along the bottom where buttons will always be visible (Gali to attach design)
3. Add **Publish** button to each screen, next to the **Next** button
4. Can **Publish** on any screen.
5. **Next** will take you through a linear editing process, which will be useful mainly when editing a new image, that needs all tags as well as the categories.

I've made this high priority as we will be uploading all backgrounds and overlays soon, and the current process is very cumbersome, slowing down the upload greatly.

**Comment by GaliShapira** [comment]
@corinnewo @dakom 
Pls see on this screen:
1. Edit for categories
2. Inner scroll for sections if needed
3. Section of buttons that will always be above fold
4. Publish and next buttons

https://zpl.io/25jjv4e

**Comment by dakom** [comment]
imho the problem is locking them into a linear flow. e.g. I might want to jump back to the `Summary` page from `Categories` or `General` without having to hit next twice, or to think about whether I need to hit next twice.

Why not just have 3 tabs: `General`, `Categories`, and `Summary` with a publish button available at all times?

We can order the tabs left-to-right in the most user-friendly flow.

Just an opinion though, I'll defer to whatever the final design is, of course.

**Comment by GaliShapira** [comment]
@corinnewo @dakom
I was working on the wrong screen.... sorry.
We can add tabs as David suggested, See attached. But I don't think that in all use cases it's enough.
We have 2 use cases:
1. When uploading a new image the user will see the first tab and go next, I suggest having a next (+back) button as well, as it's not intuitive to use breadcrumbs for a flow.
2. When editing an existing image, then we can have the breadcrumbs as a navigation tool, and no next button, only publish, although we can have the navigation buttons there as well. 

https://zpl.io/V4GGBOp

**Comment by dakom** [comment]
Ah, breadcrumbs are nice and solves the problem too.

As long as "back" means "previous breadcrumb" and not "previous page" (i.e. search / add/ etc.) that's fine.

**Comment by GaliShapira** [comment]
Yes, the back and next are only on the 3 screens of this flow of editing and uploading an image, not in search results.

**Comment by dakom** [comment]
Just to make sure - all breadcrumbs are visible all the time and it just changes which is highlighted or something, right?

(the whole point is that sometimes the person just wants to jump around without going through the linear flow)

**Comment by GaliShapira** [comment]
Yes, tit will appears on all the screens of editing or uploading a new image.

**Comment by corinnewo** [comment]
Gali submitted new design with no footer and buttons along the top
