### ISSUE TITLE
More thumbnail integration

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1345]
Picks up from #1300  and #1335 

1. Call `ModuleThumbnail::render_live()` instead of `ModuleThumbnail::render()` wherever thumbnails are needed in the jig editor (nowhere else). The render_live() is pretty heavy-handed and thrashes the cache, so as cool as it is, we should only use it when there's a real benefit (i.e. while editing). I believe the two places are specifically:
    1. Jig Editor sidebar
    2. Jig Editor publish

2. Need to trigger the screenshot generation in a couple more places, by calling `utils::screenshot::call_screenshot_service()`. It's a simple async fn that only needs the jig_id, module_id, and module_kind, so calling it immediately after a jig is created (perhaps with another call in between to get the cover module_id) should be straightforward:
    1. On new Jig creation
    2. On Jig duplication

**Comment by dakom** [comment]
> heavy-handed and thrashes the cache

Just to clarify, it's not _that_ heavy, it's not like it's polling or changing the src on a loop or something, it's event-driven and only updates when the backend really updates (using firestore to communicate changes). However, in order to _show_ those changes the image has a dynamic "cache busting" query param and also each instance sets up a listener with no way to destroy it (due to JS limitations. It does, however, Drop it on the rust side and ignore it on the JS side)

**Comment by MendyBerger** [comment]
1. Resolved in db154661634dc3fb179b3700ffd910e17e694c11
2. Canceled in favor of #1377
