### ISSUE TITLE
Publish - long path of categories - goes out of the box: Make box bigger

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1346]
When the path for the categories is long, the text goes out of the box. Either make box bigger, or cut off the text after x characters, add ... , and show the full path on rollover.

![image](https://user-images.githubusercontent.com/16290361/129589642-b2832ea3-78d1-455e-bf5d-158d6254f16e.png)

**Comment by MendyBerger** [comment]
Resolved in 74d011a6
