### ISSUE TITLE
Video carousel - only 4 items, so do not need > to go to a new page

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1347]
IF there are no more items on the next page, then we should either disable the arrow, or hide the arrows. Doesn't make sense to have a carousel if there are no items to go to.

![image](https://user-images.githubusercontent.com/16290361/129592794-7dfbd5d5-5ae9-413b-93a0-10aea8fcec07.png)

**Comment by MendyBerger** [comment]
Resolved in 582ba5f8f4b6c9af5f4e201584df3b11823af586
