### ISSUE TITLE
Profile - Password can not be edited. Should have a RESET button instead.

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1348]
The password needs to be reset. So the button should be changed from EDIT to RESET.
Press the RESET button - it goes into the same flow that a FORGOT PASSWORD triggers.

![image](https://user-images.githubusercontent.com/16290361/129598716-5718134e-2cb1-4be3-b0ab-dabb7ac5998a.png)

**Comment by GaliShapira** [comment]
@corinnewo 

I updated the Zeplin:
https://zpl.io/bWGNMNp
https://zpl.io/29GOZvp

Pls see the hover slightly different color of the button.
<img width="399" alt="Screen Shot 2021-08-19 at 17 39 39" src="https://user-images.githubusercontent.com/88834002/130088880-3373961e-4e48-460a-b7c1-ba871f6f5d04.png">

**Comment by MendyBerger** [comment]
@GaliShapira What happens after the user clicked the reset password button? Do they get a popup that an reset-password email was sent?

**Comment by MendyBerger** [comment]
@GaliShapira ping

**Comment by MendyBerger** [comment]
Resolved
