### ISSUE TITLE
Player - New modal dialog with close buttons

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1358]
We need the 2 designs for the player's modal window:

- From preview - close button would say 'Close preview' or something like that so that it is reassuring that you not losing your design.
- From play JIG - close button.
This is high priority as Mendy is waiting for it.

**Comment by GaliShapira** [comment]
Done. 
See details in Slack and Zeplin.
https://jewishinteractive.slack.com/archives/C017NCE1UVD/p1629218858003000
