### ISSUE TITLE
Small screen - image comes in larger than canvas size, and can't see the bounding box at all

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1363]
When you are working on a smaller screen, and you add an image to the main screen - comes in larger than the canvas area, so it looks like it is a background. Can't see any bounding box. Only when I told Anat to try and move the image did she see that it was movable.
Recommendation - Bring in the sticker image at 50% (or thereabouts) of the height of the canvas and centered, so that it can be obvious that it is a sticker and not a background.

See how salad came in:
![image](https://user-images.githubusercontent.com/16290361/129747976-0a67461f-88a5-43e5-904c-fd12278fa432.png)

**Comment by corinnewo** [comment]
Gali thinks it should be 30% not 50% of the canvas height.

**Comment by dakom** [comment]
This is actually a backend bug, filing there and closing this as a duplicate: https://github.com/ji-devs/ji-cloud/issues/1389
