### ISSUE TITLE
JigSearchQuery additional args

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1366]
```
* is_public: bool
* creator: Option<UserOrMe>
```

If `is_public` is `true`, no auth checks are required

Otherwise: 
  - if `creator` is `None`, the user must be an admin (returns all private jigs on the system)
  - if `creator` is `Some(UserOrMe::Me)`, the user must be logged in (but no other scopes)
    - same for if `Some(UserOrMe::User(x))` and `x` is me
  - if `creator` is `Some(UserOrMe::User(x))`, and `x` is not me, the user must be an admin

**Comment by RickyLB** [comment]
resolved in https://github.com/ji-devs/ji-cloud/pull/2468
