### ISSUE TITLE
Play icon - in player shell

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1367]
Hi @MendyBerger 
The play icon's states are switched. 
The default one should be the play, the hover should be the packman.

[https://zpl.io/an3eeAA
<img width="258" alt="Screen Shot 2021-08-17 at 19 25 52" src="https://user-images.githubusercontent.com/88834002/129765549-697b1510-8283-433a-8e63-9ba080e23279.png">
](url)

**Comment by dakom** [comment]
just swapped the names in dropbox
