### ISSUE TITLE
fix height on inputs

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1373]
discussed on slack. Putting `input-location`, `input-select`, and `input-wrapper` (with an inner `<input type="text" />`) should all have the same height, but they are currently different:

![chrome_vTL0C9dSuc](https://user-images.githubusercontent.com/6406986/129902483-c6a3ed28-aecc-48bd-80c7-1d0c90fc2c5f.png)

**Comment by MendyBerger** [comment]
@dakom how do I get to this page?

**Comment by dakom** [comment]
locally? `cargo make local-main user` and then edit https://github.com/ji-devs/ji-cloud/blob/sandbox/frontend/apps/crates/entry/user/src/debug.rs

**Comment by MendyBerger** [comment]
Resolved in 67b08c7
