### ISSUE TITLE
Sound effects from Mitch for Drag and Drop module

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1385]
Mitch supplied several versions for the sound effects for drag-and-drop module. I think we will need to test which is the best version to use.

[drag-drop.zip](https://github.com/ji-devs/ji-cloud/files/7013047/drag-drop.zip)

**Comment by dakom** [comment]
There are 3 effects:

* Drag: Starts when they start dragging (@corinnewo should it be on a loop or just end?)
* Correct: One shot, when they drop over the correct target
* Incorrect: One shot, when they drop over the wrong target

**Comment by corinnewo** [comment]
@dakom Can it loop while dragging? Is this sound suitable for looping? If not, I will get another one from Mitch.

**Comment by dakom** [comment]
It's currently looping
