### ISSUE TITLE
Publish screen - adding list of categories pushes the button off the screen - need a scroll

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1387]
I added a lot of categories, which works really nicely now. But if I add too many categories, the button to Publish JIG gets pushed off the screen, and there is no scroll to get there. I think that we need to add a scroll to the area where the categories are listed if the list gets too long. 

![image](https://user-images.githubusercontent.com/16290361/130045882-db7b3678-aac3-48d1-bcf8-46e026569c8f.png)

**Comment by MendyBerger** [comment]
Resolved in 95ef37e71dce74a9288f38df7590563d661c41e8
