### ISSUE TITLE
Audio Recorder - Cancel Button doesn't work

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1390]
In addition to the UI/state change, it should properly abort the request. On the file upload side this is pretty easy:

create an AbortController and change `api_with_auth()` in `file_change()` to `api_with_auth_abortable()`. Then the same AbortController can also be passed into `upload_audio()`

**Comment by MendyBerger** [comment]
Resolved in 135833a6b6c7cd71b40424c5f47c47a81a70f7bb
