### ISSUE TITLE
Video module - player cuts the bottom of the screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1392]
When there is a video on the screen, the player cuts off the bottom of the screen.
This shows the create screen, with video and text correctly placed.
![image](https://user-images.githubusercontent.com/16290361/130056344-d5645e52-f967-44b4-b5e5-88675a725b54.png)

This shows the player screen, with the text cut off:
![image](https://user-images.githubusercontent.com/16290361/130056069-7a65880a-d63e-4bb9-841e-adbc4fb0d03d.png)

In the creator, when I take out the video sticker, the text gets cut off in the create screen: (as it gets played on the player)
![image](https://user-images.githubusercontent.com/16290361/130055861-ff5e1c63-9484-41bd-aff4-40235ee73e54.png)

**Comment by MendyBerger** [comment]
Looks like as the screen gets wider the grid continues to expand, even when it overflows in the vertical axis.

This doesn't happen in the edit view, because of the sidebar the grid is not so wide

**Comment by dakom** [comment]
Re-assigning @MendyBerger here, but keeping me assigned too... not sure what the issue here is yet

**Comment by dakom** [comment]
We can't duplicate... if it happens again please re-open
