### ISSUE TITLE
Text size on the cards - should depend on how many letters are on the card.

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1396]
I know we said we would sit together and fix the size, but I want a ticket to remind us!

- When there is only 1 letter on the card: Should be large. Fill the card.
- 2-6 letters - size can be much larger than the text is currently.
- 2 words - can be same size as letter (2-6) above, but on 2 lines.
- riddle (sentence) - spread over several lines.

I do think we need Gali to guide us while you are setting the sizes, but this definitely needs to be sorted!

![image](https://user-images.githubusercontent.com/16290361/130105340-e5d2b2df-a5db-4869-92d1-50689b1d66cb.png)

**Comment by dakom** [comment]
ultimately I think we need to base it purely on number of letters, otherwise we have to start considering line breaks and things like that which we can't predict
