### ISSUE TITLE
Drag and drop - duplicate drop area crashed

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1398]
**Describe the bug**
I duplicated the drop trace area. The two areas went blue and I could not move anything.
**To Reproduce**
1. Go to wizard 3 in Drop Areas
2. Trace an area
2. Click on the kebab menu and duplicate

**Expected behavior**
Should duplicate the trace area and be able to move the trace area to its new position

**Screenshots**
![image](https://user-images.githubusercontent.com/16290361/130198214-d2d5eb6a-373d-4fbc-bc59-bed45b357be8.png)

**Comment by dakom** [comment]
It does work, but the UX isn't great
