### ISSUE TITLE
Thumbnails are not updated in player

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1399]
I created a new module and published. All thumbnails created.
![image](https://user-images.githubusercontent.com/16290361/130199267-788f0a56-a65b-42d7-9472-25918705ff86.png)

I went to the player from the 'play' option after publish, and the thumbnails were not updated.

![image](https://user-images.githubusercontent.com/16290361/130199171-3f95868f-68b5-44ad-b342-0b67493179b2.png)

**Comment by dakom** [comment]
Could this just be a cache issue?

**Comment by MendyBerger** [comment]
@dakom looks like it's indeed a cache issue, how do you suggest we move forward with this?

**Comment by MendyBerger** [comment]
Resolved in 84dbfa3b61d89ad0f841bb6be8d995aa5e7188de
