### ISSUE TITLE
Home page - Advanced search is too large!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1403]
Even on my large screen, it goes off the screen:
![image](https://user-images.githubusercontent.com/16290361/130211235-1394b3c9-0010-4cab-9eef-88289f8806e9.png)

Please make this fit better! It looks really bad!

**Comment by corinnewo** [comment]
Also,

- [ ] The search button that you scroll down for does nothing
- [ ] Default for all options should be All, eg All categories, All teaching goals (and if not logged in , All affiliations)
- [ ] Link to open the advanced search should say 'Advanced search' and not 'Search Advanced' as it says now.

**Comment by MendyBerger** [comment]
Resolved in 0375f7c8
