### ISSUE TITLE
Home page - rollover states for the jigglings with the 5 c's

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1405]
@GaliShapira -where are the rollover states of the jigglings? 
![image](https://user-images.githubusercontent.com/16290361/130224751-cf4d8b65-7211-4980-a538-21a5f51728aa.png)

**Comment by GaliShapira** [comment]
Hi @MendyBerger 
See attached. 
[Jigglings.zip](https://github.com/ji-devs/ji-cloud/files/7091946/Jigglings.zip)

**Comment by MendyBerger** [comment]
Resolved in 1527350f92b3530108fe0ddb3bad200af8d80ded
