### ISSUE TITLE
Tapping board - wizard counting is wrong

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1408]
![image](https://user-images.githubusercontent.com/16290361/130228505-4f7ff211-272a-4666-85d8-ee86de61f136.png)

**Comment by chayaml** [comment]
Tapping board counting updated

![Screen Shot 2021-09-02 at 2 05 34 PM](https://user-images.githubusercontent.com/78186896/131894627-124ee051-799c-4f6e-af37-cfba5a641481.png)
