### ISSUE TITLE
Drag and Drop settings - wrong text in one setting

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1417]
In the drag and drop settings, the first text should be "Continue to next activity" and not the duplicate of the third item "How to display your game". (see zeplin zpl.io/bLqyoK7)

![image](https://user-images.githubusercontent.com/16290361/130421840-2b3268f1-ecb1-4690-8641-d734b2e5bd2c.png)

**Comment by chayaml** [comment]
Still needs updating :)

![Screen Shot 2021-09-02 at 4 38 08 PM](https://user-images.githubusercontent.com/78186896/131913009-62dd03d6-ac4a-4aee-a4f9-e61fa2813fd5.png)
