### ISSUE TITLE
Share to students - need a button to generate a code

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1432]
When you are sharing to student, Mendy pointed out that you don't want a code generated each time that you go into a tab. You may just be looking at the various options, and don't need a code. So he suggests that we add a 'Generate a code' button, that will be the first thing on the tab. Once you have a code, the rest of the tab becomes active (much like the insert text button).

He needs a button 'Generate a code' please!

![image](https://user-images.githubusercontent.com/16290361/130603115-d8f93830-30d1-4124-bc48-f5ba387d8331.png)

**Comment by GaliShapira** [comment]
Hi @MendyBerger @corinnewo 
Pls see the updated flow: 
https://zpl.io/bzQw7Y8
https://zpl.io/beGzYxP

By the way, I changed the color of the field to light blue also in these screens: 
https://zpl.io/25PNAe0
https://zpl.io/2p80kxQ
https://zpl.io/bAgOWGO

[Archive.zip](https://github.com/ji-devs/ji-cloud/files/7089981/Archive.zip)

**Comment by MendyBerger** [comment]
Resolved in 1a89ef51
