### ISSUE TITLE
 No Auth! needs to rather open up the Sign in screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1433]
When you get to a screen that you need to be logged in for, but without having logged in, you currently get the 'No Auth' screen. Should rather open up the 'Time to sign up' screen. @GaliShapira please add in your new design here.

![image](https://user-images.githubusercontent.com/16290361/130608220-33a6e6d0-c1aa-4d81-9ae4-48108783fd46.png)

**Comment by dakom** [comment]
so from what I see, it looks like this is just a redirect to /user/register, and we need to update the page to add the new footer

**Comment by GaliShapira** [comment]
@dakom The footer and the title are different than the page of registration when the user clicks himself on registration. 
This page is a different version of the first page in registration and comes instead of it. (Continue will take to the next step).

**Comment by dakom** [comment]
The redirect itself is implemented, UI changes will be a separate issue: https://github.com/ji-devs/ji-cloud/issues/1498
