### ISSUE TITLE
Registration - text for terms and conditions and GDPR

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1438]
Please change the text in the sign up:

- [ ] I have read the _Terms & Conditions_ and _Privacy Policy_  (where t&c opens a new tab temporarily - until we get legal text for Jigzi - of page https://www.jewishinteractive.org/terms-and-conditions/ and Privacy Policy opens up a tab with https://www.jewishinteractive.org/privacy-policy/)
- [ ] I would like to receive educational resources 

Jewish Interactive (Ji) is committed to protecting and respecting your privacy, and we’ll only use your personal information to administer your account and to provide the products and services you requested from us.

![image](https://user-images.githubusercontent.com/16290361/130626984-c0b13aad-508e-4b2f-affb-6098f4bdbb58.png)

**Comment by dakom** [comment]
re-assigning to me... the user pages are a bit of a hodge-podge of current and old code, but I'm mostly maintaining it currently.

**Comment by dakom** [comment]
The way I did the links in the checkbox label was pretty silly/hacky btw... might be better to make custom elements for these lines
