### ISSUE TITLE
Player - Information tab

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1439]
In the player, the info tab shows a section for Courses. Since this is not yet applicable,  we should change it.

Under additional resources heading say 'Coming soon!'

Under the Courses heading, say 'Coming soon!'

Remove the Sefer Bereishit  reference too,

![image](https://user-images.githubusercontent.com/16290361/130631940-8f40adbf-1fe7-487a-94aa-dbaf488696b1.png)

**Comment by MendyBerger** [comment]
Resolved in 79c0920011d5041e59873482480f7d767e0ff652
