### ISSUE TITLE
Add example screens to tracing frame ref

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1444]
The Zeplin page at https://zpl.io/a8nmvJE shows everything for the individual trace areas (outline color, stroke style, etc.)

But we also need a reference for how it should look on the screen in the following states. Some of this is in Zeplin within modules, but I'm not sure of the universal rules, and it would really help to have it all described in one place.

The screenshots do not yet have the correct outlines applied (it is just placeholder styling), the intent is just to help describe what's needed:

**1. Drawing/editing a trace**

![image](https://user-images.githubusercontent.com/6406986/130760850-ebb41138-dd7d-4e50-a06e-ad1edf494172.png)

**2. Selecting a trace**

![image](https://user-images.githubusercontent.com/6406986/130761237-906cd258-d4f1-47e6-8061-8c05c408ac7d.png)

**3. Hint-only traces (no mouse interactivity)**

![image](https://user-images.githubusercontent.com/6406986/130761378-eae275f2-4c38-496e-8ad0-6e7693fb65eb.png)

**4. Showing _only_ one trace with out darkening the bg (currently not implemented.. not sure if required)?**

![chrome_kt3K7grdlu](https://user-images.githubusercontent.com/6406986/130762292-40671656-ce8e-47f5-aa5a-f3d74dbc7392.png)

**Comment by GaliShapira** [comment]
@dakom 
Great, done. Updated in the Ready for Dev folder. 
[Screen Shot 2021-09-01 at 12.12.03.png.zip](https://github.com/ji-devs/ji-cloud/files/7089831/Screen.Shot.2021-09-01.at.12.12.03.png.zip)

**Comment by dakom** [comment]
thanks
