### ISSUE TITLE
Player - if last module, still need the continue button, otherwise can't end

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1446]
I am trying to get to the end of a JIG to see the score popup, but the arrow on the last module is hidden. So I cannot continue to the end. I have to use the close button, so I am not getting to the end.

Suggest - keep the arrow on the last module so that you can end the module and go to the end animation.

Happy to discuss!

**Comment by MendyBerger** [comment]
@dakom needs to send `ModuleToJigPlayerMessage::Next` event to trigger the done-popup

**Comment by dakom** [comment]
@MendyBerger I don't think this is part of the module... rather it's just about keeping the bottom player arrow.

**Comment by MendyBerger** [comment]
I discussed it with Corinne, all she wants is to be able to see the done popup once she's done, she's not really interested in the arrow-button

**Comment by dakom** [comment]
if the last module is Poster, how do we know when it's done?

**Comment by MendyBerger** [comment]
I concede, I'll add the arrow

**Comment by MendyBerger** [comment]
Resolved in fce24413
