### ISSUE TITLE
JIGs must display the author's name 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1449]
The information on a JIG must show the name of the author (see https://zpl.io/2EXoJoy).
If you look at the current info panel, it does not show the name of the author. Even worse, it shows 'See JIGs' and leads nowhere, instead of showing 'See [author's name]'s JIGs' and going on to show a list of all JIGs authored by this person.

![2021-08-25](https://user-images.githubusercontent.com/16290361/130796980-98fab331-265e-4d7b-ad75-24bdb0c40e1b.png)

**Comment by corinnewo** [comment]
When testing the search with my name, 0 JIGs turned up. Is the author's name part of the search terms? It should be!

**Comment by MendyBerger** [comment]
Blocked by #1463

**Comment by MendyBerger** [comment]
Display authors name resolved in a6dbb808

View all authors jigs #1516
