### ISSUE TITLE
JIG panel - add new module - open the activity list on right hand panel

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1460]
After watching several people (and myself) add a new module while the previous module is open on the right hand side, it is confusing that you need to look for the activities. The button to add activities is on top right of the JIG panel.

Suggestion: If you add a new module (click the + in the JIG panel), or click the module that says 'Drag activity here', then the activities should appear on the right hand side. Keep the button on the top right in any case, but add in this functionality.

![image](https://user-images.githubusercontent.com/16290361/130952906-2b89253e-c532-4aea-8128-97a1af45c781.png)

**Comment by MendyBerger** [comment]
Resolved in a27fb31467853b9aeb843cd1925ee1dc8ff59000
