### ISSUE TITLE
Home page texts correction

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1468]
I have a WORD doc with all the corrected texts and the links that should be on the home page. 
Happy to work with you to update together.
[Jigzi home page.docx](https://github.com/ji-devs/ji-cloud/files/7061216/Jigzi.home.page.docx)

**Comment by MendyBerger** [comment]
Resolved in 1527350f92b3530108fe0ddb3bad200af8d80ded
