### ISSUE TITLE
Jiggling texts - keep coming back each module even though I clicked 'Don't show again'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1475]
![image](https://user-images.githubusercontent.com/16290361/131099285-8f090d7b-2031-4356-85b2-ca5e56aacbdd.png)

**Comment by dakom** [comment]
This _should_ be fixed now... though I couldn't test until sandbox release is fixed

closing but please feel free to re-open if it isn't fixed
