### ISSUE TITLE
no logs on 400

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1484]
we had a frontend bug where we weren't sending the correct data to user image uploads

specifically, the body used to be `None` (which we are still sending) and now it has data. this will be fixed soon...

in the meantime, it caused a 400 which makes sense, but it wasn't seen in the backend logs.

**Comment by LeahWhalen** [comment]
I found a log when trying to replicate this error. I posted the images of the routes I ran and what came out of them on slack.

**Comment by dakom** [comment]
ok cool, will close for now and re-open if it comes up again. thanks!
