### ISSUE TITLE
Generated code does not play the JIG on child's page

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1489]
On sandbox, I generated a code. Copied it and then placed it in code area of child's page. Was told to try again. Did not play.
Also, the link is not generated with the code.

![image](https://user-images.githubusercontent.com/16290361/131655320-71303197-c3b3-4f72-a0c0-9f2cf0b2e8d6.png)

![image](https://user-images.githubusercontent.com/16290361/131655419-a0ec72a0-6ff2-42ad-aef2-05ceaaad3bc8.png)

I'm making this high priority, since it has to do with the flow that Chana wants to see tomorrow.

**Comment by MendyBerger** [comment]
Resolved in b415c7f1aa13d25512e7c3b563c1abcbfd582159
