### ISSUE TITLE
https://jigzi.org/kids - should not have the menu along the top

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1506]
@GaliShapira pointed out that on the kids page, where the only thing that they should be able to do at this stage is play the game from the code, the top menu should not be there.

The only thing on this page would be the code entry at this stage (later, it will be a kids' dashboard).

Please remove the menu from along the top. 

@GaliShapira Perhaps we should have the JIGZI logo, just so that it is branded? Please let me know what you think? Once we've decided, we can assign to Mendy.

![image](https://user-images.githubusercontent.com/16290361/131857499-904b3fea-74ea-4ae3-af4f-ab2f6e7a5384.png)

**Comment by GaliShapira** [comment]
@corinnewo @dakom @MendyBerger 
See the Zeplin page, Only logo to go back to home.
https://zpl.io/2pRBGry

**Comment by MendyBerger** [comment]
Resolved in 00bfcb2931d7deb7f9a5ec8a0a93d9fcbb402457

**Comment by corinnewo** [comment]
Thanks for taking down the menu and leaving only the logo. However, the logo must be clickable to go back to the JIGZI home page. It does not seem to be clickable. Please add in this link. Thanks!

**Comment by MendyBerger** [comment]
Resolved in a4d3bc432a3b0c71519c5ab4e7abe2efbe248329
