### ISSUE TITLE
add checkbox setting for image search in all modules

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1508]

**Comment by corinnewo** [comment]
Does that explain why there are no checkboxes at all at the moment?

**Comment by dakom** [comment]
yes. it's added to `Scene` (Step 1) in drag and drop though, so the functionality can be tested for all 3 scenarios. Will start going through and doing the rest tomorrow

**Comment by corinnewo** [comment]
On Jigzi, where there are definitely backgrounds, checking the checkbox does not show any results.

**Comment by dakom** [comment]
I'd consider that separate than implementing the setting across the frontend... from what I can see, it's sending the right data across. 

Closing this in favor of https://github.com/ji-devs/ji-cloud/issues/1515
