### ISSUE TITLE
Home Search - implement See all authors JIG's 

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1516]
![image](https://user-images.githubusercontent.com/12537668/131993689-9825d7ad-e3b1-493f-bde3-2c723a6fea7c.png)

**Comment by MendyBerger** [comment]
What page does this load?

**Comment by MendyBerger** [comment]
@corinnewo what page does this load?

**Comment by corinnewo** [comment]
@MendyBerger
back of card should have a link that says 'See Corinne's JIGs' (or See [firstname]'s JIGs), for example, and clicking it should be a search with the author's full name. I would like to see all the games that Corinne Ossendryver has produced, for example. The result would be a list of JIGs created by that author.

![image](https://user-images.githubusercontent.com/16290361/134505436-c4e33d34-7157-4c96-b414-0a288057c763.png)
