### ISSUE TITLE
left panel - lower part - not white

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1522]
The lower part of the left panel should always use the same light blue color and not white.

**Comment by dakom** [comment]
this is only when the content is within a tab though, right? for example, here there is no tab and it doesn't get the color: https://zpl.io/25Qo7m3

**Comment by GaliShapira** [comment]
When there are no tabs: there is a very light blue color - #f6fafe
When there are tabs: light blue a bit darker: #e9eff8

**Comment by dakom** [comment]
just spoke with @MendyBerger - he is going to look into this so re-assigning to him

**Comment by MendyBerger** [comment]
Resolved in 55807f20db008f0a8a1ce96246adf19f347ac33d
