### ISSUE TITLE
inner scrollbar for sidebar contents

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1523]
the main use case is currently specific to card modules, but we may have more in the future. I'll describe it in terms of the card modules though:

The bottom "done" button shouldn't ever be hidden behind a scrollbar. Rather, when the contents overflow, there should be an _inner_ scrollbar to scroll the words list.

**Comment by MendyBerger** [comment]
Resolved in e8d17d55b97c83d57978997be0694f5f83e056b4
