### ISSUE TITLE
Player shell for children (when opened from a code) is not full screen.

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1526]
When I play a JIG from a student code, it should play on 100% of the screen, and not a small area. This is what I am seeing on my laptop screen:
![image](https://user-images.githubusercontent.com/16290361/132688529-3a1d9a67-d32b-40f4-bcc6-2ef7851940a3.png)

**Comment by MendyBerger** [comment]
Resolved in 7989d3777e1004b42623e55b85ed76d81276a3e1
