### ISSUE TITLE
Generated a code once, then I went back to same JIG and clicked to generate again - crashed

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1528]
Once you generate a code, and it is valid for 2 weeks, then it should display if you go to share that JIG again.
I tried to generate the code again, but I then got this error:
![image](https://user-images.githubusercontent.com/16290361/132695889-1c00053d-9a0e-48c9-966d-8795fc72252b.png)

**Comment by MendyBerger** [comment]
This is a backend issue and is being tracked in #1434
