### ISSUE TITLE
Sharing a JIG with a code - the URL should not be ???? but the URL with the generated code

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1529]
When you generate a code, the URL should also be generated, so that the teacher can share the URL with the child. At the moment, the URL remains the ????
![image](https://user-images.githubusercontent.com/16290361/132696550-b0851d2d-3b9c-4c4a-b120-430a832f722c.png)

**Comment by MendyBerger** [comment]
Resolved in b828fc2a
