### ISSUE TITLE
Tapping board - editing a trace is causing an error

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1536]
**Describe the bug**
I created a trace for a tapping board. Added sound and text. THen, when I went back to edit the trace (used kebab menu and EDIT), the trace disappears and there is a console error:
![image](https://user-images.githubusercontent.com/16290361/132827250-2b97168b-4576-442d-b12f-7c9bc2073a1e.png)

**To Reproduce**
1. Go to wizard 3 - interaction
2. Create a trace. confirm.
3. Add sound and text.
4. click kebab on trace and 'Edit'

**Expected behavior**
Should allow for editing of the trace.

**Comment by dakom** [comment]
I haven't been able to reproduce this yet...
