### ISSUE TITLE
DICTA - dialog too large - can't see the copy buttons along the bottom

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1549]
THe DICTA dialog is too large - can we make it smaller? Only need one or 2 rows.  If we cannot make it smaller, then we should place it higher up so that you can see the copy buttons along the bottom.
At the moment:
![image](https://user-images.githubusercontent.com/16290361/133107551-c796fda5-f2e4-4854-a89d-8ce7c44f4b4c.png)

Have to scroll down to copy:
![image](https://user-images.githubusercontent.com/16290361/133107690-ca784e15-1af0-4921-9b8f-a1c9d2bb0509.png)

**Comment by MendyBerger** [comment]
Resolved in ea163702a4462c1a9a6d7a3c61d1a9c2e84b7c66
