### ISSUE TITLE
Home page - missing images 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1551]
SVG images for home page showing up white - they are in place in the ji cloud.
![image](https://user-images.githubusercontent.com/16290361/133246400-aaaec515-110e-4855-82ea-29e0d0ab64a5.png)

Also, please add this image placeholder until we have the video to add in.

![video-placeholder](https://user-images.githubusercontent.com/16290361/133246388-05df0873-6e9a-4ffc-940a-c695da7439f6.png)

**Comment by MendyBerger** [comment]
Resolved
