### ISSUE TITLE
Rearrange image search with background checkbox in the filter, and the web/Jigzi search beneath the search field

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1554]
Rearrange the search image layout. At the moment, the choice of searching within Jigzi or web is hidden in the Filter button.
Suggest changing the layout:

1. Move checkbox for backgrounds only into the filter area, and default will be according to tab you are in (if on background images, then default is show only backgrounds. If on stickers tab, then default is to not show backgrounds)
2. Add a toggle for search in Jigzi or Web beneath the search box, where the background checkbox is currently.
3. Later, when there is a teacher dashboard, and we have folders, then we can search within folders for images that have been uploaded.

**Comment by MendyBerger** [comment]
Resolved in b656e944
