### ISSUE TITLE
The name of the use case needs to be a subtitle under the name of the module

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1564]
It's confusing if you have chosen duplicates as the use case, but when you go into the list, you forget what should be entered into the one list.
Suggest adding a subtitle of the use case under the name of the module on the creation pages.

![image](https://user-images.githubusercontent.com/16290361/133292366-5b5338d1-2191-4fdb-965f-dfe67c1e4015.png)

**Comment by GaliShapira** [comment]
@corinnewo @MendyBerger 
See attached subtitle under the title:
https://zpl.io/bPNR01m

**Comment by johnnynotsolucky** [comment]
@corinnewo I missed that the subtitle should load from the json file. Is that the case? Currently I have it setting the subtitle based on whatever the label is set to from the code. For example, [video modes](https://github.com/ji-devs/ji-cloud/blob/sandbox/shared/rust/src/domain/jig/module/body/video.rs#L144-L147) have the strings "Introduction", "Story", "Song", "How to". These are the same strings that are used when selecting which mode to use for a game.

**Comment by corinnewo** [comment]
@johnnynotsolucky The example of the video modes is correct - "Introduction", "Story", etc should be the subtitle. Most important for the user is in the card series of modules. Need to know if it is image+text, or synonyms, etc..
