### ISSUE TITLE
Drag activity to panel - must have click as well

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1568]
Activity list - drag to the JIG panel. Must be able to click and drop on the new module as well.

We need a design for how this will work - thanks!

**Comment by GaliShapira** [comment]
Hi @corinnewo I believe the following issue: https://github.com/ji-devs/ji-cloud/issues/1590 
is a reply to this issue as well. Isnt it?

**Comment by corinnewo** [comment]
Duplicate - rather go according to #1590.
