### ISSUE TITLE
Set debug_assertions to true for sandbox

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#1576]
Should still be release mode though

**Comment by dakom** [comment]
probably this in Cargo.toml everywhere:

```
[profile.sandbox]
debug-assertions = true
```

and this to rollup:
```
--profile sandbox
```

**Comment by corinnewo** [comment]
@MendyBerger David removed his assignment to this. Is this still relevant to be done?

**Comment by dakom** [comment]
Btw I _think_ the original intent of this was to get better logging when panicing on sandbox, but I'm not sure if `debug-assertions` really affects that. I think at the time we were also gating logging behind that rather than having the logging-specific features enabled.

So imho I think this could probably be closed, and then only re-opened if it turns out to be necessary, but I don't remember 100%

**Comment by dakom** [comment]
Btw I _think_ the original intent of this was to get better logging when panicing on sandbox, but I'm not sure if `debug-assertions` really affects that. I think at the time we were also gating logging behind that rather than having the logging-specific features enabled.

So imho I think this could probably be closed, and then only re-opened if it turns out to be necessary, but I don't remember 100%

**Comment by corinnewo** [comment]
@dakom Thanks - closing!
