### ISSUE TITLE
Menu - hover state is missing

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1595]
On the menu, the hover state for the different items is missing. 

<img width="383" alt="Screen Shot 2021-09-29 at 22 45 13" src="https://user-images.githubusercontent.com/88834002/135338114-fa086d3f-e379-4259-9437-10bb3c868708.png">

<img width="106" alt="Screen Shot 2021-09-29 at 22 45 17" src="https://user-images.githubusercontent.com/88834002/135338123-6d781cb4-9f49-4928-adef-4555730bba70.png">

https://zpl.io/Vqd1dem

**Comment by MendyBerger** [comment]
Resolved in e8e50ad4
