### ISSUE TITLE
Create: Card games with image - must be able to change the image on a card

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1596]
Once a sticker is selected and dragged into the card in the word-picture memory game, there is no option to delete or change the sticker. 

I created a memory game and accidentally selected the wrong image, there was no way to change it:
![Screen Shot 2021-09-27 at 4 44 51 PM](https://user-images.githubusercontent.com/78186896/135369069-d0fb687c-fd90-4c36-988d-8ece8fd891d6.png)

Please allow to edit/ change the image.

**Comment by corinnewo** [comment]
@MendyBerger Can we allow that you can drop in another image to swop it out?

**Comment by corinnewo** [comment]
Yes @MendyBerger - being able to drop in another image would solve this problem!

**Comment by MendyBerger** [comment]
Resolved in 74d2fb85
