### ISSUE TITLE
Create: Module memory game - add pair user action

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1597]
When clicking "add pair" in memory game, it's hard to tell that the button performed its action (can only tell that a new pair was added once you scroll all the way to the bottom - I kept on clicking "add pair" until I realized that I added multiple pairs and did not notice).

Suggestion: add a sound when clicking the button to indicate a reaction from the system
or 
show a screen change to give visual feedback

![Screen Shot 2021-09-27 at 4 45 50 PM](https://user-images.githubusercontent.com/78186896/135384585-f384153d-3be2-4b8c-8c25-b81bd0deeb2c.png)

**Comment by corinnewo** [comment]
@MendyBerger agreed that on clicking 'Add pair' button, he will automatically scroll down to the bottom where the new pair is added. In this way, user would notice that a new pair has been added.
