### ISSUE TITLE
Create Menus: My recent - images cut off

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1598]
In recent images, some stickers are cut off (if they are vertical/ long stickers)
Suggestion: Expand the space for "my recent" images

![Screen Shot 2021-09-27 at 4 41 36 PM](https://user-images.githubusercontent.com/78186896/135385857-72a45801-15c1-4593-87b8-63b372dd48d8.png)

**Comment by MendyBerger** [comment]
Note: We've dealt with this issue in the past, Have to figure out why it keeps popping up, can it be the difference in sizing based on responsive design?
