### ISSUE TITLE
Create: Memory Game - ask are you sure? before creating a new list

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1599]
When creating a memory game, there is an option to "create new list." This will delete all that was previously created and a user might accidentally delete all their data.

Suggestion: add a confirmation that says: are you sure? you will lose your cards / This action cannot be undone or something along those lines.

![Screen Shot 2021-09-30 at 12 19 42 AM](https://user-images.githubusercontent.com/78186896/135387847-7bae866a-1ab5-465c-8b7e-e61c89547a91.png)
..

**Comment by corinnewo** [comment]
@johnnynotsolucky Please add this confirmation on the first tab too - there is a clear button, and I would like the same confirmation if there are words in the list, then if you click clear, must confirm. Thanks!
![image](https://user-images.githubusercontent.com/16290361/157843254-22d860df-598a-499f-926e-bfc4acba1806.png)

**Comment by johnnynotsolucky** [comment]
@corinnewo will do!
