### ISSUE TITLE
Change Creator Jiggling design to the old illustration. 

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1604]
**On Creator upper right panel:**

https://zpl.io/VDgrydv

![Jiggling_Creator_Hover](https://user-images.githubusercontent.com/88834002/135835247-773a21b6-3267-4236-a3cf-c2b38cf6f932.png)
![Jiggling_Creator](https://user-images.githubusercontent.com/88834002/135835257-4be452ae-eb93-4f14-8c97-422759b7db8f.png)

**On Homepage Jigglings section:**
https://zpl.io/bAen5Bn
Idle + Hover states as in the attached preview:
<img width="588" alt="Screen Shot 2021-10-04 at 13 31 21" src="https://user-images.githubusercontent.com/88834002/135836584-2c6ab9fc-2454-4440-84ac-2d24f295588c.png">

<img width="580" alt="Screen Shot 2021-10-04 at 13 31 27" src="https://user-images.githubusercontent.com/88834002/135836565-67f17a3e-4b1a-4e40-849d-0ac88ff8aa4c.png">

**Comment by MendyBerger** [comment]
Resolved
