### ISSUE TITLE
Theme choice with default text "Shalom שָׁלוֹם" in place

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1621]
@MendyBerger - Spoke with @dakom about this, and he said to talk to him about it. 

When choosing themes, you click around and the background changes, but the fonts are an important part of the choosing process. I would like to add in a single H1 text that says "Shalom שָׁלוֹם" when you go into a THEME tab FOR THE FIRST TIME. In this way, the fonts can be highlighted. Users can then use this as the default text when they get to the text tab, or simply delete it.

It would make the theme choice much more meaningful.

**Comment by dakom** [comment]
on a technical level this isn't about themes or tracking first-use. Rather, it's merely about changing the relevant `Default` impl. For example, the common [BaseContent](https://github.com/ji-devs/ji-cloud/blob/bc3649974957ff27cc441e849aa0cd447bad7602/shared/rust/src/domain/jig/module/body/_groups/design.rs#L8) could have a manual impl which populates initial stickers with text

**Comment by corinnewo** [comment]
This is med to high priority....

**Comment by MendyBerger** [comment]
@dakom the problem with that is that base content is in shared but the default text needs to have information from the text component like default font and color

**Comment by dakom** [comment]
I don't remember the exact issue, but on a pure code level, it could be a function on the trait which takes font and color as parameters?

**Comment by corinnewo** [comment]
@MendyBerger We need to find a solution to this! Escalating.

**Comment by corinnewo** [comment]
@MendyBerger Please can we revisit this and find a solution. @ChaykeeMor wrote: Could we upgrade this one to critical? It is a HUGE pain point and users will leave if they get frustrated so early on.
