### ISSUE TITLE
End of module (non-card set) - add in extra options

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1627]
At the end of creating a module at the moment, there is only one option - to continue. I would like to suggest changing this to

1. Instead of **Continue**, change to **Add an activity** - clicking this will add in a new module (like clicking +) immediately after the current module, and then open side panel and activities screen.
2. Add in **Publish** button, and clicking this will take you directly to the publish dialog.

What do you think, @GaliShapira ? If you agree, then we need the icons for Add an activity and Publish. Let me know.

**Comment by GaliShapira** [comment]
@corinnewo  I believe we discussed it in ideation and decided not to do it for now.

**Comment by corinnewo** [comment]
OK - but I am keeping this open, as I think the ability to choose to go to Publish directly or to add another module directly will streamline the process greatly.
