### ISSUE TITLE
Kebab menu on image - reduce size of font for items

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1643]
Reduce size of font so that each item is on one line and not spilt over 2 lines - @GaliShapira  please suggest font sizes. 

![image](https://user-images.githubusercontent.com/16290361/137132668-7ea0cf10-1e9b-48e4-8b78-1f9ab3589750.png)

**Comment by MendyBerger** [comment]
Why not just make the menu wider so that the text fits on one line?
