### ISSUE TITLE
Sound effects in JIG settings - don't have any effect in the player

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1650]
I selected a few sound effects for correct and incorrect answers in the JIG settings. I also selected background music. When I previewed the JIG, none of these sounds play.

Wait - it did, just in the player, the music is off by default. 

Defaults - music on
Correct effects - select first 3 by default
Mistake effects - select first 3 by default

When correct answers, play randomly one of the correct effects.
When an incorrect answer, play randomly from the mistake effects.

**Comment by MendyBerger** [comment]
Not sure I understand the issue, mind giving me step by steps guidance to recreate?

**Comment by MendyBerger** [comment]
@corinnewo can't recreate this issue

**Comment by corinnewo** [comment]
@MendyBerger It seems to be working now on sandbox! Any reason you reopened it?
