### ISSUE TITLE
Wizard steps - very unclear

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1661]
@GaliShapira Please let's look at the coloring of the wizard steps again. Not clear where I am. Should we only highlight where you are currently and the steps leading up to it, so if you go back to step 2 from step 3, then step 3 is not highlighted anymore.
Happy to meet to finalise

![image](https://user-images.githubusercontent.com/16290361/137280271-0b78dfcb-4ed2-4b1c-9336-ad9256ccd254.png)

**Comment by corinnewo** [comment]
Much better - thanks!

**Comment by MendyBerger** [comment]
Resolved in fa11f1b6
