### ISSUE TITLE
Add Jiggling to the activities page - to click and get help

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1666]
The Jiggling is supposed to be on the Creator page.  See https://zpl.io/a8nJp1E

Please add it and have the same functionality as on module pages - can click it to get the help text. If possible, to make the help text read from a JSON file, so that we can edit it.

**Comment by MendyBerger** [comment]
Not easy to add to json, mind pasting the text here?

**Comment by MendyBerger** [comment]
Resolved in 007288f4

**Comment by corinnewo** [comment]
@MendyBerger Here is the text for the Activities screen for the jiggling:

Want to add an activity to your JIG? Just drag it to the JIG panel on the left. You can change the order of the activities any time.

**Comment by MendyBerger** [comment]
Resolved in bb5387f8
