### ISSUE TITLE
Create: Memory game-  end of module

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1671]
I created a memory game and completed the preview stage
then it says - "what do you want to do next? use the content in this memory game in..."
I picked "Matching" 
screen went blank and I can't click on the arrow to open the sidebar
(I have to go back to home page, create and open the draft to go to the activity)

![Screen Shot 2021-10-14 at 3 08 57 PM](https://user-images.githubusercontent.com/78186896/137383358-a95b8f08-80b0-4968-8cd4-466f33335a60.png)

**Comment by MendyBerger** [comment]
@chayaml having trouble recreating, mind checking again if this still happens
