### ISSUE TITLE
Memory Game: Publishing a Module - Hebrew Keyboard 

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1673]
Before Publishing a Jig in "Settings and Jig info - last steps before publishing", the Hebrew Keyboard doesn't show up properly.

( later I noticed that I am able to grab the keyboard and move it around the screen but some of the text in the background wraps to the front) 
![Screen Shot 2021-10-14 at 7 40 38 PM](https://user-images.githubusercontent.com/78186896/137409824-ec0f5eec-284c-4136-8935-a0184a3e9177.png)

![Screen Shot 2021-10-14 at 4 45 57 PM](https://user-images.githubusercontent.com/78186896/137408229-994d38c2-a84d-4327-a629-bb32c6d650ad.png)

**Comment by MendyBerger** [comment]
Resolved in ea163702a4462c1a9a6d7a3c61d1a9c2e84b7c66
