### ISSUE TITLE
Create: Memory Game - Text Panel - scrolling down

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1674]
When creating a cover, I clicked on the dropdown list to change the font. I can scroll down the font dropdown list, but its hard to look through since it hits the bottom of the screen. I expected to be able to scroll down the entire text Panel to see the drop down menu better.

Suggestion: In Text Panel, add scrolling feature.

![Screen Shot 2021-10-14 at 8 18 18 PM](https://user-images.githubusercontent.com/78186896/137413185-b850852f-b1b4-4573-bbe4-3fce7d0944da.png)

**Comment by chayaml** [comment]
Hi @MendyBerger, this is the font scrolling issue I mentioned at the meeting 

When I exit full screen mode I am unable to click on the dropdown menu at all and scroll through the fonts:
![Screen Shot 2022-01-11 at 11 47 16 PM](https://user-images.githubusercontent.com/78186896/149065974-02551a0f-abc7-48d6-bf28-d93c2023b311.png)

**Comment by MendyBerger** [comment]
@corinnewo MVP?

**Comment by corinnewo** [comment]
Is this one of the overlay issues? 
On my laptop, the pulldown does not open at all, just the arrow spins around. It really is unusable on a smaller screen. But I think it can wait until after the MVP.

![image](https://user-images.githubusercontent.com/16290361/150097031-037d3ac2-6ad8-4fb5-b337-0ce98bfe2874.png)

**Comment by MendyBerger** [comment]
Yes, overlay issue

**Comment by corinnewo** [comment]
We moved the pull-down further up the panel. CLosing this issue.
