### ISSUE TITLE
JIG panel - New activity icon for cover

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1681]
Hi @corinnewo 

A new icon card was added to the activities page for the cover:
1. Its placed top left near the cover.
2. The name area is yellow as well as the cover area on the JIG before it has a thumbnail.
3. The cover default state on the JIG panel is yellow with text. 
4. To the cover area on the JIG, only a cover activity can be dragged. If the user drags another activity to the cover, they get an error message, [see the page on Zeplin](https://zpl.io/amxYYgr) 
5. The cover icon can be dragged anywhere on the JIG. 

<img width="568" alt="Screen Shot 2021-10-15 at 11 53 52" src="https://user-images.githubusercontent.com/88834002/137460859-955e7594-7f9e-473c-86ee-6a4e12e3bb79.png">
<img width="478" alt="Screen Shot 2021-10-15 at 11 54 38" src="https://user-images.githubusercontent.com/88834002/137460888-5f4b8b09-bfb5-4405-9012-0c8401d526fb.png">
<img width="334" alt="Screen Shot 2021-10-15 at 11 54 16" src="https://user-images.githubusercontent.com/88834002/137460904-7a14faf3-0143-431e-aa29-6f25169adb59.png">

Icon's states: https://zpl.io/VYlz7Je

Screen and behaviour: 
https://zpl.io/a8q66Ox
https://zpl.io/amxYYgr

**Comment by corinnewo** [comment]
@GaliShapira If the user tries to place any activity **other than the cover** to this space, there should be a 'no entry' cursor, and if they drop it, it flies back to place on the right. (As happens now, when trying to place an activity card on an activity that exists.) Will the message appear while they are over the module, or when the card flies back? 

Message should say "Only a cover activity can be placed here!", but I am not sure when it will actually be displayed.

**Comment by MendyBerger** [comment]
Resolved in 9d8ce968
