### ISSUE TITLE
Duplicating a module in the JIG panel causes a crash

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1683]
I used the kebab menu in the JIG panel on a memory game to duplicate it, and there was a crash.
![image](https://user-images.githubusercontent.com/16290361/137476078-147643aa-6171-4a65-868f-a7ae1948f4dc.png)

![image](https://user-images.githubusercontent.com/16290361/137476158-96bbc1d6-8de8-4823-ae86-249d6e972099.png)

**Comment by MendyBerger** [comment]
Crashes resolve in 8b3a57f2
