### ISSUE TITLE
www.jigzi.org not working

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1685]
www should redirect to the apex domain

**Comment by mastapegs** [comment]
I checked out the response headers for [jigzi](https://jigzi.org/) and noticed that GCP is used for deployment.

I checked out their docs for adding sub-domains and wanted to include it [here](https://cloud.google.com/appengine/docs/standard/python/mapping-custom-domains#using_subdomains) for reference.

![image](https://user-images.githubusercontent.com/13839150/137732840-975600fa-7f26-43c3-a290-e46dc5788517.png)

**Comment by dakom** [comment]
Thanks @mastapegs !

Yes, one one foot our deployment is:

1. Runtime servers (API, pages): Google Cloud Run. This is what needs to be configured to serve the subdomain
2. Static content (SPAs, media): Fastly CDN backed by Google Cloud Storage (and a cloud function to purge the CDN cache on individual file changes)

Within the media, we differentiate between user-generated content and our static dev content like UI images.

The static content is a bit controversial in that it is not versioned along with source code, rather it is pushed via Dropbox. The reason for this is to make it very simple for designers to make changes without having to worry about GitHub, git LFS, etc. I could imagine that this part of the architecture will change in the future, but for now it is very convenient. The downside is that unlike everything else which is isolated between sandbox and release, this endpoint is shared between them (i.e. we can only change UI images in both simultaneously)

**Comment by corinnewo** [comment]
www.jigzi.org still not working
![image](https://user-images.githubusercontent.com/16290361/155540892-1777084a-7342-46e5-957d-d271fb3787b4.png)

**Comment by MendyBerger** [comment]
Notes:
Probably needs to be handled in cloud run `ji-cloud-pages`
Needs to be mapped in https://console.cloud.google.com/run/domains

**Comment by corinnewo** [comment]
@MendyBerger Now that we are live and people are using Jigzi, this is critical to fix, as people are going to type in www.jigzi.org and it still crashes. Please can this be escalated to fix? All our marketing documentation has www.jigzi.org, and we need to have this working! Please! This has been HIGH PRIORITY for months already.

**Comment by MendyBerger** [comment]
@johnnynotsolucky think you can take a look at this?

**Comment by MendyBerger** [comment]
@johnnynotsolucky have you had a chance to look into this issue?
