### ISSUE TITLE
Tapping board - Interaction step - preview button not styled

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1689]
1. The instruction is missing . Should say "Add text to appear with the sound (optional)"
2. The preview button should be styled as shown here: https://zpl.io/a7XDR5v.
3. Also Delete button is missing to delete the text.

![image](https://user-images.githubusercontent.com/16290361/137708088-9e78a255-b871-42a5-85a8-519755d4f7f0.png)

**Comment by ChaykeeMor** [comment]
@corinnewo I suggest no instructions but the text field heading should read: 'Label this item as:' 
If we add instruction also, should say: 'Optional text to appear on active item'
@MendyBerger could we please add: hebrew keyboard and dicta tools (does @GaliShapira have to design it here first?)

**Comment by corinnewo** [comment]
closing in favour of #2976
