### ISSUE TITLE
Create: Cover - background and content wizard steps unclear

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1690]
When creating a cover, 
I selected a theme (Wizard step 1)
then I went to the background (Wizard step 2), "image" tab, and unclicked the "show only background"
I was searching for images (stickers) to add to my cover, and they all showed up enlarged (as backgrounds)
then I went to content (Wizard step 3) and saw that I can add text and images, and the images show up normal size

I think that either

1) In background step 2, only background images should be available in the search (user doesn't need regular stickers until the next step- content)

2) It would be easier to edit the background and content in one tab. I'm not sure what the difference is between background and content. If I selected a theme, I have my background already. When I go to background, I can change the theme colors/ add overlays, but when changing the color the theme no longer appears.

I think this is for @corinnewo . I hope I was clear - let me know if you have questions!
![Screen Shot 2021-10-18 at 9 42 18 AM](https://user-images.githubusercontent.com/78186896/137746824-2ff89cea-ac4f-424b-84e7-bffdcc7eb819.png)

![Screen Shot 2021-10-18 at 10 04 15 AM](https://user-images.githubusercontent.com/78186896/137746909-62c2c8cf-4707-4f48-8f65-d8be3b80148d.png)

**Comment by corinnewo** [comment]
@chayaml There is a problem with the instructions at the moment - all refer to background even though it is images. We have a ticket and we need to sort it out urgently! I will keep this ticket open to check that it is resolved when the instructions and search have been fixed.

**Comment by corinnewo** [comment]
I am closing this ticket as we are combining the Theme and Background tabs, so this should be taken care of there.
