### ISSUE TITLE
Drag and Drop - Settings - Instructions and Final Feedback are opening up the same tab

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1698]
**Instructions** should open up the tab where you record instructions that will be played at the start of the activity.
**Final feedback** should open the tab for feedback that is played after completion of the activity.

At the moment they are opening up the same tab and dialogs.

![image](https://user-images.githubusercontent.com/16290361/137770993-69ac6c12-c262-4eab-8211-da760f89f0d6.png)

**Comment by MendyBerger** [comment]
Resolved in e783eed0
