### ISSUE TITLE
Always have a module on Jig panel 'Drag activity here'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1702]
When you drag in an activity to the panel, immediately add in a new empty module to drag an activity to. If you do not fill it up, then it will not be published. Original zeplin shows that this was the way to was supposed to be programmed.
Should never have a state where you have to click the + button in order to have a module to drag to.

**Comment by MendyBerger** [comment]
Resolved in a2df8bbc3409345e4939fa151081e1c1ac18d86a
