### ISSUE TITLE
All modules - After preview and DONE - the Continue button should open the JIG together with the activities on the right

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1703]
After publishing, click Continue button, should:
1. Open the Jig panel
2. Swop to activities on right hand side
3. Make sure that there is an empty module 'Drag activity here' ready to receive the new activity that will be dragged in.

**Comment by corinnewo** [comment]
At the moment it is opening the JIG panel, but not putting the activities on the right hand side. User has to go and find the icon to open activities. Will be much easier just to open up the activities automatically on the right.
![image](https://user-images.githubusercontent.com/16290361/141253510-598f17d3-f4bd-40db-a8a8-b3ecfa550b1f.png)

**Comment by MendyBerger** [comment]
Resolved in 481b3373
