### ISSUE TITLE
Publish dialog - add a link next to Publish button to come back later to publish, and close it without publishing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1704]
If you open the publish by mistake, you must be able to close, without having to publish.
Gali added a hyperlink.
https://zpl.io/bJoQWOx

**Comment by GaliShapira** [comment]
@corinnewo 
 I suggest adding "close" as a secondary button (or a hyperlink). I had this in the first design, the ideation team asked to take it off because we wanted to encourage to publish.

**Comment by GaliShapira** [comment]
Done. I added a hyperlink. 
https://zpl.io/bJoQWOx

**Comment by MendyBerger** [comment]
Resolved in d20a4501
