### ISSUE TITLE
Create: Landing page - filter dropdown menu for "my recent Jigs" doesn't yield results

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1707]
In the filter dropdown menu, theres "show drafts", "show published Jigs" etc, but clicking doesn't return results

![Screen Shot 2021-10-18 at 3 53 50 PM](https://user-images.githubusercontent.com/78186896/137797815-5352be43-ac3c-4b16-87f4-faafd1de34f1.png)

**Comment by MendyBerger** [comment]
Closing in favor of #1743
