### ISSUE TITLE
JIG panel when closed - add settings icon

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1711]
When the JIG panel is closed, Gali had made a new design - she added the icon for the settings to the closed panel so that users can access it from  the closed panel, and also the Jiggling text can refer to it easily. Also more chance that it will get noticed!

1. Please add in the JIG settings icon to the closed panel as per https://zpl.io/2En3vRl
2. Now that the modules on the closed panel are clickable, please change the cursor from the drag to the click pointer cursor

This is connected with #1710 that Chaya noted

**Comment by MendyBerger** [comment]
Resolved in 96f56a85
