### ISSUE TITLE
When loading a page or loading an image - need some sort of loader animation

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1717]
Sometimes it takes a while to load a page or image - it seems stuck. I think that if we have a loader animation, it will help to know that something is happening.

**Comment by GaliShapira** [comment]
Hi @corinnewo I updated the image search component

**Comment by corinnewo** [comment]
This is not regarding the layout of the image search. It is having some sort of progress bar indicator when an image is being uploaded.

**Comment by corinnewo** [comment]
Duplicate of #1824
