### ISSUE TITLE
Add hover feature for "My Pairs"

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1724]
In Memory game,  the matched pairs appear on the left hand side in the "my pairs" column. Currently, only one card from the pair is visible.  

Suggestion:  I think it would be helpful that while a user hovers the mouse over a card/ pair, both cards become visible and separate into two. This would reinforce the learning process and be helpful in the activity. A user can see the matches they made and compare them with what's left on the screen.

![Screen Shot 2021-10-19 at 12 25 08 PM](https://user-images.githubusercontent.com/78186896/137953499-1c841e55-5e94-40f5-b1a7-bcc33f393357.png)

**Comment by corinnewo** [comment]
Closing in favor of https://github.com/ji-devs/ji-cloud/issues/3331
