### ISSUE TITLE
Admin page: Clicking on "Add image" on the right hand side of screen causes a crash

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1726]
(Clicking "add image" on the left side menu seems to work)

![Screen Shot 2021-10-19 at 5 43 29 PM](https://user-images.githubusercontent.com/78186896/137995311-6421a3c9-c22e-43d3-80de-4b435fa43604.png)

![Screen Shot 2021-10-19 at 5 48 15 PM](https://user-images.githubusercontent.com/78186896/137995533-ad80373b-3fcf-4281-a6cc-1a9c021d8579.png)

**Comment by chayaml** [comment]
Sorry I missed this - yes @MendyBerger I am still experiencing this issue. Clicking the +add image button on the right side causes a crash

**Comment by MendyBerger** [comment]
Having trouble reproducing, are you available to show me?

**Comment by corinnewo** [comment]
@MendyBerger It's working for me on https://jigzi.org/admin/image-search?q= - can click Add image button and it goes to the add image page. @chayaml - did you meet with Mendy to show him what 's happening?

**Comment by chayaml** [comment]
Ok just realized this - the bug only happens after I publish an image and click on that button to add another one. 

https://user-images.githubusercontent.com/78186896/140176074-d6447ae3-6d06-49bf-a18e-db9df77ec079.mov

**Comment by MendyBerger** [comment]
Thanks @chayaml! With this info I was able to recreate, will look into it

**Comment by MendyBerger** [comment]
Resolved in 7656ad16
