### ISSUE TITLE
Is project open for contributions? 

### ISSUE THREAD

**Issue by vbmade2000** [ji-devs/ji-cloud#1729]
I am a Rust newbie and want to contribute to learning more. I want to try some contributions in the backend in this repo. Is it possible?

**Comment by dakom** [comment]
Contributions are more than welcome!

Though we don't have the bandwidth to improve docs or explain things in detail right now, if you find a specific issue you feel you can tackle, please feel free to comment or make a PR and the dev who it's currently assigned to will discuss with you.

**Comment by vbmade2000** [comment]
Sure. Thanks. Will find something.
