### ISSUE TITLE
Coming soon tooltip and BETA sign

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1735]
Hi @corinnewo 

This is the tooltip for the coming soon message.
https://zpl.io/ag5Z3qM

**Comment by corinnewo** [comment]
@MendyBerger Please add on the 'Coming soon' tooltip when you click Classroom or 'Community'. Also, please add in the BETA icon fixed on the top left, according to Gali's design. THanks!

**Comment by corinnewo** [comment]
Closing in favour of https://github.com/ji-devs/ji-cloud/issues/2365
