### ISSUE TITLE
Poster - reorganize the tabs:

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1737]
Poster - reorganize the tabs:

1. Take out theme tab
2. Wizard will be **Background | Content | Settings | Preview** so that it is consistent with all the other modules
3. Settings will have the audio that will play on the screen, identical to the Instructions in other modules, except for instruction.
4. Sound tab will be removed from the content tab

**Comment by MendyBerger** [comment]
Resolved in af829bb0
