### ISSUE TITLE
Setting the theme in the JIG settings does not set the theme in the individual modules

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1739]
When you change/set the theme in the JIG settings, it should set the theme for the whole JIG.
Currently, when you drag in a new module, it is not taking on the settings of the JIG theme.

**Comment by chayaml** [comment]
Setting the theme now applies to the whole Jig, when dragging in new modules. However, if you go back to change the theme in the cover, it will not change the themes in the rest of the modules. (Only If a new module is added, it opens as the new theme.) Changing the theme should change the theme in all existing modules.

**Comment by MendyBerger** [comment]
@corinnewo @chayaml think you both disagree on what should happen if the user changes the theme after the module was already created

**Comment by corinnewo** [comment]
@chayaml We made a decision that changing the theme in a module does NOT go back and change the whole JIG. It sets the global theme from here onwards. If you want to go back and make the same theme throughout the JIG, you can go back and manually change each module's theme to the same one. 

In fact, we took choosing a theme for the JIG out of the settings on the left hand panel, as it was just too confusing. It works very simply now - just choose a theme for this module. This will affect the default theme for the next module. But nothing gets updated backwards!
