### ISSUE TITLE
Signup - Verifying email on phone and then logging in from a different device should be acceptable

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1740]
This has happened to several of our testers:

1. Sign up on PC/Mac
2. Email sent for verification
3. Verify the email on phone
4. Go back to original device and try to login now that email verified - cannot login and complete registration - end up in a loop

Must be able to verify on a phone and then be able to log in on the original device and continue to complete the registration.

Here is one report:
"I'm having this issue again and I think it has to do with a registration issue. Here's why: I start the sign up. I get sent an email. I pick up my phone to check my email and confirm there because it's easier for me. One i've confirmed, I reload the page on my computer thinking it would get me to the next step. It doesn't so I go back to my phone to 'hand-off' my open registration page from my phone to the computer. NOW I can fill stuff out but it throws me in a loop...Registration is incomplete so now I'm neither able to register nor login."

**Comment by MendyBerger** [comment]
Resolved
