### ISSUE TITLE
Signing up - email field errors (first step in signing up)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1751]
Please put in the red feedback for the following errors:
Don't put in an email format -  "Invalid email address"
If email is blank - "Input email" 
If password is blank = "Input password"

**Comment by MendyBerger** [comment]
@corinnewo still applicable after the recent updates in sandbox?

**Comment by corinnewo** [comment]
We still need feedback on email address errors. What would you suggest, if not these?

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by MendyBerger** [comment]
I've added error messages that are roughly the same as these, you can try them on sandbox
