### ISSUE TITLE
Login / Registration -  Change illustrations

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1754]
Hi @corinnewo @MendyBerger 

Pls see the illustrations for the login and registrations screens.
https://zpl.io/bz3g0y7

**Image 1** is the same in:  Login / Registration / Time to Register / you don’t appear to have an account yet 
And then **images 2-5** are in order of progress. Email sent and the 3 steps.
**Image 6** - I created 2 options: 
Option 1 - at the size and place of the image as is now. 
Option 2 - If we have time (nice to have) - the illustration is better on a full-page design...

![log-in-1-100](https://user-images.githubusercontent.com/88834002/138758369-84d8dfb0-b76b-4669-a2e7-69b71c492cd7.jpg)
![log-in-2-100](https://user-images.githubusercontent.com/88834002/138758387-ba3bc101-65c7-4e36-a3a5-e13e33257135.jpg)
![log-in-3-100](https://user-images.githubusercontent.com/88834002/138758388-8a211a2f-90eb-4c38-b442-230d9396d162.jpg)
![log-in-4-100](https://user-images.githubusercontent.com/88834002/138758392-7150eb0e-0f94-40e4-b8f5-b5dd56dc6af2.jpg)
![log-in-5-100](https://user-images.githubusercontent.com/88834002/138758396-797ec2b7-cadd-4cfd-af2f-bcb24d8d6b5a.jpg)
![log-in-6-100](https://user-images.githubusercontent.com/88834002/138758400-dd66ad2e-e315-471f-8129-4b4a26d94d92.jpg)
![log-in-6-1920 1080-100](https://user-images.githubusercontent.com/88834002/139029075-6082c7ad-f8d8-4c64-b834-40c772aea0f0.jpg)

**Comment by MendyBerger** [comment]
@corinnewo should this really be in the MVP milestone?

**Comment by MendyBerger** [comment]
@corinnewo ?

**Comment by GaliShapira** [comment]
@MendyBerger If this cannot be done for the MVP can I at least give you 2 images to replace as they are? one for all the screens on the registration and login, the other for the welcome page?

**Comment by MendyBerger** [comment]
Resolved in 02d0a5016
