### ISSUE TITLE
Publish - pulldown lists are now suddenly transparent

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1757]
The pulldown menus in Publish are suddenly transparent. These should be white opaque.

Happened to see while demo'ing to the Israeli Government, so it was pretty bad! Hoping this is a quick fix!

![image](https://user-images.githubusercontent.com/16290361/138916301-94dbe87a-ac1b-4e49-bd50-e0b3f8f67581.png)

**Comment by MendyBerger** [comment]
Closing in favor of #1807
