### ISSUE TITLE
Add Google analytics to jigzi.org

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1762]
I have set up a new property in Google analytics for Jigzi.
Please add in the tracking code to the site - every page.

PROPERTY ID
291387160

MEASUREMENT ID: 
G-K8CP9TNPEV

STREAM ID: 
3019826819

The setup of Google Analytics has changed since I last set up a site. I cannot find the embed code to include here for the site. Please advise!

**Comment by MendyBerger** [comment]
Resolved in 059ab15203d49096b6c3f8eec2fd248b7a772f15
