### ISSUE TITLE
Image search - sizing of the images on the panel is not correct (not happening on all computers)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1763]
I searched for candles, and this is what was returned. THe candles at the bottom are overlapping the girl in the upper row. All image thumbnails should have maximum height.

![image](https://user-images.githubusercontent.com/16290361/139080721-edbe3475-c7db-45f3-b9a2-23356276405c.png)

**Comment by corinnewo** [comment]
Happening on my computer and on Chana's computer.

**Comment by MendyBerger** [comment]
Resolved in 8ce2358d
