### ISSUE TITLE
Icons for Hebrew keyboard, Dicta and Sefaria missing on text tabs (Drag&Drop sandbox only)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1772]
Icons missing on sandbox. Seems to be working on jigzi.org

![image](https://user-images.githubusercontent.com/16290361/139284065-3a23cb49-dcf4-4826-b028-09ce7e2581e0.png)

**Comment by corinnewo** [comment]
@MendyBerger The icons are still missing in the DRAG AND DROP activity. It seems that they are working in the other activities.

**Comment by MendyBerger** [comment]
Resolved in 1772
