### ISSUE TITLE
Change the red color of hyperlinks to "Main_Blue"

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1798]
Hi @MendyBerger @corinnewo 

Change the color of hyperlinks to Main_Blue
on the following:
- Clear  (In add a list of words)
- Creat a new list (In add a list of words)
- Clear (In playing a sound that was recording)

<img width="392" alt="Screen Shot 2021-11-03 at 16 44 51" src="https://user-images.githubusercontent.com/88834002/140083981-c62d69ae-1b8d-4381-8306-b929cd620598.png">

<img width="388" alt="Screen Shot 2021-11-03 at 16 45 07" src="https://user-images.githubusercontent.com/88834002/140083971-2a46ed49-e812-48d6-b9bf-0d7dec35ae9a.png">

<img width="388" alt="Screen Shot 2021-11-03 at 16 59 56" src="https://user-images.githubusercontent.com/88834002/140085743-8adbf5e6-080d-4691-9c29-7aacbd6f54f6.png">

**Comment by MendyBerger** [comment]
Resolved in 9bdf2366
