### ISSUE TITLE
scrolling not comfortable

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1801]
1. When I scroll on the JIG panel activities, the scroll is not showing the text of the activities on the bottom line
<img width="1430" alt="Screen Shot 2021-11-03 at 17 02 19" src="https://user-images.githubusercontent.com/88834002/140087561-b01e5405-853c-443e-a004-70106949cd23.png">
.

2. When I scroll on the activities page and the Jiggling bublle is open, the bublle is stickey at the middle of the page. Should be scrolled.
<img width="1416" alt="Screen Shot 2021-11-03 at 16 56 39" src="https://user-images.githubusercontent.com/88834002/140088032-e6a7685e-baa1-4bad-ae5b-b8468f38d05a.png">

3. On the color component the add color button does not have a bottom margin.
<img width="430" alt="Screen Shot 2021-11-03 at 17 03 23" src="https://user-images.githubusercontent.com/88834002/140087749-6ca24618-8bb4-43a6-bc44-294044900b8a.png">

**Comment by MendyBerger** [comment]
Resolved in 86c69493 and in 8b83cbb8
