### ISSUE TITLE
Homepage - Start Creating button

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1802]
The button should have a regular button margin. 24 pixels from each side.

<img width="800" alt="Screen Shot 2021-11-03 at 16 43 48" src="https://user-images.githubusercontent.com/88834002/140088262-d91d87bd-f93e-499a-9fb2-c18f53eca44f.png">

**Comment by MendyBerger** [comment]
Resolved in 05e19b17
