### ISSUE TITLE
Drag and drop - drag icon and text on a small size screen

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1803]
Hi @MendyBerger @corinnewo 

On a small size screen this icon should be reduced size, text can be reduced to 13, they both should be aligned center. 
Keep the same proportions as in the larger screen size.

https://zpl.io/VO3mYRr

**Comment by MendyBerger** [comment]
@GaliShapira not sure what text you're referring too

**Comment by GaliShapira** [comment]
@MendyBerger 
Sorry, I forgot to attach the screenshot. 
<img width="395" alt="Screen Shot 2021-11-03 at 19 56 15" src="https://user-images.githubusercontent.com/88834002/140165855-3efaa16a-edc7-401b-b46b-e9cd5741dd0e.png">
