### ISSUE TITLE
Create: Add 3 keyboard buttons to Listen & Learn activity

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1806]
Listen and Learn menu Panel is missing Sefaria, Dicta and Hebrew Keyboard. Please add those three keyboard buttons.

![Screen Shot 2021-11-03 at 4 49 13 PM](https://user-images.githubusercontent.com/78186896/140191795-aeae8509-acba-4d27-91f0-baa57090836d.png)

**Comment by MendyBerger** [comment]
Resolved in eab77eb1
