### ISSUE TITLE
Create: Publish page (settings and Jig info) - dropdown menus goes under canvas

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1807]
On publish page - settings and Jig info - the dropdown menus for language of instruction, age, and teaching goal is not showing up properly - goes under the canvas
![Screen Shot 2021-11-03 at 6 05 23 PM](https://user-images.githubusercontent.com/78186896/140199816-44e458df-aaf3-4df7-b333-a5f36b0d80f0.png)

**Comment by MendyBerger** [comment]
Resolved some time ago
