### ISSUE TITLE
Preview help text under PREVIEW heading - change text

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1813]
At the moment it is always on the left, pointing to the first wizard. Rather, remove the box and insert the text below the heading.
![image](https://user-images.githubusercontent.com/16290361/140275961-c4c8c244-6cd8-4dd8-9ee2-4721b719b57d.png)

**Comment by corinnewo** [comment]
@MendyBerger 
 Please change the text to "Your work is auto-saved. To make changes, click back to any step."

**Comment by MendyBerger** [comment]
Resolved in 2ffd1656

**Comment by MendyBerger** [comment]
Resolved in e9943c3f
