### ISSUE TITLE
Cards: Editing the text in the card itself

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1817]
There's no indication that I've clicked into this card to edit text. Needs a vertical line, flashing or steady, indicating where text will be placed when entered (the insertion point)once

<img width="386" alt="Screen Shot 2021-10-26 at 18 22 34" src="https://user-images.githubusercontent.com/16290361/140284366-bd549b3d-1744-46f3-93f9-3df484da53a3.png">

**Comment by corinnewo** [comment]
Especially after you add a new pair, and the card appears blank. Need the curser there.

**Comment by MendyBerger** [comment]
Mostly resolved in 74d2fb85, there might still be cases where the cursor doesn't show up but in most cases it will, if this isn't acceptable the issue can be reopened
