### ISSUE TITLE
Tab instructions - separate the image tabs into separate instructions

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1819]
At the moment, all image tabs have the instruction to select a background. We need to have separate instructions for background, image, overlay.

**Comment by MendyBerger** [comment]
Resolved in 1f1743d1

**Comment by corinnewo** [comment]
@MendyBerger Does this mean that it is ready for us to put in separate instructions? I see that at the moment it still says 'Select background' in overlays and in image.
