### ISSUE TITLE
Registration error format when using email

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#182]
I'm getting a `500` error when trying to register via email and the user id already exists.
when using oauth I correctly get `422` with the RegisterError::TakenId

The payload is almost identical in both cases, the only thing which is different, I think, is the firebase token (in the Authorization header)

However, another difference is that with the oauth route we don't create a user upon registering as the first step - it merely signs in to get the token (and so it can proceed even if the google account already exists). whereas with the email/pw route we do create an account (which can't be re-used). For example - to debug this I was able to re-use my google account each time, but I had to create dummy email addresses so that each registration would be unique for email/pw

**Comment by izik1** [comment]
Is this still happening after #183?

**Comment by dakom** [comment]
it's fixed - closing :)
