### ISSUE TITLE
Click Jigzi in player side panel - should go to home page

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1820]
![image](https://user-images.githubusercontent.com/16290361/140304741-f1b2f13c-4b48-4dc7-a503-0d866b067a8a.png)

**Comment by MendyBerger** [comment]
Resolved in 858d01d4

**Comment by corinnewo** [comment]
@MendyBerger When you click JIGZI from within the player shell, you do go back to the home page, but the X remains on top right corner!
![image](https://user-images.githubusercontent.com/16290361/141239610-bab3823c-193e-474f-9ab1-dc2dc4b60fec.png)

**Comment by corinnewo** [comment]
@MendyBerger We decided to remove the link in the panel at this stage, rather than start fixing the overlays and get the X button not to be on the home page.

**Comment by MendyBerger** [comment]
Turns out making this work is actually really simple, we can keep the link without any problems

**Comment by MendyBerger** [comment]
Resolved in ec5c9da3
