### ISSUE TITLE
Homepage: Yellow titles teachers/parents are missing in the testimonials

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1825]
See the titles in a screenshot from Zeplin:
<img width="930" alt="Screen Shot 2021-11-04 at 22 13 47" src="https://user-images.githubusercontent.com/88834002/140413211-10bfb611-f340-4a43-a060-82cbcccc8b93.png">
:
https://zpl.io/VOl1nE1

And this is how I see it in production
<img width="1381" alt="Screen Shot 2021-11-04 at 22 13 54" src="https://user-images.githubusercontent.com/88834002/140413305-7931ce51-a4f5-4af9-bf86-8899cab06de2.png">
:

**Comment by corinnewo** [comment]
@GaliShapira This is fine as it is for now. No need to divert Mendy to this now. I will keep it open as a ticket for later.
