### ISSUE TITLE
Homepage: News strip

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1826]
1. This is how I see it.
<img width="1409" alt="Screen Shot 2021-11-04 at 22 17 52" src="https://user-images.githubusercontent.com/88834002/140413698-92494f85-5eff-401b-a463-92aad551550d.png">
 2. If we dont add content cant we hide it for now? or other,  fix the resizing and add 2 banners content.
3. All homepage areas need to be resized for smaller screens sizes.

**Comment by corinnewo** [comment]
@GaliShapira I had wanted Chaykee to write the Jigzi highlights and we would place it here. This was put on hold when there were so many visual changes to Jigzi. 
But I agree with you - we can hide it for the UI testing now.

@MendyBerger PLease hide this row for now.

**Comment by GaliShapira** [comment]
@corinnewo After watching the testing recording I think we learn a lot from this strip being there. 
I would like to keep it, only fix the sizing and perhaps take a real text of hope. 
I am interested to see if users stop there.

**Comment by corinnewo** [comment]
@GaliShapira Mendy already hid this - sorry! Is it worth unhiding again?
