### ISSUE TITLE
"Add Overlay" component - reorganise the search 

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1827]
1. Remove filters from search
2. Remove search Jigzi/web radio buttons.
3. Text inside the search should be: 'Search a shape or number'.
4. Add trash icon on top right. On hover add the tooltip, on hover the icon is darker. Click - removes the overlay from the canvas on RHS
5. Remove Upload (probably won't have an overlay of their own to upload).
6. Make search active when typing a text and click enter or when typing a word and click on the magnifying glass icon. 
On click it turns blue.

https://zpl.io/2pw9Or8

<img width="303" alt="Screen Shot 2021-11-04 at 23 05 50" src="https://user-images.githubusercontent.com/88834002/140420900-1a4fae9b-44f2-42f7-9a22-47eade51cd8e.png">
<img width="311" alt="Screen Shot 2021-11-04 at 23 05 54" src="https://user-images.githubusercontent.com/88834002/140420925-31257e9d-9816-447e-aeba-fcc71a191be4.png">

<img width="283" alt="Screen Shot 2021-11-04 at 23 05 17" src="https://user-images.githubusercontent.com/88834002/140421251-b6b36bbf-8b74-4fa9-8f21-21a4b30e012e.png">

**Comment by MendyBerger** [comment]
#4 is tracked in #1871

**Comment by MendyBerger** [comment]
Resolved in 64899ee0
