### ISSUE TITLE
Dicta - Nikud left out when pressing Ctrl+X to cut and paste a word from dicta to text box

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1831]
When using Dicta and typing a word in the Dicta Box, when I copy Ctrl+C the word into the list the Nikud shows up. When I cut Ctrl+X the word from dicta box into list the nikud is left out. The copy button on bottom right of dicta is working. 

https://user-images.githubusercontent.com/78186896/140458889-233bf516-f149-4d41-aa93-bc1068df084d.mov

**Comment by corinnewo** [comment]
Seems to be working now. Closing.
