### ISSUE TITLE
Create: Broken image

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1833]
In the text menu panel, there is a frame icon (not sure what to call it). When you click on it, the icon turns into a broken image. See screenshots:

![Screen Shot 2021-11-05 at 1 25 21 AM](https://user-images.githubusercontent.com/78186896/140464559-2816f7bd-3a69-411c-b83b-141443b14205.png)
![Screen Shot 2021-11-05 at 1 25 37 AM](https://user-images.githubusercontent.com/78186896/140464574-73127170-a520-4e4c-9f9e-80d1573a8805.png)

**Comment by corinnewo** [comment]
@GaliShapira Please change the box-color-active.svg to white. (it was missing, so duplicated box-color.
Place in https://media.jicloud.org/ui/module/_common/edit/widgets/sidebar/text-editor-controls/box-color-active.svg
Thanks!

**Comment by GaliShapira** [comment]
Hi @corinnewo @MendyBerger 
Pls see the white icon attached.
[textbox-selected.svg.zip](https://github.com/ji-devs/ji-cloud/files/7504996/textbox-selected.svg.zip)

**Comment by GaliShapira** [comment]
@corinnewo Done
