### ISSUE TITLE
Create -  Word List: Placeholder Shemesh in word list in missing Nikud

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1834]
In the word list, there are three hebrew placeholder words (שמש, ירח and כוכב)
the word shemesh in missing the Nikud.
Please add Nikud to keep it uniform

![Screen Shot 2021-11-05 at 2 11 57 AM](https://user-images.githubusercontent.com/78186896/140466569-090e9464-1587-4746-b24f-129d1838640b.png)

**Comment by corinnewo** [comment]
Please replace the occurrences of שמש with שֶׁמֶשׁ
