### ISSUE TITLE
Remove 'START' word that appears just before USE CASE carousel loads

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1838]
On the top left corner, the word START flashed on the screen when you are creating a new module. It appears just before the USE CASE carousel appears. I know that it has a function, but can we hide it in some way? Make the font the same blue as the background?

**Comment by MendyBerger** [comment]
Resolved in c83bf5d01d4881aa59f1afa408e2c7be03bc7cc8
