### ISSUE TITLE
Create: Jig panel - Kebab menu - By cover, change wording to "drag cover here"

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1844]
In the Kebab menu, by 1) cover, it currently says "Drag activity here". 
Please change text to "Drag cover here"

![Screen Shot 2021-11-07 at 10 09 35 PM](https://user-images.githubusercontent.com/78186896/140678979-e67c51d1-e23e-404d-bfa7-deb809240ae5.png)

**Comment by corinnewo** [comment]
Duplicate of #1863
