### ISSUE TITLE
Jig Panel - dragging another activity to cover causes a crash

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1845]
Dragging another activity to Cover space causes a crash.

When a user tries to drop a different activity to the cover it should fly back, and if they drag another activity to this space there should be a "no entry cursor".

![Screen Shot 2021-11-07 at 10 31 53 PM](https://user-images.githubusercontent.com/78186896/140680236-de4f46bc-bdca-42ad-b73d-d0403dc26dd7.png)
![Screen Shot 2021-11-07 at 10 32 39 PM](https://user-images.githubusercontent.com/78186896/140680242-51348be1-7910-4d90-a5cf-25a1bd0d868b.png)

**Comment by MendyBerger** [comment]
Resolved the crashing problem in d53841bb3f8886e128fbcaed1b6aa0aeb502c7b4
