### ISSUE TITLE
Jig Panel - Kebab menu - clicking on cover module before dragging a cover icon

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1846]
In the Jig panel, the first module in the Kebab panel is Cover. Before dragging the cover icon into the cover module, I am able to click on the module (while it says "drag cover here" ) and it takes me to create a cover. 

@corinnewo should a user not be able to click on the cover module and create a cover until they drag the cover icon into the module?

**Comment by corinnewo** [comment]
@chayaml This is for historical reasons - they have just added in the ability to drag in the cover to try and make people see that there is a cover option. I don't really want to ask to undo programming that was done already, so let's park this, keep it open, and if it is a problem, then we can ask them to remove that ability.

**Comment by MendyBerger** [comment]
@corinnewo this won't really remove any code, so no need to worry about undoing previous work.

I actually think that this would be a great task for Tyrone, so I've created an issue for him and closing this in favor of that one #1961
