### ISSUE TITLE
Create: Word List - switching between text tab and Image tab before clicking "done"

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1847]
Currently, when a user creates a word list in the **text** tab, if they press on the **image** tab (without clicking "done"), and then go back to the **text** tab, they lose the words that they just inserted. A user may not realize that they need to hit "done" to save their data and may click on the image tab just to check it out.

Is it possible to save the list so a user can switch off between the tabs without it getting deleted?

![Screen Shot 2021-11-07 at 11 38 04 PM](https://user-images.githubusercontent.com/78186896/140685772-e27b00b1-a419-4649-ac4c-6c947a741f3f.png)

**Comment by corinnewo** [comment]
This is similar to #1697, where I asked for the DONE button to have to be clicked before continuing. I like your suggestion, if possible, to autosave the list, so that if they do go on to the images, the list is not lost. However, the DONE button actually generates the cards. @MendyBerger, which solution do you recommend? Either autosave list or force DONE?

**Comment by corinnewo** [comment]
Also, PLEASE move automatically to the images tab when DONE clicked.

**Comment by johnnynotsolucky** [comment]
@corinnewo for modules which have word lists and images - it looks like it's only possible to drag images once a list has been created. 

Could we disable the image tab until a list is created, and when clicking done for a list, it navigates the user to the image tab?

Also, when clicking create a new list, should the user be notified that that action will delete the current list?

**Comment by corinnewo** [comment]
Yes, please:

1. Disable the image tab until done button is clicked
2. When done clicked, navigate to the image tab (but can always go back to the first tab)
3. Add in 'Are you sure?' dialog when creating a new list, warning them that the list will be deleted. 
"Creating a new list will delete the list you have made. Are you sure?"  "Yes, start a new list | No, keep this list".

**Comment by MendyBerger** [comment]
@johnnynotsolucky please mark me for review in the PR to implement this

**Comment by corinnewo** [comment]
@johnnynotsolucky what is happening with this ticket? I just lost a list I made because I clicked the image tab without DONE first.... Please can we get this reviewed and merged? Also, make sure it is applied to all 4 card games: Memory, card quiz, matching and flashcards. Thanks!

**Comment by johnnynotsolucky** [comment]
@corinnewo I'm working on this tomorrow. I'm not sure how much is involved - hopefully by Thursday I'll have something to show.
