### ISSUE TITLE
Creator: if activities on right hand side, MUST have JIG panel open, otherwise can't continue

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1848]
Must always have the JIG panel open if activities on right. Can't have this situation where you click on an empty module while the panel is closed, and then you cannot drag an activity into place.

![image](https://user-images.githubusercontent.com/16290361/140777353-6075e095-c45b-4a4a-967a-38a18235e7b7.png)

**Comment by MendyBerger** [comment]
Resolved in d40c4eb7

**Comment by MendyBerger** [comment]
Resolved in d40c4eb7
