### ISSUE TITLE
Card games - sizing of images is not correct, especially if you go back to that wizard stage

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1853]
![Uploading image.png…]()

**Comment by MendyBerger** [comment]
@corinnewo can't see the image you uploaded

**Comment by corinnewo** [comment]
![image](https://user-images.githubusercontent.com/16290361/141124932-ba27b09b-f7c5-4ad9-95eb-a5199af422f1.png)

**Comment by MendyBerger** [comment]
It is fixed
