### ISSUE TITLE
Jig Panel - Kebab menu - Can't delete an empty Jig/ module

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1856]
In the Kebab menu, I am only able to delete a module that has an activity dragged into it. The delete button for an empty module does not delete. 

![Screen Shot 2021-11-08 at 1 23 44 PM](https://user-images.githubusercontent.com/78186896/140797038-1e244416-8005-439b-be8d-4f98a825e447.png)

**Comment by MendyBerger** [comment]
Closing in favor of #1959
