### ISSUE TITLE
Some images are defined as backgrounds, but showing up as stickers

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1862]
![image](https://user-images.githubusercontent.com/16290361/140884767-e037f15a-f331-43a8-8d54-654a8a948a3a.png) 
clearly tagged as background 1

Shows in image list, when filter is set to 'No backgrounds'
![image](https://user-images.githubusercontent.com/16290361/140884903-54f15501-36dc-47f2-9f94-0eff0618bb6b.png)

**Comment by MendyBerger** [comment]
Closing in favor of #2424
