### ISSUE TITLE
Safari browser - did not play sound and had the play button on each module

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1865]
In the usability testing, the user was using Safari browser.
Had to swap to Chrome to get the player to play sound.

**Comment by corinnewo** [comment]
@johnnynotsolucky Assigning to you as you will have the Mac to test on!

**Comment by johnnynotsolucky** [comment]
@corinnewo hopefully soon!

**Comment by MendyBerger** [comment]
Related #2208

**Comment by johnnynotsolucky** [comment]
@corinnewo I've tested on safari and on ios and the sound is playing correctly. Perhaps this issue has been fixed recently?

**Comment by corinnewo** [comment]
This was from the user testing in November, so it could have been fixed since. Glad to hear it is working. I'll close the ticket.
