### ISSUE TITLE
CREATE COVER: Dragging an activity that is NOT a cover to the cover causes a crash

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1872]
If you drag any activity that is not a cover, to the cover module, there is a crash!

![image](https://user-images.githubusercontent.com/16290361/141121480-6d75ca2a-d424-439b-874a-ca58c785a8ba.png)

**Comment by chayaml** [comment]
duplicate of #1845

**Comment by corinnewo** [comment]
Closing this issue if it is a duplicate!
