### ISSUE TITLE
After a card game, the 'what do you want to do next' page does not have a scroll bar, so on smaller screens, can't get to the options at the end of the screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1873]
FROM USABILITY TEST - ROnna - 35 minutes in - 
Add scroll bar so that users can actually go to the end of the screen and choose what you want to do next.

**Comment by corinnewo** [comment]
![image](https://user-images.githubusercontent.com/16290361/141238707-572e6e6d-ca66-4cd9-ba50-93dba1d7ae46.png)

**Comment by MendyBerger** [comment]
Resolved in d77aee2a
