### ISSUE TITLE
Drag and Drop - sorting - replace shoe (נעל) with a picture that begins with ע?

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1880]
By the drag and drop sorting activity the 3 images are ציפור, עלה, נעל -bird, leaf, shoe - and the jars have an ע and צ.
When clicking on the image, ציפור is placed in צ jar and עלה and נעל are placed is ע jar. Should the shoe (נעל) be replaced with an object that begins with ע? 

I know there is an ע in נעל but I think it makes more sense to use an object that begins with that letter  - maybe a cloud (ענן)?

![Screen Shot 2021-11-10 at 7 19 58 PM](https://user-images.githubusercontent.com/78186896/141215215-49445f67-8803-400b-a6be-c27368280409.png)
![Screen Shot 2021-11-10 at 7 22 43 PM](https://user-images.githubusercontent.com/78186896/141215472-cd96bf0d-6f13-4040-ac90-99f5e6067489.png)

**Comment by corinnewo** [comment]
Good point. @GaliShapira - please change the shoe (naal) to cloud (anan).

**Comment by corinnewo** [comment]
I think it is OK - it shows that it is sorting, and the word has an ayin in it!
