### ISSUE TITLE
Drag and Drop - matching use cases - add nikud to words?

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1881]
By drag and drop, the use case words are without nikud. Is it possible to add nikud to the usecases (יָרוֹק צָהוֹב אָדוֹם)

![Screen Shot 2021-11-10 at 7 23 19 PM](https://user-images.githubusercontent.com/78186896/141224224-fc7fe3d4-44fb-4c06-8794-7ea2b76a24c1.png)

**Comment by corinnewo** [comment]
I changed this.
