### ISSUE TITLE
Search: Enlarge backgrounds to fit Zeplin Screen

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1883]
The backgrounds size in search doesn't match the zeplin Sketch. Please enlarge the background size to match Zeplin screen (also with rounded corners).

**Currently:**
![Screen Shot 2021-11-10 at 9 30 52 AM](https://user-images.githubusercontent.com/78186896/141227332-72718959-2334-480c-99ef-7e23f9cf3a84.png)

**Zeplin:**
![Screen Shot 2021-11-10 at 10 10 04 PM](https://user-images.githubusercontent.com/78186896/141230597-432ecdef-4125-40f0-bb68-7601751e7b1c.png)

**Comment by corinnewo** [comment]
Closing this in favour of #2618
