### ISSUE TITLE
Cover - Theme - add a popup message

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1885]
Themes -  After selecting a theme on click continue to the next step a popup appears asking the user whether its for cover only or for the entire JIG. This shape of popup with illustration we will use for messages that do not alert.
I attach a screenshot and the illustration.

Zeplin:
https://zpl.io/agEBJ6Z

![illustration-theme](https://user-images.githubusercontent.com/88834002/141264621-58f5f327-aa6f-478e-b4b9-df6e827643eb.png)

<img width="810" alt="Screen Shot 2021-11-11 at 10 30 50" src="https://user-images.githubusercontent.com/88834002/141264596-0cbce385-9fdb-435f-85e6-70d182c6c91f.png">

**Comment by MendyBerger** [comment]
@GaliShapira should the menu be removed? 

![image](https://user-images.githubusercontent.com/12537668/142218437-2a66c5d4-760b-4ce0-aa31-7501660b64be.png)

**Comment by GaliShapira** [comment]
@MendyBerger 
Good question... 
For now it can be moved. 
We might need it later.

**Comment by GaliShapira** [comment]
@corinnewo What do you think about it?

**Comment by corinnewo** [comment]
At the moment, the kebab menu is not noticeable at all. So I think it can be removed, as long as we have the dialog to apply the theme to the whole JIG.

**Comment by MendyBerger** [comment]
Resolved in 66a3bcb6

**Comment by corinnewo** [comment]
@MendyBerger   - thanks for adding this dialog. But it should not appear as you click a new theme. We want people to go through and check out the themes. It should only appear when they click 'Continue' on bottom right, or any of the wizard steps (in other words, as you are leaving the themes step).
Perhaps this was not clear enough, but the instruction is at the top of the ticket!

**Comment by GaliShapira** [comment]
@MendyBerger  @corinnewo 
Is this issue solved? 
I have made some changes for responsive screens, 
I would like all our illustrated messages to be in the same modal settings.:

https://zpl.io/agEBJ6Z
https://zpl.io/bA36PRx

- Modal size + specs are smaller
- Illustration is cropped and smaller.
- Text and title are under the illustration. 

I have also made some text changes with @ChaykeeMor :
1. WAS: _"Great theme"_
**Change to:**
Your theme looks great!
2. Was: _"Apply this theme to your whole JIG to set background, fonts and colors everywhere."_
**Change to:** 
Do you want to apply this theme to your entire JIG?
This will set backgrounds, fonts and colors everywhere!

2. Was: _"Apply to cover only"_
**Change to:**
Apply to cover

Now:
<img width="900" alt="Screen Shot 2021-12-09 at 21 19 10" src="https://user-images.githubusercontent.com/88834002/145461599-52e57d87-e88f-47d1-84cd-0b9450470c80.png">

Was:
<img width="869" alt="Screen Shot 2021-12-09 at 13 09 06" src="https://user-images.githubusercontent.com/88834002/145461652-26f7c480-ed0e-456d-88a9-011ba81af5ac.png">

**Comment by corinnewo** [comment]
@MendyBerger This has not fully been solved - this dialog is great, and I accept your suggestions for text changes. BUT it should only appear once you try and continue to another tab, if you have changed the theme. ie - change the theme AND click continue button or one of the wizard steps. It should NOT come up after each theme change.

Also, it is not changing the theme - if I say apply to whole JIG, then the theme for the JIG should change, and if I go into another module, then the theme should be the new theme, by default.

**Comment by corinnewo** [comment]
This is out of date - closing!
