### ISSUE TITLE
Cover - Add settings

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1886]
Changes in the wizard:
Settings is added. 

https://zpl.io/VO6p3eL

<img width="272" alt="Screen Shot 2021-11-11 at 10 33 53" src="https://user-images.githubusercontent.com/88834002/141265319-a6faeddd-34dc-4fbf-a716-cf026cc1a9b2.png">
. 
<img width="273" alt="Screen Shot 2021-11-11 at 10 40 16" src="https://user-images.githubusercontent.com/88834002/141265894-b1f54932-e70b-46b2-bcad-15faa6aed17c.png">

**Comment by corinnewo** [comment]
@ChaykeeMor Please add in the correct English and punctuation here for the settings. Thanks

**Comment by ChaykeeMor** [comment]
instruction at top of tab: NONE
prompt:  Student finishes this activity...
buttons: by clicking on continue, automatically (buttons are lowercase)

**Comment by corinnewo** [comment]
@johnnynotsolucky I have unassigned Mendy and assigned you, as this is similar to https://github.com/ji-devs/ji-cloud/issues/2629 - adding in the settings tab to continue automatically after audio or waiting for continue. Cover and poster modules should be similar...

**Comment by corinnewo** [comment]
Closing in favor of #3284
