### ISSUE TITLE
Dark gray outlines - Why are you here?

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1888]
I see these dark gray outlines around the canvas, near the JIG panel, and on top, below the browser panel.
Can we get rid of them?

<img width="673" alt="Screen Shot 2021-11-11 at 14 22 35" src="https://user-images.githubusercontent.com/88834002/141297948-cbc9bf07-1cd0-4d2a-bbc1-1a76896f9ab0.png">
k,

**Comment by mastapegs** [comment]
This is due to the `iframe`'s frame border.

@MendyBerger, shall I take care of this for you?

![image](https://user-images.githubusercontent.com/13839150/147718752-fa89b295-7ac7-4cbc-80bb-7d361f9008a7.png)

**Comment by corinnewo** [comment]
@mastapegs I am still seeing a grey line on the left and top of the iframe. It is not as bad as before, but it is still there! Is there anything that can be done about it?
![image](https://user-images.githubusercontent.com/16290361/148185502-8687fbb9-7f9a-47bb-b4b2-8bdce68981b0.png)

**Comment by mastapegs** [comment]
Yes! That's a different iframe, same problem. I got it

**Comment by mastapegs** [comment]
Just verified, same EXACT borders, and its the `iframe`
