### ISSUE TITLE
Player shell - align icons on the right to the edge of the background

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1893]
If the aspect ratio of the screen is forcing a space to the right of the content, then the icons on the right of the screen should be aligned to the content. Any extra white space can have a shadow, or something like that.
Should **not** have this:
![image](https://user-images.githubusercontent.com/16290361/141314196-881d46ce-4333-49c4-9e19-1e30f8a321f5.png)
Should look like this:
![image](https://user-images.githubusercontent.com/16290361/141314257-28caf082-76a8-418e-8402-15373c38b4c8.png)

**Comment by MendyBerger** [comment]
Resolved in b297139d
