### ISSUE TITLE
Web image filter options: Bing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1894]
On Ji Tap web creator, we have Bing filtering options for **Photo | Animation | Clip Art | Line Art**. There is also a filter for Royalty free and No background.

Please add these filters to the web searches.

![image](https://user-images.githubusercontent.com/16290361/141314872-40bfbbf8-9f10-4afc-bc8c-609bb0ad0ffe.png)

**Comment by corinnewo** [comment]
@GaliShapira Please confirm these filters for the web search. Once you have approved and finalised, I will send to backend to implement.

**Comment by corinnewo** [comment]
Connected with #1333. Once requirements are finalised I will combine all these tickets

**Comment by GaliShapira** [comment]
Hi @corinnewo 
What is the difference between line art to clip art?
I will implement tomorrow the design of these on our page and upload here the link.

**Comment by GaliShapira** [comment]
Hi @corinnewo

Pls see my suggestion for the 2 dropdowns (JI and Web).
I added at the button all the toggles.

https://zpl.io/2yR7dkp

![Uploading Screen Shot 2021-11-18 at 11.25.52.png…]()

**Comment by GaliShapira** [comment]
@MendyBerger @corinnewo 
There is a technical problem with the Zeplin link, I will update here when its solved.

**Comment by corinnewo** [comment]
@GaliShapira looks good. I have added a few comments to the Zeplin so that the filter names are updated, according to the list we agreed on and gave Mendy.

**Comment by GaliShapira** [comment]
@corinnewo All changes are done. 
Ready for dev.
<img width="718" alt="Screen Shot 2021-11-22 at 14 13 47" src="https://user-images.githubusercontent.com/88834002/142860124-fe2e82a2-70ab-4a7c-8d13-28a35c9dfeca.png">

**Comment by corinnewo** [comment]
@MendyBerger At the moment the web search filters are not connected to BING at all, and so they are irrelevant and misleading to show. Please update the filter for the web, or else we need to hide the filter option when you are searching on the web. (Preferable to get it working!)

**Comment by MendyBerger** [comment]
Resolved in d3441fdd6
