### ISSUE TITLE
Web image search image-type

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1906]
Please add the `imageType` options to web image search.

Docs about `imageType` can be found [here](https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-images-api-v7-reference#query-parameters), scroll down until you see `imageType`

**Comment by MendyBerger** [comment]
@RickyLB I see that you added this as a string but I'd prefer to have this type checked, is it a big deal to change to an enum?

**Comment by RickyLB** [comment]
@MendyBerger I can make this happen
