### ISSUE TITLE
Edited Text for Play Settings

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#1908]
Here's the texts for all the **Play settings**. 

Here's what the play settings should look like. With prompts and buttons. Casing is intentional.
<img width="758" alt="Screen Shot 2021-11-15 at 18 09 44" src="https://user-images.githubusercontent.com/94056434/141815251-aeb98968-6a8c-4c60-a5ea-d35d9767635f.png">

(split into 2 - see #1917 for the other half!)

**Comment by corinnewo** [comment]
@ChaykeeMor The link to the spreadsheet is not working. Please check!
