### ISSUE TITLE
Create: Play settings: Set a time limit, doesn't appear in the Jig game

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1913]
In wizard step 3 (Settings), I set a time limit yet it doesn't appear in the Jig. Please add a time limit when playing Jig.

![Screen Shot 2021-11-15 at 10 32 54 PM](https://user-images.githubusercontent.com/78186896/141891127-0e2edc1a-7cbb-48f5-a7b2-a1ef987833ef.png)

**Comment by corinnewo** [comment]
@chayaml The time limit appears only in the module in the player where the timer has been set. It is not displayed the whole time. Please check whether this is the case here. If so, we can close this ticket.
