### ISSUE TITLE
Create: Jig Settings - stop background music from playing when exiting from "add background music" tab

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#1914]
In the add background music tab,  I can click the play/ pause button to sample the music options. When exiting this tab by clicking X or anywhere else on the screen, the music continues to play.

 When going back to the add background music tab to pause the music, there is no indication of which music sample is still playing and there is no way to pause it. A user can choose to play another sample and they will both play simultaneously,  which sounds messy.

**Suggestion:** When a user exits the add background music tab, the music should stop playing even if the user did not press to pause.

![Screen Shot 2021-11-15 at 10 53 41 PM](https://user-images.githubusercontent.com/78186896/141899289-ae1a43a0-715e-4738-be43-21b419511c23.png)

**Comment by MendyBerger** [comment]
Resolved in f98a29b3156b25730a31b73fa3841b67ca0359b2

**Comment by chayaml** [comment]
Hi @MendyBerger, I'm still experiencing this issue - Music continues to play after closing the tab

**Comment by MendyBerger** [comment]
@chayaml on sandbox?
