### ISSUE TITLE
sizing - need to work Gali & Mendy 

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1915]
We need to look at all platform areas
- Creator right side
- Homepage
- JIG panel
- Search results
- Player

**Comment by corinnewo** [comment]
@GaliShapira What should I do about this ticket? Perhaps set up a time to work with Mendy on these areas? Keeping it assigned to me in the meantime!

**Comment by GaliShapira** [comment]
@corinnewo 
I think we need the priority of this.
Perhaps Mendy and I can set one meeting every week to proceed.

**Comment by corinnewo** [comment]
@GaliShapira Please set up the meeting, and set the agenda according to the areas that need to be worked on!
