### ISSUE TITLE
Memory game - Player - My pairs area

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1916]
Pls make the following changes:
1. Remove title "My pairs" and place the cards higher.
2. Change the field fill and stroke colors according to the Zeplin specs
https://zpl.io/bo7zm7E
3. Add animation: on hover on the card the back card switch to front. Use this animation code: https://codepen.io/katehummer/pen/VjLjMv
<img width="568" alt="Screen Shot 2021-11-16 at 8 54 07" src="https://user-images.githubusercontent.com/88834002/141936132-55d8c73c-eeb2-4131-8c85-ea2f0bf5f3f9.png">

<img width="299" alt="Screen Shot 2021-11-16 at 8 55 10" src="https://user-images.githubusercontent.com/88834002/141936141-ef099a8f-788a-43f2-a854-ed39b7439161.png">

**Comment by corinnewo** [comment]
also see https://github.com/ji-devs/ji-cloud/issues/1724

**Comment by corinnewo** [comment]
Leave out item 3 at the moment, if it is not simple

**Comment by MendyBerger** [comment]
Did 1 and 2
