### ISSUE TITLE
Sendgrid - emails have 'Unsubscribe' text, but not a link, and don't know where to send it

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1918]
We need to add a link to the word 'Unsubscribe' in the emails that are sent through sendgrid. Where should it go to?
In Hubspot emails, it goes to a system to unsubscribe. But here it is not going through Hubspot. Should we set up an email that will have a subject "Unsubscribe from Jigzi", and it will be sent to info@jigzi.org, which will then have to manually remove from system?

![image](https://user-images.githubusercontent.com/16290361/141963149-3d83522c-e65c-4f4d-9895-6c3e1be7481c.png)

**Comment by GaliShapira** [comment]
@corinnewo 
I removed the unsubscribe from the 4 emails.

**Comment by corinnewo** [comment]
Thanks @GaliShapira
