### ISSUE TITLE
Need a warning when adding attachments to JIGs in the publish dialog that are not acceptable - just crashes, no explanation

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1923]
Can add only PDF, Images and videos, as browser security in place. Any other types (like excel, word) will have to be converted to PDF by the creator first. 
https://zpl.io/VQPMQoA

@GaliShapira please check that this is the final flow - must add in warning if not PDF, image or video.

**Comment by GaliShapira** [comment]
@corinnewo Which formats of images and video?

**Comment by corinnewo** [comment]
@MendyBerger please confirm that these are the formats that we can accept as uploaded files. Thanks

**Comment by MendyBerger** [comment]
We can except any of the following:

- All image formats
- All video formats
- All audio formats
- PDF

If there is a need we might also be able to accept csv, but that's probably going to require some extra work, so I'd wait for the need to arise

**Comment by GaliShapira** [comment]
Hi @corinnewo @ChaykeeMor 
I changed the tooltip to this, do you have other suggestions for the text?

<img width="427" alt="Screen Shot 2021-11-22 at 13 56 24" src="https://user-images.githubusercontent.com/88834002/142857809-e2ffaba7-a0de-4e2b-bad4-f02dcccf822f.png">

**Comment by ChaykeeMor** [comment]
We accept all image, video, audio, and PDF file formats. @GaliShapira @corinnewo

**Comment by GaliShapira** [comment]
@ChaykeeMor Thank you.
@MendyBerger, the Zeplin is updated with the final version of the text.
<img width="553" alt="Screen Shot 2021-11-23 at 12 56 23" src="https://user-images.githubusercontent.com/88834002/143012143-f87ad694-6c4d-45a1-b4bc-fd2406342fdb.png">

**Comment by corinnewo** [comment]
When adding a file that is not accepted, we are not getting the warning message - only a crash.

**Comment by corinnewo** [comment]
@MendyBerger I am not yet seeing this on sandbox. Where can I see this warning?

**Comment by MendyBerger** [comment]
Sorry, don't know why I closed, has not been done

**Comment by corinnewo** [comment]
If I try and upload a word file, it simply crashes and no warning! Please add in the warning and prevent the crash!

**Comment by MendyBerger** [comment]
Resolved (with different UI)
