### ISSUE TITLE
Design the upload of resources on the CONTENT page, as well as search results

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1924]
Related to #1923
For the UNITED tender, must be able to upload resources, not connected to JIGs.
Upload is for Ji Admin people only! If a client, there will be a new level of access for client admin.
For security reasons, only PDF, images and videos. No Word, PPT, or Excel files that need to be downloaded in order to be opened. Must be converted to PDF files.

Publish of the resource will include name, description, age range, categories, type of resource (lesson plan, curriculum, activities, etc) and affiliation.

These resources can be searched and will have their own row called 'Resources' on the search results page.

**Comment by GaliShapira** [comment]
@corinnewo Do we still need to do it?
