### ISSUE TITLE
Add new fields to AdditionalResource

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1933]
`display_name: String`
`resource_kind: ResourceKind`
`resource_type: ResourceType`

Remove `url`.

```
enum ResourceKind {
    Image(ImageId),
    Audio(AudioId),
    Pdf(PdfId), // once ready
    Link(String),
}
```

```
enum ResourceType {
    Activity
    Coloring
    Curriculum
    Craft
    EBook
    Flashcards
    LessonPlan
    Podcast
    WebsiteLink
    Worksheet
    Video
}
```

Currently we only have a create method for `AdditionalResource` but we also need an update method

**Comment by MendyBerger** [comment]
Thinking now, maybe the `ResourceKind::Link` value should be a `url::Url` instead of a `String`

@RickyLB what do you think about this?

**Comment by RickyLB** [comment]
@MendyBerger I like that idea. The crate does have ways to check if the link is valid.
