### ISSUE TITLE
Resources - Add + find - 2 new flows

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1940]
I uploaded the 2 flows here:
https://zpl.io/aRk6P3E
with explanations on the artboards of the changes from our JIG similar screens.

**Comment by MendyBerger** [comment]
@GaliShapira what does this link to? The create page, or search with the current authors name?

![image](https://user-images.githubusercontent.com/12537668/143599128-2b843473-f705-4f79-b275-876db7a64366.png)

**Comment by MendyBerger** [comment]
@GaliShapira are we doing both or is one just a mistake?

<img src="https://user-images.githubusercontent.com/12537668/143600340-22f9406c-eb27-4c8e-a9c8-69daf3b536b8.png" width="300">
<img src="https://user-images.githubusercontent.com/12537668/143600330-f28f3f6f-7564-461d-b3d0-3fb5f736158b.png" width="300">
