### ISSUE TITLE
Resources - create a thumbnails - smaller tabs version

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1941]
I updated the tabs different states here. Should I open a ticket for it?
https://zpl.io/VO36D9Q
<img width="596" alt="Screen Shot 2021-11-29 at 13 11 34" src="https://user-images.githubusercontent.com/88834002/143868582-1f6c9dc5-9d58-489d-a830-ca87e196865c.png">

Also a few text changes in these 2 pink circles area:
<img width="213" alt="Screen Shot 2021-11-29 at 12 21 34" src="https://user-images.githubusercontent.com/88834002/143868751-78d5dd9c-fd67-48a1-b17d-4eabf7aa0b93.png">

**Comment by corinnewo** [comment]
@GaliShapira Please look at this - is it still relevant?
