### ISSUE TITLE
Create Page: Does not show warning before deleting.

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#1943]
Just deleted my JIG by accident. Should be a warning, I believe @GaliShapira designed it with a warning, I remember seeing it.  'Are you sure you want to delete this JIG?' with buttons: 'Delete JIG' as a blue button and 'Don't delete' as secondary option
<img width="891" alt="Screen Shot 2021-11-30 at 12 28 15" src="https://user-images.githubusercontent.com/94056434/144030790-701f14ff-28d8-4e57-ab4c-4183bf3295df.png">

**Comment by GaliShapira** [comment]
Hi @corinnewo @ChaykeeMor 
I have this warning popup for deleteing activity from a JIG. 
We can use here the same, (just use the word JIG)

https://zpl.io/bL91KQD

![Uploading Screen Shot 2021-12-13 at 12.13.40.png…]()

**Comment by ChaykeeMor** [comment]
This is exactly what we need but @GaliShapira shouldn't the primary button be the one the user intended? If I click delete, the primary should be 'Delete activity' and the second option on left should be 'don't delete'.  Same with JIG.
Are you sure you want to delete this JIG? Delete JIG ('don't delete')

**Comment by MendyBerger** [comment]
@johnnynotsolucky some of the work for this might already be done, not sure though

**Comment by GaliShapira** [comment]
> This is exactly what we need but @GaliShapira shouldn't the primary button be the one the user intended? If I click delete, the primary should be 'Delete activity' and the second option on left should be 'don't delete'. Same with JIG. Are you sure you want to delete this JIG? Delete JIG ('don't delete')

@ChaykeeMor We always think about helping the user not to delete info by mistake, our warnings' purpose is to always make sure that this was the real intention of the user. So he will not click on the main call to action without reading.

**Comment by johnnynotsolucky** [comment]
I've removed the quick fix label. The confirm modal does exist, but I feel that it needs to be refactored a bit so that it can be more flexible and cater for a wider usage.
