### ISSUE TITLE
Web image library - storage

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#195]
Sortof builds off our current global image library, however, has the following differences:

1. No Search or user supplied metadata
2. Does store the original url it came from
3. Checks to see if image is unique
4. `ImageKind` for resizing purposes etc. is _always_ `Sticker`
5. The data gets downloaded from the supplied url, it's not provided via the `body`

**Comment by izik1** [comment]
Needs further comment:
In a slack discussion about #468 it was mentioned that this might be per user rather than global, @dakom, @dani-ji?

**Comment by izik1** [comment]
* note: pay attention to separation between animation and image
