### ISSUE TITLE
Categories (changed to 'Keywords') must have autocomplete suggestions

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1974]
Implement an autocomplete or suggestions based on start of type. (ie: Cha… offer chanuka, Chanukah offers chanukah lights, chanukah background etc whatever we have.)

(Use this same method for searching categories @GaliShapira to define )
![image](https://user-images.githubusercontent.com/16290361/145174698-938d2f40-2b59-477c-a6c6-97fd9bb91c07.png)

**Comment by MendyBerger** [comment]
Resolved in 347cc6243b1338bb635edcbea11d8cb0a204e42f
