### ISSUE TITLE
Translations to Hebrew and other languages of the images and JIGs for search in Algolia

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1978]
the automatic translation of image descriptions into Hebrew works on sandbox, but is not yet working on Jigzi. We need to crawl all the descriptions and translate into Hebrew for Algolia. At the moment, searching in Hebrew for images is not working at all on Jigzi.

Once we are doing this, please can we also add in the translations to the various languages that we are supporting:

![image](https://user-images.githubusercontent.com/16290361/145230028-1eef6411-72e1-400b-ae78-20e084fb7e36.png)

**Comment by RickyLB** [comment]
Would this be in the same process as updating image descriptions? If that's the case, we would just need to add an input specifying the target language.

**Comment by corinnewo** [comment]
Yes. I think so. Please go ahead. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
