### ISSUE TITLE
Add the ability for users to report Jigs

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#1982]
This is roughly how a report should look like:
```rust
struct JigReport {
    id: ReportId,
    jig: JigId,
    report_type: JigReportType,
    reporter: Option<UserId>,
    created_at: DateTime<Utc>,
}

pub enum JigReportType {
    Offensive,
    CopyrightInfringement,
    Spam,
    Privacy,
    Other,
}
```

When a user makes a report please send an email to a specified email address (we'll provide one later)

**Comment by RickyLB** [comment]
@MendyBerger @corinnewo 

- Does a user include their `Uuid` in the request body if they want to reveal themselves as the reporter? 
- How should `reporter` field be displayed in the response when a reporter `UserId` is not given?

**Comment by corinnewo** [comment]
I think we should know who reports a Jig so that we can contact them for further information if necessary. Please include their name and email address in the report sent. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by MendyBerger** [comment]
@RickyLB 

- Yes, if the user is logged in their id will be included, otherwise it will be `None`.
- `None`
- info@jigzi.org, please use the following subject line "Attention: Report from Jigzi"


Does this answer your questions?

**Comment by RickyLB** [comment]
@MendyBerger @corinnewo This answers everything for now!

**Comment by corinnewo** [comment]
Subject: URGENT: JIG Report "[reason chosen in pulldown]"
Content:
[name of reporter] with email [reporter's email] has reported [JIG name], URL: [url], created by [JIG creator name] for the following reason: [reason chosen].
