### ISSUE TITLE
Legacy - houdini still giving problems with veshamru

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1987]
https://sandbox.jigzi.org/jig/play/ff3836a0-5607-11ec-8c2d-0347ae3973bc?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

Click VERSAHMRU word - plays sound but not seeing the gif.

**Comment by corinnewo** [comment]
@dakom - can't assign this to you anymore! Please look into this urgently!

**Comment by corinnewo** [comment]
The other place I noticed that was problematic is https://sandbox.jigzi.org/jig/play/ff3836a0-5607-11ec-8c2d-0347ae3973bc?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false
Where you click on the lamed area, hear it, but don't see it.

![image](https://user-images.githubusercontent.com/16290361/145553123-830a23d7-a5d7-42e6-8d9c-62208e71942d.png)

**Comment by dakom** [comment]
fixed in https://github.com/ji-devs/ji-cloud/commit/e909531f19871c31eddecf9e335f23cf8d04dd0a
