### ISSUE TITLE
publish page - upload resources - changes

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1990]
Hi @MendyBerger  @ChaykeeMor 
Chaykee, can you please let me know if there are text changes as the flow has been changed. 
Pls see the following changes following our discussion:
2 flows of uploading file and inserting link start here:
https://zpl.io/25ljvLj

1. Outline for light blue frames: #Light Blue 3.5 - #C4D9F7
<img width="570" alt="Screen Shot 2021-12-09 at 20 19 49" src="https://user-images.githubusercontent.com/88834002/145453445-7f1d1850-d92d-4d2f-930e-56103b45c07b.png">
2. "+Add resource" - Difrenciate 2 blue colors for default text and icon to the hover+pressed states.
<img width="347" alt="Screen Shot 2021-12-09 at 20 20 51" src="https://user-images.githubusercontent.com/88834002/145453605-0169d5f2-db18-4329-b33b-9d2e17947c85.png">
3. Upload file popup: Change title orange icon from url to upload file, 
Change select file component to blue.
<img width="316" alt="Screen Shot 2021-12-09 at 20 22 35" src="https://user-images.githubusercontent.com/88834002/145453872-6441565d-a081-4854-bd4d-03fca68c0570.png">
4. Change the component of a file selected.
<img width="302" alt="Screen Shot 2021-12-09 at 20 24 57" src="https://user-images.githubusercontent.com/88834002/145454050-9b8cca4d-6215-4824-889f-ba535968db08.png">
5. Error when clicking on the disable save button without selecting the type. (Same behavior for inserting link).
<img width="590" alt="Screen Shot 2021-12-09 at 20 26 00" src="https://user-images.githubusercontent.com/88834002/145454358-1df9ef39-0bed-44a9-b50b-d010a0e85a39.png">
6. Show loader inside the popup, remove save button.
<img width="377" alt="Screen Shot 2021-12-09 at 20 30 31" src="https://user-images.githubusercontent.com/88834002/145454889-5a46aa9f-9739-49d1-813b-e1c2ea8b156a.png">
7. If the file is too big when clicked on save immediately present the error notification. If possible make the loader and field in red colors. 
<img width="639" alt="Screen Shot 2021-12-09 at 20 33 43" src="https://user-images.githubusercontent.com/88834002/145455334-f02a5165-2246-4e53-b541-e863ca7e875f.png">
8. When the file is uploaded, add an edit option links back to the popup where the user can change the type selection or delete the file and reselect.
<img width="616" alt="Screen Shot 2021-12-09 at 20 34 35" src="https://user-images.githubusercontent.com/88834002/145455507-b78fae42-f14b-4b00-8897-e8ec3a58daae.png">
9. If the name of the file is longer than the space in the field, show the full name on a tooltip.
When there are a few files uploaded, make sure that they dont pass the bottom line of the other fields and dont push the publish button down.
<img width="630" alt="Screen Shot 2021-12-09 at 20 36 11" src="https://user-images.githubusercontent.com/88834002/145455816-8c2cd83d-1c3b-476c-8c23-df0af87a7da0.png">

Insert link, same changes, same behavior.
Specific to insert link:
10. Change the text field of the link to be as the paragraph text field.
<img width="320" alt="Screen Shot 2021-12-09 at 20 38 16" src="https://user-images.githubusercontent.com/88834002/145456067-e9d6f666-9cbf-4b7c-9f2b-2d0bb5bc3c1b.png">
11. Link validation, once entering the url (before save) check validation and present an error notification if its not valid.
<img width="607" alt="Screen Shot 2021-12-09 at 20 39 59" src="https://user-images.githubusercontent.com/88834002/145456239-16f64604-8e05-4dcb-9a8e-5f74a860c4ce.png">

**Comment by GaliShapira** [comment]
Hi @MendyBerger 
I added the description of the formats in the "add file" popup.
https://zpl.io/aN3Y8ed

<img width="384" alt="Screen Shot 2021-12-15 at 19 57 49" src="https://user-images.githubusercontent.com/88834002/146240675-7d21f2ff-7fb7-451a-8d81-44ef9efc7bbe.png">

**Comment by ChaykeeMor** [comment]
@GaliShapira The Zeplin texts need updating.
