### ISSUE TITLE
Cover in sandbox is crashing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1993]
All existing covers in Sandbox seem to be crashing. Creating a new Jig - seems to be working

![image](https://user-images.githubusercontent.com/16290361/145542498-4ee7a640-9a94-4cda-8248-ec8ad14928d4.png)

**Comment by johnnynotsolucky** [comment]
Some quick debugging here.

- The jig in question is `f38e786c-e318-11eb-8e85-1759b91908ab` and the cover module is `5bd82f08-1df7-11ec-a129-bf37f14e29ad`. 
- This issue exists for both edit and play.
- Fetching the data for the cover returns the following:

```
$ curl 'https://api.sandbox.jigzi.org/v1/jig/f38e786c-e318-11eb-8e85-1759b91908ab/live/module/5bd82f08-1df7-11ec-a129-bf37f14e29ad'

{
  "module": {
    "id": "5bd82f08-1df7-11ec-a129-bf37f14e29ad",
    "stable_id": "<redacted>",
    "body": {
      "cover": {
        "content": null
      }
    },
    "is_complete": false,
    "is_updated": true,
    "created_at": "2021-07-12T13:56:26.982363Z",
    "updated_at": "2021-09-16T20:15:36.211019Z"
  }
}
```
- `unwrap` (`unwrap_ji`) is being [called on `None`](https://github.com/ji-devs/ji-cloud/blob/sandbox/frontend/apps/crates/entry/module/cover/play/src/base/state.rs#L40) where `"body"."cover"."content" is `null` in the response.

**Comment by johnnynotsolucky** [comment]
The other issue noted by @corinnewo is that the edit gallery screen only lists drafts, 
The `/jig/browse` endpoint looks like it _only_ returns drafts at the moment: [db/jig.rs#L773](https://github.com/johnnynotsolucky/ji-cloud/blob/cf5855ad/backend/api/src/db/jig.rs#L773). However, when I create a jig and publish it, it is still returned by the browse endpoint, but it does not show up in the content search screen.
