### ISSUE TITLE
Resources / Additional resources

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2021]
Wherever a resource name is presented, the name is a hyperlink, that opens it in a new tab.
Users can download it from the browser.

1. In search results back of card: Show the type of the resource as a hyperlink. add a tooltip showing the name of the file.
<img width="298" alt="Screen Shot 2021-12-15 at 14 39 23" src="https://user-images.githubusercontent.com/88834002/146188687-261a1f41-1792-4397-8553-66081d29f063.png">

2. In publish page, Add resource page:
<img width="292" alt="Screen Shot 2021-12-15 at 14 41 16" src="https://user-images.githubusercontent.com/88834002/146188788-3b3132d0-251f-41d9-86e8-7b0a3fd47a50.png">

3. In player - JIG info popup: Show the type of the resource as a hyperlink. add a tooltip showing the name of the file.
<img width="396" alt="Screen Shot 2021-12-15 at 14 38 06" src="https://user-images.githubusercontent.com/88834002/146188871-dd666dd2-afd5-40a3-978f-a9779c468da9.png">

**Comment by corinnewo** [comment]
@GaliShapira It must be clear that it is the name of the file and not 'Lesson plan', 'Curriculum',  etc. It looks like it will always be this set of 5 items, but it will be the list of names of the files.

**Comment by GaliShapira** [comment]
@MendyBerger Can we show the resources types only, and in a tooltip we show the name of the file?

**Comment by MendyBerger** [comment]
@GaliShapira sure possible

**Comment by GaliShapira** [comment]
Thank you, @MendyBerger  so lets start that way.
