### ISSUE TITLE
Add resource flow - change icons colors and switch places

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2023]
**Resources flow_MS_06**

Change the icons' colors, there is too much blue, its not similar to our other icons in the series.
Also switch sides, the left one should be on the right.

<img width="260" alt="Screen Shot 2021-12-15 at 14 52 00" src="https://user-images.githubusercontent.com/88834002/146190189-7f25ec90-2468-4cd9-a4a2-34c079ac7dd0.png">

**Comment by GaliShapira** [comment]
**Updated icons:**
<img width="260" alt="Screen Shot 2021-12-15 at 14 52 00" src="https://user-images.githubusercontent.com/88834002/146336044-b9950d9a-750e-434e-a865-3d75bba38a8c.png">

See in Zeplin:
https://zpl.io/aRk6P3E

**Comment by meravs** [comment]
https://zpl.io/brOG6e
![Screen Shot 2021-12-16 at 15 19 47](https://user-images.githubusercontent.com/96105053/146379283-35fb0037-522e-4fc1-86f2-977ca354db52.png)
[Archive.zip](https://github.com/ji-devs/ji-cloud/files/7727585/Archive.zip)
