### ISSUE TITLE
Home page - content banners materials + icons gallery

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2025]
See the banners with real texts and banners made by @ChaykeeMor . 

Place in the gallery by the order as you see on Zeplin:
https://zpl.io/bln7JY1

Here are the banners:

![banner-ji-alefbet](https://user-images.githubusercontent.com/88834002/146230233-4e7d6737-335f-4a39-9a09-6ded38e5bb54.jpg)
![banner-pj-library](https://user-images.githubusercontent.com/88834002/146230324-54a062d0-dd5c-48aa-af79-9fc359e85f8b.jpg)
![banner-iml](https://user-images.githubusercontent.com/88834002/146230353-b29184c4-7b7d-412f-b458-a595b987907f.jpg)
![banner-hop](https://user-images.githubusercontent.com/88834002/146230374-b741aeba-f3a8-418d-a47e-2d332addb285.jpg)
![banner-olam-shalem](https://user-images.githubusercontent.com/88834002/146230093-48734b44-7e6a-440b-845d-eae2495d3227.jpg)
![banner-superheroes](https://user-images.githubusercontent.com/88834002/146230152-c93869ed-8201-4c10-8270-5686b9a1404b.jpg)

**Comment by GaliShapira** [comment]
Also @corinnewo 
Pls see all the icons for the top gallery here including hover state (slightly bigger):
[Topics icons for the Homepage.zip](https://github.com/ji-devs/ji-cloud/files/7744811/Topics.icons.for.the.Homepage.zip)

**Comment by corinnewo** [comment]
@GaliShapira @MendyBerger We need to decide about the Wordpress iframe - if going ahead with that, I can implement. If not, @MendyBerger will have to do it.
