### ISSUE TITLE
Legacy player - home page is stretched - should be size of the rest of the screens

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2035]
Surely the legacy thumbnails should not be stretched - the same size as the other screens.
![image](https://user-images.githubusercontent.com/16290361/146415110-1355875c-6617-43f1-8d1b-199fe6ff9297.png)

**Comment by dakom** [comment]
There is nothing I can do about this... the spec for thumbnails and cover page are designed as 16:9, not 4:3.
