### ISSUE TITLE
Legacy - test game from Ji Alef-Bet - skips a screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2039]
In the test JIG "Let's read about tet", after playing screen 04, the next screen should be screen 05, but it is going to 06. 

![image](https://user-images.githubusercontent.com/16290361/146541856-be7df125-eb62-45ac-a541-1c8fc2f93c87.png)

**Comment by corinnewo** [comment]
It seems like the next screen after video plays is not the next screen. When you play video on screen 10, should got to screen 11. Instead, it goes to 12, which is a jump back to the menu screen. So I never see the second part of the video!

**Comment by corinnewo** [comment]
It seems like the next screen after video plays is not the next screen. When you play video on screen 10, should got to screen 11. Instead, it goes to 12, which is a jump back to the menu screen. So I never see the second part of the video!

**Comment by corinnewo** [comment]
![image](https://user-images.githubusercontent.com/16290361/146546399-3cc82a4c-c924-416c-922a-666455970560.png)

**Comment by dakom** [comment]
Note to self- since leaving the module is always definitive, this can be gated to prevent double-send
