### ISSUE TITLE
In player - highlighted hotspot is very thick!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2041]
Can we make the highlight a bit more delicate?
![image](https://user-images.githubusercontent.com/16290361/146543399-7d38a960-e9d8-437c-8cbe-45221aa8898d.png)

**Comment by dakom** [comment]
This uses the Jigzi ShapeStyle stuff, isn't legacy-specific

**Comment by corinnewo** [comment]
We have had feedback from a user again that the lines are too thick and their thickness is affecting the content. PLEASE make this blue highlight line thinner!

![152f2c8e-1d42-4da1-9b46-5e4b842f21e0-please_attach_a_screenshot_illustrating_the_issue_you_experienced_here-Screenshot_20230205_151530_Samsung-Interne](https://user-images.githubusercontent.com/16290361/216942767-a9d1f913-7355-403b-a75e-851e37e595d5.jpg)

**Comment by corinnewo** [comment]
This has been made thinner. Closing.
