### ISSUE TITLE
Legacy - In IML game  משפחה: החיות שלנו, jump to does not seem to be working and puzzle progress to next screen not progressing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2042]
@ChaykeeMor Please take a look at your IML game that we imported as a test. Please check that it works as it should.

משפחה: החיות שלנו

For example, in this screen, I assume it is a menu. Nothing happens when I click.
![image](https://user-images.githubusercontent.com/16290361/146544975-7e126c1f-3ed2-4630-9f19-6ac23f786fe3.png)

**Comment by corinnewo** [comment]
@dakom Look at https://jitap.net/activities/gdhm/play/. The menu in generated game is not working at all :(

**Comment by corinnewo** [comment]
@MendyBerger When playing this from David's direct link (https://sandbox.jigzi.org/jig/play/b9d46412-5e9f-11ec-aced-93651d382cd5?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false) - this plays well. But from the PLAY on search results, the menu does not jump to the screen.
Seems to be a player issue.

**Comment by dakom** [comment]
@MendyBerger I am sending the event via `IframeAction::try_post_message_to_top()`... if that's not the right thing to do, please let me know and I'll change it. Otherwise, it seems like a bug in the player?

**Comment by dakom** [comment]
I believe this is being sent from other modules too...

Why not just have the play button on homepage go straight to the jig player? Would solve this and also let users copy/paste the url directly for sharing.. (@corinnewo I imagine this starts as a UX question, I am sure direct links are the _easier_ thing to implement technically)

**Comment by corinnewo** [comment]
Definitely would be good to have the url. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dakom** [comment]
@MendyBerger to pave the way for a more adaptable solution overall, I am going to add a .try_post_message_to_player() method on IframeAction which will use a global var to control the behavior (`top` will be the default). That will make this problem much more manageable since it will reduce it down to just setting that global var somewhere somehow.

We try to avoid global mutable vars in general, but I think this is a very rare, valid exception to that rule.

**Comment by dakom** [comment]
I've now changed all the legacy games to use the `try_post_message_to_player()` and made this configurable.

As it's now a generic Jigzi issue (i.e. applies to every other module as well), I'm removing the `legacy` label and unassigning myself.

(happy to participate in discussion, there's just nothing for me to do in terms of legacy itself)

**Comment by dakom** [comment]
@MendyBerger see https://github.com/ji-devs/ji-cloud/blob/1529ad7207c72176c65f72718dda6c860b85226c/frontend/apps/crates/utils/src/iframe.rs#L64
