### ISSUE TITLE
Search does not seem to be searching within the game description

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2043]
In sandbox, I was searching for a word within the description "Goulston", and nothing is found. When I search for 'Tet', then because it is in the JIG name, it is found. THis is a JIG that we are using as a test case for the legacy games import from Ji Tap. 
PLease check why the description is not being searched. Thanks!

**Comment by corinnewo** [comment]
@MendyBerger FYI

**Comment by MendyBerger** [comment]
Not sure, but this might only a problem on legacy games

**Comment by corinnewo** [comment]
@RickyLB On sandbox, seems that the name is being searched, but not the description. HOWVER, on JIgzi, it seems that the search is not working in both JIG name and description. No search results at all at the moment!

**Comment by RickyLB** [comment]
Api apparently wasn't syncing `descriptions` from the db to algolia. I've made a PR for this and will have all indexes updated with the field.

**Comment by corinnewo** [comment]
@RickyLB  On Jigzi, still not searching within descriptions.

Test case: 

1. Search for 'Michael Goulston'. Returns no results. 
2. But search for game "Let’s Read About Tet (ט)", and that comes up, and within description is 'Michael Goulston'. 

Michael Goulston is the foundation that paid for over 100 games to be developed, so that is why I am searching for it. But the search is not working within description. Please can you fix this? Thanks

**Comment by RickyLB** [comment]
@corinnewo Sandbox seems to be producing results for "Let’s Read About Tet (ט)" when searching "Michael Goulston" now.

<img width="1467" alt="Screen Shot 2021-12-22 at 3 47 08 PM" src="https://user-images.githubusercontent.com/76449893/147167521-3edb39e1-ef9b-474d-ba13-49410e5a6323.png">

**Comment by RickyLB** [comment]
This has been fixed in release now. Closing this issue.
