### ISSUE TITLE
Feature request: option to skip cover in jig player

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#2045]
I understand that all jigs _technically_ need a cover, and among other things this is used to guarantee that there is a thumbnail (even if the thumbnail is blank or theme-based)

However, in some cases there is no need to actually treat the cover as a standalone module for playback.

This is especially true for the Legacy games where the cover is generated from the first module, which introduces a few problems:

1. The screen is duplicated, makes things a bit confusing
2. The screen often has instructions or clear UX indicating interactivity. Makes things _very_ confusing.
3. The 4:3 to 16:9 stretch is quite jarring.

If we could have a `skip_cover_page_in_player` or similar option in JigData, then we can have it default `false` but set it to true for all modules.

@MendyBerger - I'd imagine this is pretty easy to implement in the player, though it has to be done carefully, e.g. the "jump to index" will have to work with indices as though the cover _were_ there (the modules won't send a different index depending on this setting, the modules won't even know about this setting).

If doing this as a proper JigData isn't feasible, for whatever reason, the Jig Player could perhaps do this for only legacy games, i.e. by looking at the first non-cover module's kind.

**Comment by MendyBerger** [comment]
How about we remove the requirement for a cover altogether? Would that make sense?

**Comment by MendyBerger** [comment]
Closing since default covers have been removed
