### ISSUE TITLE
Legacy player - map the language from Ji Tap into Jigzi

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2050]
At the moment, all games have come in as English. 
I think that we need to have the language that was defined in the JSON in Ji Tap. I mapped the numbers that are in the JSON to the actual languages. 

- All English should just be brought in as English - not differentiating with countries.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CORINN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CORINN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Number   in JSON | Language | Lang   abbreviation | Jigzi
-- | -- | -- | --
NOT IN JITAP | Arabic |   | AR
16 | Danish | DK | DA
8 | Dutch | NL | NL
1 | English | EN | EN
14 | English-AUS | EN | EN
13 | English-CA | EN | EN
10 | English-RSA | EN | EN
12 | English-UK | EN | EN
9 | French | FR | FR
11 | German | DE | DE
2 | Hebrew | HE | HE
18 | Hungarian | HU | HU
19 | Italian | IT | IT
7 | Portuguese | BR | PT
6 | Russian | RU | RU
5 | Spanish | ES | ES
17 | Swedish | SV | SV
NOT IN JITAP | Yiddish |   | YI

</body>

</html>

**Comment by dakom** [comment]
Updated all the current jigs in release and fixed it so that future jigs will use the language setting
