### ISSUE TITLE
Creator menu - change ages names + Add to action menu play and share options

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2055]
@meravs 

**Creator menu_01_MS**
(As we have later versions which were not applied at this stage, Can you name the new file "Creator menu old version_02_MS"?)

1. Ages are changed following the search results shortcuts and presenting range.
As in issue #2033  (no. 3).
<img width="604" alt="Screen Shot 2021-12-21 at 10 44 21" src="https://user-images.githubusercontent.com/88834002/146899288-03cfcb00-0907-484b-af28-4598200b6c1d.png">
<img width="290" alt="Screen Shot 2021-12-21 at 10 44 27" src="https://user-images.githubusercontent.com/88834002/146899311-4107de05-e41e-480f-b691-1c7ed30f592c.png">

2. Play and share options are added to the actions menu of each JIG.
<img width="124" alt="Screen Shot 2021-12-21 at 10 41 21" src="https://user-images.githubusercontent.com/88834002/146899354-71bc1c28-ee9f-40ed-b73e-ff07c4941292.png">

Pls upload here the new screenshots and the Zeplin links, including the components page of the new icons.

**Comment by meravs** [comment]
![Screen Shot 2021-12-21 at 16 11 37](https://user-images.githubusercontent.com/96105053/146943890-41937856-e985-4c1f-ac15-77a13a06212d.png)
https://zpl.io/a34o3KQ

**Comment by corinnewo** [comment]
@GaliShapira I think we should have **Play** and **Share** above **Duplicate**. What do you think? Probably the most frequently used button would be to play.

**Comment by GaliShapira** [comment]
@corinnewo  I agree. Done.

**Comment by corinnewo** [comment]
@MendyBerger This is what we discussed yesterday that would help David - Chana could play the JIGs from the gallery while the search results are not working.

**Comment by corinnewo** [comment]
Similar to https://github.com/ji-devs/ji-cloud/issues/2258 with the age ranges.

**Comment by mastapegs** [comment]
there is an endpoint for duplicate
