### ISSUE TITLE
Jigzi search - not returning any results, but sandbox is

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2061]
even though there are thousands of JIGs, the search results show 0, even when there are no fields entered.
![image](https://user-images.githubusercontent.com/16290361/146964218-5705a042-341f-4b03-ba88-d9b851fa8903.png)

**Comment by RickyLB** [comment]
@corinnewo Working now! I guess I missed adding `jig_focus` as a facet in Algolia.
