### ISSUE TITLE
Registration and Profile: Make persona list multiselect and add in a value

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2070]
As a result of the usability testing, we need to make the persona ("I am a...") list multiselect. Users said that they have 2 funstions inthe organisation, and we don;t provide for that. 
They also asked to add '**Content manager**' to the list.

![image](https://user-images.githubusercontent.com/16290361/147059153-6e3d60e0-0d36-446c-bd4d-675e82407455.png)

**Comment by johnnynotsolucky** [comment]
This will require changes to the backend as well. Currently the backend supports a single [optional persona](https://github.com/ji-devs/ji-cloud/blob/sandbox/shared/rust/src/domain/user.rs#L159) which will need to be updated to support a list of personas instead.

**Comment by corinnewo** [comment]
@MendyBerger FY - I've added Ricky to this ticket

**Comment by RickyLB** [comment]
@johnnynotsolucky @corinnewo Just merged a PR into sandbox to add multiple personas.
