### ISSUE TITLE
JIG player- side panel - i tab - List the additional resources

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2075]
In the JIG player's i button, there is a list of all the information about the player. The additional resources says 'Coming soon'. PLease replace this with the list of additional resources for this JIG. 
If there are no additional resources, then either hide the whole section, or say 'None' in the space of the list. I prefer hiding that area if there are no resources.

![image](https://user-images.githubusercontent.com/16290361/147103225-2945ab9d-6673-4135-b95c-a6b57b0632f9.png)

**Comment by MendyBerger** [comment]
Resolved in 5590f5a6
