### ISSUE TITLE
For Legacy games - transparent icon to place in the JIG panel sections

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2077]
[icn-activities-jigpanel-legacy.svg.zip](https://github.com/ji-devs/ji-cloud/files/7764380/icn-activities-jigpanel-legacy.svg.zip)

Pls use this transparent icon instead of the missing icons.
<img width="123" alt="Screen Shot 2021-12-22 at 19 59 48" src="https://user-images.githubusercontent.com/88834002/147135679-fe60a6e4-4625-436b-9625-f9c009108f1b.png">

**Comment by corinnewo** [comment]
@GaliShapira Please attach the transparent icon to the ticket. Thanks
