### ISSUE TITLE
Legacy games - Add legs of the JIG under the last activity

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2078]
This is what we see now:
<img width="422" alt="Screen Shot 2021-12-22 at 20 04 11" src="https://user-images.githubusercontent.com/88834002/147136159-3a653c0f-8219-4bea-afc9-cab936a5778b.png">

Pls place the illustration used in the other games:
<img width="130" alt="Screen Shot 2021-12-22 at 20 01 49" src="https://user-images.githubusercontent.com/88834002/147136215-eaf09ccc-8a25-431f-bfb2-c847c325269a.png">

**Comment by corinnewo** [comment]
@johnnynotsolucky This is in the JIG panel within the player.

**Comment by johnnynotsolucky** [comment]
@corinnewo @GaliShapira this looks like it affects all JIGs.

**Comment by johnnynotsolucky** [comment]
The change in #2095 makes the robot feet appear twice when editing a jig. It’s a one-liner, I’ll update shortly.
