### ISSUE TITLE
Footer - Add "Dedicated in memory of Yochanan Hillel ben Mordechai" 

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2079]
1. Add at the button of the footer a borderline and underneath the line add the sentence.
2. Change J-Steam to J-Stem.

https://zpl.io/VOl1nE1

<img width="856" alt="Screen Shot 2022-01-04 at 12 41 30" src="https://user-images.githubusercontent.com/88834002/148047646-c3e1cb85-7f81-48fe-ae9e-ef41e2e11446.png">

**Comment by mastapegs** [comment]
Should the `Products & Services` wording of `J-STEAM` remain as is? I just wanted to verify. Picture with arrows showing what I'm referring to from **Sandbox** below

![image](https://user-images.githubusercontent.com/13839150/148406815-1a83de34-a015-4b67-bd76-2c1c4efa46da.png)

**Comment by corinnewo** [comment]
Please change J-Steam to J-STEM! Thanks for asking. 2 instances in the footer. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by mastapegs** [comment]
I've updated the attached PR with that change @corinnewo

**Comment by corinnewo** [comment]
Please change every case of J-STEAM TO J-STEM! 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by corinnewo** [comment]
Thank you!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
