### ISSUE TITLE
Sizing - Navigation menu

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2088]
Hi @MendyBerger 
Pls see the navigation menu sizing.
Icons, texts and buttons are smaller in the smaller screens.

https://zpl.io/adnAEQn

<img width="824" alt="Screen Shot 2021-12-23 at 22 13 21" src="https://user-images.githubusercontent.com/88834002/147287826-14909098-7040-4ae9-bbdf-0f32800f45b6.png">

**Comment by corinnewo** [comment]
@GaliShapira What about mobile? Perhaps it should become a hamburger menu on mobile. like Wordpress does.

**Comment by GaliShapira** [comment]
@corinnewo 
Of course, I will show it on mobile. Waiting for Mendy's reply regarding mobile sizing. (#2092)

**Comment by MendyBerger** [comment]
Resolved e1699170b8bd670a5c7c93d8dac6798b52931880
