### ISSUE TITLE
Create: "Don't show again" Tooltip is missing

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2103]
When clicking X on tooltips, "don't show again" is missing

![Screen Shot 2021-12-28 at 7 59 14 AM](https://user-images.githubusercontent.com/78186896/147568815-189fb87b-8b12-4d3a-b90f-1b50a458f369.png)

**Comment by MendyBerger** [comment]
@johnnynotsolucky assigning to you since this is related to what you were doing.

FYI The don't show again was there before I moved JigziHelp to the Rust side.
