### ISSUE TITLE
LEGACY player - Jigzi - animated gif in IML not playing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2105]
Anat has just pointed out that the animation from IML is not playing in JIgzi. 

Ji Tap: https://jitap.net/activities/gdlw/play/ - screen 5 - 'say something' - animation of hedgehog juggling cucumber.
![image](https://user-images.githubusercontent.com/16290361/147574046-294107d0-0f66-4cf4-8856-73e1ed183a27.png)

Jigzi: https://jigzi.org/kids/3704  (or search for בגינה שלנו)
<iframe src="https://jigzi.org/jig/play/fee21310-60f2-11ec-8b2b-1b8da0e29c39?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false"></iframe>

Screen 06 in Jigzi - blank

![image](https://user-images.githubusercontent.com/16290361/147573981-8fd3f246-b26d-46ae-bc1d-28208c752aa3.png)

**Comment by dakom** [comment]
Note to self, debug url: https://sandbox.jigzi.org/module/legacy/play/debug/debug?game_id=16402&slide_index=4

**Comment by dakom** [comment]
Fixed, will be available on release next time @MendyBerger merges
