### ISSUE TITLE
Player - share options - COPY URL returns a ???

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2106]
In the JIG player, when you share with students, the URL is generated with the code for the child. THe embed code seems to be working.
But when you 'Copy URL' and paste it, you paste ???.
Please fix so that the URL that is copied is usable.

![image](https://user-images.githubusercontent.com/16290361/147575780-9f990934-f299-4099-ba55-46d05a301b46.png)

**Comment by MendyBerger** [comment]
Resolved in fa299cb4

**Comment by corinnewo** [comment]
@MendyBerger please see https://github.com/ji-devs/ji-cloud/issues/2154 to add in some sort of indication that the URL has been copied. Thanks
