### ISSUE TITLE
Player share - embed code - Sizing needs to be fixed

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2107]
I copied the embed code and put into a new page of the Ji website, and it came out as follows:

![image](https://user-images.githubusercontent.com/16290361/147578555-0f494c65-d5c0-485d-9124-e80cd18c3c89.png)

Embed code I copied:
<iframe src="https://jigzi.org/jig/play/fee21310-60f2-11ec-8b2b-1b8da0e29c39?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false"></iframe>

Is it not missing the dimensions of height and width?

**Comment by MendyBerger** [comment]
Resolved in 06b1babe
