### ISSUE TITLE
After preview mode: Duplicate Jiggling texts appearing on screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2110]
Top left corner still has an empty dialog box. Please remove!

![image](https://user-images.githubusercontent.com/16290361/147642423-103dff07-1aac-481e-aadd-255f011b44a9.png)

**Comment by corinnewo** [comment]
AND, after preview mode, I went back to see the settings, and suddenly there are 2 dialog boxes!
I think please remove the dialog completely from the top left - we took it out of the preview for a reason - it just got in the way.

![image](https://user-images.githubusercontent.com/16290361/147643253-eae9d60c-229c-4126-9664-0edab3cb7079.png)

**Comment by corinnewo** [comment]
@MendyBerger - tagging you

**Comment by corinnewo** [comment]
In fact, it seems to be everywhere - here is the cover. From preview, go back to earlier wizard steps, and the jiggling text appears twice.
PLEASE take off the dialog totally from the preview mode - we had added in the text below the heading (Your work is auto-saved. To make changes, click back to any step.) so that there was no need for the JIggling text any more. Please 
remove this dialog totally from PREVIEW mode. No Jiggling text here.

![image](https://user-images.githubusercontent.com/16290361/147646542-0889eaff-6c6b-40b5-b958-b8f6b646b728.png)

**Comment by johnnynotsolucky** [comment]
@corinnewo @MendyBerger 

To reproduce:
1. Edit a jig
2. Note the tooltip appears for the first step
3. Click "Preview" - Note the empty tooltip that appears in top left of screen
4. Click back to Step 1 or any other step other than Preview - Note two tooltips appear.

It looks like the signal which creates the tooltip fires twice [here](https://github.com/ji-devs/ji-cloud/blob/sandbox/frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/regular.rs#L156-L165) when we switch back from preview mode - I haven't worked out why yet.

https://user-images.githubusercontent.com/4161106/147655928-8a904649-0d59-4f17-aa07-4ecc1c0377fc.mp4

**Comment by johnnynotsolucky** [comment]
This looks like there is a reference created inside [`JigziHelp`](https://github.com/ji-devs/ji-cloud/blob/sandbox/frontend/apps/crates/components/src/module/_common/edit/entry/base/dom/regular.rs#L161-L166) somewhere which is not being dropped when the JIG editor is switched to Preview mode and back again. I think that somehow that reference is being re-rendered, and then a new reference is created.

I modified the code slightly to test, and can confirm that each time I switch to Preview mode and back, it renders 1 more JigziHelp component and rerenders the previous set of components.

**Comment by corinnewo** [comment]
@johnnynotsolucky @MendyBerger What is happening with this bug? I am still getting duplicate dialog boxes when going back from a preview.

**Comment by johnnynotsolucky** [comment]
@corinnewo we are still working on this - David and I will meet early next week to see if we can work out what is causing this issue.
