### ISSUE TITLE
Gallery (Create page) - search returns results of JIGs that are not mine to edit (and I am able to edit them!)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2113]
In Sandbox, I searched on Gallery Page for 'Quiz' and all the JIGs in the system that had 'quiz' were found:
![image](https://user-images.githubusercontent.com/16290361/147656265-7bf1b3ea-c3bb-45df-8032-a52310bb9ef6.png)

On Gallery page, search should only be within MY JIGS, and I should only be able to open a JIG to edit if it is mine.

@MendyBerger is this a LB issue or Ji?

**Comment by MendyBerger** [comment]
Resolved in 8ed4aaf8, but still has a backend bug #2116
