### ISSUE TITLE
Resource - After created cover, the text needs to be changed

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2124]
Currently, after creating the resource cover, you get this:
![image](https://user-images.githubusercontent.com/16290361/147742990-3820d97f-ed44-4a41-84a4-5db7222c9769.png)

According to the Zeplin, there is no preview of the resource cover. Goes back to the dialog with the thumbnail in place.

THen once it is published, you get this screen: https://zpl.io/2ZA31vL

**Comment by MendyBerger** [comment]
Done
