### ISSUE TITLE
Resource dialog- Publish later button goes nowhere

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2127]
Can't get out of this dialog without publishing again.
If you click PUBLISH LATER, nothing happens. Please make sure that it closes this dialog and goes back to where it came from (my resources gallery)

![image](https://user-images.githubusercontent.com/16290361/147744171-bff4038a-4b03-4bdb-ac26-ae7b6be732e8.png)

**Comment by corinnewo** [comment]
@MendyBerger Perhaps we should also add in an X button on the top right corner to simply close this publish dialog?

**Comment by MendyBerger** [comment]
@corinnewo what does it mean to close the publish dialog? Where would you go? And what problem will if solve?

**Comment by corinnewo** [comment]
It would go back to "My Resources Gallery" as a draft, and I can come back and publish later. At the moment, I cannot leave the dialog unless I publish. We can't have a button that does nothing! If it does nothing, then we should remove it! But I do think that there is value in having it, as long as it takes you out of the dialog! In the JIG publish, the button 'Publish later' takes you back to the gallery. Should behave the same way for resources!

**Comment by corinnewo** [comment]
closing in favor of #3569
