### ISSUE TITLE
Search with language is not working at all

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2130]
I searched for alef bet with 'All languages' selected. Got 37 results.
![image](https://user-images.githubusercontent.com/16290361/147745866-19c777d6-65ac-4630-bb95-2c1b860b8e56.png)

I then changed the language to 'English' and I got 0 JIG results and 1 resource result.

![image](https://user-images.githubusercontent.com/16290361/147746124-bee9fc1d-c861-4531-aeaf-86f5b1818d82.png)

Why is not finding any English JIGs? Is it to do with the 'EN' rather than 'English' that appears on the JIG cards?

**Comment by corinnewo** [comment]
@MendyBerger FYI

**Comment by corinnewo** [comment]
@RickyLB Do I need to set up synonyms for the languages in Algolia?

**Comment by MendyBerger** [comment]
@corinnewo @RickyLB don't think the solution is synonyms

**Comment by corinnewo** [comment]
It seems to be working now.
