### ISSUE TITLE
Flashcards - Play settings

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2132]
We need to add in the ability to choose which card is displayed and which is covered.
Ability to choose to show word and cover the picture, or better still, show picture and cover the word.

Same option as in Matching or quiz game, to swap the content. 
How should your cards be displayed?
![image](https://user-images.githubusercontent.com/16290361/147748667-5a8e724c-e492-417d-b29f-1fac3f81db3a.png)

@ChaykeeMor - please add to your list of play settings
@MendyBerger  - please implement - add in a third option

![image](https://user-images.githubusercontent.com/16290361/147748911-4eecb3b8-e5eb-45c9-b914-8a1057d90c3b.png)

**Comment by MendyBerger** [comment]
Assigning @johnnynotsolucky as he played with the card modules lately

**Comment by ChaykeeMor** [comment]
already included this on my end. this is the 'card shown' you were asking about @corinnewo

**Comment by johnnynotsolucky** [comment]
@corinnewo at the moment the flashcard game cycles through all the combinations so that it shows the picture, covers the word and then the next round it shows the word and covers the picture.

Does task mean there should be a new config that lets you choose to only show words or only show pictures?

**Comment by corinnewo** [comment]
@johnnynotsolucky Yes please. I think in a classroom situation, the teacher would want to show the image and children answer the word. Makes sense to make the whole series the same - teacher chooses the column that is displayed and which is hidden.

**Comment by johnnynotsolucky** [comment]
@corinnewo if theres the option to display double-sided or side-by-side, i think that we should add a new section which then lets the teacher customize which column to display/hide or randomize. Otherwise we could add the option to a pull down for the existing options?

**Comment by ChaykeeMor** [comment]
Is there a technical issue with having 3 options in one section 2 of which are mutually exclusive and 1 of which applies in both scenarios? If not, I believe it is simplest for the user experience to have 3 icons to answer the 'how should cards be displayed' question. Additionally, there's no benefit to randomization cross columns [randomizing within columns is fine]. Like @corinnewo said, this icon should be choosing the column that displays. Remember, this has to work for all use cases within the module so not just for word/image, but word/letter, word/other word. etc.. Need the ability to decide which column is the question and which is the answer.

**Comment by johnnynotsolucky** [comment]
@ChaykeeMor sorry, I had actually misunderstood most of this earlier. I had incorrectly thought that each section should only have one selected scenario. I had also assumed that the current behavior of randomizing across columns should remain. 

I think then that we can do exactly what you said - have the 2 scenarios and then the new option which toggles which column is the question/answer, and remove the randomization altogether.

Also, currently the flashcards game doesn't end. You can just keep flipping through cards indefinitely, is that correct?

**Comment by ChaykeeMor** [comment]
each section often does.  so the assumption is fair. The way cards are displayed is not mutually exclusive and the way videos are played. I'm pretty sure the rest are toggles either this or that.

as for your last question, I suppose we should allow the user to set how many times to go through the entire list [like pages per game of matching] but that's not a priority. For now, let it flip through indefinitely and they could click the arrow when they want to move on.
