### ISSUE TITLE
(feature request): Publish should generate thumbnail

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#2140]
I noticed that when I batch-published the jigs, thumbnails weren't generated.

Not sure what kicks off the screenshot tool right now, maybe it's just when a thumbnail is attempted to be loaded the first time...

Would be nice if publishing could generate thumbnails, without depending on a frontend load attempt

**Comment by corinnewo** [comment]
@dakom This also happens when you open up the JIG panel in the player for the first time - no thumbnails. Then second time, there are thumbnails. Will discuss with @MendyBerger what can be done!

**Comment by MendyBerger** [comment]
@dakom yes, screenshots are generated if the server returns 404 on load.

https://github.com/ji-devs/ji-cloud/blob/9bea00be8b863597bb8a589009bbb59d8969ddff/frontend/apps/crates/components/src/module/_common/thumbnail/dom.rs#L17-L23
