### ISSUE TITLE
Create: Talking Poster - add premade templates?

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2141]
Hi @corinnewo,

When making a talking poster, you can select from several options, such as a family tree, comics, timeline, etc. Every option takes you to a blank canvas. I think there should be premade templates to differentiate each one (just as a base - it can be adjusted or changed by the user...) What do you think?

Edit: same applies to "drag and drop"

![Screen Shot 2022-01-02 at 5 14 17 PM](https://user-images.githubusercontent.com/78186896/147890786-8aa38000-73b0-4758-9e8d-5d7fd112aebb.png)

**Comment by corinnewo** [comment]
We should have the backgrounds that have been tagged for the various use cases show up first in the list.
Similar items: https://github.com/ji-devs/ji-cloud/issues/1567
https://github.com/ji-devs/ji-cloud/issues/2460
