### ISSUE TITLE
Play Settings: Time Limit - change display to minutes

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2143]
Currently, the timer displays in seconds. For example, I set the time limit to 2 minutes, and the timer counts down from 120. Time should be displayed in minutes:seconds format - 2:00, 1:59, 1:58, etc.

![Screen Shot 2022-01-02 at 6 16 35 PM](https://user-images.githubusercontent.com/78186896/147891992-547edd20-364c-4d1e-8b15-73993bfd0d48.png)

**Comment by mastapegs** [comment]
I'm working on issue #2145, moving the Jig timer away from the `X`, and since the timer UI is in the same area of code/logic, I figured I'd pick this up

**Comment by mastapegs** [comment]
This line is responsible for setting the value of the timer in the jig timer:

https://github.com/ji-devs/ji-cloud/blob/bf7954f9946db4191222b3e627fe6ff0fc23fa67/frontend/apps/crates/entry/jig/play/src/player/dom.rs#L300
