### ISSUE TITLE
Move Timer box In Jig Game so it it not attached to the X that is used to exit a game

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2145]
When I added a time limit to a Jig, the X that usually appears at the top right of the canvas (used to exit the Jig) lays on top of the timer box, making it appear as if pressing it will deactivate the timer (When in reality it will exit the game)

Suggestion:
Move the timer box so it is detached from the X

![Screen Shot 2022-01-02 at 6 22 49 PM](https://user-images.githubusercontent.com/78186896/147895439-952fa890-5927-4486-8e7b-c06a33ad26fc.png)
![Screen Shot 2022-01-02 at 8 45 54 PM](https://user-images.githubusercontent.com/78186896/147895443-813645e5-cae9-4660-9f3a-57847589ebca.png)

**Comment by GaliShapira** [comment]
Thank you, Its an important comment. I will work on it.

**Comment by GaliShapira** [comment]
@MendyBerger 
Pls change the seconds only to be mm:ss
