### ISSUE TITLE
Create Page - text changes

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2150]
text in Jigzi | Change to:
-- | --
Create a New JIG | Learning through creation
We have created lesson plans you can use for teaching. Create Jig from one of these templates to easily address all your student’s learning needs! | Create a new JIG (Jewish Interactive Game).  Use our lesson templates to easily create a JIG designed to fit your teaching goals or build your own from scratch.

**Comment by corinnewo** [comment]
Closing in favor of #2419, which is more updated.
