### ISSUE TITLE
Search results - less JIGs displayed so you can see resources

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2155]
- #2264
- [x] If there are no resources, then show only JIGs - hide the resource heading.
- [x] If there are no JIGs, only resources, then hide the JIGs heading, show only resource list.
- [x] If there there are no results, have a sentence saying that no results were found, with perhaps a hint to how to search better. @ChaykeeMor 
- [x] Text to display while search is running.

![image](https://user-images.githubusercontent.com/16290361/147941071-a83c4b1f-f0d0-4382-b2a5-843fb3e3e6e2.png)

**Comment by corinnewo** [comment]
Also, @ChaykeeMor, we need a text for what to display while it is searching, instead of the 0 results.

**Comment by ChaykeeMor** [comment]
@MendyBerger @corinnewo "Gee wiz! So many great JIGs and resources to sift through. Please wait while we find what you're looking for."

**Comment by corinnewo** [comment]
@ChaykeeMor - very long! Maybe just the "So many great JIGs and resources to sift through!" or simple "Please wait while we find what you're looking for."

**Comment by MendyBerger** [comment]
Controlling the amount of lines might be a bit tricky, @johnnynotsolucky please do the other things first

**Comment by MendyBerger** [comment]
Controlling the amount of lines might be tricky, @johnnynotsolucky please do the other parts first
