### ISSUE TITLE
Player differences between production to design and how to proceed

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2158]
Hi Corinne
A few comments about the way the player was developed that are not following the design and I don't know if any of these changes were decided:
1. The game starts automatically, play button does not exist, was planned to start by showing the open panel and an option to play. so the teacher can work with the layout first if she wants. https://zpl.io/am3WWzr
<img width="954" alt="Screen Shot 2022-01-04 at 9 56 39" src="https://user-images.githubusercontent.com/88834002/148027141-4ba3d567-6af1-47c0-9675-3197e762f068.png">

2. When playing, if I pause, the screen is darker. Why is that??? 
What if the teacher wants to pause or to mute sound in order to speak in front of the class, no mute option, and when pausing the teacher cant see the game or the JIG panel. 
<img width="1293" alt="Screen Shot 2022-01-04 at 10 01 57" src="https://user-images.githubusercontent.com/88834002/148027704-44c8894a-99af-49fe-ab0f-d8951dbac093.png">

**Comment by corinnewo** [comment]
@GaliShapira - I will discuss with Mendy tomorrow when he is back. He built the player.

**Comment by MendyBerger** [comment]
There are 2 separate issues for these changes 

1. #2208
2. #2196
