### ISSUE TITLE
Jig Settings: implement  Jig direction button to reflect in the player's progress bar

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2167]
In the Jig Settings, under preview, there is an option to change the Jig direction from left-right. It appears that this button does nothing in the player.

![Screen Shot 2022-01-04 at 2 01 52 PM](https://user-images.githubusercontent.com/78186896/148110203-ef825dbc-04cb-472f-9e6e-678124842f4b.png)

**Comment by corinnewo** [comment]
When the JIG setting is set to RIGHT TO LEFT. The player is supposes to  reverse direction of the arrows in the player bar. 

1. First screen should have the orange bar on the right, not the left
2. Arrow to go left is larger than arrow to go right

@GaliShapira I could not find the zeplin reference for the right to left player. Please add it here.

If we not implementing for MVP, then we must disable the option to play from Right to Left in the JIG settings.

**Comment by corinnewo** [comment]
if not implemented, hide

**Comment by MendyBerger** [comment]
Hidden

**Comment by corinnewo** [comment]
@MendyBerger As discussed, please 'unhide' the right-to-left option. The only effect it has is along the lower part of the player - the progress bar starts on the right, and the arrow to go forward one module is larger and on the left. The arrow on the right is smaller, and takes you back one module. Nothing else is repositioned. Thanks!

**Comment by MendyBerger** [comment]
Resolved in 6ab854124d2ccd36cbc11a47ae60261e1d4280ca
