### ISSUE TITLE
Search on home page - sometimes not finding anything and then hides most of the screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2176]
1. Search for a string, like 'Hebrew', Kindergarten age range, all languages
2. Get no results.
3. I unticked kindergarten, thinking that that may be the problem, returning it to all ages. Search again. No results.
4. I cleared the search text field and searched again.
5. Get the image below: whole home page has disappeared apart from search and the footer.

![image](https://user-images.githubusercontent.com/16290361/148236724-1f574219-cc97-411e-9270-c0ce03f7e79b.png)

**Comment by corinnewo** [comment]
I tried this again, and it is now fine. But this happened with Chana during a meeting earlier today, and it has happened to me again now. Seems to be intermittent, and reloading the page did not fix it either.

**Comment by MendyBerger** [comment]
Can't reproduce
