### ISSUE TITLE
Curation tool - essentials to have for Ji Tap Legacy games

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2180]
After our discussion today, these  are the essential elements that must be in the curation tool:

1. Search on the table for the name of a jig
2. make sure the jig name in the table looks like a link
3. make the table look better...
4. Once you open up the specific JIG to edit the content:

- Remove teaching goal item
- In affiliation, uncheck the no religion as the default 
- combine the SAVE DRAFT and PUBLISH buttons - changes will be published (on the assumption that there will not be edits made to the Ji Tap Library JIGs
- Add a button to play the JIG in a player, so that it can be checked and curated easily.
- Add in the RATING option - 3 stars

**Comment by MendyBerger** [comment]
Everything except affiliation is done, the one about affiliation should be a separate issue since it's not really related to curation but to publish
