### ISSUE TITLE
PUBLISH DIALOG: Reorganise the publish dialog as a stop gap measure

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2181]
As a stop gap for the MVP, please make the following changes to the publish dialog:

- [x] 1. ﻿﻿remove university from age range
- [x] 2. make only name compulsory
- [x] 3. Ages - default is 'All ages'
- [x] 4. Language - if can't detect, then default is English
- [ ] 5. Categories - must have that you can select main category and list to 2 levels only
- [x] 6. Remove teaching goal
- [x] 7. Text changes - especially the heading - @ChaykeeMor will make a ticket with the original and changed texts

**Comment by MendyBerger** [comment]
Should language not default to the users language?

**Comment by corinnewo** [comment]
Good idea!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by ChaykeeMor** [comment]
TEXT CHANGES

As on Jigzi | Chang to:
-- | --
Settings and JIG info. | Publish your JIG!
Last step before publishing | This information helps users find your JIG
My JIG is public | NO CHANGE
Add resource | NO CHANGE
Thumbnail | DELETE
JIG's name | JIG name
Type your JIG's name here | NO CHANGE
Language of instructions | Language of instruction
Select language | [Default to user language]
Age | Age Range
Select one or more | [Add 'All ages' to dropdown] [Default to 'All ages']
Teaching goal | DELETE FIELD
Select from the list | DELETE FIELD
Categories | Keywords
Select one or more | NO CHANGE
Description | NO CHANGE
This JIG is about... (include words that will help others find this JIG easily) | What's this JIG about?

**Comment by ChaykeeMor** [comment]
@GaliShapira is there supposed to be a Jiggling on the publish page? I have text for that too.

**Comment by GaliShapira** [comment]
Yes, it should to be there.

**Comment by corinnewo** [comment]
@ChaykeeMor @GaliShapira Might be too much to add in the clickable Jiggling text for MVP. But we will definitely come back to it after the MVP.

**Comment by MendyBerger** [comment]
> [Add 'All ages' to dropdown] [Default to 'All ages']
This is not a text change, opened a new issue for this #2230

**Comment by MendyBerger** [comment]
@ChaykeeMor should the 'R' in age range be uppercase? I see the other fields only have the first word capitalized

**Comment by ChaykeeMor** [comment]
> @ChaykeeMor should the 'R' in age range be uppercase? I see the other fields only have the first word capitalized

good catch. Should be 'Age range'

**Comment by MendyBerger** [comment]
5 is being tracked in #1448
