### ISSUE TITLE
If no cover is set on a jig, the first module cannot be deleted and no cover can be added

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#2183]
**Describe the bug**
When a JIG is created without a cover, the module context menu does not include a "Delete" option.

**To Reproduce**

1. Create a new JIG
2. Add a new activity, don't add a cover
3. Navigate back to the JIG edit gallery
4. Open the newly created JIG in the JIG editor
5. Attempt to delete the first activity - observe no Delete option, and no space to add a cover

**Expected behavior**
- Should be able to delete the first activity when no cover is set on a JIG.
- Should have a space to add a cover.

**Screenshots**

![image](https://user-images.githubusercontent.com/4161106/148344280-f3cfa121-4417-4cff-ad9a-0fbd46d4ab93.png)

**Additional context**
- Covers are no longer a requirement for a JIG.

**Comment by corinnewo** [comment]
Wow - Good find! Not only is the delete missing, when you come back to the JIG, there is no space to add a cover. This must be as a result of the Ji Library input.

Regular JIGs must always have a space to add a cover. It should not move the first module into the space for the cover.

**Comment by corinnewo** [comment]
If there is no cover, then it is taking the first module as the thumbnail. Should be blank if there is no cover.

**Comment by MendyBerger** [comment]
@corinnewo is this important? This would require us to have separate logic for legacy and regular jigs

**Comment by MendyBerger** [comment]
@johnnynotsolucky I think you should hold off on this until we discuss it

**Comment by corinnewo** [comment]
IN general - there seems to be a lot going wrong with the cover - if no cover, then thumbnail from module 1, Come pack to the jig again, and no place for the cover - module 1 has become the cover.

**Comment by corinnewo** [comment]
Seems to be working now. @johnnynotsolucky If no cover, it is OK to make the thumbnail for the JIG from the first module that has content. If afterwards, I add a cover, then that becomes the thumbnail. I'm closing this ticket - all good. Thanks!

**Comment by johnnynotsolucky** [comment]
Great @corinnewo! The changes which resolved the issue when editing are from #2217.
