### ISSUE TITLE
Resources - VIEW button is giving an error (on Jigzi, not sandbox)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2186]
I published a resource PDF on Jigzi, and when I turn the card to view it, it has this error: 
Search for flashcards

![image](https://user-images.githubusercontent.com/16290361/148358573-f1625f3c-0f30-4ab1-8fe1-feb0588366a6.png)

**Comment by corinnewo** [comment]
@MendyBerger Even though resources are not needed for the MVP, we want to add some in, like the educator guides, flashcards, etc. So they must have the view button working!

**Comment by MendyBerger** [comment]
@corinnewo 
Looks like this resources doesn't actually have a resource attached, please add one in that this issue should be resolved

**Comment by corinnewo** [comment]
Interesting… it uploaded without an error message originally. I will try again!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
