### ISSUE TITLE
Create: Play Settings - when selecting five cards to be displayed, score sign and Jigzi face Peaking hide words

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2191]
In the play settings, you can choose to display up to five cards to be displayed on the screen;  when selecting five cards, the most left card is covered by the Jig face, and when the display score is activated, the card all the way to the right is hidden.

Suggestion: The cards should be made smaller or arranged closer together.

![Screen Shot 2022-01-04 at 3 12 33 PM](https://user-images.githubusercontent.com/78186896/148252791-286eff2c-9c74-48fd-9fc9-ac04cbb349e8.png)

**Comment by GaliShapira** [comment]
Yes, All content in all the activities should always fit this frame:
https://zpl.io/anXyPdr

**Comment by MendyBerger** [comment]
Resolved in db2f7a250
