### ISSUE TITLE
Player update - end of JIG actions optionals

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2195]
<img width="599" alt="Screen Shot 2022-01-10 at 12 40 09" src="https://user-images.githubusercontent.com/88834002/148752744-197d99cd-8077-42a3-b891-5be9306b7afe.png">
<img width="897" alt="Screen Shot 2022-01-10 at 12 39 44" src="https://user-images.githubusercontent.com/88834002/148752761-e8304ed7-2c03-4188-b335-af847ec48d03.png">

1. End of JIG screen: Add Exit button to the student and teacher end of JIG page
<img width="141" alt="Screen Shot 2022-01-06 at 22 47 42" src="https://user-images.githubusercontent.com/88834002/148449647-37012e31-5833-43db-8139-19f19987932b.png">
7-9870546df640.png">
<img width="543" alt="Screen Shot 2022-01-10 at 12 26 50" src="https://user-images.githubusercontent.com/88834002/148751081-ba99cb90-747e-4fd4-8764-a6bc8fdd5478.png">

2. End of JIG screen: Teacher page: Add a share button to the actions. Add the X icon, bigger than the regular version if you can. Add the JIG icon. All are active above the darkening layer.
https://zpl.io/Vx98QDE
<img width="961" alt="Screen Shot 2022-01-10 at 12 27 02" src="https://user-images.githubusercontent.com/88834002/148751012-4986a211-0d23-465d-a744-1ae3e919ef14.png">

3. Add animations to end of JIG, end of challenging activity, end of activities #1732 
4. Add an open tooltip in the 5 first times of the user to show opening and closing option for the panel.
<img width="629" alt="Screen Shot 2022-01-06 at 22 55 07" src="https://user-images.githubusercontent.com/88834002/148450679-0ae00d6d-15ed-48e8-9850-13a8bd0b94f0.png">
https://zpl.io/VqrvAOZ
7. See sizing changes for 1280px:
https://zpl.io/a7DW6KY
https://zpl.io/VqrvAOZ
https://zpl.io/VD8A6lq
<img width="361" alt="Screen Shot 2022-01-06 at 22 52 08" src="https://user-images.githubusercontent.com/88834002/148450290-cfeb30a9-4989-4027-a396-2163f4326d0b.png">

**Comment by MendyBerger** [comment]
Something is off with the way this issue is displayed, are you able to fix it? It's hard to make sense of it like this

**Comment by GaliShapira** [comment]
@MendyBerger Let me know if its better now.
If not, lets meet to see what should be improved.

**Comment by MendyBerger** [comment]
Created separate issues:

1 #2271
2 #2272
3 #1732 
4 #2273
7 #2274

@corinnewo please mark MVP on the ones that need it

**Comment by corinnewo** [comment]
@MendyBerger Thanks - I have gone through and added to MVP what is essential for now (on the tickets).
1 #2271 MVP
2 #2272 MVP (similar to 2271 - should be done together)
3 #1732 MVP (If you already changing the options, then we should add the animations at the same time too)
4 #2273 Not for MVP
7 #2274 Not for MVP
