### ISSUE TITLE
Create - Text tab - Fonts - dropdown

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2198]
This applies to anywhere user can select fonts. We need the fonts to be in alphabetical order.

**Comment by MendyBerger** [comment]
This is probably not a quick fix

**Comment by corinnewo** [comment]
THis is still a huge issue! SMaller screens can not see the font list!

**Comment by corinnewo** [comment]
Also, on small screens the font list opens downwards and there is room for only 1 or 2 fonts to be seen. Please make it open upwards, so that more fonts can be seen more easily.
