### ISSUE TITLE
Create - All Modules - Use Case Page

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2202]
Subtitles on the use case pages is currently: "What do you want to do?" Please change to "Best ways to use this activity:"

**Comment by corinnewo** [comment]
@ChaykeeMor I think that there should be a colon here: "Best ways to use this activity:"
What do you think?
Can we use this for all, even the cards? Because, even, there, they are pedagogic suggestions.

**Comment by ChaykeeMor** [comment]
> @ChaykeeMor I think that there should be a colon here: "Best ways to use this activity:" What do you think? Can we use this for all, even the cards? Because, even, there, they are pedagogic suggestions.

Updated to colon and all modules. I was worried people might think there is no difference technically but fort he card games there is a difference for word/image or duplicates.
