### ISSUE TITLE
Shouldn't be possible to preview or publish an empty JIG, or a JIG which has a module with no content

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#2216]
**Describe the bug**

A JIG can be published without having any modules added. It can also be published with modules which have no content.

**To Reproduce**

1. Create a new JIG
2. Click Publish
3. Allows you to publish

**Expected behavior**

Shouldn't be able to navigate to the publish screen.

**Additional context**

This should apply to Preview JIG as well - Shouldn't be able to preview a JIG with no modules or modules with no content.

---

- [x] Update related endpoints so that module data includes `is_complete`
- ~[x] In the JIG edit sidebar, change the color of a JIG to red (instead of blue) if there's no content yet;~
  - [x] Update to remove the red color
- [x] Prevent them from publishing until all activities have content set.
  - [x] Update the publish endpoint so that it is not possible to publish when a JIG has incomplete modules
- [x] When previewing a JIG, render a new graphic on modules without content to illustrate that it is waiting for content.
- [x] Update `is_complete()` rules for each game type so that the minimum requirements are met for that type
- [x] On the publish screen notify the teacher that there are modules without content

**Comment by corinnewo** [comment]
@johnnynotsolucky I agree. Can't publish an empty JIG. Should we simply disable the preview button and the publish module if there is no content at all, and if either is clicked, perhaps add in a warning "Wait a minute! Please add some content to your JIG!" @ChaykeeMor - please comment on the warning!

**Comment by ChaykeeMor** [comment]
"Hmm..something's missing. If you'd like to publish this JIG, add activities and a cover."

**Comment by MendyBerger** [comment]
@johnnynotsolucky just keep in mind that we use the player to generate screenshots/previews of the module, so don't disable it on the player level unless we have a solution for screenshots

**Comment by johnnynotsolucky** [comment]
Thanks for the heads-up @MendyBerger!

**Comment by johnnynotsolucky** [comment]
@corinnewo should it be possible to publish _without_ a cover?

**Comment by johnnynotsolucky** [comment]
Disabling the preview/publish buttons when there are no modules is simple enough, but it is currently not possible to know if all the modules for a JIG have content. The data returned by `/jig/<id>/draft` endpoint includes the module ID and type of module. 

@MendyBerger I wonder if we should have an endpoint we can call to tell us whether a jig can be previewed or published? It can be called whenever the author clicks preview/publish. 

Right now preview will show an error if you try to play a module with no content, so both preview and publish will have the same requirements for being enabled:

- has cover
- at least one module other than cover (_?_)
- all modules have content

**Comment by corinnewo** [comment]
@johnnynotsolucky I think that only having a cover should be ok - could you not publish just a cover with additional resources (added in publish)? There would be a thumbnail for the JIG.
If a module does not have content, it should not crash - could there not be some default content there, even if it is only the current theme background?

**Comment by johnnynotsolucky** [comment]
@corinnewo for default content, this could be tricky. For games which have modes, such as card games, video, etc, if we set a mode by default, there is no way for the teacher to change the mode (that I know of?). I think that we have some options for this:

- Playing a JIG that has modules with no content, we handle the lack of content with a message instead of crashing;
  - But it still means a JIG can be published with modules without content set and students would probably see that message too.
- Or, update every module that uses a mode so that the default mode is not set, and update the logic which checks whether the content is set to display the mode selection to look for an unset mode instead.
  - I think that this would be the best approach so that the experience is more consistent and we can ensure there is _always_ content on any module (going forward).
  - It means that we'd need to still cater for existing drafts without content.
  - I'd also need to spend a bit more time making sure that all the defaults are good and that there is no other logic dependent on content not being set.

**Comment by ChaykeeMor** [comment]
WARNING UNFINISHED CONTENT: "Hmm..something's not quite done. If you'd like to publish this JIG, make sure all activities have content." Finish activity/Delete activity @corinnewo

**Comment by corinnewo** [comment]
THanks @ChaykeeMor - I like it!

**Comment by johnnynotsolucky** [comment]
@ChaykeeMor would this be when a teacher is previewing a JIG and the current activity is incomplete?

![image](https://user-images.githubusercontent.com/4161106/150112005-7b30f987-f6ee-4d3a-92d7-4d6fd625e42f.png)

The icon will change to be the same as the one in #2259

**Comment by ChaykeeMor** [comment]
@johnnynotsolucky Sorry this is confusing. This text is for a tooltip which will pop up by the JIG panel when trying to publish.
The text within preview mode is just 'no preview yet' with new illustration. Right @GaliShapira?
<img width="215" alt="Screen Shot 2022-01-13 at 16 18 20" src="https://user-images.githubusercontent.com/94056434/150115817-76a6779b-58bd-4f1c-99b4-f00570e764ce.png">

**Comment by GaliShapira** [comment]
I will upload here the exact details soon

**Comment by johnnynotsolucky** [comment]
For card games, it is possible to create a new word/image list. When this happens the function which determines whether a module is complete or not incorrectly set it to true because it checks just that there is content, not whether content which is required is actually present. In the case of card games, the lists are required.

Currently this means that if a card game is created, has a word list set, then the teacher clears the list, they can publish and play the JIG. Which will cause a similar error as before because the game expects a list of words/images.

I'm updating this task to include updating the rules for each game type so that they reflect the minimum requirements for that type.
