### ISSUE TITLE
Difficult to change activity config using the pulldown

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#2219]
**Describe the bug**

It is quite difficult to configure JIG modules using the settings pulldowns - The mouse pointer needs to remain within the bounds of the config item when moving over the pulldown otherwise it disappears. It also disappears when trying to make a selection when the pulldowns input is a select box.

**To Reproduce**

1. Create a new JIG and add a Matching activity;
2. Add the word lists, etc and navigate to step 3 to configure the module;
3. When hovering over a config item which has a pulldown config, attempt to move the mouse pointer over to the pulldown;
4. Observe that it can be a bit tricky to keep the pulldown open.

**Expected behavior**

Not really sure. Could we change the behavior of the pulldown to be more deterministic so that if a teacher clicks on the config item, the pulldown is shown instead of showing on hover. It can be hidden if the teacher clicks elsewhere or on a different item. We could probably include an 'x' to close the pulldown too.

Mainly I feel that having it only show up on hover is not great UX.

**Screenshots**

Unnecessarily long screencast:

https://user-images.githubusercontent.com/4161106/148733785-80ebedc0-ad66-45fe-8730-8abd2479b339.mp4

**Comment by corinnewo** [comment]
Agree - please fix - click icon and the bubble opens and stays open until you click out of it.
