### ISSUE TITLE
Player - place score and time under the X, change the UI

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2222]
https://zpl.io/bL911RB
1. Pls change the score and the time to round tabs as the design, not boxes.
2. Pls place them under the X icon as in the design.
<img width="266" alt="Screen Shot 2022-01-10 at 11 45 29" src="https://user-images.githubusercontent.com/88834002/148746589-d16fa4c2-4e69-489e-926f-cd524afa49ab.png">

**Comment by corinnewo** [comment]
@mastapegs Just making sure you have the final design for this, following our discussion in the meeting.

**Comment by mastapegs** [comment]
I do have the final design. Gali sent me the details via slack during our meeting earlier

![image](https://user-images.githubusercontent.com/13839150/148795116-417ae62b-819a-46a0-8642-e15ad8410b17.png)
