### ISSUE TITLE
Player is one slide off with jumps - since there is no longer a cover in the Ji Tap Legacy games

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2228]
I was showing Edward the Ji Alef-Bet games this morning, and they went haywire!
1. example: Mish mash letters - Vav and Zayin (https://jigzi.org/jig/play/b868a600-69c2-11ec-ab82-2fabd0b1edc5?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false):
 - skips over the menu screen on screen 02
 - after the videos (03 and 04) - automatically goes to 05, which sends you to the first video again, rather than the menu (02). Endless loop!
-on 06, the next arrow within the lesson should go to 07, but it is going to 08.
- similarly all along.

2. example Vav stands up straight (https://jigzi.org/jig/play/9e1d0d84-69d3-11ec-8bed-f38feabd7da3?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false)
- here, after screen 01, does go to the menu on screen 2
- click the menu option for animation - rightmost item goes to slide 04, not 03.
- etc

3. Example https://jigzi.org/jig/play/241ea9b4-69c1-11ec-ab82-3b489730761b?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false
- screen 01 - does not go anywhere, even when clicked.
- screen 02 - I don't think it is going to the correct screen - click the earphones - goes to end of activity.

Not sure why one skips over the menu, and the other goes to the menu but then is one out with the jumps. Both should have 'say something' on screen 01 with automatic continue to menu screen. something weird!

**I then randomly chose one of CHaykee's games: Gal Gadot (https://jigzi.org/jig/play/cecc3dfa-69cf-11ec-b7db-b7dfefeb2df9?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false) and screen 03 should show a map, but it is not showing anything! Same on screen 09.**

**Comment by dakom** [comment]
should be fixed in latest sandbox build, feel free to re-open if not
