### ISSUE TITLE
Publish page - add 'All ages' to dropdown, default to 'All ages'

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#2230]

**Comment by mastapegs** [comment]
Age Range is a meta value, going to have to make backend changes for this

**Comment by MendyBerger** [comment]
@mastapegs this is a frontend thing, are you referring to #2055?

**Comment by mastapegs** [comment]
Yes, I made this comment before our dev meetup. This refers to #2055
