### ISSUE TITLE
Hide templates on the gallery page

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2235]
Because we will not have the customization available yet for MVP, we need to hide the templates on the gallery page:

1. Hide the templates (will be bringing them back as soon as we have customization done)
2. Hide the button 'See all templates'
3. Leave only CREATE YOUR OWN box
4. Reword current text "We have created lesson plans you can use for teaching. Create JIG from one of these templates to easily address all your student’s learning needs!" with
**"Create a new JIG (Jewish Interactive Game). Choose the activities designed to fit your teaching goals and you'll have a complete interactive lesson in just a snap!"**
5. Remove the space in the heading below. Should be 'My Recent JIGs', with no extra space before the s

![image](https://user-images.githubusercontent.com/16290361/148899673-729854c4-1d6a-410f-bb8e-f8cf90f7ca14.png)

**Comment by ChaykeeMor** [comment]
@corinnewo how about "Create a new JIG (Jewish Interactive Game).  Choose the activities designed to fit your teaching goals and you'll have a complete interactive lesson in just a snap!"

**Comment by corinnewo** [comment]
THanks @ChaykeeMor - that's great!

**Comment by MendyBerger** [comment]
@mastapegs don't actually remove the templates, just comment out
