### ISSUE TITLE
Theme component - combined with former background component

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2238]
All flow link: https://zpl.io/a8dpd4Q

See all the changes:
*** In the Zeplin the texts are final, (on the screenshots they are not updated with last texts changes)

1. On all activities (except the card's activities) - the background step (1) is now replaced with the updated theme component. 
The idea is that the teacher always starts with the theme panel, and only if they want to, they open the background design flow. Its not the next step in the flow after the theme selection anymore as this was confusing. I show the design on the cover, but this will be consistent in all the activities (except the cards games).
<img width="689" alt="Screen Shot 2022-01-11 at 12 33 02" src="https://user-images.githubusercontent.com/88834002/148926866-cd4406d6-fb93-44c2-a510-7dcc54ddce75.png">

2. Take out the yellow mark for JIG theme. Keep only the selection for the local activity theme. Take out the popup to set as JIG theme. We make it back to simplicity (sorry...). What the teacher selected in this activity will be the default selection in future activities. If on the next activity the teacher changes the theme - change is only for that activity. On the JIG settings, if the teacher goes there and selects a theme for the JIG, this is the default theme she sees on each new activity. She can change locally. If she changes later in the JIG settings, it will change for future activities. not changing the former ones. If the teacher wants to change former activities she has to make it on each activity. @corinnewo What do you think about this section??
1920: https://zpl.io/bW5Xxmj
1280: https://zpl.io/VxjrZQJ
<img width="405" alt="Screen Shot 2022-01-11 at 12 35 50" src="https://user-images.githubusercontent.com/88834002/148927141-6fdcebce-4bc0-4c6d-8d78-d8aec9329a52.png">

3. Add a hyperlink icon "Design from scratch" (hover is a darker blue icon and text)
<img width="468" alt="Screen Shot 2022-01-11 at 12 40 17" src="https://user-images.githubusercontent.com/88834002/148927873-dcf41854-ef46-42ce-b465-562934de7cb8.png">

4. On click on this button a popup appears with 2 tabs: background and overlays.
1920: https://zpl.io/V0ApBjm
1280: https://zpl.io/2GM10wj
<img width="393" alt="Screen Shot 2022-01-11 at 12 44 17" src="https://user-images.githubusercontent.com/88834002/148928411-2b6494db-ac11-4bb4-bdb2-bf0895eaae6a.png">

5. Fill color is not a tab, the same reason, it was confusing as a flow. So it is a hyperlink button option on the background tab. 
<img width="137" alt="Screen Shot 2022-01-11 at 12 46 04" src="https://user-images.githubusercontent.com/88834002/148928680-b80a421c-cc8a-4be0-b71f-9b186584f036.png">

6. On click on the "Select fill color" button, a colors popup appears. 
I made the popup elements smaller so the same size of the popup is used for big and small screen sizes. Pls make sure to reduce all sizes on this component. I also created some rules of where to place the popup, maximum height, margin from top and bottom of the page for 1920 and 1280 screen sizes. Pls let me know if all the rules are clear, we can meet to discuss this. The same behavior is used for this colors popup on the text component. 
1920: https://zpl.io/brRPZXD, https://zpl.io/2ZdXN7l
1280: https://zpl.io/255xB8J, https://zpl.io/bJB1R4J, https://zpl.io/aXpXv8x
<img width="804" alt="Screen Shot 2022-01-11 at 12 56 31" src="https://user-images.githubusercontent.com/88834002/148931020-700e7a0f-8591-4a96-a925-ce2973a6eb0f.png">
<img width="793" alt="Screen Shot 2022-01-11 at 12 56 47" src="https://user-images.githubusercontent.com/88834002/148931035-7cba6852-516e-4049-8561-ef0c65a19251.png">
<img width="718" alt="Screen Shot 2022-01-11 at 12 57 39" src="https://user-images.githubusercontent.com/88834002/148931091-e8c40829-c678-4810-aed2-6b8f789c1690.png">
<img width="685" alt="Screen Shot 2022-01-11 at 12 58 04" src="https://user-images.githubusercontent.com/88834002/148931111-d6a06063-7b43-400b-95c2-821085ef32c7.png">

7. On click on the Add color button, a picker popup appears on top of the colors popup.
I made the picker popup much smaller. Pls add the "OK" button to this picker popup. See instructions for placing the picker popup.
Same size for all screens sizes: https://zpl.io/V1gDBBJ
@MendyBerger Can we add an icon that picks a color from an image?
<img width="673" alt="Screen Shot 2022-01-11 at 14 12 15" src="https://user-images.githubusercontent.com/88834002/148940718-c4026826-3313-4de0-8cbe-fbb1816a0c18.png">

**Comment by corinnewo** [comment]
@GaliShapira Is this with Chaykee's texts? Because I see you have Design from scratch, which implies you are designing a theme from scratch. @ChaykeeMor had reworded so it did not imply that you were designing the theme from scratch. We must have final texts in place as this is very time sensitive, and I don't want to have to go in and correct again!

Also, when you close the color picker, it goes back to the **Background** image picker. Should we not have some warning that if you have selected a color, this will be overwritten by any image selection. It's either image or fill color.

Otherwise, I think it works better than what we had before! Thanks!

**Comment by GaliShapira** [comment]
@ChaykeeMor Can you send me the text comments on the Zeplin? I will fix it tomorrow.
@corinnewo I don't think we need a warning as it is not a flow, its a button that you choose whether you use it or not, perhaps the text can be clear that its a background fill color or something.

**Comment by corinnewo** [comment]
@MendyBerger This is the tab that I told you about - combining the THEME and BACKGROUND stages in all the wizards. I think that before you start, we need to go through it and explain what needs to be done. This is really important to do ASAP for the MVP.

**Comment by corinnewo** [comment]
@MendyBerger i am adding to this ticket that we agreed to hide the JIG setting for themes  in the JIG Settings panel. You will only be able to set a theme by choosing it within the modules.
