### ISSUE TITLE
Missing QUESTION screens in JIGZI conversion

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2239]
Original Ji Tap game: https://jitap.net/activities/gcow/play/: 19 and 21
See JIGZI conversion, with these 2 screens missing: 

https://jigzi.org/jig/play/6f1812a2-69d5-11ec-8233-dfdac1df05d5?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

**Comment by dakom** [comment]
More info:

This is game id `15214` and game hash `gcow`

Module debug link: https://sandbox.jigzi.org/module/legacy/play/debug/debug?game_id=15214&slide_index=18

Ji Tap player link: https://jitap.net/media/webplayer/webplayer.html?structureJson=https://jitap.net/store/api/album/15214/structure&v=3.4.5&userId=

Game JSON: https://legacy.jicloud.org/games/15214/json/game.json

Module JSON: https://legacy.jicloud.org/games/15214/json/slides/photo21.json

Note that there are no `layers` in the game JSON.

I believe the fix will be to _always_ show the filePathImage as the bottom layer, and in the case of puzzle it paints on top of this layer

**Comment by corinnewo** [comment]
Spoke to Sammy - Slide 19 is a duplicate slide of slide 18, and slide 21 is a duplicate slide of slide 20. (They should contain the same graphics and images as the slide before them.)

**Comment by dakom** [comment]
Structurally that isn't what happens though. I don't know how tiny tap implements it, but I think the above solution will work, ultimately

**Comment by dakom** [comment]
What I mean by structurally is the JSON data of the slide definitely does not contain the actual design data of the slide before it.

**Comment by dakom** [comment]
should be fixed in latest sandbox build, feel free to re-open if not
