### ISSUE TITLE
Add rules to jig search and browse

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#2241]
```rust
JigBrowseQuery {
    privacy_level: Option<Vec<PrivacyLevel>>, // none is like Vec<PrivacyLevel::Public>
    
    blocked: Option<bool>, // none is like false
}
```
If the user isn't logged in, or if the users is logged in and they're querying outside of their own jigs, i.e. the don't have `author_id` set to `UserOrMe::Me`:
&ensp; Both of these fields behave like None

If the user is querying only in their own jigs, i.e. they do have `author_id` set to `UserOrMe::Me`, or if the user has the admin scope:
&ensp; The can set both these fields

Blocked by #2243

**Comment by MendyBerger** [comment]
Same rules for viewing drafts

**Comment by johnnynotsolucky** [comment]
@MendyBerger should the /browse endpoint be available for non-logged in users? Browse doesn't use algolia for finding JIGs/Resources, only /search does.
