### ISSUE TITLE
Player - buttons were within player area, now again on extreme right of screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2250]
In  Jigzi player, the buttons should be within the player area, on the background area.
In legacy player, the buttons should be just to the right of the background, not covering any content.

THis was fixed, and it seems to have reverted to the extreme right of the screen again.

![image](https://user-images.githubusercontent.com/16290361/149158526-21e0fce5-c4df-4bc8-a029-840982938221.png)

**Comment by MendyBerger** [comment]
Resolved
