### ISSUE TITLE
Add overlays component

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2251]
2 comments:
1. @ChaykeeMor Shouldn't we change the "search Jigzi" to something else referring this specific search? i.e. no. of elements
This is the text I used in the design as a search hint:
<img width="340" alt="Screen Shot 2022-01-12 at 16 52 58" src="https://user-images.githubusercontent.com/88834002/149163967-5a0021b6-c7b9-408a-92b5-9a3827943479.png">

And this is the production:
<img width="405" alt="Screen Shot 2022-01-12 at 16 37 07" src="https://user-images.githubusercontent.com/88834002/149160976-5986b7a6-a524-4174-a5b9-ca76eaca1c66.png">

2. Why do we see the recent images here? Either we see recent overlays used or no recent at all.

**Comment by ChaykeeMor** [comment]
I agree--delete my recent images

Texts:
Loation | Text on Jigzi: | Change to:
-- | -- | --
Search field | Search Jigzi | Try searching a shape or number 
Instruction | Search a shape or number | Place overlay on top of background

**Comment by corinnewo** [comment]
Agree - no recent images and use the text in the previous comment. Once final design, I will assign to Mendy to do.

**Comment by GaliShapira** [comment]
Thank you both, I changed the design. 
@corinnewo I see that the trash icon to delete the overlay was not implemented. 
On the background page I took it out because I have no room for it anymore now that we added the fill color. 
I suggest that after the MVP we will go back to the original design of clicking on the background to open an action menu.
https://zpl.io/ag7BYvD
<img width="401" alt="Screen Shot 2022-01-13 at 10 45 50" src="https://user-images.githubusercontent.com/88834002/149296701-cbf686c0-b4f7-433d-9f08-eadd94514bb3.png">

**Comment by corinnewo** [comment]
@GaliShapira Thanks - I will try and get the trash can to be implemented while they are doing this tab reorganisation. It is really important!

**Comment by corinnewo** [comment]
@GaliShapira I think we should wait for the whole tab overhaul before I assign this to a programmer.

**Comment by GaliShapira** [comment]
So to summerise:
Changes for Dev:
1. Change instruction + helper text inside the search field.
2. Remove "My recent"
3. Add trash icon that delete the overlay

**Comment by corinnewo** [comment]
@MendyBerger @GaliShapira We also discussed that if possible to treat the overlay as an image and not a background, it would be better all round. Would then be able to delete it, move it and resize it. Mendy will look into whether this is possible, in light of the trash can being problematic too.

**Comment by corinnewo** [comment]
@MendyBerger We had said above that on the overlays, we need to hide the RECENT IMAGES option. Please hide the row with recent images, as these are not relevant for overlays. Thanks!

**Comment by MendyBerger** [comment]
Resolved in 79782d155981b083b1d9803ee3ace353b068cb48
