### ISSUE TITLE
Improve cards in the search results

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2258]
This is a stop-gap measure for the MVP, taking into account the most important results of the usability testing:

On the JIG cards:

### FRONT:

- [ ] The JIG name is limited to one line. If its longer show it as one line ending with 3 dots (...) - MUST NOT PUSH THE AUTHOR NAME OFF THE CARD, SO IF YOU CAN FIT IN 2 LINES WITHOUT PUSHING THE AUTHOR DOWN, THEN IT WILL BE OPTIMAL

- [ ] use the shortcuts for the ages: All Ages, Pre-K, K, Elem, Mid, HS (NOTE: These shortcuts are for the cards only, and not for the age search on home page)

![image](https://user-images.githubusercontent.com/16290361/149351079-3b1418f1-441b-4f38-83c4-1adf9a05814a.png)

- [ ] For multi-select show the range from to: for example K-Mid or Elem-HS.

### BACK OF CARD: 
For MVP - afterwards, we need to implement all Gali's changes on https://zpl.io/2jOl18r 

- [ ] Description is not collapsed - must show full description, with scroll, if necessary
- [ ] If no additional resources, hide that section. IF there are additional resources, don't collapse, just list them
- [ ] Hide the 'See more JIGs by this author>' until it is developed, this should not be there.
- [ ] If possible, add in the Share button - opens up the share dialog - to get code, url or embed code.
![image](https://user-images.githubusercontent.com/16290361/149352534-16d7e58f-4351-4f2f-b702-f0bc5e2c0225.png)
![image](https://user-images.githubusercontent.com/16290361/149352818-bdb73c1f-1f96-4cf4-9890-b64568e14812.png)

This is a stopgap measure for MVP - instead of https://github.com/ji-devs/ji-cloud/issues/2033

**Comment by MendyBerger** [comment]
>  For multi-select show the range from to: for example K-Mid or Elem-HS.

Don't understand, mind elaborating?

**Comment by corinnewo** [comment]
@MendyBerger We had spoken about displaying a range of ages. If they chose from K to Elementary, then it would show K-Elem (instead of the K+2). Does that help?

**Comment by MendyBerger** [comment]
Yes, thanks for clarifying
