### ISSUE TITLE
Memory game - replace 2 illustrations

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2259]
We made the illustration nicer + we made them smaller so they fit nicely on all screen sizes.
Updated illustrations: 
[illustrations.zip](https://github.com/ji-devs/ji-cloud/files/7863841/illustrations.zip)
Zeplin:
https://zpl.io/VYDnZym
https://zpl.io/V0AjWlx
https://zpl.io/a3GDyZN
https://zpl.io/beme5dN

1. Change illustration of "No preview yet" (while working on the list)
2. Can you add the blue bubble under the words (as it is now it is not seen when the background is dark).
New:
<img width="215" alt="Screen Shot 2022-01-13 at 16 18 20" src="https://user-images.githubusercontent.com/88834002/149354184-69fe4f4b-0c82-4d2b-84e6-c39c0180d7af.png">
Old:
<img width="1093" alt="Screen Shot 2022-01-13 at 16 54 10" src="https://user-images.githubusercontent.com/88834002/149353561-43f16ce3-a20c-4dff-9c25-c813de3ca150.png">

3. Change illustration of "Edit your words on the cards" (after confirming list of words)
New:
<img width="277" alt="Screen Shot 2022-01-13 at 16 18 08" src="https://user-images.githubusercontent.com/88834002/149354194-bd9857e3-6bf3-478b-9d89-8a691b22fded.png">
Old:
<img width="902" alt="Screen Shot 2022-01-13 at 16 53 52" src="https://user-images.githubusercontent.com/88834002/149354056-09bbb722-deb8-4a24-9968-589098b04d87.png">

**Comment by johnnynotsolucky** [comment]
These changes were made as part of #2303 because the task required the "no preview yet" updates.
