### ISSUE TITLE
Publish dialog - Additional resources  TYPE- add in options to the pulldown

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2261]
- [ ] Please add in 'Educator Guide' and 'Other' to the options for types
- [ ] If they are going to be ordered alphabetically, please do it properly:

Coloring
Craft
Curriculum
eBook
Educator Guide
Flashcards
Lesson Plan
Other
Podcast
Video
Website Link
Worksheet

![image](https://user-images.githubusercontent.com/16290361/149363543-aa70e9c0-bb54-4716-8ff1-b20c9300633b.png)

**Comment by MendyBerger** [comment]
Can I put other at the end? I think that it makes more sense there

**Comment by MendyBerger** [comment]
Put other at the end, reopen if you disagree

**Comment by corinnewo** [comment]
I agree! Other is usually at the end as an extra option. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
