### ISSUE TITLE
Add Algolia logo to Jigzi

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2265]
@GaliShapira Algolia has given us a free account for being non-profit and for being open source, on condition that we display their logo on the search results page, with a link to their site. Where would you suggest to put it? I thought it should be in the footer, so that it covers all searches throughout the site, eg images within the create, etc. Please can you suggest where to place in the footer?

Logo to link in new tab to https://algolia.com
Logos to use: 
[search-by-algolia.zip](https://github.com/ji-devs/ji-cloud/files/7868713/search-by-algolia.zip)

As soon as you have given the design, I will assign to Matthew, as he worked on the footer previously.

**Comment by MendyBerger** [comment]
Resolved in 67e5decdf
