### ISSUE TITLE
End of JIG screen: Teacher page: Add a share button to the actions.

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#2272]
End of JIG screen: Teacher page: Add a share button to the actions. Add the X icon, bigger than the regular version if you can. Add the JIG icon. All are active above the darkening layer.

<img width="543" alt="Screen Shot 2022-01-10 at 12 26 50" src="https://user-images.githubusercontent.com/88834002/148751081-ba99cb90-747e-4fd4-8764-a6bc8fdd5478.png">

**Comment by corinnewo** [comment]
THis should go together with #2271

**Comment by MendyBerger** [comment]
Resolved in 4aaba305617d0374b7f65fa27b1f9eb763c46baa
