### ISSUE TITLE
Search bar: Ages and language lists on Jigzi - Items can't be on 2 lines

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2282]
Rename the 'Elementary school' option to simply 'Elementary', so that the option in the pull-down is only on 1 line. Alternatively, make the pulldown width wider, so that it is not on 2 lines.

Also, 'All languages' should only be on one line. Make the pull-down wider so that it fits on 1 line.

![image](https://user-images.githubusercontent.com/16290361/149790252-a84f0a62-212c-43c6-85b6-ecc4e6d70efe.png)

**Comment by johnnynotsolucky** [comment]
Updated to "Elementary" in release DB. 

@corinnewo it looks like "All languages" is rendering correctly so I didn't do any adjustments for that.
