### ISSUE TITLE
Styling for text for anchor links for search results

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2283]
@GaliShapira recommend to Tyrone the styling to use for the links in the search results text 

![image](https://user-images.githubusercontent.com/16290361/149791610-419e5ee2-3ec4-40b4-9f01-d1345211cb58.png)

**Comment by GaliShapira** [comment]
Hi, 
Pls see my suggestion:
https://zpl.io/VDX9Jwr
<img width="960" alt="Screen Shot 2022-01-18 at 12 34 25" src="https://user-images.githubusercontent.com/88834002/149921005-84fc8cb0-c3e9-4231-9b84-29631ec74270.png">
