### ISSUE TITLE
Use cases - the thumbnails are too big, rename, and order them

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2284]
On my screen, the use cases' thumbnails are much too big. 
They need to be proportional to what we see on Zeplin on all screen sizes.
I show only 3 activities examples, but its in all use cases.

**Zeplin:**
https://zpl.io/2544ol0
https://zpl.io/2G5Px8J

**Production:**
<img width="1189" alt="Screen Shot 2022-01-17 at 17 05 52" src="https://user-images.githubusercontent.com/88834002/149797592-1a123c26-3ff6-4e31-a345-4ec6f2d3b58a.png">
<img width="1195" alt="Screen Shot 2022-01-17 at 17 26 56" src="https://user-images.githubusercontent.com/88834002/149797575-cfda6a66-3e01-4330-87ef-32711956ef11.png">
<img width="1282" alt="Screen Shot 2022-01-17 at 17 27 24" src="https://user-images.githubusercontent.com/88834002/149797541-76ccc2d1-ca28-48fe-9ae0-ad9a38fe4441.png">

**Comment by corinnewo** [comment]
@mastapegs Please can you go through all the use cases and size them properly? At the same time, we should rename theme.

Also: #2022 #1907 #1566 #1057

**Comment by corinnewo** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Module | Location | Item Kind | Text-English | Chaykee's Version
-- | -- | -- | -- | --
Drag & Drop | Activity Use Cases | Use case item | Set a table | Set a Table
Drag & Drop | Activity Use Cases | Use case item | Sort items | Sorting
Drag & Drop | Activity Use Cases | Use case item | Build words | Build a Word
Drag & Drop | Activity Use Cases | Use case item | ADD | Build a Sentence
Drag & Drop | Activity Use Cases | Use case item | Match items | Matching
Drag & Drop | Activity Use Cases | Use case item | Dress-up | Dress Up
Drag & Drop | Activity Use Cases | Use case item | ADD | Build a Scene
Listen & Learn | Activity Use Cases | Use case item | Tap words & hear | Words
Listen & Learn | Activity Use Cases | Use case item | Tap images & hear | Images
Listen & Learn | Activity Use Cases | Use case item | Tap & talk | Talking Pictures
Listen & Learn | Activity Use Cases | Use case item | Tap & read | Read Along
Listen & Learn | Activity Use Cases | Use case item | Interactive drawing | DELETE
Listen & Learn | Activity Use Cases | Use case item | Interactive scene | Scene
Listen & Learn | Activity Use Cases | Use case item | Interactive photo album | Photo Album
Listen & Learn | Activity Use Cases | Use case item | ADD | Comics
Listen & Learn | Activity Use Cases | Use case item | ADD | Timeline
Listen & Learn | Activity Use Cases | Use case item | ADD | Family Tree
Matching Game | Activity Use Cases | Use case item | Lettering | .
Matching Game | Activity Use Cases | Use case item | What begins with… | Begins With…
Matching Game | Activity Use Cases | Use case item | Words & Images | .
Matching Game | Activity Use Cases | Use case item | Riddles | .
Matching Game | Activity Use Cases | Use case item | Opposites | .
Matching Game | Activity Use Cases | Use case item | Synonyms | .
Matching Game | Activity Use Cases | Use case item | Translate | Translation
Memory Game | Activity Use Cases | Use case item | Duplicate | .
Memory Game | Activity Use Cases | Use case item | Words & Images | .
Memory Game | Activity Use Cases | Use case item | What begins with… | Begins With…
Memory Game | Activity Use Cases | Use case item | Lettering | .
Memory Game | Activity Use Cases | Use case item | Riddles | .
Memory Game | Activity Use Cases | Use case item | Opposites | .
Memory Game | Activity Use Cases | Use case item | Synonyms | .
Memory Game | Activity Use Cases | Use case item | Translate | Translation
Quiz Game | Activity Use Cases | Use case item | Lettering | .
Quiz Game | Activity Use Cases | Use case item | What begins with… | Begins With…
Quiz Game | Activity Use Cases | Use case item | Words & images | Words & Images
Quiz Game | Activity Use Cases | Use case item | Riddles | .
Quiz Game | Activity Use Cases | Use case item | Opposites | .
Quiz Game | Activity Use Cases | Use case item | Synonyms | .
Quiz Game | Activity Use Cases | Use case item | Translate | Translation
Talking Poster | Activity Use Cases | Use case item | Printables | .
Talking Poster | Activity Use Cases | Use case item | Talking pictures | Talking Picture
Talking Poster | Activity Use Cases | Use case item | Comics | Teach a Word
Talking Poster | Activity Use Cases | Use case item | Timeline | Storytime
Talking Poster | Activity Use Cases | Use case item | Family tree | Map
Talking Poster | Activity Use Cases | Use case item | Poster | .
Tap the answer | Activity Use Cases | Use case item | Multiple choice | Multiple Choice
Tap the answer | Activity Use Cases | Use case item | I spy | iSpy
Tap the answer | Activity Use Cases | Use case item | Many questions on 1 image | Multiple Questions
Tap the answer | Activity Use Cases | Use case item | Tap a few answers | Multiple Answers
Tap the answer | Activity Use Cases | Use case item | Tap answers in order | Answer in Order
Tap the answer | Activity Use Cases | Use case item | Questions on an image | ??
Video | Activity Use Cases | Use case item | Introduction | Introduce Your Topic
Video | Activity Use Cases | Use case item | Story | Tell a Story
Video | Activity Use Cases | Use case item | Song | Play a Song
Video | Activity Use Cases | Use case item | How to | How To


</body>
</html>
