### ISSUE TITLE
Create - button options after finishing a module

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2286]
What do you want to do next (after finishing a module)
Continue--  adds a new activity 
Could we add: Share, Publish, My JIGs

<img width="1236" alt="Screen Shot 2022-01-18 at 09 21 25" src="https://user-images.githubusercontent.com/94056434/149889578-064f2fe3-cb32-4959-8387-1346d70b769f.png">

**Comment by corinnewo** [comment]
@ChaykeeMor We can't add SHARE here, as this is only one activity and not the JIG. But I had once suggested to add 'PUBLISH' to this list, as it is something that a user probably would want to do after completing an activity. The Continue is not clear, and it is the only choice.
Suggest: Add another activity | Publish 
If we add **My Jigs** here, it will take you out of this JIG without publishing, and I think it might be confusing....

**Comment by corinnewo** [comment]
@ChaykeeMor The more I work with building JIGs, the more I am convinced that the single CONTINUE after building a module is not enough. Should have 2 buttons - "Continue building JIG" or "Publish". At least there would be a choice of what you want to do! What do you think?

**Comment by ChaykeeMor** [comment]
Add new activity [on 2 lines]
Publish JIG

**Comment by GaliShapira** [comment]
Pls see the section with the new icon and the texts:
<img width="552" alt="Screen Shot 2022-03-07 at 11 46 24" src="https://user-images.githubusercontent.com/88834002/157007437-65f31277-1a9c-46ef-82e7-bea6a92e3909.png">

The publish icon (default and hover)
![icn-publish-jig-hover](https://user-images.githubusercontent.com/88834002/157007478-dc3bda19-f0e6-4f92-a99d-e9cd4d8fe22c.png)
![icn-publish-jig](https://user-images.githubusercontent.com/88834002/157007479-c985b6ca-4a58-4235-b345-bacdec07a234.png)

**Comment by corinnewo** [comment]
This is great! We still not doing the print, as far as I understand, but this will be a huge addition that you can publish at the end of a module.

**Comment by johnnynotsolucky** [comment]
Similar to #2385 with regards to design of the whole screen.

**Comment by corinnewo** [comment]
Hi @johnnynotsolucky - Just created flashcards, and this is what I see in the last screen:
![image](https://user-images.githubusercontent.com/16290361/158309551-574d1766-70bf-406b-810c-24a279889b65.png)

Gali replied yesterday that the original design was to have the illustration with the confirmation that the module has been added to the JIG, and then that would get smaller, and the 'What do you want to do next' area would appear on most of the screen.

**Comment by johnnynotsolucky** [comment]
Woah, @corinnewo I'll fix this. That's completely different to what I had just now.

RE the size of screen/illustration, I'll update that as part of https://github.com/ji-devs/ji-cloud/issues/2385#issuecomment-1066525697
