### ISSUE TITLE
Ji Tap player - on smaller screen now has scroll bars horizontally and vertically, and also now has a PLAY icon before every module within

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2289]
I was playing a Ji Tap Legacy game in Jigzi on my laptop, and suddenly there are scroll bars - that has never been there before! We can't have scrolling - must resize to fit!

Also, there is now a PLAY icon at the start of every module. This is a revert to something that was solved months ago.

https://jigzi.org/home/search?q=bet+kaf+mish+mash&page=0

![image](https://user-images.githubusercontent.com/16290361/149920810-c71cf675-844d-42c2-ac1f-967bffaa8dd2.png)

**Comment by MendyBerger** [comment]
Play icon now only on first module

**Comment by corinnewo** [comment]
I am not seeing the play button on each module anymore, but it is still not showing up on the first module, which is fine for now!
I am no longer seeing these horizontal and vertical scrollbars on my smaller laptop. I will close this now.
