### ISSUE TITLE
A link is not working in one of the Ji Tap games

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2290]
JIgzi: https://jigzi.org/jig/play/943c2c66-69d6-11ec-8549-c33288989069?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

JiTap: https://jitap.net/activities/g23m/play/

Home icon (eg on page 8), does not jump at all. Works in Ji Tap, not in Jigzi.

**Comment by dakom** [comment]
I am unable to view to jitap link, guess it's pro only

Didn't see a home icon on page 8, but I do see one on page 4, and looking at the data the only jump to page is on the day image which works correctly...

**Comment by corinnewo** [comment]
In Ji Tap: (page 8)
![image](https://user-images.githubusercontent.com/16290361/151114257-d75cd23d-b83b-446a-a1bd-3534d91b9bc2.png)

In JIgzi (page 8) - you can see that I clicked on the home icon, but there was no jump....
![image](https://user-images.githubusercontent.com/16290361/151114406-1541f6c4-cbb7-4620-997e-b7cade0ae78e.png)
