### ISSUE TITLE
Ji Tap - Jigzi player - Tooltips on soundboard remain on screen hiding important information - should disappear after sound file played

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2291]
Tooltips remain on screen instead of disappearing, and so cover important information. IN Ji Tap, the tooltips disappear when the sound file has finished playing.

JIgzi: Module 3 of https://jigzi.org/jig/play/37a4515e-69bd-11ec-98b1-f7ea789fceb7?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

Ji Tap: https://jitap.net/activities/g1rt/play/

![image](https://user-images.githubusercontent.com/16290361/149927412-3ebf751e-b9aa-4375-ba80-e644d9516d12.png)

**Comment by corinnewo** [comment]
@dakom Is this something that you can fix? It is really annoying that they remain on screen and also it covers important info that needs to be seen.

**Comment by dakom** [comment]
sure, will do.. just not sure exactly when I can get to it

**Comment by corinnewo** [comment]
@dakom THanks! If you can look at it before the end of Jan, I would appreciate it, as it does affect a lot of the Ji Tap games. THanks!

**Comment by dakom** [comment]
Fixed (will show on next merge to release)

**Comment by corinnewo** [comment]
Thanks!
