### ISSUE TITLE
Create Your Very Own Game Of The First Jewish Week - still applicable for JIGZI?

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2294]
The Jig below is an instructional game for making a DIY in the JITAP APP - should this remain in JIGZI?

https://jigzi.org/admin/curation/846f3008-69c2-11ec-bc3f-c73f7266515b

**Comment by corinnewo** [comment]
@chayaml You are right - this should probably not be part of Jigzi. Perhaps we can recreate it within Jigzi.
I have made it '**Blocked**' so it should not turn up in search results.
