### ISSUE TITLE
Quiz Game - name change

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2301]
Please change all instances of 'Quiz Game' to 'Multiple Choice'.

<img width="302" alt="Screen Shot 2022-01-19 at 11 52 36" src="https://user-images.githubusercontent.com/94056434/150108101-a9b30af6-43c3-46a5-bb32-af41b5b35e4f.png">
<img width="761" alt="Screen Shot 2022-01-19 at 11 52 28" src="https://user-images.githubusercontent.com/94056434/150108131-7438dd63-3701-4f19-b410-1e0c7e200f93.png">

**Comment by corinnewo** [comment]
@ChaykeeMor Doesn't sound right - **Create a Multiple Choice**
Does it not need something else? Like **Create a Multiple Choice Activity** or **Game**

**Comment by ChaykeeMor** [comment]
Activity

**Comment by MendyBerger** [comment]
So to be super clear, the task is to change all instances of the words "Quiz Game" to "Multiple Choice Activity", right?

**Comment by corinnewo** [comment]
yes, please. Multiple Choice Activity

**Comment by ChaykeeMor** [comment]
NO. The Activity is called "Multiple Choice" in the instance of the heading within the JIG creator, the title is: "Create a Multiple Choice Activity"

**Comment by corinnewo** [comment]
@MendyBerger Please see Chaykee's comment - I hope that you have not yet changed them....
