### ISSUE TITLE
Wonder Women - Sarah Aaronsohn: The buttons do not perform any actions

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2312]
The green button should jump to the next slide with a quiz; the red button should skip the quiz and jump to the next slide. 

![Screen Shot 2022-01-20 at 12 29 42 PM](https://user-images.githubusercontent.com/78186896/150390929-7472341b-1f2a-4468-b729-8fac812da88d.png)

https://jigzi.org/admin/curation/d23288a8-69bd-11ec-a962-c75ccfb7ac61

**Comment by corinnewo** [comment]
@dakom module 06: another case of the buttons not having the jump to link, but in Ji Tap they work.
