### ISSUE TITLE
Parashat Vayigash - Jigzi Player: letters typed into text boxes in activity are wrong size

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2331]
There is an activity on page 9 where users enter letters into a text box to spell "Goshen". The letters in Jigzi Player are either extremely large or extremely small.

**JiTap:**

![Screen Shot 2022-01-26 at 12 24 16 AM](https://user-images.githubusercontent.com/78186896/151063132-a1390365-61ad-4cea-9b60-1e867ac3924f.png)

https://jitap.net/activities/g2ob/play/

**Jigzi:**

![Screen Shot 2022-01-26 at 12 14 00 AM](https://user-images.githubusercontent.com/78186896/151063227-63742e2a-6caa-4a4f-8e2e-2a539390ed71.png)

https://jigzi.org/admin/curation/f44ea66e-69be-11ec-ab82-e30ab578cdd4

Edit: I am experiencing this issue in other games as well. When a user has to type words into a text box, letters appear very large, and as more are typed, the words gradually shrink

**Comment by corinnewo** [comment]
@dakom Please can we refine the size of the fonts when typing in. I have also noticed this in other games - first letter is huge.

**Comment by corinnewo** [comment]
played this game today, and look what I see:
![image](https://user-images.githubusercontent.com/16290361/154051947-d8c31436-67a2-439b-a663-f9d6cef20da9.png)

**Comment by corinnewo** [comment]
![image](https://user-images.githubusercontent.com/16290361/154052077-7e2473e9-d5cb-4768-b04f-827ca000600e.png)

**Comment by dakom** [comment]
@corinnewo - I cannot duplicate this. Tried in both Chrome and Firefox...

**Comment by corinnewo** [comment]
I have just tried on another computer, chrome. It seems fine. On Thursday, when I created the ticket, I was on my laptop in chrome. And it definitely was playing up- you saw the screen shot! I’ll check on a few more computers. Hopefully it is all fixed now!!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dakom** [comment]
This is definitely one of the elements I was most nervous about acting up, it even has a "fudge factor" baked in.. another alternative might be to set the size in advance based on the answer word. So it won't change dynamically as they type, but will look fine once they have entered all the text, and would be much more predictable

**Comment by corinnewo** [comment]
That sounds like a good solution. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dakom** [comment]
game id is 2233

**Comment by dakom** [comment]
I can’t reproduce this particular problem, so just going to leave it as-is… it’s not exactly in the player code itself anyway, it’s in a “custom element” side and ideally one which would be used elsehwere in jigzi -i.e. anywhere we’d want a dynamically sized input
