### ISSUE TITLE
 Parashat Vaera: Jigzi Player sensitive to Capitalization usage in user activity

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2334]
In the Page 8 activity, the user has to unscramble the words, and the box turns green when they have done so correctly. 

The Jigzi player seems to be sensitive to capitalization and lowercase letter usage. Although the answer is correct, pressing enter with the incorrect capitalization/lowercase letter results in a red text box with a tooltip. The letters can be entered in any form in Jitap, and the text box locks once the user has entered the correct words (unlike in Jigzi, where the user can always go back and edit the text.

**Jigzi:**

![Screen Shot 2022-01-26 at 1 21 04 AM](https://user-images.githubusercontent.com/78186896/151069527-5b68508e-1fcd-4e99-b7bf-4f2fa6e1697f.png)

https://jigzi.org/admin/curation/f2e4ed6e-69bf-11ec-bc3f-1bc0b59ed6cf

**JiTap:**
![Screen Shot 2022-01-26 at 12 55 09 AM](https://user-images.githubusercontent.com/78186896/151067536-aa53f9f7-aa6b-4b11-a53a-25d1afaa71d6.png)

https://jitap.net/activities/gd51/play/

**Comment by corinnewo** [comment]
@dakom Please change the text input to be case insensitive.
