### ISSUE TITLE
Update activity JSON schema so that Jiggling text is mapped better to tabs in the UI

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#2341]
Related to https://github.com/ji-devs/ji-cloud/pull/2337#issuecomment-1023867136

We need to be able to render tabs in any order in the JIG edit UI without requiring the content in the relevant JSON files to be updated as well. We also need to cater for different sets of tabs, for example:

- Text, Image, Audio
- Text, Audio
- (possibly in the future) Image, Audio

### Solution

- For each tab in each step in the JSON file, include a `kind` field which maps to the relevant tab kind in the app;
- The app should match the tab with the item in the tabs array from the JSON file.

**Comment by corinnewo** [comment]
Keep me updated if we need to change how we do the json texts!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
