### ISSUE TITLE
Parashat Bereshit: Video link needs to be updatd 

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2355]
Video is unavailable on page 6. Please update to a new link.

![Screen Shot 2022-02-01 at 2 00 15 AM](https://user-images.githubusercontent.com/78186896/151956074-849c81cb-1add-4d28-ac79-d7935eabba72.png)

**Jigzi Link:**
https://jigzi.org/admin/curation/55496b26-69c8-11ec-a00b-63499746d49a
**JiTap Link:**
https://jitap.net/activities/g51t/play/parshat-beraishit-s-creation

**Comment by corinnewo** [comment]
Waiting for Sammy to provide the updated link, then I can go in and update the JIG

**Comment by corinnewo** [comment]
Replace video with https://youtu.be/-8uymg_l0GI

**Comment by corinnewo** [comment]
@MendyBerger Please look into this. I can see that the YouTube link is updated on Google Cloud Platform for both public and authenticated URL. But when you play the JIG, the video link is still broken.

https://storage.googleapis.com/ji-cloud-legacy-eu-001/games/5311/json/slides/photo6.json

JI TAP: g51t
Game ID: 5311

**Comment by corinnewo** [comment]
Finally done!
