### ISSUE TITLE
Jigzi Player - Drag and Drop: Voiceover stops when dropping an item

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2360]
During a Jig activity, a voiceover is heard while dragging and dropping an item to the correct area. 
Even once the item has been dragged to the correct place, **Jitap** plays the voiceover until the voiceover is finished.
 **Jigzi** stops playing the voiceover after the item is dropped in the correct place, even if it is still in the middle of playing.

Would it be possible to ensure that the voiceover/sound continues to play even after it's been dropped?

**Comment by corinnewo** [comment]
@dakom Please let me know if this is a big change... otherwise, leave it

**Comment by dakom** [comment]
These interactions are very specific and can vary per-module... which module is this referring to?

**Comment by corinnewo** [comment]
It refers to puzzle pieces. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by dakom** [comment]
oh, if it's just puzzle, _probably_ not that difficult, but not sure on one foot

**Comment by corinnewo** [comment]
Eg screen 4 in https://jigzi.org/jig/play/43196ace-69c7-11ec-841b-7f5810146d59?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false (some puzzle pieces have a bracha on them)

**Comment by dakom** [comment]
game id: 3484
