### ISSUE TITLE
Add HUBSPOT tracking code to the website

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2361]
We’re starting to use HubSpot software to manage our marketing analytics, and I’m hoping you can help with some of the technical setup steps necessary to get us up and running.

Specifically, we’ll need to insert some tracking code into every page of our website, just before the </body> tag. The code for that is right here:

<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/2636713.js"></script>

**Comment by MendyBerger** [comment]
@mastapegs just put it next to the google analytics tags
