### ISSUE TITLE
Sandbox - My Jigs - searching not working 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2362]
I just created a JIG and published it called 'testing'. Could not see it in gallery, so searched for 'testing'. Nothing appears in results. When no search, there are other games with the word 'testing' in the name, but they were not found.

Searching for 'testing':
![image](https://user-images.githubusercontent.com/16290361/152159299-6ded4ba3-4b4d-4ac9-9182-7687fc2d503c.png)

No search - can see that other jigs with 'testing' are listed, but were not found. The jig that I just created and published is not there ....
![image](https://user-images.githubusercontent.com/16290361/152159538-53c1292d-2282-486b-b569-eb8c7ff59904.png)

**Comment by johnnynotsolucky** [comment]
@corinnewo no, I think this is a different issue.
