### ISSUE TITLE
"Listen and Learn" module - wizard 3 - missing instructions/illustration on left panel

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2363]
You get to stage 3 in the wizard, and you get a blank panel. Must have the instruction to trace. There is also an illustration that should be there, explaining what to do. @GaliShapira please add in the illustration.
Text should say: Trace an area for sound (@ChaykeeMor - this is what is in the excel, but it is not in your column, so what is the final text?)

![image](https://user-images.githubusercontent.com/16290361/152160516-17eddd6a-a596-4019-a17c-45bcade2c615.png)

**Comment by ChaykeeMor** [comment]
Text is "Trace and select to add audio or label." as mentioned in #2285

**Comment by corinnewo** [comment]
@ChaykeeMor I agree - would be great to solve #2285 and this missing text issue at the same time!

**Comment by GaliShapira** [comment]
See the illustration attached. 
![illustration-trace-area](https://user-images.githubusercontent.com/88834002/152213230-2876860f-cdee-4c0f-8cf3-4139d3ac3c69.svg)

Zeplin:
https://zpl.io/g8qv6eD
https://zpl.io/9qkZjew

The illustration is for all the trace areas stages, text may change between one module to another.
<img width="194" alt="Screen Shot 2022-02-02 at 20 13 26" src="https://user-images.githubusercontent.com/88834002/152213197-3e03bde9-96e0-491a-a471-23fcf4a233bd.png">

**Comment by johnnynotsolucky** [comment]
@corinnewo @GaliShapira I included the sidebar graphic on the Drag and Drop acitivity for Step 3: #2529
