### ISSUE TITLE
Add tab showing that this is a beta version and add popup and link

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2365]
Please add in the tab that says 'Beta' along the menu. Clicking the i will open the popup as designed by Gali. Please use Chaykee's edited texts:
**Tooltip currently:**
Title: You are using our beta version.
Body: We would love to hear your feedback, it will help us learn and improve.
Link: Share your thoughts

**Change to:**
Title: You are using the beta version
Body: Your feedback will help us improve our platform.
Link: Tell us what you think!

The link should open up the Hubspot form in a **new tab** with this link: https://share.hsforms.com/1pCg45ADPSlCFSiL0NzOYIQ1kii1

![image](https://user-images.githubusercontent.com/16290361/152179285-b4fb27c9-9129-4706-93c4-a49e34441d1d.png)

Link to Gali's design:
https://zpl.io/2yMpQvn

**Comment by corinnewo** [comment]
@johnnynotsolucky Mendy suggested not to make as a tab, like the ADMIN tab, as it gets in the way of content on other pages. If you can add it within the top menu bar, between the logo and home, it would be better. 
@GaliShapira please look at it and suggest how to do this. Perhaps have a vertical icon?

**Comment by GaliShapira** [comment]
Hi @johnnynotsolucky I checked it and there is no room really on the header, especially on the small screen sizes.
As far as I remember I chacked the other screens, on the creator I showed a different place for this label. I suggest to go on that way. 

Also I have updated the texts on the Zeplin.

**Comment by corinnewo** [comment]
Gali - the tab is not great as it covers content on other pages. We need to find a different position. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by GaliShapira** [comment]
But there is no content at this area on the other pages

**Comment by corinnewo** [comment]
On the admin page, this would cover content, which is annoying for the admin people (i know that it is a small section of users, but it interferes, nevertheless. It is better within the menu area, if possible.

**Comment by corinnewo** [comment]
@johnnynotsolucky Please can you prioritise this, as we can't start releasing as a beta without this indicator and link to the form for feedback. If a problem, please assign to someone else!
