### ISSUE TITLE
Jigzi Player: Parashat Vayishlach - game crashes in middle

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2366]
The game crashes on page 8 and lands on an error page

![Screen Shot 2022-02-02 at 9 43 20 PM](https://user-images.githubusercontent.com/78186896/152225560-1d5f46a2-0aa0-41de-881d-a2e4cec84959.png)

https://jigzi.org/admin/curation/fe92a39e-69bb-11ec-9193-b74bf705cc9b

**Comment by corinnewo** [comment]
@dakom Please can you look at why this is crashing? In JI Tap (https://jitap.net/activities/g204/play/) it completes the puzzle about the hip joint, then automatically goes to the next screen (p8) which is a Tap n Type activity. It does not crash. But it is crashing in Jigzi (https://jigzi.org/jig/play/fe92a39e-69bb-11ec-9193-b74bf705cc9b?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false). Thanks!

**Comment by corinnewo** [comment]
@dakom Did you have a look at this? Why is it crashing on module number 8?

**Comment by dakom** [comment]
I think I missed it because it didn't have the `legacy` label and was previously sorting on that since I was assigned to old issues.

Removed myself from old issues so I can track this more easily. Will take a look next session.

Thanks for the reminder

**Comment by dakom** [comment]
Again, corrupt data is to blame - but thankfully we can work around this on the player.

One of the shapes has an empty text hint. Not "no hint", but a hint with empty text, and so the player crashes when it tries to walk through the text one letter at a time.

I'll fix it so the player treats empty text as actually no hint
