### ISSUE TITLE
Cookie policy banner shows up in JIG module thumbnails

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#2374]
When thumbnails are generated for JIG modules, the cookie policy banner is captured as well.

![Screenshot from 2022-02-04 11-18-03](https://user-images.githubusercontent.com/4161106/152503601-b4a97fc6-b807-4f92-8249-907653b1c6f7.png)

**Comment by MendyBerger** [comment]
Resolved in 8679b50
