### ISSUE TITLE
Jigzi Player: tooltip should disappear when clicking another item

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2379]
When there are several items to click on for tooltips, the tooltip stays on the screen even while clicking on another item. Tooltips should disappear as soon as another button is clicked, just like in JiTap.

(Singalong Ma Nishtana)

**JiTap:**

![Screen Shot 2022-02-06 at 3 22 15 PM](https://user-images.githubusercontent.com/78186896/152683104-7076acea-00c5-4391-b0c6-926966176fea.png)

https://jitap.net/activities/ga5s/play/

**Jigzi:**

![Screen Shot 2022-02-06 at 3 22 45 PM](https://user-images.githubusercontent.com/78186896/152683147-e86d2b25-5229-4a7d-82f6-9ed2e492f2a8.png)

https://jigzi.org/admin/curation/1b57a55c-69c5-11ec-8181-9f2145e66e0d

**Comment by corinnewo** [comment]
I think David fixed this. I saw on sandbox before that it had been fixed. Must check that it has been merged with jigzi. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by chayaml** [comment]
I see that the tooltip vanishes as soon as the voiceover is complete. The tooltip remains on the screen if a user taps another button before the voiceover is completed... It should disappear when the user clicks in a different area.

**Comment by corinnewo** [comment]
@dakom Please can you implement this? Closing the tool tip when you click somewhere else on the screen. Or is this part of the player for Mendy?

**Comment by dakom** [comment]
I think it makes more sense to do this as part of legacy player, will update when I can carve out the time to do it

However - it's a bit tricky, since there may be a conflict between dismissing a tooltip vs. starting the next one.

Is it okay if instead of dismissing it on click anywhere, it just kills the current tooltip if a new one is opened?

**Comment by corinnewo** [comment]
@dakom I think so - the main thing is not to have the screen filled with tooltips.... so if you open another one, and the first one closes, I think that it will do the job!

**Comment by dakom** [comment]
fixed for soundboard... if it happens anywhere else please let me know
