### ISSUE TITLE
Card games- Unable to edit text.

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2383]
Since adding the functionality of the 'add audio' has made it so clicking on a card selects it for adding audio---I am unable to edit my text in the cards.

<img width="986" alt="Screen Shot 2022-02-09 at 10 39 01" src="https://user-images.githubusercontent.com/94056434/153157543-2943bfed-b0d8-451a-a09f-fdb1c3b0f547.png">

**Comment by ChaykeeMor** [comment]
Oh wow! I just discovered the 'edit text' in the kabob menu. How do we share with users that it's there?

**Comment by corinnewo** [comment]
@johnnynotsolucky Was there a reason that the ability to edit on the cards themselves was removed?

**Comment by ChaykeeMor** [comment]
Best functionality for the UX would be editing text enabled while in text tab or image tab. Select card for audio only while in audio tab.

**Comment by johnnynotsolucky** [comment]
@corinnewo for #2280, I worked off this https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/61e057e273a966b70eec1b96. With the new selection of cards and the context menu, I removed the ability to click a card to edit the text.

**Comment by corinnewo** [comment]
@johnnynotsolucky What is possible to do here? I agree with Chaykee's suggestion, but I also understand the conflict about selecting to add sound and selecting to edit text. Can we discuss a way to improve the UX here a little?

**Comment by corinnewo** [comment]
Edit is now possible. CLosing.
