### ISSUE TITLE
Use cases - Listen and learn - all images should be the same size and mouseover should not make them bigger

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2388]
In listen and learn - the first few images are too large. The last few are the correct size. Please make sure that all the use cases are the same smaller size, and that mouseover does not make them larger.

![image](https://user-images.githubusercontent.com/16290361/153186606-7a52dc15-c5a0-4547-b36c-b7f685bc1aed.png)

**Comment by mastapegs** [comment]
I've messaged Gali about sending me some updated pictures for the listen and learn use cases. I've sent her over an example of a good pair of formatted images (the timeline pair) along with an example of a pair that need revision (the read along pair)

**Comment by corinnewo** [comment]
@GaliShapira - Did you see this?

**Comment by GaliShapira** [comment]
@meravs הי מירבי האם תוכלי לבדוק ולהעלות לפה את היוזקייסים שהגודל שלהם לא נכון מתוקנים?
רק שלושת האחרונים נכונים. ב- listen and learn.
כל השאר הגודל לא נכון, תבדקי גם את מצבי ההובר.

**Comment by meravs** [comment]
Listen and learn - use cases
[Listen&Learn 29.3.zip](https://github.com/ji-devs/ji-cloud/files/8370370/Listen.Learn.29.3.zip)

**Comment by meravs** [comment]
Listen and learn - fridge magnet
[fridge magnet.zip](https://github.com/ji-devs/ji-cloud/files/8370928/fridge.magnet.zip)

**Comment by mastapegs** [comment]
The trick that seemed to force the CDN to update with the new Dropbox content was to DELETE the dropbox content, then re-adding it.

All Listen & Learn use case images are now correctly sized and are still sized correctly on hover.
