### ISSUE TITLE
image search isn't working

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#239]
Might need to debug together - but I'm getting a 500 both on sandbox and local

**Comment by izik1** [comment]
As mentioned in slack, I'm can't reproduce this on my machine.
The lack of logs is... Concerning

**Comment by dakom** [comment]
I do see an error in the logs :) locally, it's buried between the pings but it's there:

```
19:00:59 [ERROR] Internal Server Error: ""
19:00:59 [ERROR] ISE while responding to request: decode error: error decoding response body: invalid type: map, expected a string at line 1 column 3379

Caused by:
    0: error decoding response body: invalid type: map, expected a string at line 1 column 3379
    1: invalid type: map, expected a string at line 1 column 3379
```

**Comment by dakom** [comment]
Discussed with @izik1 - that catching this in automated tests is a bit of a problem currently, requires adding the ability to hit endpoints that depend on Algolia from the test suite. Adding that will open up the possibility for more comprehensive testing in general.

**Comment by dakom** [comment]
Probably fixed in https://github.com/ji-devs/ji-cloud/pull/251
