### ISSUE TITLE
Card games - implement combined theme/background/fill color tab as with other modules

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2390]
In the card games, we still have the 3 tabs for theme| Background| Fill color.
This should follow the same combination as with the other modules.

Currently:
![image](https://user-images.githubusercontent.com/16290361/153557621-ef16cdd0-03ae-42d1-82af-a1093e60a644.png)

**Comment by MendyBerger** [comment]
Related #2391

**Comment by corinnewo** [comment]
@MendyBerger Discussed this at ideation today as to why the card games were excluded from the change. Came to the conclusion that they should work exactly tyhe same way as the Design modules, except that  instead of 'Create from scratch' on the Theme tab, it will say 'Change background' (Change the text). Otherwise, exactly the same functionality.
@GaliShapira Please add in the link to the Zeplin.
