### ISSUE TITLE
Card games - choice of theme should become the global theme

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2391]
Currently, choosing a theme for the card game does not affect the theme going forward. It should be the current theme when you add a new module.

**Comment by MendyBerger** [comment]
Related #2390

**Comment by corinnewo** [comment]
@MendyBerger This is important - if you choose a theme for the cards, then create a new non-card module, like poster, that same theme from the cards should be applied.

**Comment by MendyBerger** [comment]
Not done yet?

**Comment by corinnewo** [comment]
Was not working this afternoon when I checked sandbox. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by MendyBerger** [comment]
Just tried it and looks good now (sandbox)

**Comment by corinnewo** [comment]
That’s great! Thanks. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by corinnewo** [comment]
@MendyBerger It is working when I add a new module (other than a cover) - the default is the theme that was set in the cards. But when I go to the **cover** to create the JIG cover, the theme there is not the global theme. It is the default BLANK.
- Tried it with dragging in a cover AFTER I created the memory game and had selected a theme. This theme is not selected in the cover. 
- Even if you drag in a cover module to a place within the JIG that is not the first module, the current theme is not selected.

**Comment by corinnewo** [comment]
Well done @MendyBerger!
