### ISSUE TITLE
Resource add during publish - add web link -  must add warning that you need to have the https:// - or else add it automatically

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2398]
At the moment, when you add in a URL to define a weblink for a resource, if you start with "www.", then the box turns red, but there is no written warning about what is happening. The button simply remains inactive. We cannot leave it like this.
Two solutions:
1. If the user starts typing "www", then add in a warning that you need to have the https// before it (@ChaykeeMor -please suggest text here) or
2. automatically add 'https://' to the beginning of the URL
![image](https://user-images.githubusercontent.com/16290361/153834189-57b61243-6ccb-448d-9fda-349218bbd803.png) 

Please advise which is the easier option to implement, @MendyBerger

**Comment by ChaykeeMor** [comment]
This should be automatic. It's 2022, and nowhere are you required to enter https:// in order to input a link.
