### ISSUE TITLE
Profile - both in registration and editing my profile - need explanation about the filters

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2400]
@ChaykeeMor We're going to need your help here!  For MVP, we need to add in explanation of the filter system. Chana suggested:
in MY PROFILE:
1. Change the heading from 'Teaching Settings' to 'Jigzi Filters'
2. Move the school to be under location area
3. Add in an explanation that if you leave these filters blank, then you will see all the images, JIGs and resources that are available in Jigzi. BUt if you define filters, then you will ONLY see images, resources and JIGs that match those criteria, and so you are likely to see a reduced set of results.

REGISTRATION:
Need to have a similar explanation about the filters.

![image](https://user-images.githubusercontent.com/16290361/153836562-690e760c-2cb9-412e-9cf6-5433c0dd8971.png)

**Comment by ChaykeeMor** [comment]
A note about our filters: Ji believes in making Jewish education accessible to ALL Jews, everywhere. For this reason, we would like to customize your experience so that it supports your Judaism (alt: Jewishness?) (alt: needs). If you would like to see ALL our images, resources and JIGs leave these blank. If you would like to see only what Jigzi tags as relevant to you, use these filters so we could fine-tune your search results.   

what do you think @corinnewo

**Comment by corinnewo** [comment]
@ChaykeeMor I think we are on the right track. Might be a little long. How about:

**A note about our filters:** Ji believes in making Jewish education accessible to ALL Jews, everywhere. We would like to customize your experience so that it supports your needs. 
- If you would like to see ALL our images, resources and JIGs leave these blank. 
- If you would like to see only what Jigzi tags as relevant to you, use these filters to fine-tune your search results.

... not much shorter! But laid out well on page, it might look ok.

**Comment by ChaykeeMor** [comment]
So you only took out 'for this reason'. Something isn't right....I took this text from our onboarding idea to ask questions that weight these filters. In this context, the first sentence doesn't really make sense in framing the second without saying your needs as a Jew somehow. Are we going to do the onboarding thing? If not, then let's simplify. 

A note about our filters: Ji believes in making Jewish education accessible to ALL Jews, of all ages and affiliations. If you would like to see only what Jigzi tags as relevant to you, use these filters so we could fine-tune your search results. If you would like to see ALL our images, resources and JIGs leave these blank.

**Comment by corinnewo** [comment]
I think this is good. Only change I would suggest is  change "so we could" to "to". It would read ...."use these filters to fine-tune your search results." (giving them the power to fine tune)

**Comment by ChaykeeMor** [comment]
TEXT @corinnewo 

A note about our filters: Ji believes in making Jewish education accessible to ALL Jews, of all ages and affiliations. If you would like to see _only_ what Jigzi tags as relevant to you, use these filters to fine-tune your search results. If you would like to see ALL our images, resources and JIGs leave these blank.

**Comment by corinnewo** [comment]
@ChaykeeMor Thanks - we'll use this final version of the text!

@mastapegs  To recap:
In MY PROFILE:
- Change the heading from 'Teaching Settings' to 'Jigzi Filters'
- Move the school to be under location area
- Add in an explanation under the filters heading:
A note about our filters: Ji believes in making Jewish education accessible to ALL Jews, of all ages and affiliations. If you would like to see only what Jigzi tags as relevant to you, use these filters to fine-tune your search results. If you would like to see ALL our images, resources and JIGs leave these blank.
- REGISTRATION:
Need to have a similar explanation about the filters.

This is high priority as people will be signing up for the BETA and not understanding the filters will result in their not seeing the content that they might need!
