### ISSUE TITLE
Ji Tap - puzzle - problem with layering

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2401]
Please take a look at https://jigzi.org/jig/play/e8c723da-69bd-11ec-bb37-6b3777f1d704?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false, screen 3. (Gematria for Beginners 1)

Ji Tap: https://jitap.net/activities/g51v/play/

There is a problem with the layering, which we have seen in other Ji Tap imports with the same sort of activity.
1. The puzzle pieces are placed over wrong placement areas.
2. When you place an item correctly, it falls into place, and is the topmost layer.
3. When you try and access the puzzle piece underneath it, it is impossible to grab, since it is 'behind' the correct layer.
4. Can't finish the activity

Is there any way to solve this problem with the layers? It is a very confusing interaction - and really hard to do, even on Ji Tap. But at least you can do it on Ji Tap. On JIgzi, it is impossible!

![image](https://user-images.githubusercontent.com/16290361/153872605-e30ae6be-eed2-48b6-b111-c0b8a2d8e0a8.png)

**Comment by corinnewo** [comment]
@chayaml - just so that you are tagged on here!

**Comment by dakom** [comment]
In other words the problem is that when a puzzle piece is dropped into place, it should disable the mouse interaction completely, thereby allowing whatever is underneath it to still register?

This is a bit harder in puzzle than other activities but shouldn't be a problem if that's the bug

**Comment by corinnewo** [comment]
Not sure.... if I drop a puzzle piece in place, it seems to go behind the piece that is waiting to be placed (in Ji Tap). Otherwise, how do I see the piece that can still be dragged?

**Comment by dakom** [comment]
Good point, interactive pieces should also always be a layer above the finished pieces.

However, I'm not sure if I can easily maintain the original layering once we shift things around - i.e. if the original cutouts were placed on top of eachother, it'll _probably_ turn out the same way, but on one foot I'm not sure if in every edge case that's always going to be true

For example if in the original the cutouts are on top of eachother like:

A,B,C

Then when playing the puzzle the user drops them in order

B,C,A

I am not sure that A will end up on top of B easily (haven't dug into the code yet)

Note though that this is also a very weird scenario, in real life you can't have puzzle pieces that are actually cutting out the same space at the same time and this should ideally be prevented at the creation level

**Comment by dakom** [comment]
@corinnewo I can't access the Ji Tap game (maybe it's locked behind "pro", which I don't have)? but anyway, I can see the problem in jigzi and I'll fix by just making the locked/correct pieces on the bottom layer

**Comment by corinnewo** [comment]
That sounds like it will fix it. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
