### ISSUE TITLE
Add Google Tag Manager codes to the web pages

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2405]
In addition to the Google tracking codes which have been inserted into the code, please add in the Google Tag Manager codes:

Copy the code below and paste it on to every page of your website.
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'[https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)](https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f));
})(window,document,'script','dataLayer','GTM-P4BFMJW');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P4BFMJW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by MendyBerger** [comment]
@mastapegs put next to hubspot and google code please

**Comment by MendyBerger** [comment]
@corinnewo was the `iframe` element wrapped with a `noscript` element?

**Comment by corinnewo** [comment]
Which iframe? Matthew would know if you are referring to home page iframe. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by MendyBerger** [comment]
I'm referring to the iframe tag in the tag manager script you pasted here

**Comment by corinnewo** [comment]
That came from tag manager. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by corinnewo** [comment]
@mastapegs Dini is reporting that the Tag Manager code is giving an error. Please check that this is installed correctly.

**Comment by mastapegs** [comment]
@corinnewo 

I had to adjust the script given in the issue description above when I created the PR for this because the given script above generates a syntax error

![image](https://user-images.githubusercontent.com/13839150/158161580-a075ecfb-bf54-48b2-b250-76e039b72fe9.png)

Could you re-copy and paste here the script from Google Tag Manager?
