### ISSUE TITLE
Image search in Hebrew - not finding all instances

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2406]
I search for 'dog' in english. Find https://jigzi.org/admin/image-meta/4a8df32c-3756-11ec-abb4-c3bddefb105e/false, which has image description "Animals, עברית מסביב לעולם, IML, Ivrit Misaviv La'Olam, dogs, dog, brown,".

I then search for dog in Hebrew 'כלב', and this image does not come up. 

What is wrong?

![image](https://user-images.githubusercontent.com/16290361/154082171-200e9451-2b72-4e32-910f-00c9daa4007a.png)

**Comment by corinnewo** [comment]
@MendyBerger This is the problem that I was talking about.

**Comment by RickyLB** [comment]
@corinnewo This should be fixed once #2442 is merged release.
