### ISSUE TITLE
New USE CASE for card games: Image -Image

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2408]
For all card games:

1. Add in use case IMAGE-IMAGE @GaliShapira to design use cases for 4 card games
2. Starts with image tab and audio tab, one pair of cards in place on RHS
3. Add in a more prominent ADD PAIR as the last pair on the screen - @GaliShapira to design
4. Can drag images into each card. If you want a duplicate image, drag in twice.
5. Audio will work as normal.

**Comment by corinnewo** [comment]
@GaliShapira Please upload zeplin for this and implement @ChaykeeMor 's text changes so that we can implement. Thanks!

**Comment by GaliShapira** [comment]
Hi @corinnewo 
Pls see the new use case:

**Use cases page:** I placed this use case third, let me know what you think.
<img width="809" alt="Screen Shot 2022-03-14 at 12 32 15" src="https://user-images.githubusercontent.com/88834002/158154876-a13151a0-8807-40b2-935e-c99de311a097.png">
I uploaded the images use case to Dropbox.


We added a new setting to the Memory game:
<img width="379" alt="Screen Shot 2022-03-14 at 12 35 17" src="https://user-images.githubusercontent.com/88834002/158155459-89160f22-6fb4-4582-a815-8151a3f6bbe3.png">


**Screens on Zeplin**:
https://zpl.io/ew8mdrD
https://zpl.io/3XkGZ71
https://zpl.io/1ykgWmQ
https://zpl.io/6NkpRO


<img width="1263" alt="Screen Shot 2022-03-14 at 12 34 51" src="https://user-images.githubusercontent.com/88834002/158155524-9ae76d21-a544-4e7b-9166-8fae65831ef4.png">
<img width="816" alt="Screen Shot 2022-03-14 at 12 34 58" src="https://user-images.githubusercontent.com/88834002/158155540-c8460947-8af2-4aed-b685-5016d90e253c.png">

<img width="816" alt="Screen Shot 2022-03-14 at 12 34 58" src="https://user-images.githubusercontent.com/88834002/158155604-885e427b-2642-43a4-b0d9-6e38df63b035.png">

**Comment by GaliShapira** [comment]
@meravs 
Can you kindly upload to here the use cases of image-image for the other 3 card games activities?

**Comment by meravs** [comment]
Matching
[matching-images.zip](https://github.com/ji-devs/ji-cloud/files/8371347/matching-images.zip)
![Screen Shot 2022-03-29 at 15 23 27](https://user-images.githubusercontent.com/96105053/160610762-9d4fccfe-e39a-4c58-9fbd-a4bff33a4de8.png)

flashcards
[flashcards-images.zip](https://github.com/ji-devs/ji-cloud/files/8371351/flashcards-images.zip)
![Screen Shot 2022-03-29 at 15 20 24](https://user-images.githubusercontent.com/96105053/160610882-028dd86b-ed9d-4070-956c-510d0458b355.png)

Quiz game
[Quiz game-images.zip](https://github.com/ji-devs/ji-cloud/files/8371359/Quiz.game-images.zip)
![Screen Shot 2022-03-29 at 15 18 46](https://user-images.githubusercontent.com/96105053/160611005-6206c9db-5941-4146-be1d-46859499edc8.png)

**Comment by johnnynotsolucky** [comment]
Whoops, tagged wrong issue in my PR!
