### ISSUE TITLE
Image search results - randomization should be prioritized according to relevance of the search term

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2411]
Search results are randomized so that the same results do not appear each time. When searching for a term, relevance is mixing up with the randomization.

Randomization should be prioritized based on relevance of the search term.

For example, when searching for "king," the results are randomized, but some are irrelevant:
![Screen Shot 2022-02-16 at 12 02 51 PM](https://user-images.githubusercontent.com/78186896/154247262-a0f3e5df-b3f1-4206-8106-6e1adaae2a3a.png)

**Comment by corinnewo** [comment]
@RickyLB We must keep the most relevant search results first, randomized.
