### ISSUE TITLE
Create: Theme/ background tab - only stickers should appear in the search results

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2412]
In Wizard Step 2 (Content) backgrounds appear when searching for images. When searching for images in the content section, only stickers should appear in the search results.

![Screen Shot 2022-02-16 at 11 59 39 AM](https://user-images.githubusercontent.com/78186896/154249544-5ccd1192-ad6e-4078-b45c-c0a17862c3bf.png)

**Comment by corinnewo** [comment]
I checked the filters on the image tab, and it is set to NO BACKGROUNDS. @MendyBerger Please check why this is not being honored?
![image](https://user-images.githubusercontent.com/16290361/154266795-1bb884b0-41f7-4495-b595-e7c921e0332d.png)

**Comment by MendyBerger** [comment]
@chayaml @corinnewo do you know if this worked in the passed?

**Comment by corinnewo** [comment]
I see that there is ticket #1862 that indicates that it did not work properly in November... 

This image search should definitely filter out backgrounds and show only stickers, unless the filter is unchecked by the user.

**Comment by MendyBerger** [comment]
Closing in favor of #2424 as that's the underlying issue.

(You can subscribe to that issue if you wanna get notifications on it)
