### ISSUE TITLE
Theme/ Background tab update: needs to be applied to all modules

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2413]
Theme component was combined with the former background component. The change appears in "cover" but need to be updated with all other modules as well

Cover with updated version:
![Screen Shot 2022-02-16 at 1 13 48 PM](https://user-images.githubusercontent.com/78186896/154253438-424054bc-7828-44c6-9461-5ef7aa4ccbde.png)

"matching game" activity, still with the old design:
![Screen Shot 2022-02-16 at 1 14 43 PM](https://user-images.githubusercontent.com/78186896/154253624-5ed1e84b-6a42-4d17-8527-ad77a340a785.png)

**Comment by corinnewo** [comment]
Closing in favor of https://github.com/ji-devs/ji-cloud/issues/2390 as this is a duplicate.
