### ISSUE TITLE
Create: theme/ background - Can't select a theme after designing a background from scratch

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2417]
When creating a cover, I designed a background from scratch. I then decided to go back and select one of the themes, but I am unable to do so.

How can we allow a user to change from a custom background design to a premade theme?

Note: By the overlay tab, there is an option to delete the overlay selected with the trash icon. Maybe the same can be done with the background so that the user can delete their selection if they change their mind and return to 
![Screen Shot 2022-02-16 at 2 44 49 PM](https://user-images.githubusercontent.com/78186896/154267194-2f7aa6f6-c13f-4723-aac8-a463d2cd2360.png)
themes.

**Comment by corinnewo** [comment]
@GaliShapira Why do you recommend?

The remove overlay is working well, but we felt that the extra trash icon on the background tab would be too much. There are currently two ways to 'remove' a custom background:

1.  You can use the undo function on the top right of the screen
2.  You can select 'fill color' and make it transparent
Both of these are really roundabout ways to remove a background and return to the theme!

@GaliShapira Please advise! Thanks

**Comment by chayaml** [comment]
btw, @corinnewo and @GaliShapira, it could  just be me, but I did not notice the undo/ redo buttons or realize their function until pretty late in the game - maybe because they are placed on the far right of the screen (and when creating I am just paying attention to the left side)

Perhaps it would be helpful to have a redo/undo tooltip or to have the words under the buttons - just an idea - I know those are widely used icons and most users will probably be able to recognize them right away:)


![Screen Shot 2022-02-16 at 3 18 28 PM](https://user-images.githubusercontent.com/78186896/154276841-43158483-0105-43ae-8056-f2a40af3cc2c.png)
![Screen Shot 2022-02-16 at 3 16 52 PM](https://user-images.githubusercontent.com/78186896/154277354-062ed5aa-18f8-407d-988c-edb5a6c6181e.png)

**Comment by corinnewo** [comment]
@MendyBerger I think that if you have chosen a background, and then come back and choose a theme, the background should be overwritten (or deleted, as the case may be). Otherwise, choosing a new theme cannot be seen.

I have moved the redo/undo comment to its own ticket: https://github.com/ji-devs/ji-cloud/issues/2459

**Comment by corinnewo** [comment]
Closing in favor of #2590
