### ISSUE TITLE
Video module - add ability to define in and out points

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2418]
Apparently we have received feedback from users that without the ability to define a clip in YouTube, they will not use this video module. It is important to be able to play a clip and not have to play the whole video.

@GaliShapira Please can you design how this will look in the video module?
Thanks

**Comment by corinnewo** [comment]
@GaliShapira We also need the ability to search for a video once, and then be able to create the various clips on the one video. Perhaps the ability to duplicate a module with the same video reference, just different in and out points. In other words - search for the video once, and then have different screens with different clips on the same video.  Happy to discuss...

**Comment by GaliShapira** [comment]
IF IT'S POSSIBLE TO HAVE A PLAYER ON THE CREATOR CANVAS - 
I HAVE A DIFFERENT DESIGN THAT HAPPENS ON THE CANVAS.
I didn't upload it to Zeplin, let me know if this is possible and I will update the Zeplin. 
This is a much better experience if possible. The teacher sees the actual video and stop it on the relevant points.
See what I mean in the 2 screenshots: 
<img width="430" alt="Screen Shot 2022-08-21 at 18 29 27" src="https://user-images.githubusercontent.com/88834002/185798700-436ef79e-d2d4-4858-9276-005ad104bd83.png">
<img width="424" alt="Screen Shot 2022-08-21 at 18 29 34" src="https://user-images.githubusercontent.com/88834002/185798709-053523b5-795a-4bdb-9eea-44f5cc0664ab.png">


**### My Option B:** On the panel

See the flow here:
https://zpl.io/PqMYBqk

1. Starting point, The time text fields are typable. User can drag dots or type the exact time on the fext fields.
<img width="408" alt="Screen Shot 2022-08-21 at 18 22 08" src="https://user-images.githubusercontent.com/88834002/185798352-7fae8aff-6a9d-4d6b-b4ff-71ed0ce98e62.png">

2. On dragging the cursor changes to dragging, the dot changes to blue, a tooltip with the seconds appears above the active dot.
<img width="407" alt="Screen Shot 2022-08-21 at 18 22 15" src="https://user-images.githubusercontent.com/88834002/185798395-deb80a6b-49cf-45a2-b6a5-680df987b0fe.png">

3. When done dragging, on reliese the dot is light blue again, the tooltip disapear and the seconds are updated in the text field as the starting/ending point.
<img width="418" alt="Screen Shot 2022-08-21 at 18 22 20" src="https://user-images.githubusercontent.com/88834002/185798459-b22ebb28-b509-46ad-9c7c-7e5f159aeb9e.png">

**Comment by corinnewo** [comment]
@MendyBerger Please can you give your opinion here, so that we can finalise this ticket? Which option do you recommend?

**Comment by MendyBerger** [comment]
Can we discuss it over a video call?
