### ISSUE TITLE
Create Page - Edit Headings

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2419]
Where | What | On Jigzi: | Change to:
-- | -- | -- | --
Create | Heading | Create a New JIG | Learning Through Creation
Create | Body | Create a new JIG (Jewish Interactive Game). Choose the activities designed to fit your teaching goals and you'll have a complete interactive lesson in just a snap! | Create a new JIG (Jewish Interactive Game) in just a snap! Choose activities that fit your teaching goals to develop complete interactive lessons for your students.
Create | Button | Create your own | New JIG
Create | Heading | My Recent JIGs | My JIGs

**Comment by corinnewo** [comment]
@ChaykeeMor are these changes incorporated into the new zeplins with the creation of courses, JIGs, and resources? If so, then we can close this ticket. PLease advise.

**Comment by ChaykeeMor** [comment]
I think disregard this in favor of the new design but I will update the texts here as well if you'd like. @GaliShapira have you put in all the texts for the create menu page? Maybe we could take a quick minute before/after ideation to look all together @corinnewo?

**Comment by corinnewo** [comment]
Good idea - I've invited you both to a meeting before ideation.
