### ISSUE TITLE
Translating of Image file names and JIG names into the list of languages

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2425]
The translation of the description has been so successful. It now appears to be necessary to automatically translate the file names and JIG names in the same way, so that they can be searched in any language.

**Comment by corinnewo** [comment]
@RickyLB Please go ahead with the translation of the names as well.

**Comment by RickyLB** [comment]
@corinnewo This will need to be pushed to Release in order for name translations to be searched.
