### ISSUE TITLE
Image search: searching "2" returns irrelevant results

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2428]
Searching for "overlay 2" or simply "2" returns irrelevant results because overlays are being tagged as "background layer 2" (by "tags - internal use only")

![Screen Shot 2022-02-18 at 8 55 10 AM](https://user-images.githubusercontent.com/78186896/154640318-d8a5627b-f435-4506-be5f-46e30247d4e1.png)

**Comment by RickyLB** [comment]
Got rid of the existing `image_tag_names` field in algolia as searchable attribute. 

<img width="1190" alt="Screen Shot 2022-02-18 at 1 30 42 PM" src="https://user-images.githubusercontent.com/76449893/154763950-d2daa71c-4055-4444-8082-7b896ec5e259.png">

Searching using "2" will bring up title/descriptions with "2" and "two" as well. Did you want this?

**Comment by corinnewo** [comment]
@RickyLB Thanks - this looks good! I will close it now.
