### ISSUE TITLE
Create: Jig Kebab panel - correct icon?

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2431]
I've noticed that the settings icon by the kebab menu panel looks different - @GaliShapira is this the correct design?
 
**Currently on Jigzi:**
![Screen Shot 2022-02-20 at 9 52 49 PM](https://user-images.githubusercontent.com/78186896/154861639-f37ff537-19c5-4078-8232-35ad97da9c70.png)

**Previous icon:**
![Screen Shot 2022-02-20 at 9 52 29 PM](https://user-images.githubusercontent.com/78186896/154861624-4b240c66-8d9e-4d0f-aebd-5ac4cd35e44e.png)

**Comment by GaliShapira** [comment]
You are right, its not the correct icon. Need to be as in the previous version you showed.

**Comment by mastapegs** [comment]
@chayaml, I took a look at both the Release (jigzi.org) and the Sandbox environments (sandbox.jigzi.org) and both are using the previous image for the icon

![image](https://user-images.githubusercontent.com/13839150/155010866-1eb0fc30-0279-4544-ae6c-654d4943f4ca.png)
![image](https://user-images.githubusercontent.com/13839150/155010949-ad80a7da-bfcb-4e2d-8fe7-ea541a7491ac.png)

**Comment by GaliShapira** [comment]
Hi @mastapegs 
Pls see the icons attached, regular state and hover/clicked state

![Icni-JIG-Settings-hover](https://user-images.githubusercontent.com/88834002/155141815-a88ed4e8-4314-4967-8afe-c71cee58f43e.svg)
![Icn-JIG-Settings](https://user-images.githubusercontent.com/88834002/155141817-783cd45f-3c0f-4119-b7ea-8c7096088207.svg)
