### ISSUE TITLE
Drag & Drop  - Wizard changes - 1 - Theme component

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2437]
<img width="278" alt="Screen Shot 2022-02-22 at 15 31 20" src="https://user-images.githubusercontent.com/88834002/155142341-bc742482-46f3-4497-985a-ff568a2ae389.png">

Pls see step 1 on the Zeplin:
https://zpl.io/VDggo3r

Entire flow:
https://zpl.io/p1rJLRo

**Comment by MendyBerger** [comment]
Mind elaborating? Not sure what needs to be done here

**Comment by GaliShapira** [comment]
@MendyBerger 
Step 1 in drag and drop should be consistent with the other activities, so it now shows the component of the theme.

**Comment by corinnewo** [comment]
We did not include this in the original set of modules that needed the theme to be implemented, as it needed a complete overhaul. We had 5 tabs on the first wizard stage, This module is now ready for the theme improvements, as well as the reorganisation into the INTERACTION tab. @MendyBerger @GaliShapira We probably need to go through together to see what needs to be done here before you start.

**Comment by corinnewo** [comment]
@GaliShapira Please make sure that the final text changes are in the zeplin before Mendy gets to this! Thanks,
