### ISSUE TITLE
Drag & Drop  - Wizard changes - 2 - flow

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2438]
New version:
<img width="274" alt="Screen Shot 2022-02-22 at 15 32 33" src="https://user-images.githubusercontent.com/88834002/155142604-67f4802d-5b7d-4abd-9451-f926281ee5ae.png">

Old version:
<img width="393" alt="Screen Shot 2022-02-22 at 15 32 20" src="https://user-images.githubusercontent.com/88834002/155142612-8ac4e1bd-36c7-46a6-a131-7998450aca80.png">

Changes:
1. Step 2 is now consistent with the other activities.
https://zpl.io/ad33YoE
https://zpl.io/29mmz3B
2. Step 3 replacing the older steps of 2-4
the flow if the 4 tabs under interaction, to be consistent with the other activities.
https://zpl.io/bo336lo
https://zpl.io/Vx33Qjm
https://zpl.io/2EQQx7y
https://zpl.io/nolEwWQ
https://zpl.io/aNxx5W4
https://zpl.io/VO3mYRr
https://zpl.io/VKddQJq

**Comment by johnnynotsolucky** [comment]
Related to #2437
