### ISSUE TITLE
Jigzi Player: "Teffilah Tunes - Sfardit Pronunciation" text expanded beyond canvas area

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2456]
Another instance (#2453) where some of the text is expanded and goes outside the canvas area/ hides content.

**Jigzi:**
![Screen Shot 2022-02-24 at 10 12 12 AM](https://user-images.githubusercontent.com/78186896/155486323-9ad7ef67-70b0-457e-b274-2347a257fe75.png)

https://jigzi.org/admin/curation/589664fa-69d2-11ec-8bed-77e56ebff23a

**Jitap:**
![Screen Shot 2022-02-24 at 10 15 12 AM](https://user-images.githubusercontent.com/78186896/155486461-e432fd0d-a99e-4971-a2b2-2beab0bb99ff.png)

https://jitap.net/activities/gzf/play/

**Comment by corinnewo** [comment]
@dakom Is this a player issue or to do with the legacy translation?

**Comment by chayaml** [comment]
Same issue here with many pages in the game  - https://jigzi.org/admin/curation/7efa89a6-69c2-11ec-ab82-33693acdeea0

**Comment by dakom** [comment]
Yikes.... these seem really, really gnarly. I can't say for certain what's going on here, or if it'll require game conversion.

@chayaml - can you please do me a favor to make it a bit easier:

1. Confirm that in all these cases it's text, not like photos or clipart
2. Close all the issues that were opened and are really 1 issue
3. Create one issue - and in that issue provide the links to the examples you've seen so far.

My hope is that even if something got corrupt in converting text stickers, it's _consistently_ corrupt and so we can fix it either in our player or in our database, but won't need to go back to download and convert from tiny tap.

Really really hope so 🤞

**Comment by chayaml** [comment]
closing in favor of #2471
