### ISSUE TITLE
Map all use cases to background tags 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2460]
Map all use cases to the relevant background tags so that when we search, the backgrounds that most suit that use case will appear first.

**Comment by corinnewo** [comment]
@MendyBerger I've assigned this to you, but need direction from you to prepare how best to map the tags to use cases.

**Comment by corinnewo** [comment]
For each use case, we want to prioritise the images/backgrounds that are most suitable for that use case. I have created a spreadsheet of all the use cases that we have so far, and the images/backgrounds that should appear at the top for those use cases: https://docs.google.com/spreadsheets/d/1vAhXmCUeswL4QDAiMQzPnP9PNhNP4bRqF27jD1B7CPk/edit?usp=sharing
We currently have the following tags for images in the backend:

- Background Layer 1
- Background Layer 2 (a.k.a. "Overlay")
- I Spy
- Multiple Choice
- Drag & Drop
- Video
- Navigation Button
I would like to add in the following new ones:
- Table
- Map
- Boards
- Timeline
- Book
- Printables
- Photo album
- Music
- Comix
- Wardrobe
- Stage

Once these are added to the backend, we can go through the images and make sure that they are tagged. (@chayaml, myself, Jess, Anat, etc)

Then we need to program that for each use case, these tagged items are shown first.

**Comment by MendyBerger** [comment]
Added tags in 66095e267, need to sync after pushing to release

**Comment by MendyBerger** [comment]
Resolved
