### ISSUE TITLE
Curation tool:  arrows to change page not working correctly

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2470]
The arrows to go to the next  page or changing the numbers on the dropdown list do not work - the Jig table remains the same or changes slightly - not sure what's wrong but something is off.

![Screen Shot 2022-03-01 at 10 40 26 AM](https://user-images.githubusercontent.com/78186896/156134819-3c860fe1-96d9-4578-965a-4bb6e3afa0ef.png)

**Comment by MendyBerger** [comment]
@RickyLB Server always returns the same jigs even when changing `page`
