### ISSUE TITLE
Player - written instructions cover important content and disappear before children can read it

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2482]
Beta testers commented that the written instructions can cover too much of the screen and disappear before child can read them. She submitted this screen capture:
![five](https://user-images.githubusercontent.com/16290361/156388976-2086baa9-7612-4822-9c51-80ae57476ed0.png)

Some solutions:
- Add close button to the instruction 
- HIghlights and activity should only start after the instruction has been closed
- Center the text so that it suits both Eng and Heb
- Make instruction font smaller
- Limit the number of characters in the instruction input field in the create section
(@GaliShapira, please add your suggestions for close button, font size, and position of text, and then we can assign to a programmer.)

## Definition of done/Requirements:

- [x] When editing instructions for an activity, limit the text that a teacher can enter to 200 characters. Without the character counter for now, show the limit in the label.
- [x] Create a new element to display the instruction text (similar to the jiggling help popup) with the repeat and OK buttons;
  - [x] If there are instructions, then the activity will start with the instructions dialog open, and they can then close it to start
- [x] Add the "repeat" button to the player
  - [x] When the jig is played inside a popup, place the button next to the "X" button as in the screenshots above;
  - [x] When the jig is _not_ inside a popup and there is no "X" button, place the button where the "X" would normally be;
  - [x] Add a new message to pass up to the player to tell it what text to display and audio to play.
- [x] Activity doesn't start until the student closes the popup by clicking OK or clicking anywhere else on the screen;
- [x] Clicking the "repeat" icon will display the popup;
- [x] When a student opens the popup, the activity should pause, and then resume once it's closed again;
- [x] For instructions with only audio, use the default text "Are you ready?"
  - [x] For feedback, play the audio and don't display the popup.
- [x] For feedback that has text - once the activity ends, show the popup and play any audio that is set. When the student clicks OK or closes the popup, continue on to the next activity (if the activity is configured to move on).
  - [x] When there is no text but has audio, play the audio and continue to the next activity (if the activity is configured to move on).
  - [x] Make the font of the instructions/feedback larger.

**Comment by GaliShapira** [comment]
מירב כשתסיימי תוכלי להעלות לכאן צילום מסך של העמוד + עמוד פריסת האייקונים, את הקישור לזפלין  ואת כל האייקונים כולל hover ?

**Comment by corinnewo** [comment]
@GaliShapira Is this now ready for dev to implement? It looks good to me. Perhaps we need to make the 200 character limitation on the instruction input screen on the settings tab rather than only here - this will just cut off text, but on input screen, user will be able to make sure the instruction is concise and fits in.

**Comment by GaliShapira** [comment]
Hi @corinnewo 
Yes, this is ready for dev.
You are right, limitation should be on the creator as well. We can add this in the text field title. And the dev should limit once reach the limit. 
@ChaykeeMor would you like to give me the final text for the limitation?
<img width="422" alt="Screen Shot 2022-03-14 at 13 42 23" src="https://user-images.githubusercontent.com/88834002/158165177-7ca4fc21-c382-471d-9127-bb1e46b751f8.png">

**Comment by ChaykeeMor** [comment]
Can we just have a countdown from 200 just below the text field [bottom right]?

**Comment by GaliShapira** [comment]
yes, you dont think we should mention it?

**Comment by corinnewo** [comment]
@GaliShapira I think people are used to seeing a digit count in a field. Doesn't need explanation.

**Comment by GaliShapira** [comment]
@corinnewo 
I updated the design for both functionality:
**1. Instruction**
<img width="751" alt="Screen Shot 2022-08-16 at 13 02 41" src="https://user-images.githubusercontent.com/88834002/184853400-f99f5e6d-9bce-4d47-ba53-b244bf816b99.png">
<img width="400" alt="Screen Shot 2022-08-16 at 13 02 52" src="https://user-images.githubusercontent.com/88834002/184853420-cbe31541-5ba7-427e-9b94-eed40e7b418e.png">
<img width="365" alt="Screen Shot 2022-08-16 at 13 03 01" src="https://user-images.githubusercontent.com/88834002/184853440-cbda6c2d-8f54-4ff4-aea9-d92f1685c1aa.png">

**2. Play again audio** of a question. 
Do you think of another use case/activity except Answer it that it will be used?
<img width="776" alt="Screen Shot 2022-08-16 at 13 03 07" src="https://user-images.githubusercontent.com/88834002/184853479-a5364e9d-ce62-443e-b717-44c9c6f05e9e.png">

Components:
<img width="582" alt="Screen Shot 2022-08-16 at 13 04 53" src="https://user-images.githubusercontent.com/88834002/184853692-a8fbdfb0-1d84-48ba-a8d0-775459f4684c.png">

Zeplin:
https://zpl.io/Nwk3ZBv
https://zpl.io/W4Wky8K
https://zpl.io/llvZeKz
https://zpl.io/Z0yk3Mq
https://zpl.io/Md89Xko

**Comment by johnnynotsolucky** [comment]
After discussing with @corinnewo, we will implement the following:

- When editing instructions for an activity, limit the text that a teacher can enter to 200 characters. Without the character counter for now.
- Create a new element to display the instruction text (similar to the jiggling help popup) with the repeat and OK buttons;
- Add the "repeat" button to the player
  - When the jig is played inside a popup, place the button next to the "X" button as in the screenshots above;
  - When the jig is _not_ inside a popup and there is no "X" button, place the button where the "X" would normally be;
  - Add a new message to pass up to the player to tell it what text to display and audio to play.
- Activity doesn't start until the student closes the popup by clicking OK or clicking anywhere else on the screen;
- Clicking the "repeat" icon will display the popup;
- When a student opens the popup, the activity should pause, and then resume once it's closed again;
- For instructions with only audio, use the default text "Are you ready?"
  - For feedback, play the audio and don't display the popup.
- For feedback that has text - once the activity ends, show the popup and play any audio that is set. When the student clicks OK or closes the popup, continue on to the next activity (if the activity is configured to move on).
  - When there is no text but has audio, play the audio and continue to the next activity (if the activity is configured to move on).

**Comment by corinnewo** [comment]
This is an accurate reflection of what we discussed.
The only thing that I want to add is that if there are instructions, then the activity will **start with the instructions dialog open**, and they can then close it to start. Thanks

**Comment by ChaykeeMor** [comment]
Quick question... why does the replay button for written instruction have the audio icon in the middle of the replay? Will it change between written and audio instruction? if not, I believe a standard replay icon would work for both written or audio. @corinnewo @GaliShapira

**Comment by GaliShapira** [comment]
This icon will not replay the JIG, only the instruction or the last audio. 
Although it shows also the text, I prefer to keep the audio icon inside.
