### ISSUE TITLE
Create gallery - add in the options for Play and Share to the Kebab menu

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2483]
Beta testing feedback - did not know how to share easily.
Please add in the 2 extra options to the kebab menu that Gali designed here: https://zpl.io/a34o3KQ
![image](https://user-images.githubusercontent.com/16290361/156390467-537c21ba-3a4b-43a9-a09a-80e95272193c.png)

Play - opens the player and plays the selected JIG
Share - Opens the share dialog

**Comment by RickyLB** [comment]
@corinnewo Were you thinking about sharing drafts, or was it just the published versions in a user's Gallery?

**Comment by corinnewo** [comment]
You’re right. Only published games can be shared - if a draft, please disable the share option. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by corinnewo** [comment]
Closing this in favor of #3672
