### ISSUE TITLE
Jiggling text to 'Don't show again'- needs to be changed so that it is clear can open help again

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2484]
Jiggling texts - some found them annoying, but we scared to close (don’t show again) as they were worried that they would not be able to get the help again. Suggest changing the text.
@ChaykeeMor - Go back to Dismiss? THen have Jiggling say "I'm still here to help you. Click me if you need me."

**Comment by ChaykeeMor** [comment]
"Dismiss"  Alt: "I don't want help"
return-- "Ok! Just click me if you need me!"

I think when Jigglings are not popping up at each stage, we should have it occasionally spin or wiggle or bounce...etc

**Comment by corinnewo** [comment]
1. Change "Don't show tips again" to "I don't want help".
2. When you click "I don't want help", Jiggling should response with "Ok! Just click me if you need me!" And if will not show help again until it is clicked again.
3. Can you make it wiggle or bounce once in a while?

**Comment by ChaykeeMor** [comment]
This one should be "I don't want help" on the right
and "Take the tour" on the left
<img width="421" alt="Screen Shot 2022-03-07 at 11 15 19" src="https://user-images.githubusercontent.com/94056434/157002081-d92cb9b2-89fe-4ab3-95ca-04f83fc32b09.png">
