### ISSUE TITLE
Voice recording - Add warning to wait until it is uploaded (otherwise if don't, will lose the recording)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2485]
When recording a voiceover, the beta tester did not know to wait until the end of the upload was done. Lost her recording. We need to add a warning: "Please wait while we are uploading your recording."
@ChaykeeMor

**Comment by ChaykeeMor** [comment]
Below progress bar:
"Uploading... please wait."
<img width="376" alt="Screen Shot 2022-03-07 at 11 31 00" src="https://user-images.githubusercontent.com/94056434/157004633-70648dac-0c88-4e68-92b7-66907d00c707.png">
@corinnewo

**Comment by corinnewo** [comment]
@mastapegs Please add in the text below progress bar:
"**Uploading... please wait**."
