### ISSUE TITLE
phone - home page - resize the search strip?

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2493]
The rest of the page is fine for phone (the wordpress part). But the strip with the search is terrible. Can we make the strip fit 100% width?
![Jigzi](https://user-images.githubusercontent.com/16290361/156732368-85e939a5-c153-487e-887e-86c9b55dda2d.png)

**Comment by MendyBerger** [comment]
Resolved in f288a3229ff805476326839ae8f0134253300319
