### ISSUE TITLE
Phone - menu - show a hamburger menu with the items? 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2494]
The top menu is totally unusable. Any suggestions apart from showing a hamburger menu?

![Jigzi](https://user-images.githubusercontent.com/16290361/156733013-1428879e-ca1d-44ee-a682-c68adc6ac8bb.png)

**Comment by MendyBerger** [comment]
Resolved in f288a3229ff805476326839ae8f0134253300319
