### ISSUE TITLE
Background music from Ji Tap games is still not playing in Jigzi

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2504]
Eg whole series of HopTV games have background music. EG https://jigzi.org/jig/play/785a8092-69d1-11ec-b7db-4f8face28521?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false, but it is representative of many Ji Tap games that should have background music, and it is not playing at all.

When you play it, the music icon does not even show on the player. There is no background music at all. I thought that this was sorted in sandbox.

**Comment by corinnewo** [comment]
@MendyBerger to coordinate with @dakom to get this working

**Comment by MendyBerger** [comment]
Closing in favor of #2297
