### ISSUE TITLE
Add share option to the create page

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2506]
CHaykee wants to add a SHARE option to the create page, as she says she always looks for it there to share the JIG. At the moment it does not make sense there, as you can't share until it is published. CHaykee is suggesting that if it has been published, then the share works as normal. If there is no published version yet, you get prompted to publish and then share.

@GaliShapira Where would you add in a SHARE option on this page?

<img width="1640" alt="Screen Shot 2022-03-07 at 10 44 07" src="https://user-images.githubusercontent.com/16290361/157018079-fa87ad84-97c6-4e21-b3d6-b273e33908bd.png">

**Comment by GaliShapira** [comment]
Lets discuss it, need to understand it better in order to make decisions.

**Comment by corinnewo** [comment]
This is being taken care of by adding the SHARE and PLAY options to the KEBAB menu on the gallery page. CLosing.
