### ISSUE TITLE
Safari - Player sizing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2509]
The player on Safari does not fit the screen. It is too small. Buttons overlap. iPad looks like this:
![IMG_6912](https://user-images.githubusercontent.com/16290361/157060271-b3b8ec91-2e54-4a94-8625-6f18d2f38bc2.PNG)

1. Enlarge the player to fill the available space (100% width?)
2. Space the NEXT and PAUSE buttons so they don't overlap. Also take into account that if background music, then that icon will be overlapping too.
3. When you open the side panel, the panel should be made smaller, according to the device. At the moment, the open panel looks like this: 
![IMG_6913](https://user-images.githubusercontent.com/16290361/157060704-68905207-2076-4100-b31f-4cfb3716249d.PNG)

.

**Comment by MendyBerger** [comment]
Resolved in eb282915a
