### ISSUE TITLE
Playing JIGs on mobile- everything seems to work, except dragging

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2518]
Not sure if there is anything we can do about this at the moment, but the JIGs all playing nicely on mobile (apart from having to click play for each module). The only thing is the dragging in this activity type. 

![IMG_6914](https://user-images.githubusercontent.com/16290361/157225045-f342e928-0c16-4c40-8a0b-c1dce308f966.PNG)

**Comment by MendyBerger** [comment]
Resolved in 0a5b84eb20a35a2b7edc76f1a3b717f2227598aa
