### ISSUE TITLE
Add scroll bar to the activity screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2520]
USer feedback that they did not know that there were more activities. Need to add a scroll bar.

![PHOTO-2022-03-08-10-31-05](https://user-images.githubusercontent.com/16290361/157226719-f6ce08a9-dd3d-42d1-ab37-ebc8811fbc9c.jpg)

**Comment by corinnewo** [comment]
On my chrome laptop, I have a scroll bar. Is it only on Mac?
![image](https://user-images.githubusercontent.com/16290361/157227230-fc32cac5-371c-490f-ab3f-d3e6237ea00e.png)

**Comment by corinnewo** [comment]
Suggestions to fix:

1. Add scroll bar to the area, just as on the jig panel on left
2. Check that you can change sizing so that the second row is slightly cut off, and not completely on the screen. Hints that there is another row below.
3. Discuss with Gali...

**Comment by MendyBerger** [comment]
As far as I know both Chrome and Firefox have scrollbars (@johnnynotsolucky mind checking Safari?)

What might have happened there was that Zoom was covering it, but not sure.

**Comment by johnnynotsolucky** [comment]
@MendyBerger @corinnewo I've tested firefox, chrome and safari on Mac and all had the scrollbar. iOS doesn't show the scrollbar though.

**Comment by corinnewo** [comment]
@johnnynotsolucky Is it possible to implement Gali's idea of positioning the activity tiles so that some are cut off and obvious that there are more below, rather than fully on the page?

**Comment by johnnynotsolucky** [comment]
@corinnewo I don't know if we should. The activity tiles are positioned based on dimensions of the device - narrower screens will have less columns of tiles vs wider screens. If we had to force the positioning I'm worried we'd have to add a lot of complexity to cater reshuffle cards instead of letting the browser do it for us.

**Comment by corinnewo** [comment]
I understand - agree. Let's keep it as it is. CLosing this ticket
