### ISSUE TITLE
Font size - Matching + Multiple choice (quiz game)

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2521]
We need to make a change here.
Pls make sure that in the cards presented to select the answer, font size needs to be equal for them all.
Pls make the font size as big as possible.

Different font size might look like one of the card  is the correct answer or that we are leading the student to pick this one.

<img width="1440" alt="Screen Shot 2022-03-08 at 13 25 49" src="https://user-images.githubusercontent.com/88834002/157230382-a8f2cde3-9c0d-4d29-8f9f-2e5ea8b2dbd3.png">
<img width="1440" alt="Screen Shot 2022-03-08 at 13 27 37" src="https://user-images.githubusercontent.com/88834002/157230268-57e3629a-b074-4dce-8e14-834e05cf3c34.png">

**Comment by corinnewo** [comment]
If possible - can the size be calculated on the set of words? If all 1 letter, then they can all be larger than if all the answers are 3 words.

**Comment by johnnynotsolucky** [comment]
The scaled font size was introduced with this change https://github.com/ji-devs/ji-cloud/pull/2188

**Comment by corinnewo** [comment]
I know @johnnynotsolucky - I worked with you on this. But we have received feedback from users that on the quiz cards (matching and multiple choice) the variation in size hints falsely at the answer. We will keep the varied size on the memory game and flashcards, but on the quiz cards, we need to have the same size font on all cards - as large as possible!

**Comment by corinnewo** [comment]
@johnnynotsolucky Please can you look at this - it keeps on coming up as an issue with teachers. We must have the same font size for all cards in these 2 activities. Thanks!
