### ISSUE TITLE
Missing close sidebar button when editing a JIG

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#2525]
**Describe the bug**

The button to close the sidebar is not showing anymore. The image is still present on the page and can be clicked, but it is not visible.

**To Reproduce**

1. Edit a JIG
2. Note the open/close button for the sidebar is not visible.

**Expected behavior**

Button should be visible

**Screenshots**

![Screenshot 2022-03-09 at 08 28 06](https://user-images.githubusercontent.com/4161106/157387696-59eb1e54-b881-4d3c-a09a-f81ed3bf0e70.png)

**Additional context**

On **Safari**, the close button is visible.

**Comment by corinnewo** [comment]
@johnnynotsolucky That's a great observation! I wonder when it disappeared! I'm assigning it to you as you are such a great detective...

**Comment by johnnynotsolucky** [comment]
@corinnewo it looks like this is intended behavior that I have overlooked.

Whenever the teacher is on the "Add an activity" screen, the open/close button is hidden. Once they've added an activity and the activity is selected so that they can edit it, the button is visible.

I think that there is still a bug, although not so important - When the button is hidden, it should not be clickable.
