### ISSUE TITLE
Quiz Game correction to "Multiple Choice Activity" - needs to be throughout the Create process

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2550]
We renamed the 'Quiz Game' to 'Multiple Choice', which has partly been implemented.

- The name of the activity on the activity-choosing screen is correct
- The use case carousel has been correctly renamed.
- When you actually go in to create, the **heading is still saying 'Quiz Game'**. Please rename to "Create a Multiple Choice Activity" NOTE: USE THIS CAPITALISATION AND NOT AS I WROTE ON THE GRAPHIC!
![miltiple choice not quiz game](https://user-images.githubusercontent.com/16290361/158341850-ddfb550f-4781-4950-b7e2-1df4443e6ab3.JPG)
-The end is also reworded correctly (after the preview).

-

**Comment by mastapegs** [comment]
The module title is coming from the media CDN `card-quiz.json`.

I updated the file in the DropBox and am just waiting on the CDN to update.

Here is a link to the file: https://media.jicloud.org/config/module/_header/tips/card-quiz.json

Once the CDN updates, I'll close this ticket

**Comment by mastapegs** [comment]
The CDN has updated, so this ticket is complete!

![image](https://user-images.githubusercontent.com/13839150/160608617-ea6e66c8-4f01-4a38-986a-1f918b2af92a.png)
