### ISSUE TITLE
Distorted X button on iPad and phone

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2552]
On iPad, the close button is not a circle, but oval. Please make it a circle on any device!
![IMG_6922](https://user-images.githubusercontent.com/16290361/158358438-8da69e4b-24bd-4966-a0bc-71e2c607f3b4.jpg)
<img width="375" alt="PNG image 2" src="https://user-images.githubusercontent.com/16290361/158358517-a352db5e-12bc-442d-b278-62fe6d71f94b.png">

**Comment by johnnynotsolucky** [comment]
Still an issue, noted in #2757

**Comment by johnnynotsolucky** [comment]
Sorry, this is fixed on sandbox. Jigzi.org still needs to be updated.
