### ISSUE TITLE
Background image in card games is not showing in preview

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2565]
This bug was reported by ShalomLearning:
When you choose a background for any of the card games, the background appears on the canvas. But when you preview, the background does not show. But if you go back to the design page, the image is there.

1: Choose a background:
![image](https://user-images.githubusercontent.com/16290361/158950045-dba24d64-1a25-4681-92a9-c331782974c3.png)

2: Preview:
![image](https://user-images.githubusercontent.com/16290361/158950106-b893b8bb-f7a2-48b3-b1b6-0273d2c7971a.png)

3: Thumbnail does not show background either
![image](https://user-images.githubusercontent.com/16290361/158950306-4dd49ab6-9f33-4760-a0b4-a772437a4846.png)

**Comment by MendyBerger** [comment]
Resolved in e5e94af08
