### ISSUE TITLE
Covers are not being saved, so unable to publish (Jigzi, from a user)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2570]
A customer from ShalomLearning is reporting that she cannot save a cover, and so she cannot publish. This is on Jigzi, as she is actually creating content.

**Comment by corinnewo** [comment]
![image](https://user-images.githubusercontent.com/16290361/159292056-76209189-39ff-40c4-a192-043e9329c1f6.png)

**Comment by MendyBerger** [comment]
Resolved in 7d0d918a1b4680ec1426897bbc25da20a0b1735e
