### ISSUE TITLE
Collection of small quick issues

### ISSUE THREAD

**Issue by mastapegs** [ji-devs/ji-cloud#2576]
# Collection of small quick issues

I'm creating this issue for @corinnewo to track the completion of several other small issues that individually are fairly small and should be quick wins to complete and close.

- [x] #2561 
- [x] #2552 
- [x] #2550 
- [x] #2439 
- [x] #1964 
- [x] #2388 
- [x] #2292

**Comment by corinnewo** [comment]
@mastapegs please do the embedding issue #2561 soon, as it is causing errors when trying to share. At the very least, update the embedding code to make it the student player. Thanks!
