### ISSUE TITLE
Guess the audio file path (legacy)

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#2578]
Grrrrrrrrr

It seems that in many cases, the tiny tap manifest says that a file is `.aac`, and the file *DOES NOT EXIST*

But if you magically assume, hey, maybe they meant `.mp3`, then *IT DOES*

Example: https://jitap.net/store/api/album/39/structure/ says that there is a `photo14/question0/question0.aac` file, which should reside at https://d24o39yp3ttic8.cloudfront.net/Purim-Fun_E6CAECB3-4724-4278-A9BF-1DAAB761D673/unzipped/photo14/question0/question0.aac ... which it doesn't, but https://d24o39yp3ttic8.cloudfront.net/Purim-Fun_E6CAECB3-4724-4278-A9BF-1DAAB761D673/unzipped/photo14/question0/question0.mp3 does

This is a major problem, because when originally doing the conversion, tons of stuff was wacky, and we had to assume that things were just missing... in some cases that can mean not even adding an activity (or parts of it), the alternative would have been to break the player in many cases.

This is fixable but it means replacing the JSON for all existing JIGS, basically re-running the process from start to finish.

It's a giant headache... but @corinnewo let's discuss - if we already are planning to do another batch of imports, it might make sense to just erase _everything_ and re-run

**Comment by dakom** [comment]
Note, if we do this, then we can improve on https://github.com/ji-devs/ji-cloud/commit/e7564c50e8a3bd26ad3669b2e7b176559b8d9d4d#diff-c59c513cccca98f77409d34716fc22bff3f89d9929c137d3e7b977b65ca54ba8R52 as well

**Comment by corinnewo** [comment]
OY - we have curated hundreds of the imported games already! I would hate to erase and start again! Unless we are able to save the curation details, as well as the IDs of the games.

**Comment by dakom** [comment]
Yeah, I hear it... other option is to have it go through the whole pipeline, but overwrite the module data without affecting the jig.

Going to be a real pain to do this, but it's doable
