### ISSUE TITLE
Missing graphic for blank audio tab in Drag and Drop activity

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#2580]
Add graphic when no draggable item is selected in the Drag and Drop activity:

![image](https://user-images.githubusercontent.com/4161106/159857152-72fc3f29-58c9-409f-8a3b-a2dfd31857b6.png)

#### Reference from card games

![image](https://user-images.githubusercontent.com/4161106/159857361-3714572c-6cd3-4292-addb-a21b5a8315f4.png)

**Comment by corinnewo** [comment]
Thanks for finding this! We have to redo the drag and drop next ... so will take this into account!

**Comment by johnnynotsolucky** [comment]
@corinnewo can this include the "Select" tab too. In the changes implemented in #2619, select and audio tabs don't have a graphic, but Trace and Place have graphics.

**Comment by corinnewo** [comment]
@GaliShapira - please take a look and supply the graphics that can be used. You can see the reworked frag and drop in sandbox.
 THanks!

**Comment by ChaykeeMor** [comment]
Old Drag and drop.
