### ISSUE TITLE
Delete a JIG on MY JIGs page - add a sentence to the warning

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2582]
We have to make clear that deleting an item from MY JIGs deletes the item from the database. This warning is not enough. Need to add a sentence to warn that deleting from this list will delete altogether. (This differs from Ji Tap where you have a local creation area, and you can delete from there once you have published. So it is really important to add in the explanation.)

![image](https://user-images.githubusercontent.com/16290361/159898804-e744ceae-1844-4882-b0f6-b2cba18c2e8b.png)

**Comment by ChaykeeMor** [comment]
Are you sure you want to delete this JIG?
Add:  Deleting this JIG will delete it permanently. This cannot be undone.
Add to resource: Deleting this resource will delete it permanently. This cannot be undone.
Add to course: Deleting this course will delete it permanently. This cannot be undone.

**Comment by ChaykeeMor** [comment]
I still wish we could change all the delete warnings so the delete buttons are primary. The warning gives you pause and the big button is supposed to be confirmation-- not cancelation. It drives me crazy every time. The little red link should be 'don't delete' and the big blue should be go ahead with what I asked you to do.

**Comment by corinnewo** [comment]
@ChaykeeMor 
I've asked Carina to check this in the user testing. It does annoy me too, but we need proof from the users that it is not correct....
I wanted the extra warning as this is different from Ji Tap in that in Jigzi, if you delete from your working area, you are deleting what is in the database of published items. In Ji Tap, you have the local area on your iPad, and if you delete from there, if you have published, then there is no effect on the database. So I think we need to make this clear in the warning.

**Comment by corinnewo** [comment]
@ChaykeeMor I think we should be more explicit: Instead of "Deleting this JIG is permanent and cannot be undone." we need something like "Deleting this JIG removes it from Jigzi altogether and cannot be undone."  

We need to differentiate from Ji Tap, where published database is not affected by deleting in the work area.

**Comment by corinnewo** [comment]
@ChaykeeMor Please finalise this text so that I can ask DEV to implement. Thanks!

**Comment by ChaykeeMor** [comment]
Are you sure you want to delete this JIG?
Add: Deleting in Jigzi is **permanent** and cannot be undone.
