### ISSUE TITLE
Ability to remove a background I added and go back to the theme

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2590]
@GaliShapira 
Anat is begging for the ability to remove a background and go back to the theme. The layout removal works well. Why can't we implement the same functionality with the background? Please look at it and see how we can add the little trash can and delete the background. Teachers need it.

**Comment by GaliShapira** [comment]
Pls see the removing background and overlay in this link:
https://us04web.zoom.us/j/73564335590?pwd=KCiML9m7Xtr0ZdllB3AgGBYC7RFLHm.1

1. Remove trash icon from overlays.
2. Add to backgrounds and overlays the first image as attached. Click on it will remove the overlay or the background.
See the first image:
![first-image](https://user-images.githubusercontent.com/88834002/161058628-19050b2c-900d-4517-af27-55789d95ef02.svg)


<img width="294" alt="Screen Shot 2022-03-31 at 15 48 19" src="https://user-images.githubusercontent.com/88834002/161058550-c385179d-beaf-4978-8b92-f4c210fe5557.png">
<img width="307" alt="Screen Shot 2022-03-31 at 15 48 15" src="https://user-images.githubusercontent.com/88834002/161058575-3ac8201f-9199-4b86-8c73-04b84564e59c.png">

**Comment by corinnewo** [comment]
@GaliShapira If there is no background or overlay in place, then should the first item be a regular background or the transparent item anyway?

**Comment by corinnewo** [comment]
THis applies to ALL THEMES, including card games

**Comment by MendyBerger** [comment]
Resolved in ae94fb3dd
