### ISSUE TITLE
Sharing in the player - create a code causes a crash and signs you out of Jigzi

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2591]
Reported by one of our users, and I see that it is now happening to me. From the player, you create a code. You see the broken screen momentarily, and then you are logged out of Jigzi. Watch the movie:
https://www.dropbox.com/s/ll4znhbn4cv02w9/sharing%20code%20is%20crashing.mov?dl=0

**Comment by MendyBerger** [comment]
Looks like this is caused by a combination of different issues:

- Not only admin users should be allowed to generate code
- In cases where we do restrict to admin the proper return code would be 403 not 401
- In the frontend 403 should not be handled the same way as 401

**Comment by corinnewo** [comment]
Definitely teachers must be able to generate a code! Not just admin.

**Comment by MendyBerger** [comment]
@corinnewo can you please make sure that it works now?
