### ISSUE TITLE
signup-login - if you try to login with google with an email that is not yet signed up, should get a designed screen!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2601]
I tried to login with Google using one of the emails I have, and this is the screen I got:
![image](https://user-images.githubusercontent.com/16290361/160785412-06f40db9-885c-4612-bc02-786040c911c9.png)

Should rather be redirected to the signup screen, with the message that you do not have an account yet. 
See zeplin https://zpl.io/anv6wqk for the correct design.

**Comment by MendyBerger** [comment]
Resolved in 78c56fecc
