### ISSUE TITLE
Change password from profile - dialog does not close when you click SAVE

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2602]
I tried to change my password. Opened up MY PROFILE and clicked EDIT button to change my password. Filled in new password, and clicked SAVE button. Dialog does not close.

**Comment by corinnewo** [comment]
Also, clicking the button 'Forgot my password' in the dialog does nothing!
![image](https://user-images.githubusercontent.com/16290361/160802983-a6e42727-b603-41b5-a813-ba8767c9f083.png)

**Comment by MendyBerger** [comment]
Changing this to a reset password.
