### ISSUE TITLE
Login - message that an email sent when there is no email address!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2603]
I tried to reset my password on the login page, and clicked 'forgot my password' **before** I had put in an email address. This is what I see:
![image](https://user-images.githubusercontent.com/16290361/160803500-6316816c-4de3-4db0-81e5-7c3d03a2e99a.png)

How can we have a message that an email has been sent when there is NO email in the email field?

**Comment by corinnewo** [comment]
I then put in an email (nadav2@jewishinteractive.net) and actually received an email - but the firstname is not taken from the database... how do we make sure that the firstname is in the email?

![image](https://user-images.githubusercontent.com/16290361/160804528-680c7f0a-93db-48b3-a99f-36d639003622.png)

**Comment by corinnewo** [comment]
I went into sendgrid and read about setting up the 'handlebars' within emails to personalise the emails. Read about it here: https://docs.sendgrid.com/for-developers/sending-email/using-handlebars
I have replaced the "Hi [firstname]" with "Hi {{firstname}}" in the email, but it is blind as I do not know what is the variable name in the JSON with the email.  At least the mail is now coming through without the [firstname], but it is blank:
![image](https://user-images.githubusercontent.com/16290361/160814807-0d07567e-116e-418c-9e45-850f976143d4.png)

Please help me with the variable that should be there from the JSON file? Thanks!

**Comment by MendyBerger** [comment]
Moved the {firstName} issue to #2625 as it's not related to the original issue

**Comment by MendyBerger** [comment]
Resolved
