### ISSUE TITLE
Reset password - text needs editing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2604]
@ChaykeeMor This is the screen I get to when I click the reset button in the email to reset my password:
![image](https://user-images.githubusercontent.com/16290361/160804974-6b9859f2-bcac-4907-a0b8-abb34e556bde.png)

Please edit this, including adding an instruction that a password should be at least 6 characters.

**Comment by MendyBerger** [comment]
@corinnewo still applicable after the recent updates in sandbox?

**Comment by corinnewo** [comment]
@MendyBerger It is working much better now. But, please change the text "You will need to log in after this" to "You will need to log in again after changing your password."

**Comment by MendyBerger** [comment]
Resolved in 575b92d2d

**Comment by corinnewo** [comment]
As long as you are accepting passwords with weaker ratings!!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
