### ISSUE TITLE
Content/Search: Age does not appear as tagged in curation tool.

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2607]
The Jig below is tagged as suitable for pre-K - Kindergarten ages, but appears in the search as Pre-K - Pre-K, not sure why that is.
![Screen Shot 2022-03-30 at 2 07 06 PM](https://user-images.githubusercontent.com/78186896/160821152-a3f4d60d-2c89-4fc2-801e-b160cb8a6cfc.png)
![Screen Shot 2022-03-30 at 2 07 42 PM](https://user-images.githubusercontent.com/78186896/160821206-33e4879e-93a9-4699-bdb2-5e78f8b9451a.png)

**Comment by corinnewo** [comment]
@mastapegs Please look into this. It should show 'Pre-K - K'. I'm also wondering whether the dash should not be replaced by a '>', as there are so many dashes when there is a Pre-K. 
@GaliShapira - what do you think of replacing the - with a >, as in 'Pre-K > K', or 'K > Elem'

**Comment by GaliShapira** [comment]
Perhaps we can add from font awesome an arrow icon like one of these instead of the ">"? 
<img width="279" alt="Screen Shot 2022-03-30 at 16 07 39" src="https://user-images.githubusercontent.com/88834002/160841859-fa015316-1ba7-4f8e-a80d-2b2f1569991c.png">

**Comment by corinnewo** [comment]
@GaliShapira -perfect!

**Comment by corinnewo** [comment]
@johnnynotsolucky Please look into this. I assume it is a quick fix. I came across it again today with a JIG I created for the Ji Alef-Bet, and tagged it for Pre-K to K. We also asked that the dash showing the range would be an arrow instead.
![image](https://user-images.githubusercontent.com/16290361/168803085-5548a7db-11c7-45bb-a179-afe00bb51b32.png)

**Comment by chayaml** [comment]
I just came across a Jig that I curated as suitable for K, but showed up in the search as suitable for Pre-K, so something is not right! @corinnewo 
![Screen Shot 2022-05-18 at 2 25 26 PM](https://user-images.githubusercontent.com/78186896/169118516-ecd58a77-6145-436b-8af6-a382a22728ea.png)
![Screen Shot 2022-05-18 at 2 30 40 PM](https://user-images.githubusercontent.com/78186896/169118701-2741ab64-8207-4d35-9bf4-987588039566.png)
