### ISSUE TITLE
Jigzi Player: Puzzle pieces shrink/disappear when clicking on them

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2608]
On page 2, the dragging and dropping of pieces works, but if I tap or click on the puzzle piece, it shrinks in size or disappears... I have experienced this in several Jigs with puzzle activities.

Original:
![Screen Shot 2022-03-30 at 2 56 22 PM](https://user-images.githubusercontent.com/78186896/160830050-ea9afdab-9988-4f1c-a7e5-f177513dd298.png)
After Tapping:
![Screen Shot 2022-03-30 at 2 58 18 PM](https://user-images.githubusercontent.com/78186896/160829789-372530ea-0f48-4d8f-b4a2-fa9404599960.png)

https://jigzi.org/admin/curation/90090fde-69c6-11ec-a535-a73f43fbe83c

**Comment by corinnewo** [comment]
Link in Jigzi: https://jigzi.org/jig/play/90090fde-69c6-11ec-a535-a73f43fbe83c?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

**Comment by dakom** [comment]
game id is 14879
