### ISSUE TITLE
Card games - sizing on content tab

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2609]
When you create a card game on a laptop screen, the margins are really wide, and as a result you can only see one pair of cards on a row. Now that we have added on 'Add a pair', this is serious, as you do not see that 'add a pair' and might not know to scroll down.
The margins need to be much narrower, so that you can see 2 pairs on one screen.

![image](https://user-images.githubusercontent.com/16290361/160833652-1125e80b-25a3-4ac4-a3c4-08b9962165a1.png)

**Comment by MendyBerger** [comment]
Looks like you are zoomed in...
