### ISSUE TITLE
Auth bug when uploading images

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#261]
This might affect more services than just images, but anecdotally - when I try to upload an image, the service to create the database record succeeds, but the raw upload fails

The CreateRequest should fail as well when the user isn't authed with the required credentials

**Comment by mehcode** [comment]
#266 should have fixed this. @dakom are you still seeing the problem?

**Comment by dakom** [comment]
yep, seems to be fixed :)
