### ISSUE TITLE
Talking Poster -- move audio tab and add play settings tab

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2629]
'Talking Poster' should have the audio tab in Step 2 [Content] and not in Step 3. This tab functions like the cover audio playing with the screen and not the audio added to items that plays on click.

<img width="1410" alt="Screen Shot 2022-04-05 at 12 54 53" src="https://user-images.githubusercontent.com/94056434/161734909-87386300-de58-45ab-9b0c-cfcc8d538101.png">

<img width="1401" alt="Screen Shot 2022-04-05 at 13 23 36" src="https://user-images.githubusercontent.com/94056434/161735003-b65ff7e6-ba8d-4f1e-8a5b-d61344e0d8d0.png">

Step 3 is missing Play Settings tab: "Student finishes this activity..." with 2 buttons "automatically" "by clicking continue"

<img width="374" alt="Screen Shot 2022-04-05 at 13 26 32" src="https://user-images.githubusercontent.com/94056434/161735034-62cec266-d40a-4a09-99d3-485eabd5ed2b.png">

**Comment by corinnewo** [comment]
Closing as this contradicts the final settings for poster as per #3285
