### ISSUE TITLE
Make sure all 4 emails are sent at the right time

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2630]
In sendgrid, there are 4 different emails. Please check that all 4 are sent:
![image](https://user-images.githubusercontent.com/16290361/161802473-26e436b0-3858-4e8a-881f-ff9a75f9ff61.png)

I have not received the welcome email since October 21! Please check that at the end of registration, this welcome email gets sent.

**Comment by MendyBerger** [comment]
Verify Your Email: Working.

Password Reset: Working.

Update Your Email: Never implemented, opened #2638

Welcome to JIGZI: Never implemented, opened #2637

Confirm Email: Don't think it's needed
