### ISSUE TITLE
drag and drop - ability to define multiple target areas in the 'place' step of interaction

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2636]
We need the ability to define that an object might be correct in multiple trace areas. So we need to define multiple targets.
We spoke about dragging an object to the target, and leaving a ghost image behind, which can then be selected again (on mouseover it becomes a full image, which can be dragged again). Dragging the image out of a trace area will remove the target.

Waiting for @GaliShapira's zeplin reference with this!

**Comment by GaliShapira** [comment]
Hi @johnnynotsolucky @corinnewo 
Pls see this screen. 
Make the ghost 50%.
https://zpl.io/VKddQJq

<img width="592" alt="Screen Shot 2022-04-07 at 14 13 49" src="https://user-images.githubusercontent.com/88834002/162186800-628f7814-409e-46eb-893a-03e1b0f8d499.png">
