### ISSUE TITLE
Resources - edit cover - implement the theme tab for wizard step 1

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2642]
Resource cover still has the old tab with background, fill and overlay. Please implement the new Theme tab as it is for all the other units.

**Comment by corinnewo** [comment]
This would also be relevant for the course covers.

**Comment by corinnewo** [comment]
@MendyBerger Themes etc works well, but when you click continue to get to the preview, it is crashing. Also crashes when you click the preview button on top right.

I noticed that if you add a name and description when you create the resource, then go out to add a cover, when you come back to the publish dialog, the name and description are not there. You need to publish to save them before you create a cover.



index.js:1036 panicked at 'internal error: entered unreachable code', crates/components/src/player_popup/dom.rs:23:43

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/index.js:22028:21)
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[632]:0x1110c3
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[1634]:0x16b4be
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[1851]:0x174692
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[3691]:0x19b073
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[3162]:0x194219
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[3281]:0x195e75
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[2990]:0x1914f3
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[340]:0xaf1ea
    at https://frontend.sandbox.jicloud.org/module/resource-cover/edit/js/assets/app-resource-cover-edit-45e84dd4.wasm:wasm-function[1204]:0x15222e


imports.wbg.__wbg_error_09919627ac0992f5 @ index.js:1036
$func632 @ app-resource-cover-edit-45e84dd4.wasm:0x11118b
$func1634 @ app-resource-cover-edit-45e84dd4.wasm:0x16b4be
$func1851 @ app-resource-cover-edit-45e84dd4.wasm:0x174692
$func3691 @ app-resource-cover-edit-45e84dd4.wasm:0x19b073
$func3162 @ app-resource-cover-edit-45e84dd4.wasm:0x194219
$func3281 @ app-resource-cover-edit-45e84dd4.wasm:0x195e75
$func2990 @ app-resource-cover-edit-45e84dd4.wasm:0x1914f3
$func340 @ app-resource-cover-edit-45e84dd4.wasm:0xaf1ea
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func3637 @ app-resource-cover-edit-45e84dd4.wasm:0x19a6d6
$func2061 @ app-resource-cover-edit-45e84dd4.wasm:0x17bbf0
$func2962 @ app-resource-cover-edit-45e84dd4.wasm:0x190d31
$func1305 @ app-resource-cover-edit-45e84dd4.wasm:0x159153
$func2191 @ app-resource-cover-edit-45e84dd4.wasm:0x17f912
$func4778 @ app-resource-cover-edit-45e84dd4.wasm:0x1a268a
$func498 @ app-resource-cover-edit-45e84dd4.wasm:0xf1bd5
$_dyn_core__ops__function__FnMut___A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h8a8391259054d634 @ app-resource-cover-edit-45e84dd4.wasm:0x1959ae
__wbg_adapter_38 @ index.js:232
real @ index.js:208
firstUpdated @ preview.ts:53
performUpdate @ updating-element.js:572
_enqueueUpdate @ updating-element.js:508
await in _enqueueUpdate (async)
requestUpdateInternal @ updating-element.js:474
initialize @ updating-element.js:326
initialize @ lit-element.js:150
we @ updating-element.js:90
De @ lit-element.js:82
xt @ menu-items.ts:4
Ft @ preview.ts:5
(anonymous) @ index.js:1136
handleError @ index.js:288
imports.wbg.__wbg_createElement_86c152812a141a62 @ index.js:1134
$func2693 @ app-resource-cover-edit-45e84dd4.wasm:0x18b9bc
$func2796 @ app-resource-cover-edit-45e84dd4.wasm:0x18db29
$func2360 @ app-resource-cover-edit-45e84dd4.wasm:0x184074
$func247 @ app-resource-cover-edit-45e84dd4.wasm:0x5a390
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func3637 @ app-resource-cover-edit-45e84dd4.wasm:0x19a6d6
$func1704 @ app-resource-cover-edit-45e84dd4.wasm:0x16e7f9
$func3819 @ app-resource-cover-edit-45e84dd4.wasm:0x19c61f
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_8c2d62e8ae5978f7 @ index.js:1084
$func1434 @ app-resource-cover-edit-45e84dd4.wasm:0x160f2a
$func849 @ app-resource-cover-edit-45e84dd4.wasm:0x130ee1
$func287 @ app-resource-cover-edit-45e84dd4.wasm:0x86e25
$func235 @ app-resource-cover-edit-45e84dd4.wasm:0x474c3
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func3637 @ app-resource-cover-edit-45e84dd4.wasm:0x19a6d6
$func1704 @ app-resource-cover-edit-45e84dd4.wasm:0x16e7f9
$func3819 @ app-resource-cover-edit-45e84dd4.wasm:0x19c61f
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_8c2d62e8ae5978f7 @ index.js:1084
$func1434 @ app-resource-cover-edit-45e84dd4.wasm:0x160f2a
$func923 @ app-resource-cover-edit-45e84dd4.wasm:0x13902f
$func569 @ app-resource-cover-edit-45e84dd4.wasm:0x1040a4
$func287 @ app-resource-cover-edit-45e84dd4.wasm:0x86d0b
$func235 @ app-resource-cover-edit-45e84dd4.wasm:0x474c3
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func3637 @ app-resource-cover-edit-45e84dd4.wasm:0x19a6d6
$func1704 @ app-resource-cover-edit-45e84dd4.wasm:0x16e7f9
$func3819 @ app-resource-cover-edit-45e84dd4.wasm:0x19c61f
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_8c2d62e8ae5978f7 @ index.js:1084
$func1434 @ app-resource-cover-edit-45e84dd4.wasm:0x160f2a
$func849 @ app-resource-cover-edit-45e84dd4.wasm:0x130ee1
$func236 @ app-resource-cover-edit-45e84dd4.wasm:0x4830d
$func235 @ app-resource-cover-edit-45e84dd4.wasm:0x46a5e
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func3637 @ app-resource-cover-edit-45e84dd4.wasm:0x19a6d6
$func1704 @ app-resource-cover-edit-45e84dd4.wasm:0x16e7f9
$func3819 @ app-resource-cover-edit-45e84dd4.wasm:0x19c61f
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_8c2d62e8ae5978f7 @ index.js:1084
$func1434 @ app-resource-cover-edit-45e84dd4.wasm:0x160f2a
$func923 @ app-resource-cover-edit-45e84dd4.wasm:0x13902f
$func569 @ app-resource-cover-edit-45e84dd4.wasm:0x1040a4
$func236 @ app-resource-cover-edit-45e84dd4.wasm:0x481f1
$func235 @ app-resource-cover-edit-45e84dd4.wasm:0x46a5e
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func3637 @ app-resource-cover-edit-45e84dd4.wasm:0x19a6d6
$func1704 @ app-resource-cover-edit-45e84dd4.wasm:0x16e7f9
$func3819 @ app-resource-cover-edit-45e84dd4.wasm:0x19c61f
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_8c2d62e8ae5978f7 @ index.js:1084
$func1434 @ app-resource-cover-edit-45e84dd4.wasm:0x160f2a
$func849 @ app-resource-cover-edit-45e84dd4.wasm:0x130ee1
$func672 @ app-resource-cover-edit-45e84dd4.wasm:0x118191
$func302 @ app-resource-cover-edit-45e84dd4.wasm:0x94008
$func738 @ app-resource-cover-edit-45e84dd4.wasm:0x12267e
$func342 @ app-resource-cover-edit-45e84dd4.wasm:0xb09e5
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func3637 @ app-resource-cover-edit-45e84dd4.wasm:0x19a6d6
$func1704 @ app-resource-cover-edit-45e84dd4.wasm:0x16e7f9
$func3819 @ app-resource-cover-edit-45e84dd4.wasm:0x19c61f
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_8c2d62e8ae5978f7 @ index.js:1084
$func1434 @ app-resource-cover-edit-45e84dd4.wasm:0x160f2a
$func923 @ app-resource-cover-edit-45e84dd4.wasm:0x13902f
$func585 @ app-resource-cover-edit-45e84dd4.wasm:0x107a13
$func1444 @ app-resource-cover-edit-45e84dd4.wasm:0x16184c
$func302 @ app-resource-cover-edit-45e84dd4.wasm:0x93e9d
$func738 @ app-resource-cover-edit-45e84dd4.wasm:0x12267e
$func342 @ app-resource-cover-edit-45e84dd4.wasm:0xb09e5
$func1204 @ app-resource-cover-edit-45e84dd4.wasm:0x15222e
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h376db4c85e008dc3 @ app-resource-cover-edit-45e84dd4.wasm:0x19eff5
__wbg_adapter_41 @ index.js:239
real @ index.js:208
Promise.then (async)
imports.wbg.__wbg_then_2fcac196782070cc @ index.js:1088
$func1313 @ app-resource-cover-edit-45e84dd4.wasm:0x159a7e
$func1803 @ app-resource-cover-edit-45e84dd4.wasm:0x172993
$main_js @ app-resource-cover-edit-45e84dd4.wasm:0x19efb4
finalizeInit @ index.js:1291
init @ index.js:1320
await in init (async)
(anonymous) @ index.js:1321
(anonymous) @ index.js:1321
app-resource-cover-edit-45e84dd4.wasm:0x16b4e1 Uncaught (in promise) RuntimeError: unreachable
    at app-resource-cover-edit-45e84dd4.wasm:0x16b4e1
    at app-resource-cover-edit-45e84dd4.wasm:0x174692
    at app-resource-cover-edit-45e84dd4.wasm:0x19b073
    at app-resource-cover-edit-45e84dd4.wasm:0x194219
    at app-resource-cover-edit-45e84dd4.wasm:0x195e75
    at app-resource-cover-edit-45e84dd4.wasm:0x1914f3
    at app-resource-cover-edit-45e84dd4.wasm:0xaf1ea
    at app-resource-cover-edit-45e84dd4.wasm:0x15222e
    at app-resource-cover-edit-45e84dd4.wasm:0x19eff5
    at __wbg_adapter_41 (index.js:239:10)

**Comment by MendyBerger** [comment]
This has nothing to do with this issue.
It's because of the change to use the jig player for preview, and resources can't be previewed.
Don't know how I'll fix it yet

**Comment by corinnewo** [comment]
OK - so I will create a new ticket for this issue for you.
https://github.com/ji-devs/ji-cloud/issues/3338
