### ISSUE TITLE
2 ShalomLearning migrations - the Hebrew words don't show at all

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2643]
Just heard from ShalomLearning - there are 2 lessons where the Hebrew words are not showing at all throughout the lesson.

1. https://jitap.net/activities/gajs/2a-llh-het
2. https://jitap.net/activities/g9mv/2b-llh-words-beginning-with-het

Ji Tap: https://jitap.net/activities/gajs/play/2a-llh-het
![image](https://user-images.githubusercontent.com/16290361/162222343-e691a91b-eff5-4f28-800e-a8d60959094c.png)

Jigzi: https://jigzi.org/jig/play/89b3a2a4-69bf-11ec-976d-93c5425874e1?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

![image](https://user-images.githubusercontent.com/16290361/162222473-6908c2b4-2e76-4900-9737-2a9340910021.png)

**Comment by corinnewo** [comment]
Michele from ShalomLearning says that those Hebrew words were just typed in using the online editor on the online JiTap Create site.

**Comment by dakom** [comment]
game id is 12438
