### ISSUE TITLE
Ji Tap game - missing image - extra .jpg added to image name

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2647]
Ji Tap: https://jitap.net/activities/ga05/play/
![image](https://user-images.githubusercontent.com/16290361/162395253-aca52b12-7f52-4d4c-903c-c34265bd7c79.png)

Jigzi: https://jigzi.org/jig/play/e824a8bc-69d6-11ec-ab00-b7fe86ffecf9?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false 
No screen capture as it is a blank screen with a missing image icon

Seems like the image has an additional .jpg appended.

"album_embed_code": "<iframe  width='640' height='480' src='https://jitap.net/media/webplayer/webplayer.html?structureJson=https://jitap.net/store/api/album/11731/structure&v=3.4.2&emded=true' webkitallowfullscreen='' mozallowfullscreen='' allowfullscreen='' style='border:0'></iframe>",
"album_play_link": "https://jitap.net/activities/ga05/play/makot",
"album_share_image": "https://d24o39yp3ttic8.cloudfront.net/makot_AndroidGame_61a73327-84c5-437f-94ac-67d137c49a444686/shareImage.png",

**Comment by dakom** [comment]
game id: 11731
