### ISSUE TITLE
Add 'Share to Google Classroom' button 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2650]
API for sharing to Google classroom: https://developers.google.com/classroom/guides/sharebutton

We need to add this sharing to our list of share possibilities.

@GaliShapira Please mock up where this should be added: Is it in the list of Sharing options, or within the Share with Students popup?  I think it should be in the main list of Sharing Options. "Share to Google Classroom" with the icon. Their instructions for the button is on the link above (min size is 32 pixels).

**Comment by meravs** [comment]
Screen in zeplin:
https://zpl.io/aMynyPK
Screenshot:
![Screen Shot 2022-04-19 at 9 55 33](https://user-images.githubusercontent.com/96105053/163943858-054274dc-a868-4e48-979c-215f68827eec.png)

**Comment by corinnewo** [comment]
@johnnynotsolucky This is important to add in as soon as possible, as without it, we have been rejected as partner developers.
Thanks!

**Comment by GaliShapira** [comment]
@corinnewo @ChaykeeMor 
Do we have the helper texts for the different share options? 
We need to add the text for Google classroom as well.
<img width="672" alt="Screen Shot 2022-04-25 at 11 32 40" src="https://user-images.githubusercontent.com/88834002/165051554-ae833233-f305-496f-b33b-ca3635fe85c5.png">

**Comment by ChaykeeMor** [comment]
Location |  text currently | Should be
-- | -- | --
Button | 'share the JIG' | 'Share JIG' not 
Title | 'Want to share this JIG?' | 'Share this JIG'  
Option | Share with Students | Share with students
tooltip | Use this... | Share a code to play this JIG (no login required)
Option | Share to Google Classroom | NO CHANGE
tooltip | Use this... | Share this JIG in Google Classroom 
Option | Embed this JIG | NO CHANGE
tooltip | Use this... | Embed and play this JIG within another website
Option | Copy URL | NO CHANGE
tooltip | Use this... | Share a direct link to this JIG (login required)
--

**Comment by GaliShapira** [comment]
The texts are updated in the Zeplin.

**Comment by corinnewo** [comment]
Similar to #2710
