### ISSUE TITLE
Add SHARE link to the search results card

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2651]
Connected with #2258 
Add in the **Share** and **Edit** links to the cards in the search results. 
1. Share - opens up the same popup the opens up from within the player.
2. Edit (only visible if it is a JIG that I created) - opens the JIG up within the creator, ready to edit.

![image](https://user-images.githubusercontent.com/16290361/162749034-1e7275da-c87c-4f3e-9cba-736dd5584dbc.png)

**Comment by corinnewo** [comment]
@mastapegs Also, while you working on the search result cards, please change the - to > as per #2607, and fix up the age range.

**Comment by johnnynotsolucky** [comment]
@GaliShapira would you be able to send me the play button arrow for this task?

**Comment by GaliShapira** [comment]
@johnnynotsolucky 
See attached the icon. Pls make sure to have a hover color for the button as in the Zeplin.
![icn-play](https://user-images.githubusercontent.com/88834002/167394755-9001f9b5-9224-4df9-b67e-327970eb6d31.svg)
https://zpl.io/2jOl18r
<img width="331" alt="Screen Shot 2022-05-09 at 13 44 36" src="https://user-images.githubusercontent.com/88834002/167394762-156e93bf-0413-43d2-bb1f-ceb863499628.png">
