### ISSUE TITLE
Jigzi Registration/ reset password: text changes and typos

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2655]
![Screen Shot 2022-04-11 at 4 58 36 PM](https://user-images.githubusercontent.com/78186896/162771035-f54fb36c-7352-4558-b519-7928fcb3e335.png)

1) Change "Reset Password " to "Reset **your** Password"

2) Change check **you**  inbox to: Check **your** inbox.

3) Change "We **send** you a password reset link to your inbox if there's an account associated with this email address. Please make sure to check your spam folder if you can't find it "  to - 

 "If you have an account associated with this email address, a password reset link was sent to your inbox. If you don't see an email from us, please be sure to check your spam folder.

Corinne  - last sentence can also be: If you didn't receive an email from us, please check your spam folder.

**Comment by corinnewo** [comment]
Should be "Reset Your Password", all capitalized, as it is the heading.

**Comment by ChaykeeMor** [comment]
Change "Reset Password" to "Password Reset"

Change "check you inbox." to: "Check your inbox"

Change "We send you a password reset link to your inbox if there's an account associated with this email address. Please make sure to check your spam folder if you can't find it " to -

"If there is a Jigzi account associated with this email address, a password reset link has been sent to your inbox. If you don't see an email from us, please be sure to check your spam folder.

**Comment by MendyBerger** [comment]
Resolved in 575b92d2d
