### ISSUE TITLE
Email registration - wrong feedback appears first when password < 6 characters

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2664]
I put in a password of 5 characters. The feedback I got was “Password can’t be empty”, which does not make sense, as the password is not empty. I then cleared the password, and got another feedback “Your password should be at least 6 characters.” This is the only feedback that should appear.
![image](https://user-images.githubusercontent.com/16290361/163327557-d1cea76a-9bb0-4ca2-91f3-ede7fbe997e9.png)

After clearing the password to try again, I get this: (Feedback that should appear initially)
![image](https://user-images.githubusercontent.com/16290361/163327754-26b06d94-3de5-4c69-b3b3-9c9edd26f342.png)

**Comment by MendyBerger** [comment]
Resolved in 575b92d2d
