### ISSUE TITLE
MY PROFILE - Edit password - Correct the text message

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2666]
In MY PROFILE, after I click the button to edit my password, I get a message 'We just sen**d** you a reset password email!'
Please change to: 
'We just sent you a reset password email!'
![image](https://user-images.githubusercontent.com/16290361/163333763-98402a8c-2551-4fca-ba6b-fe1f2877d931.png)

**Comment by MendyBerger** [comment]
Resolved in 575b92d2d
