### ISSUE TITLE
Imported lesson - no sound on houdini words and video not playing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2669]
Jigzi Game: https://jigzi.org/jig/play/b449f2f6-b91b-11ec-916d-8fba8f342d51?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=true&draft=false

Ji ID: https://jitap.net/activities/gewl/play/   gewl

Module 17 - click on any word that ends on AY
Module 22 - clicking on any word should play the sound
Module 23 - video not playing

**Comment by dakom** [comment]
game id is 18083
