### ISSUE TITLE
2 Ji Tap games that have to be imported are not there

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2678]
Edward and I made a series of 5 vowel lessons for Ji Alef-Bet Vowels. 
3 have been imported, but 2 are missing (It is really important to have these in JIgzi as he paid for them!):
![image](https://user-images.githubusercontent.com/16290361/163796462-b13635b3-65b6-4cbc-9136-be006e67d543.png)

One dot, two jobs:
 https://jitap.net/activities/geqj/play/one-dot-two-jobs
 **ID: 17865**
Words ending in Av:
 https://jitap.net/activities/geqf/play/words-ending-in-av
 **ID: 17861**

**Comment by corinnewo** [comment]
actually, checking  in backend, curation shows these 2 JIGs, as visibly, but they are not being found in search..... @MendyBerger ?

**Comment by MendyBerger** [comment]
Can you give the ids of those two?

**Comment by corinnewo** [comment]
One Dot, Two Jobs: https://jigzi.org/admin/curation/c6143f1e-69d4-11ec-ab00-0f4361c4f738
Ending in Av: https://jigzi.org/admin/curation/32bef07c-69d1-11ec-8193-1387799ac1a0

**Comment by corinnewo** [comment]
@MendyBerger They are still not there -how do we set them to public?

**Comment by dakom** [comment]
Closing this issue as they are now public
