### ISSUE TITLE
Admin image upload - New images are not appearing in any search results

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2680]
Anat uploaded about 200 images yesterday, 6 words per Hebrew letter, all names 'Card Alef, Card Bet' etc. None of them are appearing in the search results.
I uploaded a test image and published - named it 'test kids', and it is also not findable.

Please look into this urgently. It is probably an indexing issue. Thanks!

Example card: 
![image](https://user-images.githubusercontent.com/16290361/163960477-d66b0b92-b668-4277-b255-262e02f31069.png)

**Comment by corinnewo** [comment]
Uploaded 2 test images, and the image count remains at 7893. Just uploaded an image 'test bytes'. Count did not increment.

**Comment by RickyLB** [comment]
Algolia index is out of date in Release. Once Sandbox is merged to Release, this should be fixed.

**Comment by RickyLB** [comment]
This is fixed in release now.
