### ISSUE TITLE
Sharing - the JIG link should differ for students and for teachers

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2682]
I had asked for the embed link to be changed (#2561) so that it embedded the version for students, without the JIG panel and ability to share. This was done. But in the meantime, I think that ALL links have been changed. Please make sure that the third link, "Copy JIG link" has 'student=false' and so when sharing with another teacher, there is the JIG panel.

![image](https://user-images.githubusercontent.com/16290361/165045465-ff6ece99-1e4f-4bce-810a-45e661a6523b.png)

**Comment by MendyBerger** [comment]
Resolved in 66116bfe7
