### ISSUE TITLE
Chat icon/ HubBot covers the pause button

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2685]
The chat option added to Jigzi's bottom right corner hides the pause button when a game is playing 

![Screen Shot 2022-04-26 at 3 23 13 PM](https://user-images.githubusercontent.com/78186896/165300181-8bb3ab8d-f228-4096-987c-b1fefe230554.png)

**Comment by corinnewo** [comment]
I thought it was only going to appear on the home page. If it appears everywhere, then I will remove it!

**Comment by corinnewo** [comment]
@chayaml I have gone in incognito, and I am not getting the chat - only on the home page. How did you get to this screen? Did you get the chat on the home page as well?

**Comment by chayaml** [comment]
@corinnewo In my regular Chrome browser, chat appears on the home page and also within games
