### ISSUE TITLE
Background music - mute should remain on mute from screen to screen!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2688]
when I go into a JIG and there is background music, if I want to turn it off, I mute. But then when I go to the next screen, the mute button is now on again, and I have to turn it off again.
Please make it that the state of the mute button remains from screen to screen. Example JIG: https://jigzi.org/jig/play/2923c356-69c4-11ec-8181-d75d28c699ba?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

![image](https://user-images.githubusercontent.com/16290361/165460058-ada62c78-daba-463b-b257-d4a0c18e7074.png)

**Comment by MendyBerger** [comment]
Resolved in ceff7e96b
