### ISSUE TITLE
Add tooltips to the text functions

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2709]
We are seeing in the user testing, that people do not know what DICTA is, and when they open it up, and there is a 'i' button, it is all in Hebrew! SO they think it is some sort of translator.

I think that the easiest way to help people would be to have tooltips on the buttons, not only explaining what they are, but briefly how to use them. We could also add in more text to the Jiggling on Text tab pages.

Suggest: (@ChaykeeMor please fix up!)

- on Sefaria button: Copy Hebrew or English Torah texts from Sefaria and paste them into your textbox.
- on DICTA button: Automatically add Hebrew vowels (nikud) easily to your Hebrew words: just start typing in Hebrew. Then copy the word into your textbox.
- on Hebrew keyboard icon: Add Hebrew text using our Hebrew keyboard: Open the keyboard, then click in the textbox where you want to type. Now, click the letters and vowels that you need.

![image](https://user-images.githubusercontent.com/16290361/166904580-2bcff4af-6456-4b14-8728-850207844e2e.png)

**Comment by ChaykeeMor** [comment]
Tooltips:
Sefaria: Find Torah texts in Hebrew or English. Copy and paste into your text box.
DICTA: Add Hebrew vowels (nikud) to any words you type. Copy and paste into your text box.
Hebrew keyboard icon: Use our Hebrew keyboard. Click to open, then select the text box where you want to add Hebrew, then select the letters to type.

**Comment by corinnewo** [comment]
@ChaykeeMor Thanks - I would like to suggest changing "Hebrew keyboard: Use our Hebrew keyboard. Click to open, then select the text box where you want to add Hebrew, then select the letters to type." 
to
"Hebrew keyboard: Use our Hebrew keyboard. Click to open, then click inside the text box where you want to add Hebrew. Then select the letters to type."

We have to make sure that they click inside the text box, and not just select it.

**Comment by ChaykeeMor** [comment]
@corinnewo updated. And dropped click to open as we don't say it in the other tools and it's implied when you roll over a button that the tooltip refers to the current click.

**Comment by corinnewo** [comment]
Final Tooltips:
Tooltips:
Sefaria: Find Torah texts in Hebrew or English. Copy and paste into your text box.
DICTA: Add Hebrew vowels (nikud) to any words you type. Copy and paste into your text box.
Hebrew keyboard: Use our Hebrew keyboard. Double click the text box where you want to add Hebrew, then select the letters to type.

**Comment by corinnewo** [comment]
CLosing in favor of #1730
