### ISSUE TITLE
Search shows empty pages

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#271]
Searched Chanukah...says 8 pages but images finish on page 7
![Screen Shot 2020-11-05 at 9 44 32 AM](https://user-images.githubusercontent.com/73904351/98255634-9bb0de00-1f4b-11eb-87c2-41c98b73931a.png)
@dakom

**Comment by dakom** [comment]
there were some other changes here too:

* back/next button
* sanity checks for invalid pages in input
* resetting to page 1 if it's a new query
* basing the page index at 1 instead of 0 (for display purposes)
