### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#2726]
```rust
struct BadgeId(uuid::Uuid);

struct Badge {
    id: BadgeId,
    display_name: String,
    description: String,
    members_count: u32,
    thumbnail: url::Url,
    created_by: UserId,
}
```

## APIs
Create
Update (can only be done by `created_by`)
Delete (can only be done by `created_by`)
Get
Join badge
Leave badge
Browse
Search
Browse badge members

**Comment by RickyLB** [comment]
@MendyBerger What fields should Browse Badge Members response contain for each member?

**Comment by MendyBerger** [comment]
Think `PublicUser` (https://github.com/ji-devs/ji-cloud/issues/2727)
