### ISSUE TITLE
Discrepancy in JIG counts on HOME page and CREATE page. Why?

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2729]
On the home page it says we have 13,510 JIGs
![image](https://user-images.githubusercontent.com/16290361/168028390-99997a11-d30d-4c11-8d51-a78b39d1ff47.png)

But on the CONTENT page, with no search parameters filled in, the total is 17251.
![image](https://user-images.githubusercontent.com/16290361/168028588-ab8b0293-e522-4d24-824b-9a9fe9c4f9d6.png)

Any idea why there is this discrepancy? Which stat is correct? I would like to have the same tally on both pages, otherwise we lose credibility.

**Comment by johnnynotsolucky** [comment]
@corinnewo it looks like we have 4646 JIGs which have a privacy level of `Unlisted`, and 13509 which are `Public`. 

The discrepancy appears to be because when we search on the content page, the endpoint is not filtering out unlisted and private JIGs.

Should the search endpoint be returning JIGs which aren't `Public`?

I think we can use the same Algolia query for the count endpoint without filters so that the counts match up. If we need to exclude non-public JIGs from search results, we should update that too.

**Comment by corinnewo** [comment]
As long as they match up! I think we should go for the higher count - much more impressive!

**Comment by johnnynotsolucky** [comment]
@corinnewo to keep the counts consistent we can switch the Algolia search for the home count. However, to go with the higher count would mean that non-public JIGs will be searchable from the content section. My assumption with `Unlisted` is that it shouldn't be included in search results. A comment from the definition in the source code: "Not indexed, but can be accessed by non-owners if the id is known. 'Private' in the front-end"

**Comment by corinnewo** [comment]
I don't understand - on the content page there are higher counts, so must be counting all JIGs, whether they are unlisted or hidden. They should not be in the search results anyway. How is this different from the home page? It should be the same search rules!
Private (unlisted) can be accessed if you have the link. Should never appear in search results, but could be counted.
Blocked - should never be able to be opened at all, except by the creator in order to edit/delete. (Not sure if we have any blocked like this). We do have the setting in curation to hide. 
What do you recommend regarding the counts? Whatever we do, we should have the same numbers on home and content pages!

**Comment by corinnewo** [comment]
I don't understand - on the content page there are higher counts, so must be counting all JIGs, whether they are unlisted or hidden. They should not be in the search results anyway. How is this different from the home page? It should be the same search rules!
Private (unlisted) can be accessed if you have the link. Should never appear in search results, but could be counted.
Blocked - should never be able to be opened at all, except by the creator in order to edit/delete. (Not sure if we have any blocked like this). We do have the setting in curation to hide. 
What do you recommend regarding the counts? Whatever we do, we should have the same numbers!
