### ISSUE TITLE
Rename database entries

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#273]
Age:
*  All ages
*  Kindergarden
*  Elementary
*  Middle school
*  High school
*  University

Jewish Streams:
*  Show me everything
*  No religious content
*  Reform/Liberal content
*  Conservative content
*  Orthodox content
*  Charedi content
*  Israeli secular content

**Comment by corinnewo** [comment]
Please correct 'Jewish secular content' to be 'Israeli secular content'

**Comment by dakom** [comment]
Ok - I made that change, lemme know if anything else before we commit it. Changing _labels_ is fairly easy - the main reason I'm holding back until absolute final approval is because adding/removing options might cause problems. In fact, for all I know, this could be the culprit in #264  (I doubt it since we also saw it with users who didn't tick any boxes, but still...)

**Comment by corinnewo** [comment]
Ages: 

- Please use 'Elementary school' to be consistent with the others.

- I think we should go with "Kindergarten" rather than "Kindergarden" - seems to be the correct term in US

Affiliations:

- Seems to be good. APPROVED!

**Comment by dakom** [comment]
just spoke to @izik1 - confirmed that we can edit the Db and it should automatically sync to Algolia :)

**Comment by dakom** [comment]
Pushed these updates though they may appear out of order, opened a new issue to track that: https://github.com/ji-devs/ji-cloud/issues/375
