### ISSUE TITLE
Listen and Learn - need a setting to keep all the clicked items highlighted or not

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2734]
We received feedback from a client, and I think it is very valid:
She wrote:  
For any of the ‘Listen and Learn’ activities, after you have clicked on a hot spot and listened to it, it remains highlighted.  For games with a lot of hotspots this can get very confusing.

I recommend that we add a setting where the default is off, where the teachers can decide whether clicked items remain highlighted or not.

@ChaykeeMor Please can you send wording for this setting? Thanks!

**Comment by ChaykeeMor** [comment]
Option 1:
keep previous and add another highlight option for after click.

<img width="477" alt="Screen Shot 2022-05-16 at 11 15 43" src="https://user-images.githubusercontent.com/94056434/168549085-df130445-fb2a-4c22-8de0-f2a25037cee8.png">

Option 2:
incorporate on the assumption that teachers will not care to highlight at start and remain highlighted after click. (in some ways simpler and cleaner than adding more options but would need another icon)

<img width="278" alt="Screen Shot 2022-05-16 at 11 19 24" src="https://user-images.githubusercontent.com/94056434/168549694-c90c5a35-6e7c-4925-9aae-5ec7bcda89a3.png">

@corinnewo @GaliShapira

**Comment by ChaykeeMor** [comment]
Hey, since we are addressing play settings-- Will we be adding this? @corinnewo

**Comment by corinnewo** [comment]
@GaliShapira @ChaykeeMor We forgot about this setting when we were going over everything this week! I do think it is an important setting! Can we go with Option 1, as I think it is very clear that one is before, and one is after clicking.

**Comment by ChaykeeMor** [comment]
I like option 1. @GaliShapira what do you think? How do you feel about duplicate buttons with 2 different prompts?

**Comment by GaliShapira** [comment]
I think it may be too much to have 2 lines for the highlights theme. 
I would try to make them in one line. 
Also I belive we can have multi-select of both highlights at the start and a highlight after the click. 
After click highlights - should be only what is still relevant to click (exclude whats have already clicked)

**Comment by ChaykeeMor** [comment]
What was suggested is highlights after click stay highlighted to indicate they e already been interacted with. Are you saying you want to do the opposite? In case of Option 2 with multi select--Have highlight at start keep clickable areas highlighted until clicked and then hide? There's something to that.. but it would need rewording and doesn't act the same way as other instances of 'highlight at start'. We might need to discuss options in person.

**Comment by corinnewo** [comment]
Let's discuss - I have added to the agenda for ideation.

**Comment by corinnewo** [comment]
**Decided at ideation:**

1. DO NOT NEED to keep clicked areas highlighted.
2. Change so that the highlight remains ONLY as long as there is audio on the box.
3. Will not be adding any extra settings. Just need to change the way the player works.

**Comment by corinnewo** [comment]
Closing in favor of https://github.com/ji-devs/ji-cloud/issues/3309
