### ISSUE TITLE
Theme image does not match the thumbnail

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2741]
Corinne to check the thumbnails and update from Shiri
![image](https://user-images.githubusercontent.com/16290361/168549530-1f7e2690-1598-4cbd-bf3a-45920bc8e9fb.png)

**Comment by corinnewo** [comment]
@GaliShapira Do you have the updated thumbnail for this theme? The back of the cards seem fine in the card games, but the image for the theme choice is misleading. We need to update the thumbnail in dropbox. Please can you attach the new Eng and Heb thumbnails ? Thakns

**Comment by GaliShapira** [comment]
Hi @corinnewo 
I updated the 2 thumbnails in the dropbox. I see on Jigzi that it works.

**Comment by corinnewo** [comment]
Great! Thanks. Closing
