### ISSUE TITLE
Jigzi/ legacy player: Games not playing/ loading

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2744]
Here are some examples of games that wont load/ play:

https://jigzi.org/admin/curation/29536932-69d6-11ec-8549-07c86b340cf4

https://jigzi.org/admin/curation/739beea6-69d6-11ec-b39d-83649aaceb93

https://jigzi.org/admin/curation/929b068c-69d3-11ec-a181-3fa10bceb473

https://jigzi.org/admin/curation/3231d7be-69d6-11ec-8233-87dc96df5aad

https://jigzi.org/admin/curation/2ac2c916-69d6-11ec-b39d-6fc62765e684

**Comment by corinnewo** [comment]
More that are not playing even though they are 'visible' in curation tool. These are for Ji Bytes, and all thumbnails are in the panel, but won't play. 

- https://jigzi.org/admin/curation/388c7bbc-69c9-11ec-98eb-ffd6ee817f73 Israel's Water Sources - (Ji Tap: gega) https://jitap.net/activities/gega/play/israels-water-sources
- https://jigzi.org/admin/curation/0ad654fa-69c8-11ec-98eb-8b2b4d96ca0e What's the Innovation  -  (Ji Tap: gegd) https://jitap.net/activities/gegd/play/whats-the-innovation
- https://jigzi.org/admin/curation/67079a68-69c3-11ec-8181-8711b04c3299 Good for Green - (Ji Tap: gegb) - https://jitap.net/activities/gegb/play/good-for-green

**Comment by corinnewo** [comment]
https://jigzi.org/admin/curation/3df635d4-69d3-11ec-8bed-8fc3ed0bbc4d -Tzadi Ji Alef-Bet Hebrew

**Comment by dakom** [comment]
Fixed, along with roughly 4000 other games (basically the difference in games between albums that came from Tiny Tap in the first iteration vs. the second)
