### ISSUE TITLE
Highlighting text in text box does not show size correctly on the text tab

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2753]
When adding text to the cover slide.....
If I add a text box....default text appears at a set size. In the text settings where you can change the size/style etc...the default text size is 16....this doesn't change when you highlight the text you are working on. If you press the + or - next to the size button the inserted text changes to size -14 or -15 which is much much smaller than the automatic size that is appears at.

**Comment by chayaml** [comment]
I think this is related to #2421

**Comment by MendyBerger** [comment]
Closing in favor of #2421
