### ISSUE TITLE
Player - sound button not playing background music and sometimes on top of the next arrow

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2754]
I received this feedback from a user:
On some games there is a musical note icon at the bottom right hand corner.
On the games that it does appear on:
1 - when i click on it, it shows the musical note crossed out but i can still hear the sound. if i try to click the musical note again it stays showing as crossed out (and has not affect on the sound).
2 - the icon appears partially covering the play icon (is on 100% view on Chrome, pc laptop desktop view)
On games in the Hebrew reading and iml series this icon does not appear - but on most of other games it does.

I have checked this out, and where the background music was playing a few weeks ago, now it is no longer playing, so the icon is not making sense! Also, on my laptop full size, the button is on top of the play, but on smaller sizes, it is placed correctly.
![Sound-button](https://user-images.githubusercontent.com/16290361/168811059-29a88d2d-aa8c-47a3-a3f8-76f500f1923d.jpg)

**Comment by MendyBerger** [comment]
Resolved in 181287210
