### ISSUE TITLE
Search results - list exact results first

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2755]
IN Algolia I have defined margin of error as 1 character. But we are getting irrelevant results listed high up and the exact searches lower down. Can we list exact results first (for both images and JIGs)? If not, then I will have to make the margin of error 0, which I am reluctant to because of the many non-english speakers using the platform.

Example
Search for דג (fish), but get results for דגל (flag) first. Should show all the fish first, and then the flags.

![image](https://user-images.githubusercontent.com/16290361/168848887-a73b5f25-f836-4f94-9973-69ff41c2dbbf.png)

**Comment by corinnewo** [comment]
@RickyLB Yes, please go ahead and do the translations of the names of images and JIGs.

But it still will not solve the issue of sorting, prioritizing the exact search result. By the way,  "דג" and "דגים" - one is the plural of fish. Both are fish in English. This is the important feat in this ticket! Thanks

**Comment by corinnewo** [comment]
@RickyLB Listing the EXACT results first is essential. Please look at this again. Also see examples in issue #

**Comment by RickyLB** [comment]
@corinnewo Merging a PR to Release which will fix a bug with image ordering. From there, Image results will match with what's being returns from algolia.
