### ISSUE TITLE
Player not playing at all on iPad Air

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2756]
Edward Gold (who paid for the Ji Alef-Bet) can't play the drill and practice game at all on his iPad. His config is:

Game he is trying to play is https://jigzi.org/jig/play/20d5296c-d5b5-11ec-861f-37a38be303b9?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft=false

Just gets blank screen with the player strip along the bottom (with the music button ON TOP OF HIS play button.

**Comment by MendyBerger** [comment]
Can this ipad still be updated? IOS 12.5 is practically ancient nowadays

**Comment by corinnewo** [comment]
Edward said he kept his ipad updated.... so it probably cannot be updated to iOS 15...

**Comment by corinnewo** [comment]
Edward has verified that his iPad cannot be upgraded - his is more than 8 years old!
So I will close this ticket...

**Comment by MendyBerger** [comment]
Deleting this
