### ISSUE TITLE
matching: on smaller screens the bottom row is covered by the player bar

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2757]
Please raise the bottom row of the matching so that they are not covered by the player bar. On iPad, it looks like this:
![IMG_6980](https://user-images.githubusercontent.com/16290361/168855724-a39ef479-b911-4e57-9804-476de3a695bb.PNG)

Please raise the lower row so that they are not covered by the player. (also not the stretched close button and overlapping music)

**Comment by johnnynotsolucky** [comment]
Resolved in 7463cdbfdf1dcec38fad4e67d40f3bb80b2eb025
