### ISSUE TITLE
smaller screens and iPad: Music button overlaps the forward arrow, so can't proceed!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2761]
On iPad and on smaller laptop screens, the music button overlaps the next arrow, so you cannot get to the next screen at all.
Please move the music button to the right! On phones it is placed correctly.

![IMG_6979](https://user-images.githubusercontent.com/16290361/169036865-f876b23c-4d57-4066-b517-2a12d4db4749.jpg)

**Comment by corinnewo** [comment]
I've made this critical as user cannot play the JIG at all if there is a music button! Show stopper!

**Comment by MendyBerger** [comment]
Resolved in 1dbba5fad
