### ISSUE TITLE
Image display order -  when there is no search in place

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2762]
There is still a problem with the default order of the images when you are creating a JIG. If you go into images and there is no search in place, the order needs to be better. I am still getting the salads first. When we have the tagging programmed, this may not be relevant, but at the moment, the order is strange. Were you not randomising at one stage, so that each time you went in, the order would be different? If we are not going according to most popular (#1895), then we need to make sure that this order has more logic/variety. It seems to be the same order for me every time I go into the images.

Happy to discuss!

![image](https://user-images.githubusercontent.com/16290361/169051207-2319df3c-3ea3-4d6c-886d-38f4834d8045.png)

**Comment by RickyLB** [comment]
@MendyBerger @corinnewo Did we come to a decision on ranking images based off of most popular?

**Comment by corinnewo** [comment]
I think that the most popular would be the best way to go!

**Comment by RickyLB** [comment]
@MendyBerger @corinnewo I'll proceed with adding an endpoint that records the amount of times an image is used to the backend.
