### ISSUE TITLE
Menu on images in creation - add in layer management

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2769]
A very desperate cry from our users in the field - please add in the option to **Send to back** and **Bring to front**.
Please add in the two extra items to the image menu:
Send to back _(sends to the furthermost layer)_
Send backwards _(sends to the next layer backwards)_
Bring to front _(sends to the topmost layer)_
Bring forwards _(sends to the next layer towards the top)_

![image](https://user-images.githubusercontent.com/16290361/169242967-ca4a95ac-e21c-4ee7-86c6-d74cb4d4f0f0.png)

Also, please space out the options according to ticket #2694

**Comment by johnnynotsolucky** [comment]
@corinnewo @GaliShapira are there icons for the two new menu options?

**Comment by corinnewo** [comment]
@GaliShapira Please add in the link to Zeplin. @johnnynotsolucky Please use a temporary icon and we will replace after our ideation meeting! Thanks

**Comment by GaliShapira** [comment]
@johnnynotsolucky 
Pls see the icons in regular and hover states

![Icn_SendToBack_hover](https://user-images.githubusercontent.com/88834002/183897369-10abfa9a-3c4a-4e3d-9ac5-3792607c113a.svg)
![Icn_MoveToFront_hover](https://user-images.githubusercontent.com/88834002/183897359-3862369b-f332-4ba3-9a8c-23892b80ad0e.svg)
![Icn_MoveToFront](https://user-images.githubusercontent.com/88834002/183897363-4f6f387e-e19e-44f3-8ae2-bb9f10d181c3.svg)
![Icn_SendToBack](https://user-images.githubusercontent.com/88834002/183897365-4cf4885e-3ebf-458b-b8b6-57a7a8521d28.svg)

**Comment by corinnewo** [comment]
@johnnynotsolucky Please remember to come back to this - here are the icons ready for you!

**Comment by ChaykeeMor** [comment]
<img width="655" alt="Screenshot 2022-11-07 at 9 09 32" src="https://user-images.githubusercontent.com/94056434/200331596-73e0fee6-c8df-407d-95b9-7b63fed215c8.png">
@corinnewo Should be no 'S' in move backward or forward.
