### ISSUE TITLE
Text for resources in Publish AND uploading resources without JIG

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2804]
While editing a new flow realized this old text was never input correctly. So this is to match.

<img width="1416" alt="Screen Shot 2022-05-30 at 15 18 32" src="https://user-images.githubusercontent.com/94056434/171121936-c970e954-5aa5-454c-ada5-5c0b4c035f69.png">

<img width="1438" alt="Screen Shot 2022-05-30 at 15 18 41" src="https://user-images.githubusercontent.com/94056434/171121915-33811e97-35e7-4502-ade3-2947ef1f841f.png">

Title: Add link
Field title: none
Field: Insert URL here

**Comment by MendyBerger** [comment]
Resolved 2b1326678
