### ISSUE TITLE
Cards print version

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2809]
We created 2 PDF print versions for the cards.
The cards content will be placed on white, 12 cards on a page (A4 or letter size).
The themes will not be taken, only the fonts in black color. 

1. Each card is separate - to use in Memory game, Matching, Quiz game
Zeplin link:
https://zpl.io/406lGdy
<img width="591" alt="Screen Shot 2022-06-07 at 16 02 42" src="https://user-images.githubusercontent.com/88834002/172386457-3fce0e7b-9b70-4363-936c-696f43fe89a7.png">

2. Folding line to print a card with an info on both sides - to use in Flashcards
Zeplin link:
https://zpl.io/Am6EK5B
<img width="593" alt="Screen Shot 2022-06-07 at 16 04 49" src="https://user-images.githubusercontent.com/88834002/172386839-20a10033-f619-45eb-ad93-8ad1db66d72a.png">

**Comment by corinnewo** [comment]
@GaliShapira how do we get to print these cards? From the end of the preview? Please add in the trigger.

Anat would really like this done before the conference in Argentina on 17 July.

**Comment by corinnewo** [comment]
@MendyBerger The label for the icon should be "Print cards" and not "Print the cards". The icon must be added to the current version of the DONE screen (which includes the publish)

**Comment by MendyBerger** [comment]
Done
