### ISSUE TITLE
IMAGE SEARCH - still have a problem with the exact search results NOT appearing first

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2811]
We discussed that the exact match would appear first, and then the 'fuzzy' ones.
I just searched for 'ball', and all the balloons come up first, before any balls. In this case, all the balls should appear first, and then balloons, as the word 'ball' is contained within the word 'Balloon'.
![image](https://user-images.githubusercontent.com/16290361/172611071-7d1bbe5d-caf3-4478-a20d-2d1d4be9fd86.png)

Another strange example of this is searching for a (computer) mouse: It seems like all the images that could be 'Moses' or 'Moshe' appear way before you get the exact match.
![image](https://user-images.githubusercontent.com/16290361/172611363-358ec083-57c2-428f-ad02-d58d8e7dcb10.png)

We have to get this right, as it happens with every search - you get these really illogical results first.

**Comment by RickyLB** [comment]
@corinnewo I managed to sort out the ordering of the pictures where the images with explicit word "ball" within the name or description showed up at the top. When I tried to sort everything by alphabetical order it worked fine for inputs, but with no input this would yield a result where all image names are in alphabetical order so I took that out. Let me know if you have any questions or concerns about the change.

![Screen Shot 2022-06-09 at 4 13 38 PM](https://user-images.githubusercontent.com/76449893/172961003-6b7c67f6-097a-4a14-9980-fccfc80670e3.png)
