### ISSUE TITLE
Deleted a resource, but it is still in the count

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2825]
I duplicated a resource in error, so I deleted it. The count is showing 4 resources, but the result lists only 3:
![image](https://user-images.githubusercontent.com/16290361/173383004-380caa83-29a5-44f4-abb9-cc464741f0a4.png)

![image](https://user-images.githubusercontent.com/16290361/173383116-53aabc3a-ead4-4272-9904-ddaaff27b449.png)

**Comment by MendyBerger** [comment]
@RickyLB any idea why it would not have been deleted from Algolia? Does it make sense to add an integration test that checks for this?

**Comment by RickyLB** [comment]
Yeah, we can do that. I'll set up a testing index in Algolia.
