### ISSUE TITLE
Please check why duplicating a published JIG results in a second published JIG - copy should be draft

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2827]
I duplicated my drill-and-practice Alef-Bet JIG twice, as I wanted to make variations of it. Without making any changes or re-publishing, all 3 appeared in the search results on Jigzi.
Please make sure that a published JIG that is duplicated makes the copy a draft.

**Comment by MendyBerger** [comment]
Closing in favor of #2833
