### ISSUE TITLE
Alert before delete - activity in JIG

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2830]
We learned from teachers that the actual buttons dont work well, they click on the main button without read and think they have deleted the activity. Its important because teachers cant publish once they havent deleted the empty activities on a JIG.

Pls see the changes I made:
1. Primary button is with a trash icon and the words "Yes, Delete", color red, on the right side.
2. Secondary button "Don't delete" white with orange outline on the right.
3. Pls see the colors of the buttons including the hover states. The primary button is an alert button and the color is different than the usual buttons.

Pls use the same logic for all alerts before delete in the platform.

Zeplin: https://zpl.io/bL91KQD
Trash icon svg attached: 
![icn-delete-white](https://user-images.githubusercontent.com/88834002/173542836-2bd88712-6ae5-4cd0-b44d-ac53e802b49e.svg)

Screenshots:
<img width="546" alt="Screen Shot 2022-06-14 at 12 14 28" src="https://user-images.githubusercontent.com/88834002/173542882-9aec5944-ba01-465f-90d1-09ba73072db5.png">
<img width="715" alt="Screen Shot 2022-06-14 at 12 14 33" src="https://user-images.githubusercontent.com/88834002/173542933-6e78ad9f-c54f-44ca-ada6-429766545ea0.png">

**Comment by ChaykeeMor** [comment]
_Text should be:._
**Are you sure you want to delete this activity?**
_add line:_ **Deleting in Jigzi is permanent and cannot be undone.**
_instead of 'Yes, Delete' button:_ **'Delete forever'**

_and this is for activity but should also be replicated for:_
**Are you sure you want to delete this JIG? Deleting in Jigzi is permanent and cannot be undone.
Are you sure you want to delete this resource? Deleting in Jigzi is permanent and cannot be undone.**

**Comment by corinnewo** [comment]
@ChaykeeMor - please finalise these texts for JIG, resource, and course. Thanks!
