### ISSUE TITLE
Images added recently do not have any translations in Algolia and are not being found

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2846]
Anat added over 300 images yesterday - all to do with numbers. When you search for them, nothing is coming up.
I went into Algolia, and it seems like the translations for the names and descriptions are empty. Here is an example looking for items with 'zero':
![image](https://user-images.githubusercontent.com/16290361/174279249-caa3b166-b0d9-4817-87e0-fa7edbb79ae6.png)

Tyrone has made ticket #2845 to try and find what is going on.
Please can you look into this urgently?
Thanks!

**Comment by RickyLB** [comment]
@corinnewo @johnnynotsolucky I turned it off yesterday when investigating some words that were attempting to repeat translations. I turned it back on and the images are translated now. These images now have `translated_names`. I have yet to incorporate name translations for the newer assets like courses and badges.
