### ISSUE TITLE
Publish page: closing the hebrew keyboard 

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#2849]
When I use the Hebrew keyboard and then click onto another tab, the unrelated keyboard remains open. Suggestion: The unrelated keyboard should close automatically when a different tab is clicked
![Screen Shot 2022-06-20 at 11 19 27 AM](https://user-images.githubusercontent.com/78186896/174558135-b639ae83-771a-496b-9be7-759ed28dcb1d.png)

**Comment by MendyBerger** [comment]
Resolved
