### ISSUE TITLE
Curation - add in 2 sort options: one according to publish date, the other according to creation date

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2852]
Curation - difficult for Anat to see the JIGs that have just been created and she wants to look at them and curate. If Ji Tap games have been curated and re-published, they appear first, and she can’t find the new JIGs. 
Requests that we add ability to sort in 2 ways:
- According to publish date - most recently published JIGs first
- According to creation date - most recently created JIGs first

**Comment by corinnewo** [comment]
@johnnynotsolucky Please implement this now on the frontend. Thanks!
User can choose how they want to see the JIGs - pulldown?

- According to publish date - most recently published JIGs first
- According to creation date - most recently created JIGs first

**Comment by johnnynotsolucky** [comment]
@corinnewo we don't include the date the JIG was created in the data sent from the backend, only the date it was last published. I can add it, but it'll take a bit of time to do. 

In the mean time, I'm going to rename the current date column to "Last published"

**Comment by corinnewo** [comment]
Thanks. At least we'll know what date that is!
