### ISSUE TITLE
Resource - tried to edit the language - but won't publish again

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2855]
Even though all fields filled in, the publish button is not active. Can't change language from Hebrew to English.
![image](https://user-images.githubusercontent.com/16290361/174849835-97cb93a1-6a30-4a39-9d41-72d73eaa22d8.png)

**Comment by MendyBerger** [comment]
Resolved in 84aee66d1baa81016ea75d5a29a6f486c7d19a7c
