### ISSUE TITLE
Force login/sign up before ability to share, play or create

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2864]
- Have had more than 10,000 visitors to site, but only 250 signups
- Gali to design forcing login before you are able to play/share a JIG. 
- Can search without login
- To play a JIG, Share, Create - must be forced to login - emphasise that it is free

@GaliShapira to attach her initial design for 'Time to sign up'.
@ChaykeeMor to edit the copy

**Comment by GaliShapira** [comment]
@ChaykeeMor 
This is the design.
Can you have a look at the texts and update them?
Its really urgent.

https://zpl.io/2yoQWOy

![Uploading Screen Shot 2022-06-27 at 15.43.20.png…]()

**Comment by ChaykeeMor** [comment]
Texts on Zeplin. check them out @GaliShapira @corinnewo

**Comment by ChaykeeMor** [comment]
Now that I'm looking at it... There's so much Jigzi...they know where they are.. @GaliShapira should we drop 'Go Jigzi!' and just say 'What are you waiting for?' and should we say 'Create an account, it's free!'

**Comment by corinnewo** [comment]
@ChaykeeMor We should have one 'Jigzi' mention...

**Comment by GaliShapira** [comment]
Texts are updated in the design above

**Comment by MendyBerger** [comment]
Closing as no longer needed
