### ISSUE TITLE
Create a JIG - collapsed panel - clicking on the head should open the panel

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2866]
In usability test, I watched the user click on the head of the jig to open the side panel, as it does in the player, It did nothing. Please make the head of the jig clickable as well as all areas where no other links - to open up the panel, as well as the little arrow.

![image](https://user-images.githubusercontent.com/16290361/175312577-441b42ab-de0d-4d29-8c56-7124cd4a19fb.png)

**Comment by corinnewo** [comment]
Also, from the user testing, many people clicked the JIG 'logo' by mistake because it is close to the arrow. We would like to take the blue letters 'Jig'  out of the collapsed panel, and only when the panel opens up, you see the full  Jigzi logo, which will take you back to the home page if clicked.

**Comment by MendyBerger** [comment]
Resolved in 521c2befc
