### ISSUE TITLE
'Find the answer' activity in sandbox

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2884]
This activity lookin so good and I may have looked at this (on sandbox) prematurely but I noticed a few things:

Activity should be called "Answer This"

<img width="311" alt="Screen Shot 2022-07-04 at 11 00 37" src="https://user-images.githubusercontent.com/94056434/177109830-6110d957-a183-4180-93c3-b9d1858dfd50.png">

And I believe this is the wrong image...should be showing a selection and all this text should be just text and only add a question button (at the bottom) should add a question. no? 
<img width="375" alt="Screen Shot 2022-07-04 at 11 11 33" src="https://user-images.githubusercontent.com/94056434/177111589-ba6a350f-4a86-48c8-bdbf-30b16eeea2a8.png">

And this warning should follow the same structure as our other delete warnings #2830 
<img width="485" alt="Screen Shot 2022-07-04 at 11 06 02" src="https://user-images.githubusercontent.com/94056434/177110555-f0231e31-2eef-4528-8f56-9405c015a90b.png">

**Comment by ChaykeeMor** [comment]
@corinnewo My point exactly. It is misleading. There is no tracing happening here. The user is supposed to select the question on the page.

**Comment by johnnynotsolucky** [comment]
@ChaykeeMor @corinnewo sorry for only seeing this now.

The empty area on Answer It will be overhauled in https://github.com/ji-devs/ji-cloud/issues/2923. 

With regards to the confirm modals, the changes in https://github.com/ji-devs/ji-cloud/issues/2830 will be done for all delete modals across the entire app.
