### ISSUE TITLE
Courses: close button in player should take you back to the course list, not close the course

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2899]
Closing the player of one of the JIGs in the course should take you back to the course list, not close the course.

There are 2 buttons one on the other in the player. Should be only 1, and it should close the player and take you back to the course list.
![image](https://user-images.githubusercontent.com/16290361/178305065-4a93bc2d-54f3-4c3c-b216-e8ec02fbe2fa.png)

**Comment by MendyBerger** [comment]
Resolved in f786a61b0
