### ISSUE TITLE
Ipad - Search results - Share with students - UI margins between elements

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2903]
Margins are missing from the original design.

1. Add a margin between the icon to text on the blue icon.
2. Add a margin between Go to site to the line to the Copy URL 

![IMG_0293](https://user-images.githubusercontent.com/88834002/178465526-81063589-5010-4a44-9db7-f8cc7f093c1e.PNG)

**Comment by corinnewo** [comment]
On PC this spacing is good. So it seems to be only on iPad

**Comment by corinnewo** [comment]
Seems to be OK on my iPad today
