### ISSUE TITLE
Ipad - Homepage - Margin is missing between the video to the creator text on the right

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2905]
1. Margin is missing between the video to the creator text on the right
2. I would add a bit vertical space above "Series created by JI"

![IMG_0295](https://user-images.githubusercontent.com/88834002/178467174-24952577-edf1-4a77-9007-56a8b6a35941.PNG)

**Comment by corinnewo** [comment]
changed the sliders in wordpress
