### ISSUE TITLE
Ipad - footer doesnt fit width

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2906]
1. Pls reduce a bit margins so all the right section fits.
2. Social media icons are overlapping. 

![IMG_0297](https://user-images.githubusercontent.com/88834002/178467660-3a6593d6-2987-458f-bfab-3eb7360e7026.PNG)

**Comment by corinnewo** [comment]
@GaliShapira If you look at (https://www.jewishinteractive.org/) on the iPad, you will see that wordpress automatically splits up the columns to 2 rows. Should we do the same thing? On iPad, we could put the section ABOUT US onto a new row. What do you think?

**Comment by GaliShapira** [comment]
We can have the About us below the Jewish interactive if this is the fastest way to solve it.
