### ISSUE TITLE
Ipad - My settings page - need to be responsive

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2907]
Left panel need to be narrow, so it keep the proportions of the original design. 
All fields of the left panel need to fit.
Do you need my design for it? or to have me online with you when working on it?

![IMG_0298](https://user-images.githubusercontent.com/88834002/178468094-45ebe6f2-8a5e-4d8d-9f22-810aeb810a45.PNG)

**Comment by corinnewo** [comment]
This is still happening, and needs to fit! Users will not know to scroll across to the right to see the edit buttons.

**Comment by MendyBerger** [comment]
Resolved
