### ISSUE TITLE
Ipad - settings page - filters popup - checks are not our designed components - UI comment

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2908]
![IMG_0300](https://user-images.githubusercontent.com/88834002/178469694-cacd6189-9bc8-40fa-bb5b-c13c491cb880.PNG)
![IMG_0301](https://user-images.githubusercontent.com/88834002/178469711-2386cd7a-ed4a-4279-82f6-10c78f046325.PNG)

**Comment by corinnewo** [comment]
On my ipad today, it looks fine.
