### ISSUE TITLE
Ipad - Activities menu

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2909]
Pls make the jig panel smaller and show the activities with margins between them.
Also the icons of settings on the JIG panel needs margins.
Do you need a design from me? or need me to be with you when working on it?

![IMG_0303](https://user-images.githubusercontent.com/88834002/178470124-e2200cad-07c4-46c5-a925-d08617d826ac.PNG)

**Comment by corinnewo** [comment]
I think that you don't need to make a design - when dev is working on this, they can call you if needed to approve.

**Comment by corinnewo** [comment]
It's still problematic - now only one column - must be able to see at least 2 activities across. 
<img width="1024" alt="File 2022-11-07, 12 49 11" src="https://user-images.githubusercontent.com/16290361/200292347-aa3cf9c7-dcd2-4966-a61b-d7ade8f129a9.png">
