### ISSUE TITLE
Icons at end of JIG - need to add words to them

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2911]
Try and change the icons to include the words, as people do not understand what they mean. If the icon includes the word then we can simply change them in the dropbox folder.

![image](https://user-images.githubusercontent.com/16290361/178503355-ef2e3b2d-75ff-4a5e-8337-8e131219644b.png)

@ChaykeeMor What are the words? Should they be **Replay | Share | Exit JIG**

**Comment by ChaykeeMor** [comment]
Replay/Share/Exit seems clear to me. Why are they 3 different sizes? That's not how Gali designed it.

**Comment by MendyBerger** [comment]
@corinnewo what do you want me to do here?

**Comment by corinnewo** [comment]
@MendyBerger Add the words Replay/Share/Exit underneath the icons. We had wanted to simply add to the icon, but could not. So we need it in programming. Example: https://zpl.io/VYDrlWe

**Comment by GaliShapira** [comment]
Hi @MendyBerger @corinnewo 
Can I ask to change the sizes of the icons to a smaller version as attached?

https://zpl.io/an3eeAA

<img width="489" alt="Screen Shot 2022-08-16 at 12 58 09" src="https://user-images.githubusercontent.com/88834002/184852471-24566294-3b7b-4c0f-8c91-68b369f52b44.png">
<img width="352" alt="Screen Shot 2022-08-16 at 12 56 22" src="https://user-images.githubusercontent.com/88834002/184852490-ff3e1749-431d-4023-925b-25d97ccab25f.png">

Icons:
![icon-replay](https://user-images.githubusercontent.com/88834002/184854155-9c1c0f48-473e-45f3-8af8-2a710da7cd07.svg)
![icon-share](https://user-images.githubusercontent.com/88834002/184854160-70bb711b-db76-4d23-97a0-f433f1c241dc.svg)
![icon-exit](https://user-images.githubusercontent.com/88834002/184854163-3e58b11b-cf44-4c82-8637-b6868f04d6c6.svg)

**Comment by MendyBerger** [comment]
@GaliShapira It would be a lot easier to make the icon look good if I can use font awesome icons, can I use these icons?

https://fontawesome.com/icons/rotate-left?s=solid
https://fontawesome.com/icons/share-nodes?s=solid
https://fontawesome.com/icons/arrow-right-from-bracket

**Comment by MendyBerger** [comment]
@GaliShapira should I make the other larger buttons (play/pause/background-music etc.) smaller as well?

**Comment by MendyBerger** [comment]
Resolved
