### ISSUE TITLE
Ipad - preview mode - resizing

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2917]
Resizing problems
We need to make the text: "Your work is auto..." in 2 lines and place it all between the button to the wizard.
The done button, needs to have margin from right side to the edge of the page.

![IMG_0316](https://user-images.githubusercontent.com/88834002/178526360-51775f36-4588-46f6-9ba8-31264a4d4ec3.PNG)

**Comment by corinnewo** [comment]
No longer applies as we have redone the preview.
