### ISSUE TITLE
Ask a question - change the select/add a question instruction

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2923]
Hi @johnnynotsolucky 
I would like to make it more clear by designing this step as in this screenshot.
Its a sketch, I will upload the final version later on.
<img width="279" alt="Screen Shot 2022-07-13 at 11 47 44" src="https://user-images.githubusercontent.com/88834002/178692047-970a72f9-ec7a-47d8-8427-2f9819401f07.png">

**Comment by meravs** [comment]
link to zeplin:
https://zpl.io/r1yj7q3

screen shot:
![Screen Shot 2022-07-14 at 10 46 11](https://user-images.githubusercontent.com/96105053/178930082-483e7afc-abfb-4b8d-98b9-372609d0b562.png)

Icon / illustration:
![Add a question](https://user-images.githubusercontent.com/96105053/178930260-63f5988a-1d54-4b3f-8bf2-dd98fcbdebd5.svg)
![Select the question](https://user-images.githubusercontent.com/96105053/178930267-6dbe571e-9cba-41ae-957c-bc33f7de84dd.svg)
