### ISSUE TITLE
Share to Microsoft Teams - add to the Share dialog

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2926]
@GaliShapira to design the button to add to the dialog.

Relevant links that I found with the button and how to add it to a website:

- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps
- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps#share-to-teams-for-education  
- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-web-apps#embed-a-share-to-teams-button

**Comment by meravs** [comment]
Links to zeplin:
https://zpl.io/aMynyPK
https://zpl.io/a8qpG34

screen shot:
![Screen Shot 2022-07-14 at 10 52 33](https://user-images.githubusercontent.com/96105053/178930971-8c96d19b-0d60-435a-9502-f8abca4f3987.png)
![Screen Shot 2022-07-14 at 10 52 19](https://user-images.githubusercontent.com/96105053/178930980-db14858b-3be0-404c-8d89-9305acd6e648.png)

Logo png:
<img width="25" alt="share-to-teams-icon" src="https://user-images.githubusercontent.com/96105053/178931067-ccfe7ed4-a1a2-4635-8d78-0bb0132e093b.png">

**Comment by corinnewo** [comment]
@johnnynotsolucky You did the share to google classroom, which in the end was very easy. I am hoping that sharing to Microsoft Teams will be as easy! I have given you the pages I found for sharing to Teams. If you can fit it in, inbetween everything else, that would have huge value! Thanks

**Comment by corinnewo** [comment]
@johnnynotsolucky You did the share to google classroom, which in the end was very easy. I am hoping that sharing to Microsoft Teams will be as easy! I have given you the pages I found for sharing to Teams. If you can fit it in, inbetween everything else, that would have huge value! Thanks
