### ISSUE TITLE
Course description - should allow for page breaks

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2930]
When putting in the description for a course, I would like to be able to break into paragraphs. For example, in the description field I made 3 paragraphs here, but it came out in one long paragraph. Can we add in line breaks?

![image](https://user-images.githubusercontent.com/16290361/178954973-c376d937-1bb7-4e92-9168-8600434b1311.png)

**Comment by MendyBerger** [comment]
Is this specific to courses? What about jigs?
