### ISSUE TITLE
Courses - Thumbnail not updating if it was built after the first publish

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2933]
As you can see in the 2 courses I have built so far, the first one, with SHALOM cover is because I went back and edited from the publish dialog AFTER i had published once. The one that has the image is the image I put in from the dialog window BEFORE I published once. Not sure if that is the reason, but it is the only difference.

![image](https://user-images.githubusercontent.com/16290361/178965224-e05ffd8d-28e5-4c91-8e2e-c2fcc5e25263.png)

**Comment by MendyBerger** [comment]
@corinnewo still happening?

**Comment by corinnewo** [comment]
On both sandbox and live site, yes, it is still happening!
On both live and sandbox, the **PREVIEW is crashing** when I want to preview my cover, as the 3rd step in building the cover.

![image](https://user-images.githubusercontent.com/16290361/199918574-f0dc080c-98ac-40b4-b9fa-c47461321d48.png)

**Comment by MendyBerger** [comment]
Think this is resolved. Reopen if still happening
