### ISSUE TITLE
Courses: Missing JIGs in the list

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2939]
I uploaded 24 JIGs, and now there are only 20 showing (UK version): https://jigzi.org/asset/edit/course/c546a4ba-036b-11ed-a75f-776ea5390f18

Also, with another course, should be 24, but there are 23, and ALEF is missing from the list. https://jigzi.org/asset/edit/course/6a95de2e-0356-11ed-8e50-e7b7d627cc16

**Comment by MendyBerger** [comment]
@corinnewo this still happening?

**Comment by corinnewo** [comment]
No. I think it was solved with the correct order. Thanks. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
