### ISSUE TITLE
Copied JIG - reordering the modules keeps reverting

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2944]
In this JIG, I had copied it from a previous JIG.  I have added a few new modules, so the last screen "Kol Hakavod" was now in the middle. I have moved it down to be at the end a few times now. Each time I go back in to edit, it is again in the middle. I have not yet published this JIG.

https://jigzi.org/asset/edit/jig/905bef20-f877-11ec-afcd-833f8f70f833

**Comment by MendyBerger** [comment]
I believe that this is now resolved
