### ISSUE TITLE
JIG panel: Module does not stay in place when 'moved down'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2948]
https://jigzi.org/asset/play/jig/905bef20-f877-11ec-afcd-833f8f70f833?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

See 'kol hakavod' - it should be last....

**Comment by corinnewo** [comment]
@MendyBerger Anat just complained that something that she moved up/down did not stay where she had put it when she published. I just tested on one of my JIGs and the same thing - the new order is not being saved.

**Comment by MendyBerger** [comment]
Seems like only move down is not working, move up does work

**Comment by corinnewo** [comment]
Move down should work as well!

**Comment by MendyBerger** [comment]
@RickyLB this seems to be a backend issue.

Call is `endpoints::module::Update:` with index in body.

Can help you reproduce if you're having trouble

**Comment by RickyLB** [comment]
@MendyBerger @corinnewo Issue has been resolved in Sandbox
