### ISSUE TITLE
Courses on mobile - layout needs to be changed

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2957]
Courses look great on PC, but on iPad and iPhone, they are unusable.
I suggest that we stack the columns instead - have the left hand side full width, then the list of courses underneath, also full width.
@GaliShapira Please take a look and see what you recommend. Thanks!

Courses built so far:
Ji Alef-Bet Stage 1 (USA): https://bit.ly/JiAlefBet1-US
Ji Alef-Bet Stage 1 (UK): https://bit.ly/JiAlefBet1-UK
Ji Alef-Bet -Mish Mash Letters: https://bit.ly/JiAlefBetMishMash1
Ji Alef-Bet Vowels and Symbols: https://bit.ly/JiAlefBetVowels
Ji Alef-Bet Stage 2 https://bit.ly/JiAlefBet2-Words
Ji Alef-Bet - קריאה עברית בעברית https://bit.ly/JiAlefBet2-Ivrit
Ji Alef-Bet Stage 3 https://bit.ly/JiAlefBet3-Prefixes

This is what it looks like on iPhone:
![IMG_4191](https://user-images.githubusercontent.com/16290361/180168264-690b5308-bc19-4c26-82d2-6d260f1656bf.PNG)
and zoomed in:
![IMG_4190](https://user-images.githubusercontent.com/16290361/180168329-12800c3a-e0e8-44d3-bd16-0e446ce0537c.PNG)

On iPad:
![IMG_6987](https://user-images.githubusercontent.com/16290361/180168373-99edfd2f-469e-4869-a533-6319669719bc.PNG)

**Comment by MendyBerger** [comment]
Resolved
