### ISSUE TITLE
Community - Add the Pincus logo at the bottom

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2961]
Community - 
Add the sentence " in partnership with the Pincus Fund." + the Pincus logo 
at the bottom of the page, above the footer

https://zpl.io/vMLd3er

@MendyBerger 
As the logo is a flat image with white background. 
Is it possible to add it in a multiply transparency mode? 
Logo: 
![PF-LOGO](https://user-images.githubusercontent.com/88834002/180254208-aecea446-a2e6-4a4c-8fd2-b8312d57a359.png)

<img width="1190" alt="Screen Shot 2022-07-21 at 18 32 32" src="https://user-images.githubusercontent.com/88834002/180253972-901ad595-05a7-4aed-a739-3aea6120321b.png">

**Comment by corinnewo** [comment]
@ChaykeeMor Is this the correct punctuation? Please finalize? Thanks!

**Comment by ChaykeeMor** [comment]
In partnership with the Pincus Fund

**Comment by corinnewo** [comment]
Chana says to add to only the home page of the community section

**Comment by MendyBerger** [comment]
@GaliShapira can you send me the image? Can't download from zeplin

**Comment by MendyBerger** [comment]
@GaliShapira reminder

**Comment by GaliShapira** [comment]
Hi @MendyBerger 
The logo is above here in the first comment.
Its with white background, can you place it in a multiply mode so white is not seen?

**Comment by corinnewo** [comment]
I have a transparent logo for them:
![The-Pincus-Fund](https://user-images.githubusercontent.com/16290361/182554169-88dc389d-d745-4661-92a7-4121c06202bf.png)

**Comment by MendyBerger** [comment]
Resolved in fbe9ecffc

**Comment by corinnewo** [comment]
@MendyBerger - you used Gali's original text instead of Chaykee's final text. PLease change "in partnership with the Pincus Fund." to "In partnership with the Pincus Fund", with capital I and no period at the end. Sorry about that - thanks!

**Comment by corinnewo** [comment]
closing in favor of #3073
