### ISSUE TITLE
Ipad - cards games - Add words component

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2963]
1. The "Generate" button should be above fold. 
2. All vertical margins need to be smaller (between the wizard to the tabs, between the tabs to the Add your words title, Between the title to the Hebrew icons.
3. lines can be slightly smaller (height)
Should I create a design?
Lets discuss.

![IMG_0319](https://user-images.githubusercontent.com/88834002/180263759-6f64cc58-ee61-445b-9435-9ecd67be9aba.PNG)

**Comment by corinnewo** [comment]
@GaliShapira Yes - happy to discuss. I have been thinking that on the PC as well there is the GENERATE button below the fold, and it is really annoying (if you know it is there). Why don't we change the CONTINUE button to say GENERATE - that is always visible on RHS, and it is disabled until you click the GENERATE button.
