### ISSUE TITLE
Ipad - audio component

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2964]
1. Add a margin between the icon play to the word on the button.
2. The radio button components are not our design.
3. We need to discuss the canvas/panel widths proportions.

![IMG_0321](https://user-images.githubusercontent.com/88834002/180265145-d60b374a-7047-478a-a87e-b58d26eefa35.PNG)

**Comment by corinnewo** [comment]
Seems to have been fixed on my iPad
