### ISSUE TITLE
Ipad - instructions component need to be smaller so it fits the height

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2966]
We have a smaller version of this component of text and audio in ask a question activities. 
Should I make a design? 

![IMG_0323](https://user-images.githubusercontent.com/88834002/180266576-b775a0ce-3b36-4f9b-adbd-3700c2ab4744.PNG)

**Comment by corinnewo** [comment]
@GaliShapira If you have the smaller design in ask a question, then we should use it. Do you need to do more work on it?

**Comment by corinnewo** [comment]
Related to #3176 - need to make all recording areas smaller.
