### ISSUE TITLE
IPad - End of JIG screen in creator - the icons and their texts need to be smaller so it fits width

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#2967]
I suggest to make the icons a bit smaller and the texts maybe in 2 lines. 
Should I make the design?

![IMG_0325](https://user-images.githubusercontent.com/88834002/180266996-e2f713eb-b86c-4e2e-abc9-15dc4c6e1527.PNG)

**Comment by corinnewo** [comment]
@GaliShapira Yes, I think it will be useful to have an iPad version. Definitely get rid of any scrolling!

**Comment by corinnewo** [comment]
This has been taken care of in the new review flow. Closing this issue.
