### ISSUE TITLE
Find the answer: Can the question box show the correct question?

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2978]
The question box keeps the original first question there, no matter which question I select, or how it has been updated, yet the answer updates, showing the answer area for that question. It is quite confusing!
Can the question box display the question that will be displayed in the player for that question?

![image](https://user-images.githubusercontent.com/16290361/180828038-9b3114ef-92fd-4d42-902b-4dc128d4dbb3.png)

**Comment by corinnewo** [comment]
In fact, when you play the game, the original text remains in the question box until the first question is played. Then it changes to the text of the first question!

**Comment by johnnynotsolucky** [comment]
@corinnewo the plan for editing is to either update the question text in the sticker when going through questions, or if there is no sticker, then show the popup with the question text.

RE your comment, should we not show the question sticker at all until the first question is played?

**Comment by corinnewo** [comment]
It's an interesting question... as in the case I had, the question in the question box was no longer the text of the question, but because it was the original text, it appeared. Probably, only show the text of the question when it is being asked, as if there are random orders, it will only be relevant when the question is being asked.

I like your plan for the editing!

**Comment by corinnewo** [comment]
We definitely need the question text to show correctly when you are tracing the answers. Teachers are not understanding that the question is changing (since the original text displays during the create, and only changes in the preview), and I think that displaying the current question in the question box will help that be understood.

**Comment by johnnynotsolucky** [comment]
@corinnewo this is an interesting problem to solve. If the teacher hasn't selected a sticker, it's fairly simple, we can show the popup text with the question. However, if they have selected a text sticker for the question, we need to update the text in that sticker whenever they open a question in the sidebar to edit. My concern is that we update the text and actually save that new text so each time they edit a question, we resave the content of the sticker. I think that we can bypass the logic to save the text, and directly set it on the sticker like we do when students are playing the activity, but I'm unsure how complicated that might be.

**Comment by corinnewo** [comment]
Closing in favor of #3085
