### ISSUE TITLE
Rename "Find the Answer" to 'Answer this"

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2981]
Please rename the module to "Answer this".

1.  In the list of modules on create page (@ChaykeeMor All the names are title case. Should this not be "Answer This" in this case?
![image](https://user-images.githubusercontent.com/16290361/180937463-0a8b3cb8-c5a5-4059-9d6e-6cc57ca6bb3e.png)

2. On the side panel: 
![image](https://user-images.githubusercontent.com/16290361/180937739-8f4eec93-1fbb-4d86-8b62-635141e176cb.png)

3. In the use case list: "Create an Answer This Activity" (@ChaykeeMor Does this sound correct? ) 
![image](https://user-images.githubusercontent.com/16290361/180938204-c3a0cb68-afb6-41a1-b1af-8f1665855294.png)

4. While creating - the heading is actually missing at the moment! "Create an Answer This Activity" (@ChaykeeMor -is this correct?) 
![image](https://user-images.githubusercontent.com/16290361/180938591-cea7fb70-529d-4f4b-b95e-4d151de6c726.png)

5. After DONE on Preview stage: "Your Answer This activity is ready!" (@ChaykeeMor please check this... ) 
![image](https://user-images.githubusercontent.com/16290361/180939200-7fb2cf6f-f255-4e9c-9389-cc15fba96d3a.png)

6.  In player - on JIG panel: 
![image](https://user-images.githubusercontent.com/16290361/180939129-3bde7762-4d4c-485e-967a-aae9e82ea772.png)

**Comment by ChaykeeMor** [comment]
I would agree with all your adjustments but maybe the heading (over use cases and canvas) needs rewording along with all of these headings across all the activities. I'd like to look at all of them as a group and reword. In the meantime, let's put this one as "Create an Answer This activity" making sure that only the first word and the activity name are capitalized.

**Comment by johnnynotsolucky** [comment]
@corinnewo for point 4 in the list, those are controlled by the json file in dropbox. When this issue was created the file didn't exist yet. Since yesterday it's been available, and I've updated it to use "Answer It", and also to use @ChaykeeMor's suggestion on capitalization.

Point 3 is defined in code and I've updated it to have the correct text and capitalization. I've also updated the other copy in code to Chaykee's suggestion.

**Comment by corinnewo** [comment]
@johnnynotsolucky Thanks - did you use "Answer It" or "Answer This"? Chaykee wanted "Answer This"!

**Comment by johnnynotsolucky** [comment]
Sorry, I did use Answer This (https://github.com/ji-devs/ji-cloud/pull/2994), I had Answer It in my head when I typed that message 😅

The find-answer.json file has been updated and synchronized, but the Fastly cache doesn't seem to be updating correctly. It's currently cached a version with incorrect syntax.
