### ISSUE TITLE
Cover has disappeared from JIG panel!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2982]
I was testing the FIND THE ANSWER module, and did not make a cover. I then went back to add in a cover, and there is no space for the cover. If I try and make a cover from the publish, it goes straight to the FIND THE ANSWER module, and would overwrite the module!

![image](https://user-images.githubusercontent.com/16290361/180972287-9830121b-dd64-4b99-94cc-ec1ffa9d71fc.png)

**Comment by johnnynotsolucky** [comment]
@MendyBerger is this possibly related to the changes to the sidebar made recently (a month or so back)?

To reproduce:

1. Create a new JIG;
2. Add an acitivity, not a cover though;
3. Refresh the JIG;
4. Note that the cover placeholder is gone, instead 2 "Drag activity here" blocks are under the activity created in 2.


https://user-images.githubusercontent.com/4161106/180990745-2d137b97-5fbf-4739-9d0c-d341fbe10873.mov

**Comment by corinnewo** [comment]
@MendyBerger please make this a high priority item! 
It is happening on the live site as well, and really frustrating to lose the ability to add in a cover thumbnail. If the fist activity is a card game or another interactive activity, when you edit it, you get the 3 wizard steps for the cover. So I am sure something is going to get messed up there too!

**Comment by MendyBerger** [comment]
Resolved in 16cfc456c
