### ISSUE TITLE
Card games - Generate button is often below fold and can't be seen - make into a floating button

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2987]
Gali has changed the design of the 'Generate' button that is at the end of lists. Problem is that often that button is below the fold, and users do not know that they have to click it before going to the next tab. Next tab is disabled, as is the CONTINUE button. So there is a lot of frustration.
Gali changed the design to have a floating button at the end of the screen, always visible, that would generate the cards.
https://zpl.io/2pNdYjE

**Comment by corinnewo** [comment]
A huge school in Califoria will not use Jigzi because this TechED teacher thought that it had stopped working! These are the screens that she sent to illustrate what was not working:

<img width="1154" alt="Screen Shot 2022-08-03 at 10 58 41 AM" src="https://user-images.githubusercontent.com/16290361/183063926-56bb32df-2ff6-4270-a49c-1e42a4860f7a.png">
<img width="1127" alt="Screen Shot 2022-08-02 at 7 45 23 PM" src="https://user-images.githubusercontent.com/16290361/183063931-7dc198c5-e4c5-47d1-b96b-6e467554ad34.png">

**Comment by johnnynotsolucky** [comment]
@corinnewo will look at it first thing tomorrow. 

I was looking at the screenshots above and wondered maybe the Continue button could serve as the generate button too? So if a teacher fills out a list and clicks continue, it’ll generate the cards.

**Comment by corinnewo** [comment]
@johnnynotsolucky We discussing in ideation..... Everyone agrees that the continue should also do the generate.... But, we still feel that there should be a floating button (according to Gali's zeplin https://zpl.io/2pNdYjE) that is always visible, or else reduce the size of the scrolling area so that you always see the button. This should apply to ALL use cases of the card lists.

**Comment by corinnewo** [comment]
@johnnynotsolucky At the training today, the teachers could not find Dicta, etc... as they had scrolled down to add in their words. If you are already changing that the GENERATE button is always visible, can you also make sure that they do not lose the top of the panel too?

**Comment by johnnynotsolucky** [comment]
I've implemented the solution Mendy suggested - to have the Generate button always visible and the list itself scrollable:

https://user-images.githubusercontent.com/4161106/186880365-0598314c-70b5-41d1-90b4-32fff936c71b.mov

Should this issue be closed, or will we want to revisit to implement the new design for the button?

**Comment by MendyBerger** [comment]
@johnnynotsolucky we need to discuss before closing
