### ISSUE TITLE
Community: Crashes when clicking on the name of a person who follows me

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2997]
When I click on a person who is follwoing me, in the live JIgzi COmmunity, I get the OOPS screen. 
This is the error:
Failed to load resource: the server responded with a status of 500 ()
index.js:726 panicked at 'not yet implemented', crates/entry/community/src/member_details/actions.rs:150:23
Stack:
Error
    at imports.wbg.__wbg_new_693216e109162396 (https://frontend.jicloud.org/community/js/index.js:15741:23)
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[336]:0x919d7
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[2602]:0xdb88a
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[817]:0xbc32b
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[994]:0xc362a
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[2125]:0xd8f06
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[1764]:0xd4b22
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[1601]:0xd2150
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[636]:0xb1b71
    at https://frontend.jicloud.org/community/js/assets/app-community-8969f983.wasm:wasm-function[164]:0x5250f
imports.wbg.__wbg_error_09919627ac0992f5 @ index.js:726
app-community-8969f983.wasm:0xbc34e Uncaught (in promise) RuntimeError: unreachable
    at app-community-8969f983.wasm:0xbc34e
    at app-community-8969f983.wasm:0xc362a
    at app-community-8969f983.wasm:0xd8f06
    at app-community-8969f983.wasm:0xd4b22
    at app-community-8969f983.wasm:0xd2150
    at app-community-8969f983.wasm:0xb1b71
    at app-community-8969f983.wasm:0x5250f
    at app-community-8969f983.wasm:0xaeb46
    at app-community-8969f983.wasm:0xd9db1
    at __wbg_adapter_35 (index.js:234:10)

**Comment by MendyBerger** [comment]
Should be fixed, reopen if not the case
