### ISSUE TITLE
Courses - laptop screen should get the side-by-side view, not stacked

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2999]
On my laptop, I am seeing the course stacked. THere is plenty of space to have the columns side-by-side. Please change the cut-off size so that laptops see the proper layout and not stacked. It is made all the worse in that all I see is a very low res image and have to scroll down to see that it is a course.
https://files.slack.com/files-pri/T04TP8PFZ-F03RBN4KXN2/image.png

**Comment by MendyBerger** [comment]
Resolved
