### ISSUE TITLE
Community: profile dialog corrections

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3000]
1. Please look again at the zeplin [zpl.io/PqOoBOp](http://zpl.io/PqOoBOp) - You have used different texts.... 

- Instead of persona, should be 'What I do' 
- instead of 'Organization", it is "Where I work"
- Languages should be the long list of languages and multi-select. Idea is that I can search for people who speak my language....  

Language dropdown shows the 3 "language of communication" choices. This dropdown is "Languages that I speak",  and should be the list of 13 languages (same list from the  search). Also, please put the names of the languages in the profile , and not just the 2-letter abbreviation. At the moment I can search for 'en' but not 'English'. That is what people would be searching for, not the abbreviations....

**Comment by MendyBerger** [comment]
Resolved in https://github.com/ji-devs/ji-cloud/commit/486833dcdfa17662049c807176a48860ae90c9d5

Not including multi language as still waiting for decision from ideation, should be a separate issue

**Comment by corinnewo** [comment]
@MendyBerger Decision made about default languages: see #3036 

Also, please look at the ZEPLIN again (http://zpl.io/PqOoBOp) - there is no duplication there of field names - you have both on the left and within the field. No need - on the left, need only the icon.
