### ISSUE TITLE
Community - profile upload dialog needs to have correct wording

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3001]
https://files.slack.com/files-pri/T04TP8PFZ-F03RD43SHV1/image.png

Please change to Chaykee's text:
Red Title: Profile picture
Instruction: Upload or drag image here
Parameters:: Stretches to fit. Max 5 MB
Button: Save

If you are able to change the stretching feature, then that would be amazing! Could you make it a proportional stretch?

**Comment by MendyBerger** [comment]
Resolved in 486833dcd

We should definitely consider keeping the image in shape but should probably be different issue
