### ISSUE TITLE
Courses - additional resources - display the type rather than the file name, and have file name as tooltip

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3007]
At the moment, the course lists the file names of the additional resources, which can be quite long!
![image](https://user-images.githubusercontent.com/16290361/182159885-38d99413-c168-46eb-9066-3a000feee17d.png)

Rather, display the type (like Worksheet, Flash cards), and the link and tooltip will be the URL.

**Comment by corinnewo** [comment]
Also, leave more space between them to allow for fingers to tap, especially on mobile devices.

**Comment by MendyBerger** [comment]
Resolved in 81f5ae4f0

**Comment by corinnewo** [comment]
@MendyBerger Please  add in the **tooltip** of the URL so that when there are several flashcards, there is some indication as to what the various versions are.

**Comment by MendyBerger** [comment]
Resolved in 18fee1b08
