### ISSUE TITLE
jig resources text changes

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#3013]
Add an intro line above button @GaliShapira size/color/weight?
'You can add resources for teachers to use along with this JIG.'

Red popup title: 'Add resources' change to: 'Add resource'
<img width="370" alt="Screen Shot 2022-08-03 at 11 53 02" src="https://user-images.githubusercontent.com/94056434/182567755-65e3934f-0369-4f44-b223-8b6a579b69a8.png">

'Additional resources' change to: 'Teacher resources'
<img width="324" alt="Screen Shot 2022-08-03 at 11 54 16" src="https://user-images.githubusercontent.com/94056434/182567725-5d0bfe41-0cf4-482d-ac61-92207ca3e26b.png">

**Comment by ChaykeeMor** [comment]
@corinnewo What kind of instruction do you mean? Something like 'You can add a resource for other teachers to use along with this JIG.' and then the button? If so, we do not need the full 'Add a teacher resource'. If you have this line in bold above, I'd then stick with 'Add resource' here. Either way, on the back of the cards needs to say 'Teacher resources'

**Comment by corinnewo** [comment]
@ChaykeeMor I think that the extra instruction would make it clearer what the resource is. Let's add it in. (I have closed 3035)

**Comment by MendyBerger** [comment]
@corinnewo looks like some context/conversation is missing from this issue, mind giving me a basic rundown of what the final decisions are?

**Comment by corinnewo** [comment]
@MendyBerger Final decisions:

- On the back of card in search results: 'Additional resources' change to: 'Teacher resources'
- Add an intro line above button to add a resource: '**You can add resources for teachers to use along with this JIG**.'
- Red popup title: 'Add resources' change to: 'Add resource'

**Comment by GaliShapira** [comment]
Changed text:
@MendyBerger Final decisions:

On the back of card in search results: 'Additional resources' change to: 'Teacher resources'
Add an intro line above button to add a resource: 'Add resources for teachers to use with this JIG.'
Red popup title: 'Add resources' change to: 'Add resource'

**Comment by GaliShapira** [comment]
<img width="479" alt="Screen Shot 2022-08-15 at 14 35 22" src="https://user-images.githubusercontent.com/88834002/184628277-078091d3-5336-4b44-9860-0311ed7cbaa0.png">

**Comment by MendyBerger** [comment]
Resolved in da75e7134
