### ISSUE TITLE
Courses - correct order for Corinne's courses

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3016]
### Ji Alef-Bet: Letters (Stage 1, USA)
•	The alef bet song
•	Alef
…..
•	Tav
•	Final letters: Club sofit
•	Practice makes perfect (Junior)
•	Practice makes perfect
•	מִי שֶׁמְּנַסֶּה מַצְלִיחַ
### Ji Alef-Bet: Letters (Stage 1, UK)
•	The alef bet song (UK)
•	Alef (UK)
…..
•	Tav (UK)
•	Final letters: Club sofit (UK)
•	Practice makes perfect (Junior)
•	Practice makes perfect

- •	מִי שֶׁמְּנַסֶּה מַצְלִיחַ

### Ji Alef-Bet: Vowels & Symbols
1.	Vowel sounds and symbols
2.	Reading with vowels
3.	One dot two jobs
4.	Words ending in Ay and Oy
5.	Words ending in AV
6.	Practice makes perfect

### Ji Alef-Bet: קריאה עברית בעברית
Seems to be in the correct order

### Ji Alef-Bet: Words and Stories (Stage 2)
Alef
…
Tav

### Ji Alef-Bet: Prefixes and Suffixes (Stage 3)
1.	Let’s learn about shorashim
2.	G-d’s name
3.	Add HEY to the beginning
4.	Add VAV to the beginning
5.	Add BET to the beginning
6.	Add KAF to the beginning
7.	Add LAMED to the beginning
8.	Adding ‘ee’ to the end makes it mine
9.	Adding ‘O-‘ to a word makes it his…
10.	Adding CHA or AICH to a word makes it yours

### Ji Alef-Bet: Mish Mash Letters
Seems to be ok

### Ji Alef-Bet: Practice Makes Perfect
1.	Alef Bet
2.	Mish Mash letters
3.	Hebrew vowels

**Comment by MendyBerger** [comment]
@corinnewo please confirm that all are in order now

**Comment by corinnewo** [comment]
@MendyBerger The order all seems fine now. BUT - I accessed them from the bottom of the 'Content' screen, and when I click play, the wrong course comes up!

**Comment by MendyBerger** [comment]
Original issue resolved.
Wrong course issue being tracked here https://github.com/ji-devs/ji-cloud/issues/3051.
