### ISSUE TITLE
Answer this: Settings - number of tries 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3023]
@GaliShapira We need to define exactly what this means - what does each setting do? Then we need to add it back to the settings page.
I think if the user sets a number of tries, then if the kid has not answered correctly after that number of tries, we highlight the answer, and allow them to answer again. Tyrone hid it so that we could make live, but we need to define what happens there!

**Comment by GaliShapira** [comment]
Lets discuss this

**Comment by corinnewo** [comment]
closed in favor of #3291
