### ISSUE TITLE
Community - Add option for member to leave circle

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3024]
Add the missing arrow to the Member button. 
With a dropdown to leave for a member. 
Admin has the option to delete the circle.

Merav will soon update here the arrow button.

**Comment by meravs** [comment]
screen shot:
![Screen Shot 2022-08-04 at 15 52 19](https://user-images.githubusercontent.com/96105053/182851655-b724a1d4-9566-4beb-b0b2-b1a2c2a73b43.png)
![Screen Shot 2022-08-04 at 15 52 13](https://user-images.githubusercontent.com/96105053/182851660-fc213851-e25d-4d29-b1b1-eec22f4207cd.png)

Screens in zeplin:
https://zpl.io/Z0yqX9L
https://zpl.io/O0jBGd1

**Comment by corinnewo** [comment]
@GaliShapira Where is the delete for the person who created the circle?

**Comment by GaliShapira** [comment]
Delete is in the admin page only:
https://zpl.io/Q0pqEYx

<img width="361" alt="Screen Shot 2022-08-04 at 16 53 27" src="https://user-images.githubusercontent.com/88834002/182864618-bd12351a-02b8-49e9-878a-beb88a64cbe7.png">

**Comment by corinnewo** [comment]
In sprint we decided that you **can** delete a circle with members in it. There should just be a warning before hand. "There are members here! Are you sure you want to delete this circle?" (@ChaykeeMor - please check the text!)
