### ISSUE TITLE
Community - Edit details of user - delete titles

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3026]
Take out the titles on the left. 
Merav will update the design.

<img width="846" alt="Screen Shot 2022-08-04 at 12 48 26" src="https://user-images.githubusercontent.com/88834002/182832003-0ce633d5-2b33-4e46-86ac-b9d68cb5ec92.png">

**Comment by meravs** [comment]
Screen shot:
![Screen Shot 2022-08-04 at 14 19 24](https://user-images.githubusercontent.com/96105053/182834782-4eed4e66-b2bb-4f73-8a76-e039a08f254d.png)

Linke to zeplin:
https://zpl.io/PqOoBOp

**Comment by GaliShapira** [comment]
Please make sure to follow the margins as in the design.

**Comment by corinnewo** [comment]
@ChaykeeMor Please confirm the texts here. Thanks!

**Comment by MendyBerger** [comment]
Resolved in b208c9c5a
