### ISSUE TITLE
2 new themes assets are saved in the Dropbox

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3032]
IML
Hebrew Reading

In Zeplin its under "Themes"
https://zpl.io/z8BwZXG
https://zpl.io/GENn0vE
https://zpl.io/jZopJxp
https://zpl.io/Q0OM58m

<img width="491" alt="Screen Shot 2022-08-04 at 18 24 52" src="https://user-images.githubusercontent.com/88834002/182886701-a974d455-5aa1-4348-b7ae-947641ec0609.png">

**Comment by corinnewo** [comment]
Added to the JSON - ready to be implemented.
