### ISSUE TITLE
Text stickers: Add 'Edit' option to the kebab menu

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3033]
From user testing it has become clear that users do not know how to edit the text. We want to add a menu option to the sticker to 'Edit text', as the first option in the list. Clicking this option will open up the text panel on the left and enable the text-edit mode.
![image](https://user-images.githubusercontent.com/16290361/183378109-a487b8bd-b353-432a-b4b6-f53cbc955fd4.png)

@ChaykeeMor please confirm text in menu
@GaliShapira please attach icons for edit and hover states

**Comment by ChaykeeMor** [comment]
Just 'Edit'

**Comment by GaliShapira** [comment]
Pls see the icon.
![Icn_Edit](https://user-images.githubusercontent.com/88834002/183398331-3e16a3f2-24cb-4ece-b1a0-6e761e38867d.svg)
![Icn_Edit_Hover](https://user-images.githubusercontent.com/88834002/183398341-fdc2352b-aa8a-48ee-9738-6397f00f6931.svg)
