### ISSUE TITLE
Additional resources: Rename to 'Teacher Resources' 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3035]
To avoid confusion that the teachers may add in worksheets for students as additional resources, we need to rename the area in the publish dialog to from '**Additional Resources**' to '**Teacher Resources**'. Any worksheets for the children must be added to the 'Embed it' module which still has to be developed.
Change in the following places:

1. Publish dialog: change 'Add resource' to 'Add teacher resource'. @ChaykeeMor Do we need to add in an instruction here too?
2. Back of a card in search results: Change 'Additional resources' to 'Teacher resources'

![image](https://user-images.githubusercontent.com/16290361/183381872-f02debae-0d6a-44ea-ae5a-1660663055a3.png)

![image](https://user-images.githubusercontent.com/16290361/183384014-efb97851-98e1-45b0-bb66-1860aa3e8a7f.png)

@ChaykeeMor Please confirm these changes

**Comment by ChaykeeMor** [comment]
Assuming we should close #3013 -- what kind of instruction do you mean? Something like 'You can add a resource for other teachers to use along with this JIG.' and then the button? If so, we do not need the full 'Add a teacher resource'. If you have this line in bold above, I'd then stick with 'Add resource' here. Either way, on the back of the cards needs to say 'Teacher resources'

**Comment by corinnewo** [comment]
Closing in favor of #3013
