### ISSUE TITLE
Community circles - options in the circle should be a dropdown

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3037]
Currently, you click on MEMBER button to leave a circle. This is not clear enough. @GaliShapira please put in correct design from ZEPLIN here. THanks!

**Comment by GaliShapira** [comment]
Hi @corinnewo 
I have opened a different ticket for it - https://github.com/ji-devs/ji-cloud/issues/3024
I believe we can close this ticket here.

**Comment by corinnewo** [comment]
Closing this ticket in favor of https://github.com/ji-devs/ji-cloud/issues/3024
