### ISSUE TITLE
Video module - UI comment - 

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3039]
The gray background of the Video tab should not be cut, should fill the panel to the bottom edge as in the design.
This comment refers to all the fields on panels.
https://zpl.io/bl35wGk 

Production:
<img width="408" alt="Screen Shot 2022-08-08 at 13 54 20" src="https://user-images.githubusercontent.com/88834002/183402499-2756b4ad-7717-47c1-bf4a-bc46b02dbe81.png">

Design:
<img width="284" alt="Screen Shot 2022-08-08 at 13 56 29" src="https://user-images.githubusercontent.com/88834002/183402889-8b73d1a4-f630-4b7b-9614-f800f862959d.png">

**Comment by MendyBerger** [comment]
Resolved in 982680e00
