### ISSUE TITLE
Fonts component width

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3040]
I see that in the actual production the font dropdown is narrower than the name of the font.
We do not want the fonts to be longer than one line 
(See attached, look at the Architect daughter font and the one below it)
<img width="371" alt="Screen Shot 2022-08-08 at 16 03 53" src="https://user-images.githubusercontent.com/88834002/183424890-7ceddb68-979f-4a5d-a073-9c0bfa6b1f48.png">

I suggest making the weight field below the font field.
<img width="568" alt="Screen Shot 2022-08-08 at 16 06 59" src="https://user-images.githubusercontent.com/88834002/183425009-00b45ae7-1a1e-475c-8455-ca7b42ab4a75.png">

**Comment by MendyBerger** [comment]
Resolved in 329aba8c5
