### ISSUE TITLE
Curation - need to be able to curate resources and courses as well

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3044]
@GaliShapira Please suggest how we can separate the 3 types of curation. Basic functionality should be the same - ability to add stars, edit, etc.

**Comment by GaliShapira** [comment]
Hi Corinne

I added tabs on top. 
<img width="546" alt="Screen Shot 2022-08-10 at 17 02 12" src="https://user-images.githubusercontent.com/88834002/183921207-89a116a6-4dcd-45cb-a971-760756ca7995.png">


https://zpl.io/bexpXEP

**Comment by corinnewo** [comment]
@MendyBerger Do this require anything else from Ricky in order to progam?

**Comment by MendyBerger** [comment]
Yes, we don't have curation setup for resources at all

**Comment by corinnewo** [comment]
@MendyBerger We need CURATION for resources as well as courses. Please add this to the LaunchBadge agenda for next week. THanks

**Comment by corinnewo** [comment]
@MendyBerger In Resource curation table, please add in a button to view the resource from the resource details page in curation.

![image](https://user-images.githubusercontent.com/16290361/225960979-e09ff2ee-8b29-4739-818e-89393cfc67e9.png)

**Comment by MendyBerger** [comment]
Added link to open resource from resource details page

**Comment by corinnewo** [comment]
@MendyBerger When I open the linked document, it opens in the same tab full screen, and I cannot get back to the curation table. Please open the attached resource in a new tab, or new window. Must be able to close the resource easily and get back to the RESOURCE TABLE. Thanks!
