### ISSUE TITLE
Community - Perhaps we should list the full member's name

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3049]
I came across this: Member put in her name as Mrs Zegze. So we end up with Mrs's Network.
The same thing is going to happen if people put in their names as Rabbi Cohen, or Mr Cohen.

I think we should rather have the full name in the profile, eg Mrs Zegze's creations, or Corinne Ossendryver's network. @ChaykeeMor ? @GaliShapira ? What do you think?

![image](https://user-images.githubusercontent.com/16290361/184099956-b6fa1203-14b5-4b3f-85ef-ddf5a4f1584d.png)

**Comment by GaliShapira** [comment]
I agree, full name

**Comment by ChaykeeMor** [comment]
Absolutely

**Comment by corinnewo** [comment]
Please put the person's full name in the  CREATIONS and NETWORK headings.

**Comment by MendyBerger** [comment]
Resolved in b461a3cd9
