### ISSUE TITLE
Scrollbar on wide screens

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#3052]
@johnnynotsolucky I think you introduced a small regression with commit e71cd5c36aca06c2235fbcc20582ac6285eaa680, on side screens the sidebar now has a scrollbar in the module edit sidebar.

(think you can deploy to live with this, don't think many people are going to have the issue)

If you don't have a wide monitor you can just zoom out to recreate.

![image](https://user-images.githubusercontent.com/12537668/184177589-69419fb1-e72e-4e47-b54b-dc07b3e87e53.png)

**Comment by johnnynotsolucky** [comment]
Thanks for picking this up @MendyBerger, will resolve!
