### ISSUE TITLE
User languages

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#3053]
Please update user languages to the following:

```rust
/// The language of the app.
pub language_app: String,

/// The language of emails.
pub language_emails: String,

/// Languages the user speaks
pub languages_spoken: Vec<String>,
 ```
 
 And remove `language` and `locale`.

For existing users:
- `language_app` and `language_emails` use `"en"`.
- `languages_spoken` a vec with a single value taken from the removed `language`. (probably has to be done before language is removed)

**Comment by MendyBerger** [comment]
@RickyLB can you please rename `language_spoken` to `languages_spoken`?

**Comment by RickyLB** [comment]
@MendyBerger Oops, missed that! I'll fix that now.
