### ISSUE TITLE
WEBSITE: Update links in the site footer

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3058]
Please update the following links in the footer:
1. **Create activities** - change "..../asset/edit/jig/gallery" to "..../asset/edit/jig-gallery" (GIVING ERROR)
2. Add in the link "...jigzi.org/community" to **Join community** and remove the alert.
3. Add in the link to a new tab "https://www.jewishinteractive.org/jigzi-demo-sessions/" **Online webinars** and remove the alert.
4. Support and FAQ - change the current link "jigzy@jewishinteractive.org" to "info@jigzi.org"
5. Change the phone number in the US (Ji United States Tel: +1 (703) 517-5182)  to **+1 (866) 601-8000**

![image](https://user-images.githubusercontent.com/16290361/184328145-c63fed81-7329-47da-ad4f-def6fa4514ee.png)

**Comment by MendyBerger** [comment]
Resolved in 84b05d9f5d5ff9fea5f54e3bde01fcae70dd50b7
