### ISSUE TITLE
Community text changes

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3070]
- **Community home, heading:** New Circles - change to: Join a new circle
- **Community, My profile, Edit About:** Location - change to: Where I live
- **Community, My profile, Edit About, button:** Apply - change to: Save
- **Community, My profile, Edit Bio, heading:** Add/ Edit bio - change to: Bio
- **Community, My profile, Edit Bio, field heading:** Bio- change to: My bio
- **Community, My profile, Edit Bio, field:** Empty - change to: Tell the community about yourself
- **Community, Circles, New circle, Invite members, field:** Search members - change to: Search

**Comment by MendyBerger** [comment]
Resolved
