### ISSUE TITLE
Community, Circles - start a new circle text field

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3071]
Under the field heading "circle name", you can't read the full text (Choose a name that aims to connect members).... Clicking the right arrow in the keyboard doesn't move the text forward.

![Screen Shot 2022-08-15 at 1 24 16 PM](https://user-images.githubusercontent.com/78186896/184686658-2195b94c-7a7e-43a1-80c9-949399d32d9c.png)

**Comment by corinnewo** [comment]
@ChaykeeMor  This is the text that you had written, but it is too long. Can we shorten to "Type a name"?

**Comment by ChaykeeMor** [comment]
Text: My circle's name
While we're at it..  can we modify the button and the red title here to drop 'new'? Just 'Start a Circle'
@corinnewo

**Comment by corinnewo** [comment]
To sum up:
1. Change the header from "Start a new circle" to "Start a Circle"
2. Change the default text in the name field from "Choose a name that aims to connect members" to "Type a name"

**Comment by ChaykeeMor** [comment]
> To sum up:
> 
> 1. Change the header from "Start a new circle" to "Start a Circle"
> 2. Change the blue button on the circles page from "Start a new circle" to "Start a circle"
> 3. Change the default text in the name field from "Choose a name that aims to connect members" to "Type a name"

lowercase c in "Start a circle"

**Comment by MendyBerger** [comment]
Done
