### ISSUE TITLE
Community - remove "follow" button from my profile page

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3072]
There shouldn't be a follow button on the "my profile" page - users shouldn't need to follow themselves (when you click the button, it crashes with error page).

![Screen Shot 2022-08-15 at 1 35 10 PM](https://user-images.githubusercontent.com/78186896/184688926-d07e4793-4977-4175-8044-b8683e0bd79e.png)

**Comment by MendyBerger** [comment]
Resolved in 9b5e54326
