### ISSUE TITLE
Community Page - pincus fund - Capitalize I

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3073]
"in partnership with the Pincus fund" I should be capitalized
![Screen Shot 2022-08-15 at 4 21 06 PM](https://user-images.githubusercontent.com/78186896/184711750-c5356764-ba08-4481-ae2d-30cbcfce6afe.png)

**Comment by corinnewo** [comment]
Should be "In partnership with the Pincus Fund" with no period at the end either.

**Comment by MendyBerger** [comment]
Resolved
