### ISSUE TITLE
Answer this - request from field to have positive feedback after every correct click, not just at the end

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3083]
At the moment, if there are 2 correct items, then the positive feedback only comes after the second item. Teachers are saying that we need the feedback after every correct click. Please put in feedback after every click. 
We still need to add the advanced feedback options (https://zpl.io/qy88NJG) and the final feedback (https://github.com/ji-devs/ji-cloud/issues/2924).

**Comment by johnnynotsolucky** [comment]
@corinnewo what feedback would we give once they've selected all the correct items if the teacher hasn't added any final feedback (once #2924 is done)?

**Comment by corinnewo** [comment]
@johnnynotsolucky Please can you add in the positive feedbacks to all correct clicks! Thanks
