### ISSUE TITLE
Community - Must be able to delete a circle (admin or creator of the circle)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3087]
Delete is in the admin area of the circle only:
https://zpl.io/Q0pqEYx

In sprint we decided that you can delete a circle that has users in it, but that there should be a warning alert if there are members.

"There are members here! Are you sure you want to delete this circle?" (@ChaykeeMor - please check the text!) 
With Option to Delete and Cancel.

**Comment by MendyBerger** [comment]
Resolved in a67ef8470

**Comment by corinnewo** [comment]
@MendyBerger I deleted a circle with 3 members - there was no alert. Please add the alert!

**Comment by MendyBerger** [comment]
@corinnewo didn't we decide that you can delete circles even with members?

**Comment by corinnewo** [comment]
Yes, you can delete with members, but we do need an alert warning that there are members, and are you sure you want to delete.

**Comment by MendyBerger** [comment]
What should the alert say?

**Comment by corinnewo** [comment]
I suggested soemthing above:
"There are members in this circle! Are you sure you want to delete it?" 
With Option to Delete and Cancel.

**Comment by MendyBerger** [comment]
Resolved
