### ISSUE TITLE
Courses - must indicate where you are in the course for this session

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3088]
When a JIG within a course has been played, when you come back to the course list, please put in the green icon next to the JIG that has just been played. I know that this cannot persist as the students do not have  logins, but it would be really useful to know where I am and have just completed a JIG in this session. THere is also so a blue line on the left to show the current position.
https://zpl.io/5EkJJqj

**Comment by MendyBerger** [comment]
Resolved
