### ISSUE TITLE
Answer this: Change wording and order of the use cases, and add a new use case

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3096]
Currently, the use cases are too specific.
Change wording (@ChaykeeMor - please approve) :

1. Change 'Map' to 'Find it!'
2. Change 'Family' to 'Family tree'
3. Change  'Scene' to 'Find everything that...' (to emphasize that there are several answers)
4. Add new use case 'Find the differences'. @meravs - we need an illustration for 'find the differences' use case - maybe 2 simple boxes 

Change the order to have MULTIPLE CHOICE first, then SCENE, then everything else.

![image](https://user-images.githubusercontent.com/16290361/186370437-935edf8e-45d8-418e-995c-c5cfeb30fdfa.png)

**Comment by ChaykeeMor** [comment]
Text | Change to:
-- | --
Family | Family tree 
Map | Where on the map?
Scene | Find the answer
Text | Find the text

Would also recommend text changes in the graphics:
Text | Change to:
-- | --
Who is John's Mom? | Mom?
איפה אפריקה | אפריקה?
Words with א | Starts with א?
What starts with א | בננה?
Which word means a bridge | Bridge?

**Comment by ChaykeeMor** [comment]
@corinnewo the use case 'Find the differences' belongs in iSpy.

**Comment by corinnewo** [comment]
Adding a new use case: ticket #3122 (we will add this image to both Answer This and the iSpy module, when it is developed.

**Comment by corinnewo** [comment]
@GaliShapira Please can you update the graphics according to Chaykee's suggestions? Thanks!

**Comment by GaliShapira** [comment]
All texts are updated:
https://zpl.io/3Xk7ZBQ
https://zpl.io/1ykmWB4
https://zpl.io/kDB3N6L

**Comment by meravs** [comment]
Screen shots:
![Screen Shot 2022-09-08 at 9 21 29](https://user-images.githubusercontent.com/96105053/189049195-8414ef9e-4ff9-4137-8ff9-bf1fab97ed1a.png)
![Screen Shot 2022-09-08 at 9 21 22](https://user-images.githubusercontent.com/96105053/189049201-b9745b7f-a548-4f72-ab23-b60bb3200acb.png)
![Screen Shot 2022-09-08 at 9 21 10](https://user-images.githubusercontent.com/96105053/189049208-b4ad6acb-508a-4a1f-8df0-4b79c712edbb.png)

**Comment by ChaykeeMor** [comment]
@GaliShapira need an S in 'Starts with'

**Comment by ChaykeeMor** [comment]
@GaliShapira need an S in 'Starts with..'. and I am SO SO sorry but I just realized the use case in other modules are all Title case. So it's Multiple Choice, Find the Answers, Find the Text, Where on the Map, Family Tree, Find the Differences

**Comment by corinnewo** [comment]
@ChaykeeMor The headings are done in programming, not in the graphics. Will have to ask Tyrone to go in and change, if they are not correct.
I had wanted "Find the differences', etc with an s to emphasize that this deals with **multiple** answers as well. It was a request from Anat, and I agree with her.

**Comment by meravs** [comment]
Updated
![Screen Shot 2022-09-08 at 14 32 51](https://user-images.githubusercontent.com/96105053/189111961-4b114303-ea71-4691-a329-6b79146bf429.png)

**Comment by corinnewo** [comment]
Thanks @GaliShapira - are you replacing them in JI Cloud?

**Comment by GaliShapira** [comment]
@corinnewo Done

**Comment by corinnewo** [comment]
@johnnynotsolucky The use case in other modules are all Title case. So it's Multiple Choice, Find the Answers, Find the Text, Where on the Map, Family Tree, Find the Differences.
