### ISSUE TITLE
Drag and drop - need to make it clearer in instructions/help text that ANYTHING that is draggable should be made interactive

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3119]
We should update the wording or instructions to indicate that any sticker which can be dragged around should be selected as an interactive sticker.

This comes after ticket https://github.com/ji-devs/ji-cloud/issues/3117 where the creator put all options on the screen, but only made the correct answers draggable (interactive). So when you tried to drag an incorrect item, the screen froze. This has now been fixed, but it would make interactions much more effective if all options that could be dragged are made interactive.

**Comment by ChaykeeMor** [comment]
What do you think?
Current Jiggling text:
Decide what's draggable
Select each item you want students to be able to move around the screen.
Change to:
Select ALL items you want students to be able to move around the screen. Right or wrong.

Instruction texts:
Where? | Text
-- | -- 
Wizard Tab: Select | Select ALL items that students can drag
Wizard Tab: Trace | Trace areas where items can be dropped
Wizard Tab: Place | Place each item in their correct areas

ALSO: The select tab is missing the graphic.
![image](https://user-images.githubusercontent.com/94056434/187873441-d7774208-6d0a-4457-ae8e-cecb9e07ec5c.png)

**Comment by johnnynotsolucky** [comment]
@ChaykeeMor, I've used the graphic from the Trace tab for now. I've asked Gali for the svg version of the image you attached above, and will update it once she's sent it.
