### ISSUE TITLE
Resources - My Resources are all 'Yom Kippur' and in Content the 79 resources are without thumbnails

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3120]
When I look at MY RESOURCES, all are listed as Yom Kippur resources, and all have thumbnails.
![image](https://user-images.githubusercontent.com/16290361/187697401-1ccd027a-2153-4388-a3f8-a49256916ae5.png)

However, when you go to CONTENT and click on the 79 resources, then they are all without thumbnails, show fronts as if they are JIGs. Backs are resources.

![image](https://user-images.githubusercontent.com/16290361/187698510-18099706-7a7d-4574-82e4-b3d1935e6429.png)

**Comment by RickyLB** [comment]
Names and thumbnail issue has been fixed in production.

<img width="1295" alt="Screen Shot 2022-08-31 at 3 51 24 PM" src="https://user-images.githubusercontent.com/76449893/187803561-10b803f4-b07f-4a5e-b108-bd956108773e.png">

**Comment by RickyLB** [comment]
@MendyBerger When I call the Resource search endpoint through Http request, the response contains 79 results. Same in the DB. But Jigzi.org is showing 59 for some reason. Any idea?

**Comment by MendyBerger** [comment]
Not sure, will have to take a look

**Comment by MendyBerger** [comment]
Showing 79 for me now

**Comment by MendyBerger** [comment]
@RickyLB still experiencing this issue?

**Comment by RickyLB** [comment]
Issue has been resolved!
