### ISSUE TITLE
Answer it : Add a new use case

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3122]
Screenshot:
<img width="370" alt="Screen Shot 2022-08-31 at 17 35 00" src="https://user-images.githubusercontent.com/88834002/187705409-88c7a02f-fbf7-4b44-805d-089eef3eb644.png">

Zeplin:
https://zpl.io/kDB3N6L

PNGs:
![find-the-differences-hover](https://user-images.githubusercontent.com/88834002/187705895-65272988-e35a-4a2b-aa91-1998ad2510b9.png)
![find-the-differences](https://user-images.githubusercontent.com/88834002/187705903-fdf883e8-c335-4db3-a245-4c7c6af327e4.png)

**Comment by ChaykeeMor** [comment]
@GaliShapira @corinnewo I think this should be an iSpy use case.

**Comment by corinnewo** [comment]
@ChaykeeMor We can add it to the iSpy module too. But Anat wanted it for this module too, emphasizing that there are multiple possible answers.

**Comment by corinnewo** [comment]
I have saved these in ji-cloud-media as differences.png and differences-hover.png.
