### ISSUE TITLE
Resources - PLAY count should be 'Views' and not all 1

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3130]
At the moment - all resources show plays of 1. If this can't be fixed quickly, then at least, please hide the play count.

Please see https://zpl.io/V1LEwQZ
1. Change the 'Play' count (which at the moment is all 1) to 'Used' and 'Liked', as in the Zeplin.
2. Would love to have the little icon that pops up when the card is turned over, as happens now for JIGs

Currently:
![image](https://user-images.githubusercontent.com/16290361/187901824-c4d7610b-bae8-4acf-9e84-f96cef9cdac6.png)

**Comment by corinnewo** [comment]
There is no way to **LIKE** the resource at the moment, so we can ignore that part!

**Comment by corinnewo** [comment]
@ChaykeeMor Should this be 'Viewed' rather than 'Used', as it shows in the Zeplin? Please confirm! Thanks

**Comment by ChaykeeMor** [comment]
> @ChaykeeMor Should this be 'Viewed' rather than 'Used', as it shows in the Zeplin? Please confirm! Thanks

Yes. I would go with 'Views'
