### ISSUE TITLE
Drag and Drop - Jiggling has disappeared and top header is also not there

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3131]
I was looking to check the Jiggling text in drag and drop, and the Jiggling is no longer there. Also, the heading has disappeared.

![image](https://user-images.githubusercontent.com/16290361/187929158-2001042d-3d7a-44d1-a875-b71a4f164613.png)

**Comment by johnnynotsolucky** [comment]
There was some invalid JSON syntax in the drag-drop.json file which I've corrected.

Perhaps JSON isn't the most user-friendly format to use for this? I think these issues may be permanently resolved once we implement localization for the system.
