### ISSUE TITLE
Add new themes and fonts

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3135]
New themes and fonts are defined in these JSON files:
[new fonts and themes.zip](https://github.com/ji-devs/ji-cloud/files/9476518/new.fonts.and.themes.zip)

I have placed the fonts in the fonts folder in ji-cloud-media. They should be listed alphabetically in the panel.

The correct order of the themes is listed here: (there is still a problem with Tu-Bishvat)
[new list of themes for dev- Sept2022.txt](https://github.com/ji-devs/ji-cloud/files/9476621/new.list.of.themes.for.dev-.Sept2022.txt)

**Comment by corinnewo** [comment]
The most updated list of fonts (now includes Tu Bishvat, that was problematic before):
[new list of themes for dev- Sept2022.txt](https://github.com/ji-devs/ji-cloud/files/9476781/new.list.of.themes.for.dev-.Sept2022.txt)
[Updated fonts and themes.zip](https://github.com/ji-devs/ji-cloud/files/9476793/Updated.fonts.and.themes.zip)

**Comment by MendyBerger** [comment]
Resolved
