### ISSUE TITLE
Fonts: bug in new fonts/ themes

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3163]
When clicking through the various themes while creating a flashcard activity, I noticed that on the cards, some letters in Hebrew/English at the end of the words disappear, and in other themes, the words are not displayed properly/ bottom half of words are  cut off (only when previewing the cards).

![Screen Shot 2022-09-08 at 6 34 31 PM](https://user-images.githubusercontent.com/78186896/189238220-5a3bc836-348f-4ef2-a6d7-ee3ddfeae16b.png)

![Screen Shot 2022-09-08 at 6 28 48 PM](https://user-images.githubusercontent.com/78186896/189237318-171b7c0c-f74d-48de-a164-da1ab2747cf7.png)
)

![Screen Shot 2022-09-08 at 6 20 28 PM](https://user-images.githubusercontent.com/78186896/189236183-5f3de309-b8bc-4560-9e08-bac4bad94b65.png)
![Screen Shot 2022-09-08 at 6 23 14 PM](https://user-images.githubusercontent.com/78186896/189236812-2b6a7573-d1b2-4b25-8ffd-0fd2576f265c.png)

**Comment by corinnewo** [comment]
This has been fixed on sandbox.
