### ISSUE TITLE
Editing text on all card games - can't see the keyboard icon on some backgrounds

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3164]
Gali, I think that the icon needs to be filled in with a solid background to cater for all themes.
![image](https://user-images.githubusercontent.com/16290361/189298648-8f69a0ab-5b8a-47ee-a9c4-ffc2549ef988.png)

**Comment by GaliShapira** [comment]
The design was made with white background to the icon and with the Dicta and Sefaria. 
<img width="210" alt="Screen Shot 2022-09-28 at 17 44 30" src="https://user-images.githubusercontent.com/88834002/192809786-9b409f52-9dbd-4196-9de6-9dce1c429c56.png">
https://zpl.io/p1mxn1y

Also, Can we make it that double-click on the text will be as selected in the kebab menu edit text?

**Comment by corinnewo** [comment]
Mendy - please put the button on the white background. And if you can solve the DICTA story like we discussed yesterday, that would be wonderful:

- Try to add in DICTA
- Keep it in edit mode while focus is in DICTA dialog
- Try and make it double click to edit the text (in addition to the menu 'edit')
