### ISSUE TITLE
Courses: Search results for courses - missing count of items and plays/likes count

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3168]
In the original design (https://zpl.io/aM36kWK), the results for courses has an icon with the number of lessons in the course, as well as the count of Plays/Likes. This is all missing from the current course listing in search results.
![image](https://user-images.githubusercontent.com/16290361/189330428-b6872e80-3427-4c65-a7f8-b5a8295279cd.png)

Please add:
1. Yellow icon with the count on it
2. Plays | Likes count

**Comment by corinnewo** [comment]
@MendyBerger I think this will be taken care of with Gali's updated card results component.

**Comment by MendyBerger** [comment]
@corinnewo correct, closing
