### ISSUE TITLE
Backgrounds & overlays - replacing the no image thumbnails

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3171]
As we got feedback that the thumbnails with the line are not clear we changed them to texts.

Old version:
<img width="545" alt="Screen Shot 2022-09-12 at 11 17 51" src="https://user-images.githubusercontent.com/88834002/189606996-100debcc-ee3b-4e58-a92b-d7722cb68e64.png">

Change to:
![ No overlay](https://user-images.githubusercontent.com/88834002/189607091-0dbcd1b1-c15f-4169-acc6-58d1380ccb6e.png)
![No background](https://user-images.githubusercontent.com/88834002/189607097-025b6fb2-e2f2-411f-af79-fe30ad142e1a.png)

**Comment by corinnewo** [comment]
This is the same as #3161. I need the svg inorder to replace on ji cloud.

**Comment by GaliShapira** [comment]
Pls see the SVGs

![no-overlay](https://user-images.githubusercontent.com/88834002/189620954-1d83fa19-6ae1-4341-a2eb-7698e69193e9.svg)
![no-background](https://user-images.githubusercontent.com/88834002/189620991-5838cac4-a78f-4054-8dff-74df4de83368.svg)

**Comment by corinnewo** [comment]
@MendyBerger I have saved the NO BACKGROUND icon as clear-image.svg and the NO OVERLAY as clear-image-overlay.svg in ....\ji-cloud-media\ui\module\_common\edit\widgets\sidebar\image-select

Please make sure that the overlay image is added to the programming. THanks!

**Comment by corinnewo** [comment]
@MendyBerger Please look at this, as it seems to be another case with caching. Currently, the icon shows on background as "No overlay", even though the clear-image.svg should say "No background". Thanks!

**Comment by MendyBerger** [comment]
resolved in 2302cfce4
