### ISSUE TITLE
Video settings - needs small edit

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3180]
In the video settings, the text does not flow for both options:

Currently:
"Student finishes this activity by...
    clicking on continue
    automatically after video"

I would like to suggest changing slightly:
"Student finishes this activity...
    by clicking on continue
    automatically after video"

@ChaykeeMor Do you agree?

![image](https://user-images.githubusercontent.com/16290361/189822919-1912d8b4-a74b-4572-9df5-7ea9cae8842a.png)

**Comment by ChaykeeMor** [comment]
sure

**Comment by corinnewo** [comment]
closed in favor of #3289
