### ISSUE TITLE
Improve keyboard image so that users know that it can be dragged

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3184]
Anat and others did not know that you can drag the keyboard.
Perhaps we need some indication that it is draggable? 

![image](https://user-images.githubusercontent.com/16290361/189869891-1a2933eb-10e3-49e2-acb5-bd7ef026fd7d.png)

**Comment by GaliShapira** [comment]
Pls see our suggestion, to add a tab with an icon and a text.
<img width="613" alt="Screen Shot 2022-09-22 at 14 52 07" src="https://user-images.githubusercontent.com/88834002/191739526-ba2f5e0a-88bb-4521-97cd-064da96968ce.png">

Zeplin:
https://zpl.io/b6GYAnP

icon:
![icon-drag](https://user-images.githubusercontent.com/88834002/191739574-06adf3c9-321a-4c5c-87d7-0c404fe0626a.svg)

**Comment by MendyBerger** [comment]
Resolved in 0d1f959a9
