### ISSUE TITLE
Card games - don't need the keyboard on the design pages

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3187]
On design pages, at the moment, there is no use for the keyboard, as you cannot edit the text here.
PLease remove keyboards from the design pages!

![image](https://user-images.githubusercontent.com/16290361/190089509-4541f730-fd55-4601-9416-136abe16db1d.png)

**Comment by MendyBerger** [comment]
@corinnewo made it only show keyboard when actually editing the card
