### ISSUE TITLE
Community - my profile: Setting "where I live" as public does not make it appear in "about" section

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3193]
When editing my details in my profile page, The "where I live" section can be set as public or private. Setting it as public does not make it appear in the "about" section.

<img width="357" alt="Screen Shot 2022-09-18 at 1 00 28 PM" src="https://user-images.githubusercontent.com/78186896/190896798-22835cec-592a-4f03-bcb3-6b2fba39c34f.png">

(btw, when changing any details from public to private,  the settings only update once I log out and back in to my account, not when pressing the "save" button.)

**Comment by corinnewo** [comment]
@chayaml You are right, it should appear, and should be searchable, so that I can find teachers in my area.... but because we are storing the string as a Google string, Mendy has not been able to extract the country reliably. @MendyBerger - is there any progress with this? It is very missed.

**Comment by MendyBerger** [comment]
@corinnewo haven't looked at this for a while, feel free to mark as August
