### ISSUE TITLE
Uploading image from web into card -crashed

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3217]
I was building word-image cards. Searched the web for 'palm leaf' and dragged it in to the card for 'schach'. 
https://sandbox.jigzi.org/asset/edit/jig/3b80325c-1c6a-11ec-ab1d-f390d2c510af/b0ef79d6-3969-11ed-aeb5-171666cbaccd

![image](https://user-images.githubusercontent.com/16290361/191418150-d67265cd-0fcc-4a66-930d-7070dd1e1e1e.png)

![image](https://user-images.githubusercontent.com/16290361/191418408-4c173929-f485-439b-bcda-fdbb4d36e5db.png)

Also note the words cut off.

This is the image that crashed - consistently: 
![th](https://user-images.githubusercontent.com/16290361/191419108-3c9472ba-f31e-48fb-9423-542ee203bfaa.jpg)

**Comment by MendyBerger** [comment]
Having trouble recreating

**Comment by corinnewo** [comment]
If it happens again I’ll let you know! It has not happened to me again at all. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by MendyBerger** [comment]
@corinnewo so can we close for now?

**Comment by corinnewo** [comment]
Yes

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
