### ISSUE TITLE
Upload image - Circle - no response when large file or PDF

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3218]
I tried to upload a jpg file of 9mb to test the upload. Got no response, nothing about size, and nothing happened.
Same thing when I tried to upload a PDF. No response and no feedback about wrong file type.

![image](https://user-images.githubusercontent.com/16290361/191419918-ed1e6af3-3542-41da-a910-7128b0336db9.png)

**Comment by MendyBerger** [comment]
Resolved in 5cb922a92
