### ISSUE TITLE
Poster - add in ability to print the poster

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3220]
Similarly to the print cards function on the cards, please add in the printer icon, and call it **Print poster** on the page "What do you want to do next?", after the Preview. Printing will print a high res image of the poster.

![image](https://user-images.githubusercontent.com/16290361/191501482-8967de02-cb0b-46f2-b0ea-f4c335778501.png)

**Comment by MendyBerger** [comment]
@corinnewo what about cover?

**Comment by corinnewo** [comment]
Good idea. Will be same as poster, except Print cover!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by MendyBerger** [comment]
Resolved in d2795792e
