### ISSUE TITLE
Create - undo/redo seems to take you to preview, instead of what it used to do

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3222]
Undo and Redo used to work really nicely when David first built that. I don't know when it went wrong, but it is now taking you to the preview screen each time, instead of the the previous/next state.
Please look into this.

**Comment by corinnewo** [comment]
https://sandbox.jigzi.org/asset/edit/jig/531595d8-6260-11ec-8f97-d79fa4eaf220/5311ebe0-6260-11ec-8f97-131c39caf3bb  Happens on the cover in sandbox

**Comment by MendyBerger** [comment]
Can't reproduce this anymore, @corinnewo  is it still happening for you?

**Comment by corinnewo** [comment]
@MendyBerger No, it seems to be working fine now! THanks!
