### ISSUE TITLE
Add to curation table -status of private/public  - in addition to the hide 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3224]
Following on from #3205, where it turned out that the problem was not that the JIG was not found, but that it was made private by the creator, so never showed up in search results:

- We need to know that something has been made private by the creator
- We need to be able to hide a JIG, no matter what the creator has done.

Please add this to the curation table - ability to HIDE/UNHIDE, and to indicate whether the game is public or private.

I found this in zeplin: https://zpl.io/29W3yop, where there are 4 statuses
- public (searchable), private (not searchable), block and hide. I think
that we need the Public, Private (both set by creator) and Hide (set by
curator). I don't remember what the difference is between HIDE and BLOCK.

**Comment by MendyBerger** [comment]
@corinnewo I've added a column to the table which can be public/unlisted/private, feel free to reopen if that's not enough

**Comment by corinnewo** [comment]
Hi @MendyBerger Mendy - this is great, to be able to see if it is private or not. But I also need to be able to make something public in curation. This is important mainly for the Ji Tap Library imports, as if they were private when imported, they can never be seen - as the creator cannot make it public themselves. Please can you add to the internal page the ability to change something that is private to public?

**Comment by MendyBerger** [comment]
Resolved
