### ISSUE TITLE
Sharing resources - we need to be able to share the URL of a resource

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3228]
If I want to share the resource, at the moment, I view it and send the URL of the link.
We need to be able to share the resource, like we can share a JIG or Course, so that people are sent to Jigzi and not to the attached file.
![image](https://user-images.githubusercontent.com/16290361/192789273-1eebc8da-ea47-4508-bee1-9c10fe0384ff.png) 

It should be similar to the share in a JIG, but clicking the share will open up the SHARING OPTIONS dialog, which will just have the links to 'Share to Google Classroom' and  'Copy resource link'.

![image](https://user-images.githubusercontent.com/16290361/192790074-9b745e1c-08d7-47b2-91fa-5cb994120ba0.png)

**Comment by MendyBerger** [comment]
This turned out to require a major rewrite of a large amount of code, but it's now implemented

**Comment by corinnewo** [comment]
@MendyBerger  - this is amazing - I am sorry that it caused a major rewrite, but it is an important one, as it will lead people into Jigzi and not into random PDF files.
I have one small correction to make here - Please change the 'resource link copied' to 'Resource link copied'.
![sharing options2](https://user-images.githubusercontent.com/16290361/193504643-72c5f593-8fdb-4738-abc4-55c9d3f729e6.JPG)
![sharing options1](https://user-images.githubusercontent.com/16290361/193504653-0da5496c-f110-49be-8898-320ed1077131.JPG)

**Comment by MendyBerger** [comment]
Let's discuss

**Comment by corinnewo** [comment]
Closed this ticket in favour of #3258
