### ISSUE TITLE
Change themes component for card games so the background can be seen

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3229]
I have built new icons for the cards games, for example:
icon-cards:
![icon-cards](https://user-images.githubusercontent.com/88834002/192791276-7289a42c-404b-4308-ba33-37f2a08f8320.jpg)

Icon-cards-hover:
![icon-cards-hover](https://user-images.githubusercontent.com/88834002/192791299-b4d815fc-bd63-4a5c-adc0-b9b72221d058.jpg)

The thumbnail is the same size and format as the thumbnails of the canvas activity (non-cards ones):
icon +icon-hover:
![icon-hover](https://user-images.githubusercontent.com/88834002/192791437-2f4a653e-058e-422b-aaae-2bcc3b4b5b22.jpg)

![icon](https://user-images.githubusercontent.com/88834002/192791398-ad642476-88b0-4a6d-8cdc-63484e0c0f68.jpg)

I saved in each theme, the name of the new icon is:
**icon-cards
icon-cards-hover**

So from now on, we need to duplicate the component of the non-cards games and change the names of the images to the new name.

**Comment by corinnewo** [comment]
Please implement the component used in non-card activities to show the theme designs (one large icon with a hover), but in the card games, show the images with the pairs of cards on the background - one large image with hover, that Gali has prepared in each theme's folder: 
icon-cards.jpg
icon-cards-hover.jpg

Currently, there are 2 parts to the image, left and right. Only the left-hand icon has a hover. This must be replaced with the single image and hover.
