### ISSUE TITLE
Add branding to the cover/poster printout

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3233]
We need to add to the bottom of the printout like we have on all the cards that are printed. Thanks!

![image](https://user-images.githubusercontent.com/16290361/192812766-c2803b24-2d17-40e6-a028-96aee746c7a6.png)

**Comment by corinnewo** [comment]
@GaliShapira Please add in the graphic to this ticket. Thanks

**Comment by meravs** [comment]
Screen shots:
![Screen Shot 2022-10-09 at 11 22 33](https://user-images.githubusercontent.com/96105053/194746026-db56b30d-911a-4b97-8c11-48fd0e320b3f.png)
![Screen Shot 2022-10-09 at 11 22 22](https://user-images.githubusercontent.com/96105053/194746027-d0ad94ce-972e-4f4f-89c2-84cbecf42aaa.png)
![Screen Shot 2022-10-09 at 11 22 14](https://user-images.githubusercontent.com/96105053/194746029-f8dec5b4-6fa0-40b8-97cf-1a17f6796c55.png)

Links to zeplin:
https://zpl.io/dxjjGQn
https://zpl.io/9qAA1MY
https://zpl.io/RMLL7Kg

Logo svg:
![Logo Jigzi - print canvas](https://user-images.githubusercontent.com/96105053/194746210-b02bd2d5-6dc7-43da-8594-2ccadeaff3ae.svg)

**Comment by corinnewo** [comment]
Chaykee and I both feel that this should not have the word Jigzi twice. @GaliShapira Please make a version in SVG that looks more like this one that we discussed. For the cards as well!

![logo-svg copy](https://user-images.githubusercontent.com/16290361/198577565-c4b9c051-0a6a-4eea-a2ee-09e6df32ecb1.png)
