### ISSUE TITLE
Create - Add 2 more kabob menu functions

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#3236]
Need to update the JIG panel kabob menus as in #2200 
And add for each activity:
Save design - saves a screenshot of the entire canvas to computer
Print design - prints a screenshot of the entire canvas to computer

Because activities like Drag&Drop, Type Here, are very different in the building mode versus the final result. Should be excluded from this option.

If possible, Answer This should produce one file per question or also be excluded.

**Comment by corinnewo** [comment]
Closed in favor of #3252
