### ISSUE TITLE
Publish - text should change to reflect the state of the privacy toggle

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3239]
In the publish , if the toggle is off, it should say "My JIG is private" and when it is on "My JIG is public".

![image](https://user-images.githubusercontent.com/16290361/193238268-fc0379d7-2541-41d6-a7fc-c72ba3f4efec.png)

**Comment by MendyBerger** [comment]
Let's discuss

**Comment by corinnewo** [comment]
At ideation, everyone agreed that the text should reflect the toggle, just to make it clear what the current status is.

- Change “My JIG is private” when toggle is on left.
- When toggle switched off, there should be a warning popup that @ChaykeeMor will write the text for the popup, based on the original design on https://zpl.io/awzyOnd
- Text will have a warning that 

> - Making it private means it will not show up in any search results
> - You can share the link once it is published as private, and assign to your students
> - Encourage to share with the community

**Comment by MendyBerger** [comment]
@corinnewo can I write “My JIG is unlisted” to reflect what we're really doing a bit better?

**Comment by corinnewo** [comment]
Good idea! Go ahead please!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
