### ISSUE TITLE
Flashcards - Add in the Feedback tab to the settings

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3248]
Anat said that it was important to add in the feedback tab to the flashcards, as there was a use case for teachers to want to give feedback when all cards have been done. (We will be adding in a setting to define how many pairs will be shown out of the full set, and not only infinite the way it is now).

Please add in the Feedback tab to the settings, after the Instructions tab.

**Comment by johnnynotsolucky** [comment]
Added in #3278
