### ISSUE TITLE
Printing cards - must have the fonts that the teacher defined

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3250]
If a teacher has chosen a specific font for Hebrew, like printed or script, then the printed cards should reflect this.
Please try and make the printouts use the fonts that are defined in the JIG.

**Comment by corinnewo** [comment]
Discussed at sprint: Will wait 1 second for the fonts to load - Mendy concerned that it may not be ok if the internet is slow. We should try and see if there is a problem. PLease go ahead!

**Comment by MendyBerger** [comment]
I believe this has been done already
