### ISSUE TITLE
Login/registration should have cutoff at 1280px, and not as it is now

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3257]
Josh and Anat both complained that they see the login with a scroll bar. When I saw what they are seeing, I saw that they do not have the illustration either. When they zoomed out to 60%, suddenly the illustration appeared. 
Please change the cutoff point to 1280!

They also complained that the OOPS screen flashes on screen before it diverts to the login screen (if you are not logged in and try to create)
![image (3)](https://user-images.githubusercontent.com/16290361/194351496-077282a8-2cac-4f82-af77-3db282f954d4.png)

BTW, the courses still need to be cutoff at 1280. PC still showing stacked courses, and it looks terrible. #3185

**Comment by MendyBerger** [comment]
Resolved
