### ISSUE TITLE
Drag and drop: Feedback pop up appears under the text

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3264]
Feedback appears under the text inserted in step 2
@corinnewo 

<img width="1228" alt="Screen Shot 2022-10-13 at 12 13 59 PM" src="https://user-images.githubusercontent.com/78186896/195556350-5ca01458-e735-4b31-9798-5c8095e54e4e.png">

**Comment by corinnewo** [comment]
Closing this, as the new system of instructions and feedback will take care of this issue.
