### ISSUE TITLE
Force login/registration after 1 JIG play (only for teacher players, not students)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3274]
Josh and Chana want this implemented - to make the user who is not yet logged in to login in after playing one JIG, and to give a message along the lines of 
"Thanks for trying out Jigzi! To see more JIGs and to enjoy Jigzi to its fullest, please take a minute to set up your free account."
@ChaykeeMor please make this copy friendlier! Then @MendyBerger can implement.

(I know that we discussed 10 JIG plays, but that was changed today!)

**Comment by ChaykeeMor** [comment]
Enjoying Jigzi? Set up a FREE account!

What's inside?
Explore a huge library of JIGs created by educators like you!

Generate your own JIGs in just a few clicks with access to thousands of images made just for you!

Easily share JIGs and resources with your students or colleagues!

Network with other users in our community and form circles to share ideas and collaborate.

Receive resources specially created by our team straight to your inbox!

**Comment by GaliShapira** [comment]
I would take off the community at the moment as it's still a beta version 
And maybe add something about the huge library of images to use
Once they are ready and confirmed I will try to make the spacing of them all.

**Comment by GaliShapira** [comment]
This is the design:
https://zpl.io/7w6MGyj
<img width="959" alt="Screen Shot 2022-10-31 at 14 35 13" src="https://user-images.githubusercontent.com/88834002/199009114-51f4ba15-d6bb-43f5-bfbd-4b685691d445.png">

**Comment by GaliShapira** [comment]
I believe we can have the same design for these 2 use cases.
Texts will change. 
And I think the option to login if you already have an account will be bigger.

**Comment by ChaykeeMor** [comment]
@GaliShapira  think you might find that some the texts need to be shortened once it's input in the design. Let me know.

**Comment by GaliShapira** [comment]
Hi @ChaykeeMor Pls see the design of the Forced login popup we discussed today in the ideation.
The design is not final. But would love to get hte final texts.
<img width="725" alt="Screen Shot 2022-12-08 at 17 33 24" src="https://user-images.githubusercontent.com/88834002/206487833-1cd0ea7c-79c5-47cd-b7d2-44a81a3c9e24.png">
https://zpl.io/llRGJKk

**Comment by corinnewo** [comment]
This has been implemented after 5 plays.

**Comment by corinnewo** [comment]
This has been implemented after 5 plays.

**Comment by ChaykeeMor** [comment]
@corinnewo wrong design and texts implemented. Worth fixing? or wait until paywall implemented and then fix with specific parameters when to show pop up for each subscription level?

**Comment by corinnewo** [comment]
@ChaykeeMor I think that it is worth changing, as the current one has text that is aimed at getting you to sign up. Our 'Time to login' is assuming you have an account, but have not yet logged in (and by the way, you can sign up for free). It is subtle, but I think it is important. What do you think?  
How can we do specific parameters when they are not logged in yet? I think it will remain this generic one, and only once they have logged in can we start with specific parameters.

**Comment by ChaykeeMor** [comment]
@corinnewo Agreed. But the Zeplin was never updated with the correct texts.. so that needs to be done before sending back to dev.

By parameters I mean pop up for after 5 shares, or after clicking create or after wanting to share.. etc.

**Comment by corinnewo** [comment]
@ChaykeeMor I do see that the Zeplin is not updated with your texts! But I think that it should be the same generic 'Time to sign in' popup. Unless you were thinking of saying something specific , like 'Time to sign up before you can share', or something like that?

@GaliShapira Please update the Zeplin with Chaykee's texts so that dev can go ahead and implement without error. Thanks!

**Comment by GaliShapira** [comment]
Pls see the updated design with updated text.

https://zpl.io/Am067Oq

<img width="510" alt="Screen Shot 2023-01-04 at 10 15 47" src="https://user-images.githubusercontent.com/88834002/210512069-4487938f-135e-4c42-b7cd-b9861c6afc28.png">

**Comment by ChaykeeMor** [comment]
@GaliShapira Any chance we could go back to the other design it's far superior. More balanced and this design has so much text on the right side with a button that get's lost and no longer looks like a button and the Jigglings are suddenly squished. Is the problem the text? I could try to cut it down.
