### ISSUE TITLE
Flashcards: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3278]
- [x] reword "How should your cards be displayed?" to "How should card pairs be displayed?" and options are 'double sided' and 'side by side'
- [x] Move 'card position' to an extra option
- [x] Extra option
  - [x] 'Which card should be face-up? ' 
  - [x] and then the option is the same icon as card position, but the caption is 'swap'.
- [x] New option: "Should student view all pairs?" and options are 'show all' and 'show some'. "Show some" will have a dropdown of a count of how many pairs to show.
- [x] With the addition of this new option, there is a way to end the flashcards, so we need to add in the tab "Feedback" to the settings step, and this will be shown when either all pairs have been shown, or else the number of pairs has been reached. (Ticket #3248)

**Comment by corinnewo** [comment]
@GaliShapira Please add in link to the Zeplin settings for flashcards here.

**Comment by corinnewo** [comment]
https://zpl.io/09WAPrQ

**Comment by GaliShapira** [comment]
Screenshot:
<img width="545" alt="Screen Shot 2022-10-25 at 15 54 00" src="https://user-images.githubusercontent.com/88834002/197778275-49aa874e-3323-4209-abfb-c6fc68025732.png">

**Comment by GaliShapira** [comment]
Hi @johnnynotsolucky Pls see the icons:
![Settings - some-selected](https://user-images.githubusercontent.com/88834002/206178173-a7fedaba-830c-4f01-8a02-31621cf1f93d.svg)
![Settings - show all-selected](https://user-images.githubusercontent.com/88834002/206178181-5264a153-3395-419b-8c06-4248295b96d2.svg)
![Settings - some-hover](https://user-images.githubusercontent.com/88834002/206178184-ce2524e7-ea1d-4457-be9a-8dd42e3c1622.svg)
![Settings - show all-hover](https://user-images.githubusercontent.com/88834002/206178190-6485b5fb-903f-4ea8-ab15-38dc3b5f1d89.svg)
![Settings - some](https://user-images.githubusercontent.com/88834002/206178193-f2e7021f-5778-48f8-ae4f-3345e85f45d0.svg)
![Settings - show all](https://user-images.githubusercontent.com/88834002/206178197-aff43229-379c-4da1-9b9a-aa905642304e.svg)
