### ISSUE TITLE
Memory game: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3279]
- [x] Change "How should your cards be displayed?" to "Should student view all pairs?" and options are 'show all' and 'show some' with the pulldown of how many pairs. 
- [x] Pulldown must have 'pairs' not 'cards'
- [x] Time limit - unchanged

 If >14 pairs of cards:
- [ ] ~disable the 'show all' option~
- [x] default the count to 14 pairs
- [x] Change 'show all' to 'show max' and have a tooltip "We can only show a maximum of 14 pairs in a memory game."

@GaliShapira Please add in the link to the Zeplin for memory game settings here

**Comment by GaliShapira** [comment]
Zeplin:
https://zpl.io/3XyG0rW

Screenshot:
<img width="815" alt="Screen Shot 2022-10-25 at 13 14 47" src="https://user-images.githubusercontent.com/88834002/197747501-c909766e-40b7-4297-b9c1-5eac27c78731.png">
