### ISSUE TITLE
Matching: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3281]
- [x] For option "How should your cards be displayed?", change the icon (should not be multiple choice)
- [x] Pulldown of the number should say 'pairs' and not 'cards' (Display [x] **pairs**)

@GaliShapira Please add in the link to the final Zeplin for Matching settings here

**Comment by GaliShapira** [comment]
Also pls change the icon to matching new icon:
[icons_matching.zip](https://github.com/ji-devs/ji-cloud/files/9860186/icons_matching.zip)

Zeplin:
https://zpl.io/amLQxd6

Screenshot:
<img width="590" alt="Screen Shot 2022-10-25 at 14 57 04" src="https://user-images.githubusercontent.com/88834002/197768643-7b0f9a43-e1ce-4928-a319-1f7f97c986ca.png">
