### ISSUE TITLE
Multiple choice: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3283]
- [x] In the option "How should your cards be displayed?", the pulldown should say "Display [x] choices" instead of cards.
- [x] **Remove** the option "How many tries does the student get?" altogether

@GaliShapira Please add in link to Zeplin here

**Comment by GaliShapira** [comment]
Zeplin:
https://zpl.io/Nwd4md4

Screenshot:
<img width="445" alt="Screen Shot 2022-10-25 at 15 26 00" src="https://user-images.githubusercontent.com/88834002/197772457-b08bfe6c-1c8b-4c26-a8f1-f2f419dc107c.png">
