### ISSUE TITLE
Cover: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3284]
Add in the settings tab, which is TOTALLY missing:

- [x] Add in option "Student views this page until..." and the options are 'clicking next' and 'after audio'
- [x] If there is audio recorded, then the default option is 'after audio'
- [x] If NO audio recorded, then force the 'clicking next' option.
- [x] Make sure that the 'clicking next' icon is an arrow like in the progress bar, and not the current continue button.
- [x] Add tooltip if there is no audio recorded, but click 'after audio': "This option available only when you have added audio."
- [x] Add in tab 'Instructions' to the cover settings, that will play before the audio of the content. (Most people won't have instructions on the cover, but there are use cases when teacher might want to give an instruction for the whole lesson...)
- [x] Add after-audio icon
- [x] Implement ending so that it moves to next activity based on new setting

@GaliShapira Please add in the Zeplin link here

**Comment by GaliShapira** [comment]
Zeplin:
https://zpl.io/V0OEvzQ

See the new icon for clicking next:
[clicking next.zip](https://github.com/ji-devs/ji-cloud/files/9860235/clicking.next.zip)

Screenshot:
<img width="663" alt="Screen Shot 2022-10-25 at 15 31 16" src="https://user-images.githubusercontent.com/88834002/197773639-a4bbfbbe-041c-48c1-a2ae-69c86b5f44e7.png">
