### ISSUE TITLE
Poster: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3285]
In addition to #2629, here are the settings that should be in the poster:

- [x] Same continue as in cover, ie Add in option "Student views this page until..." and the options are 'clicking next' and 'after audio' (see ticket #3284)
- [x] Add in instructions tab, no feedback, as in cover.
- [x] Make sure that the instruction audio plays BEFORE the audio of the content.
- [x] Implement ending so that it moves to next activity based on new setting

@GaliShapira Please add in link to the zeplin.

**Comment by GaliShapira** [comment]
Zeplin:
https://zpl.io/VYzAL0E

Screenshot:
<img width="843" alt="Screen Shot 2022-10-25 at 15 33 35" src="https://user-images.githubusercontent.com/88834002/197774298-427c30fc-c06d-4095-bcd3-ea8413626e58.png">
