### ISSUE TITLE
Listen and Learn: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3286]
- [x] Change "Student finishes this activity by..." to "Student views this page until…"
- [x] Change the options for "Student finishes this activity by..." to "clicking next" (with updated icon of arrow) and "clicking all items"
- [x] Erase third option of 'clicking a minimum'

@GaliShapira please add in the link to the zeplin

**Comment by GaliShapira** [comment]
Waiting for after the ideation for the final open decision regarding the highlights.

**Comment by GaliShapira** [comment]
Zeplin:
https://zpl.io/nolZ1Pr

Screenshot:
<img width="511" alt="Screen Shot 2022-10-26 at 20 15 47" src="https://user-images.githubusercontent.com/88834002/198093173-ebfc9610-c002-42b7-b3b9-b4212fb360eb.png">
