### ISSUE TITLE
Drag and Drop: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3287]
- [x] Take out the first option of "Student finishes this activity by..." as student can always click out of the activity.
- [x] Move timers to be the last option
- [x] Change "Highlight clickable areas:" to "Highlight area to drop items:"
- [x] The highlighting is too long. Can we change it to start without the highlight, then a brief flash, and hide.

@GaliShapira Please add in Zeplin links

**Comment by GaliShapira** [comment]
Zeplin:
https://zpl.io/PqzQLOL

Screenshot:
<img width="471" alt="Screen Shot 2022-10-25 at 15 43 10" src="https://user-images.githubusercontent.com/88834002/197776033-d9d81008-25fa-4eb9-9c8d-38b4a6d912a5.png">
