### ISSUE TITLE
Video: Settings FINAL

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3289]
- [x] Change option "start automatically" to "play on click", and all options start off unselected.
- [x] Change option "Student finishes this activity by..." to "Student views this page until..." and the options are 'clicking next' and 'after video'

@GaliShapira PLease add in the Zeplin links

**Comment by GaliShapira** [comment]
Zeplin:
https://zpl.io/VOyKXg8

New icon:
[icn_settings_video_play_on_click.zip](https://github.com/ji-devs/ji-cloud/files/9860303/icn_settings_video_play_on_click.zip)

Screenshot:
<img width="464" alt="Screen Shot 2022-10-25 at 15 38 57" src="https://user-images.githubusercontent.com/88834002/197775796-2450e531-93bd-46ef-a7a7-c95509c7a7c0.png">
