### ISSUE TITLE
Matching - Can we change the 3 question marks to be in the color of the text of the selected theme?

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3294]
As we dont know what will be the card color...
<img width="540" alt="Screen Shot 2022-10-25 at 15 02 38" src="https://user-images.githubusercontent.com/88834002/197768308-d55b1157-ea67-4a82-822c-f54582a57ef0.png">

**Comment by corinnewo** [comment]
I'll check with @johnnynotsolucky, but it should be possible.
