### ISSUE TITLE
Player - timer - UI changes

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3298]
Can you kindly place the clock icon + time centered (same margin from left and right)
<img width="71" alt="Screen Shot 2022-10-26 at 11 53 28" src="https://user-images.githubusercontent.com/88834002/198093452-a9610ea4-60ad-4cc8-be55-6749db26ace7.png">

Also, Do you know why the image looks so bad? What do you need from my side? Can I replace it with a gif?
<img width="321" alt="Screen Shot 2022-10-26 at 11 54 46" src="https://user-images.githubusercontent.com/88834002/198093467-2e6c145e-1c0d-4859-9981-6ba67e226a63.png">

**Comment by corinnewo** [comment]
@GaliShapira please attach the correct timer graphic so that we can see what it should be. Thanks!

**Comment by MendyBerger** [comment]
@GaliShapira 

The timer is actually centered, it just doesn't look that way because of the rounded side. 
![image](https://user-images.githubusercontent.com/12537668/200942206-5968ecca-70c0-439e-aa22-75cbb2b62d4e.png)


Please send me the clock image as svg

**Comment by GaliShapira** [comment]
Hi @MendyBerger 
Thanks, You are right, its an optical illusion that makes it look like it should be placed a bit more to the right.
We made a gif animation for the clock, if you can place it instead of the image. 
See the gif:
![clock-new4](https://user-images.githubusercontent.com/88834002/201073169-1d36e0b6-fb22-48a5-b129-fff3ac77de32.gif)

If you cant, pls use the svg:
![clock](https://user-images.githubusercontent.com/88834002/201073234-a9ade230-c7a5-471e-a9c5-1faf5348c85d.svg)

**Comment by MendyBerger** [comment]
@GaliShapira if you can give me an svg with the animations that'll be great, otherwise I'll just use the gif

**Comment by GaliShapira** [comment]
@MendyBerger 
We converted the gif to animated svg. 
We cant see the preview... so we don't know if it was exported well. 
See attached.
Does the svg have any benefit over the gif? Why not using the gif?
![clock-new4](https://user-images.githubusercontent.com/88834002/201665260-e73b8017-32da-47d8-a3fd-1ce033d2e0a5.svg)

**Comment by MendyBerger** [comment]
@GaliShapira SVGs are MUCH smaller and are a lot clearer on high res screens, but I can use the gif for now

**Comment by MendyBerger** [comment]
Resolved
