### ISSUE TITLE
New preview flow - texts needed

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3299]
Zeplin:
https://zpl.io/9qJ5EZz

<img width="958" alt="Screen Shot 2022-10-31 at 14 16 01" src="https://user-images.githubusercontent.com/88834002/199005794-cc96de04-40a4-498d-b31e-c8cdf85efa7b.png">

**Comment by ChaykeeMor** [comment]
Like what you see?

To make changes, click back to any step.
If you are happy with your activity, click Done.

**Comment by GaliShapira** [comment]
Love it.
I updated the texts on the Zeplin and my earlier comment above.
