### ISSUE TITLE
Logo on printed cards - should not have Jigzi twice, rather logo and .org

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3304]
Currently in the cards:
![image](https://user-images.githubusercontent.com/16290361/198564193-9efffb65-5a02-499b-b858-3bcb3ce7da84.png)

There is no need to have the word Jigzi repeated twice. 
@GaliShapira  - please provide a graphic with the logo and '.org' added after it. (what we discussed in Ideation)

**Comment by GaliShapira** [comment]
Hi @corinnewo 
Pls see the updated svg logo:
![logo for cards](https://user-images.githubusercontent.com/88834002/201839468-4e513cf3-f83b-4460-b880-8dd6cafd254e.svg)

Screenshot:
<img width="847" alt="Screen Shot 2022-11-15 at 8 09 09" src="https://user-images.githubusercontent.com/88834002/201839532-50d59933-0dae-4982-8d9d-18b5c1ba2643.png">

Zeplin:
https://zpl.io/406lGdy

**Comment by corinnewo** [comment]
That's great, much better! Thanks,

**Comment by corinnewo** [comment]
@MendyBerger Please also replace the logo on the printed poster and cover. Thanks.

**Comment by corinnewo** [comment]
@RickyLB You have not used the graphic that Gali wanted. Please see the Zeplin (https://zpl.io/406lGdy) for the new graphic of 'Jigzi.org'. On the cards, the '.org' does not look connected to the Jigzi part - please use the new graphic and delete any text. New graphic is "Jigzi.org" in grey.

The same goes for the poster and cover print - please use the latest graphic for "jigzi.org'". Thanks!

[Jigz222i.pdf](https://github.com/ji-devs/ji-cloud/files/10216967/Jigz222i.pdf)

**Comment by RickyLB** [comment]
@corinnewo Didn't realize the logo in Gali's message. I'll apply that one.

**Comment by corinnewo** [comment]
Thank Ricky. Glad you found it. 

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by RickyLB** [comment]
@corinnewo New logo has been added!

**Comment by corinnewo** [comment]
@RickyLB Thank - looks great on the cards.
Please can you also add to the print of the **Cover** and **Talking Poster** modules. They are also printed from the Post-preview page. Thanks!
