### ISSUE TITLE
After done page

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3326]
https://zpl.io/mDz90Km
https://zpl.io/Am0Zy9n
https://zpl.io/noAdRPv
https://zpl.io/z8vAol7

**Non cards games:**
- Pls change the order of buttons accordingly.
- We made the text shorter, took out one line (Its now a part of your JIG)
<img width="431" alt="Screen Shot 2022-11-03 at 15 32 48" src="https://user-images.githubusercontent.com/88834002/199734434-34cdb80e-cc23-4528-a89a-01039f2b5ef0.png">

**Cards games:**
- Pls change the order of buttons accordingly.
- We made the texts shorter:
1. Took off "Its now a part of your JIG"
2. We made this text shorter: "Use this content in:" 
<img width="437" alt="Screen Shot 2022-11-03 at 15 32 55" src="https://user-images.githubusercontent.com/88834002/199736506-a742b3bc-19f1-4b94-8a00-ba2956f322c6.png">

**In all activities:**
- Make the gaps between lines smaller
- Align the names of buttons to the top
- See font sizes and margins, I made the same version for all screen sizes, including tablets.
<img width="752" alt="Screen Shot 2022-11-03 at 15 37 13" src="https://user-images.githubusercontent.com/88834002/199736477-e7debed7-3105-4e41-8fed-fd5f1e4fc3de.png">

**Comment by RickyLB** [comment]
@corinnewo @MendyBerger @johnnynotsolucky 

The coloring surrounding the activities isn't on the platform. It's not specified in the issue, but is this something that needs to added?

![Screenshot 2022-12-02 at 1 16 17 PM](https://user-images.githubusercontent.com/76449893/205387916-5b095ff0-c9cc-4499-ba8d-7976480cf1e3.png)

**Comment by johnnynotsolucky** [comment]
Closed in #3413
