### ISSUE TITLE
PLAYER: Pause button behavior

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3327]
Currently, if you press PAUSE, the button changes to the triangle, and audio is paused.
When you go to the next screen, the button still shows the triangle, but audio starts playing.

Please change to:
1. Press pause, audio stops and button changes to the triangle.
2. Press the triangle, the button toggles to the ON PAUSE button
3. If you don't toggle the pause button, but click the NEXT or BACK arrows, on the new screen the PUASE button will now be the pause and not triangle, and the audio will start as normal.

**Comment by MendyBerger** [comment]
Is this still an issue? I thought we fixed it

**Comment by corinnewo** [comment]
Yes, it is fixed! Closing.
