### ISSUE TITLE
Accessibility: Blind users need to be able to go from screen to screen with keyboard

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3328]
Teacher who has created successfully for blind children using JI TAP reported that Jigzi does not allow for blind children to simply click a screen to continue. She asked for keyboard shortcuts.
Next button - right arrow
Back arrow - left arrow

If a Hebrew RTL player, then the arrows should work with left arrow to go next, right arrow to go back.

**Comment by MendyBerger** [comment]
Done
