### ISSUE TITLE
Memory cards - make matched cards visible on the panel on left

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3331]
At the moment, when you find a pair, they pile up on the left. Teachers have complained that it would be more valuable if we had the pair visible, reinforcing the words and images. We had discussed visible on hover (https://github.com/ji-devs/ji-cloud/issues/1724). But now we all agree it would be best to lay out the pairs one per line, with the most recent pair at at the top of the area. If there is a need to scroll, then add in the scroll bar.

![137953499-1c841e55-5e94-40f5-b1a7-bcc33f393357](https://user-images.githubusercontent.com/16290361/199947388-b69b5f29-dbde-49cf-9ab5-121b88f9b25c.png)

@GaliShapira , please add in zeplin here.

**Comment by meravs** [comment]
Screen shot:
![Screen Shot 2022-11-08 at 12 22 58](https://user-images.githubusercontent.com/96105053/200539975-61a36f72-682c-484b-be71-8cd505a9eead.png)

Link to zeplin:
https://zpl.io/GEgG84m

**Comment by GaliShapira** [comment]
An updated design!!!
@johnnynotsolucky @corinnewo 

https://zpl.io/DlRoK0w

<img width="771" alt="Screen Shot 2022-11-15 at 7 58 39" src="https://user-images.githubusercontent.com/88834002/201838165-2da77252-60db-4c14-be7b-44ead194ca1d.png">
