### ISSUE TITLE
Hebrew keyboard on iPad: can't move it around and close is out of the screen

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3339]
The Hebrew keyboard on the iPad can not be dragged around.  Also, the x button looks distorted, and is outside of the tappable area.
![IMG_6991](https://user-images.githubusercontent.com/16290361/200285876-83dc53ae-8386-4ffa-8d09-40a313c2f8a2.PNG)

Please make the keyboard draggable and place the keyboard within the ipad area.

**Comment by MendyBerger** [comment]
Fixed
