### ISSUE TITLE
Student code - remove expiration of the code and codes for courses as well

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3342]
Currently, a teacher creates a code to share with the students, and it expires after 2 weeks. Teachers asked that we do not expire the code as they have to update their worksheets every 2 weeks. At sprint we decided:

1. Rather have 6 digits instead of 4
2. A teacher generates the code when he/she wants to share the game - and the code does not expire
3. We discussed using letters and digits, but taking out letters that would be confusing (1,l,i,0,o), but at ideation we felt that it was better to just use numbers. 
4. One game can have several codes, and it will be a way for us to connect a teacher and students.
5. Need to have a code to share courses as well to students (student player)

**Comment by corinnewo** [comment]
@GaliShapira Please look at the UI for sharing and how it will change. Thanks!

**Comment by corinnewo** [comment]
@GaliShapira Please add in any changes to UI here. Thanks!

**Comment by GaliShapira** [comment]
Pls see the 6 digits design in both pages: The code page and on publish.
https://zpl.io/Am0wM3n
https://zpl.io/beGzYxP

<img width="956" alt="Screen Shot 2022-12-19 at 14 57 52" src="https://user-images.githubusercontent.com/88834002/208431537-4511f5e7-4d19-484d-84f4-207cf15e34bb.png">

<img width="956" alt="Screen Shot 2022-12-19 at 15 05 02" src="https://user-images.githubusercontent.com/88834002/208432656-051239b5-ac7b-4905-bdd2-a2d313b4ddb6.png">

**Comment by corinnewo** [comment]
@GaliShapira - please take out the 'Valid for a week until....' text in the Zeplin, as we are taking out the expiration totally. Thanks!

**Comment by MendyBerger** [comment]
@corinnewo have the limits of having a _6 digit number only_ code been considered?

**Comment by corinnewo** [comment]
yes - they were adamant that having letters in there is hard for children, especially kids with a different alphabet, like Hebrew, Russian, Arabic, etc. 
10 digits in 6 positions will give us (10 to the power of 6) combinations, which is 1,000,000 unique codes for sharing. I think that we should go for it. If we are in the position that we run out of codes, we could possibly clear out codes that were generated more than x years previously. But it will be a great problem to have!

**Comment by corinnewo** [comment]
In discussion with LB, we decided that in the 2 weeks it will take to have the 4-digit codes to die out, add in an enter and a text that if the code is 4 digits, to press enter key. This text will be removed after the last code of 2 weeks has expired. 
@ChaykeeMor     please suggest text....

**Comment by ChaykeeMor** [comment]
"You can still use your 4-digit code! Just type your code and press Enter."

**Comment by corinnewo** [comment]
@MendyBerger Please can you fix the 'valid for....' text! It should say 'Valid until [date of expiry, including year]', and not what is there currently!
![image](https://user-images.githubusercontent.com/16290361/221134231-0c5b6c08-ccde-490e-9c6a-b515e1fc3534.png)

**Comment by MendyBerger** [comment]
Resolved
