### ISSUE TITLE
Jigzi - help center

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3352]
Hi Corinne and Chayee

This is the design for the help center, according to what we have at the moment. 
This page is opened from the top bar - the -?- icon. I will add this icon also on the creator
Corinne will make it in Wordpress. 
The design is not final colors yet, I will complete it till the end of the day.

Chaykee, what do you think about the texts? 

https://zpl.io/r1jv39L

**Comment by corinnewo** [comment]
you can see the page that needs to be embedded in Jigzi here: https://www.jewishinteractive.org/jigzi-help-center/

**Comment by ChaykeeMor** [comment]
What texts should I be looking at here? I see a few lines under Pro Tips and the tips themselves could use rewording. And the contact forms?
