### ISSUE TITLE
Jigzi player: Clicking next does not stop the voiceover from playing

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3361]
The voiceover continues to play even after clicking next and viewing the following slide ( I think this worked before)

Example:
https://jigzi.org/admin/curation/fa937272-53cc-11ed-9fe7-b31a71a2892f

**Comment by corinnewo** [comment]
Yes - Mendy is working on it. It has to do with how he reprogrammed the audio for iOS compatibility.

Closing this in favor of https://github.com/ji-devs/ji-cloud/issues/3320
