### ISSUE TITLE
How do we delete a member from a circle?

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3396]
![image](https://user-images.githubusercontent.com/16290361/204541680-36c97a4e-def9-42a7-bddc-57870e46c6d1.png)
There is a student who has added himself to our Ji Team Circle. How can we delete him?
It should be something that a circle-creator can do.

**Comment by MendyBerger** [comment]
Think we need Gali to design something for this

**Comment by corinnewo** [comment]
@GaliShapira Please advise what to do here.
@MendyBerger In the meantime, can we delete this Zeev as a Ji Team member? Somehow in the backend?

**Comment by GaliShapira** [comment]
Hi @corinnewo 
There is a design for it. 
We decided that its for the MVP.
I added to Zeplin, the last 2 screens in the Community section:
https://zpl.io/GEgZg3d
https://zpl.io/jZeGeKx

<img width="641" alt="Screen Shot 2022-12-01 at 6 14 39" src="https://user-images.githubusercontent.com/88834002/204964434-c520a5bf-7f6a-4447-8924-7006f5ecc598.png">

**Comment by corinnewo** [comment]
@MendyBerger Here are Gali's designs for the management of circles by the circle admin. 
Can we add in the kebab menu and just have the 'Remove' option? Or else, please remove Zeev from the Ji Team circle in the backend somehow. Thanks!

**Comment by corinnewo** [comment]
This has been added to sandbox.
