### ISSUE TITLE
Flashcards - make the image with the same corner radius of the frame

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3397]
<img width="317" alt="Screen Shot 2022-11-29 at 17 23 20" src="https://user-images.githubusercontent.com/88834002/204570280-b7dec702-9e90-4c7b-b874-464c03f30ac4.png">

**Comment by corinnewo** [comment]
@RickyLB I happened to choose an image with a white background, which now covers the new corner. Please can you apply the same radius to the image as well, so that this does not happen on the cards?
