### ISSUE TITLE
Flashcards - being able to decide when the card should flip

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3403]
In the "developing young leaders" Israelbytes/ jigzi game, it is difficult to read the flashcards because they flip too fast and there is a lot of information on the cards.

@ChaykeeMor do you think using flashcards is the best module for this activity? Or maybe we need to add in a setting option to control when the user is ready for the next card. What do you think?

https://jigzi.org/asset/play/jig/a9cbf54c-5ea5-11ed-97b0-43c67993f264?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

**Comment by corinnewo** [comment]
@ChaykeeMor Perhaps swop the sides of the flashcards, so that the text is fixed on the left and can be read.
I don't think we will be getting to add a 'control' to the flashcards anytime soon.

**Comment by ChaykeeMor** [comment]
Thanks
