### ISSUE TITLE
Listen & Learn: Defined labels don't appear in game

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3409]
In "listen & learn", I defined labels for items (interaction step), but when previewing and clicking on an item, the labels do not appear in the game.
<img width="866" alt="Screen Shot 2022-12-01 at 2 33 29 PM" src="https://user-images.githubusercontent.com/78186896/205143568-49c5f903-75f5-463a-a5a7-4bcfdcda0e8f.png">

**Comment by corinnewo** [comment]
Closing this in favor of #3329, where I had also commented about the labels not appearing.
