### ISSUE TITLE
Image tabs - make the default for filter for "no backgrounds" unselected

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3417]
At the moment, 'No Backgrounds' is selected as the default for image search. Please change to unselected, so that by default, all images are shown. 

![image](https://user-images.githubusercontent.com/16290361/205619128-96fc5c3a-2e73-433b-9180-46a24542314f.png)

**Comment by corinnewo** [comment]
@RickyLB I asked for only the images default to be to include all images.
I see that the **backgrounds** and **overlay** tabs have also had their defaults cancelled. This is incorrect.

- The **Backgrounds** tab should have the filter default as 'Backgrounds only' (Tag = 'Background Layer 1')
- The **Layout** tab should filter on 'Background Layer 2' tags - at the moment, on the overlay tab, you see all images, and no overlays! 
Please correct this! Thanks

**Comment by MendyBerger** [comment]
Resolved in a40529673
