### ISSUE TITLE
Legacy import - link not opening anything

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3430]
https://jigzi.org/asset/play/jig/651e6648-69cb-11ec-836b-5f007ecb462d?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

בגינה שלנו - IML game that has been updated

I click on 'hasratim shelanu' and nothing happens: 
If i go to slide 54, the video plays. Is it a problem with the link?
![image](https://user-images.githubusercontent.com/16290361/207003743-7a89db70-1897-465a-8b28-1fc6509cf5e8.png)

In the Ji Tap game, it opens up a video from YouTube. https://jitap.net/activities/gdlw/play/ (p52)

It's strange, as the first video plays without a problem 9

**Comment by corinnewo** [comment]
I think you are right, but it is not consistent. When I click the kipod (first menu item), it goes to to screen 3, which is correct. But if I click the music icon, it goes to screen 52 and misses 51. Video camera goes to menu.
'Listening' goes to correct screen.
'games with words' goes to correct screen
'puzzle' seems to go to 41, but looks like it should start at 40.
'10 fingers' - also off by 1 - goes to 57 instead of 56

Could this have anything to do with the fact that it is not new, but edited?

**Comment by dakom** [comment]
Ahh... I think I know what's going on. We decided that existing jigs would have their content updated but wouldn't touch the jig _metadata_

However, jigs are built of two things: metadata and a _list of modules_

I need to make it rewrite the list of modules for the existing jigs. Tbh this is tricky. @MendyBerger - is it safe to do the following:

For each jig in our spreadsheet

1. Get its list of modules
2. Delete these modules - specifically, can we have a jig with 0 modules?
3. Recreate new modules
4. Assign them to the jig

?

**Comment by MendyBerger** [comment]
I believe it's totally fine to have jigs with 0 modules

**Comment by dakom** [comment]
Ok, thanks @corinnewo  :) what's the API needed to disconnect a module from a jig and then delete it? Or is it just one call to delete the module?

**Comment by MendyBerger** [comment]
Guessing it's just delete https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/module/struct.Delete.html

**Comment by dakom** [comment]
@corinnewo I believe this is now fixed
