### ISSUE TITLE
Create: Memory game, Play settings: Can't modify how many cards should be displayed

### ISSUE THREAD

**Issue by chayaml** [ji-devs/ji-cloud#3440]
I was able to edit the number of cards displayed in the memory game play setting "How should your cards be displayed" the first time, but when I tried to modify it again, the setting was disabled.

![Screen Shot 2022-12-12 at 9 45 35 AM](https://user-images.githubusercontent.com/78186896/207075467-3159c16f-9a42-4208-984e-f0229321b105.png)

![Screen Shot 2022-12-12 at 9 44 50 AM](https://user-images.githubusercontent.com/78186896/207074871-195b7b6d-6b2a-4c07-890a-dd7e6b2997aa.png)

**Comment by corinnewo** [comment]
@johnnynotsolucky It seems that in the memory game, you can set the number of pairs, preview, and then when you go back to the change the number of pairs, the pulldown does not open again. (Tested on Sandbox)

**Comment by johnnynotsolucky** [comment]
@corinnewo this is fixed in #3474 with the updated settings
