### ISSUE TITLE
Cannot edit cover image in resource

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#3450]
https://jigzi.org/asset/edit/resource/0e76f23a-7a17-11ed-aed4-73ec5a2378b3
I uploaded a resource and wanted to upload a cover...Didn't we have this in the original design? 

So I went to create a cover and after first image input I got an error and couldn't make any changes.
<img width="1473" alt="Screenshot 2022-12-13 at 10 33 55" src="https://user-images.githubusercontent.com/94056434/207266317-28d00021-c47a-41e6-88b1-c3b51e5e6051.png">

**Comment by corinnewo** [comment]
@ChaykeeMor  I am able to upload the images, both as background and as an image. Where we know it crashes is when you click PREVIEW (Mendy has not yet implemented the preview that Ty built in the modules, but he is working on it). But when you open the resource to edit again, the cover should be there.
How big is the image that you are trying to upload?

**Comment by ChaykeeMor** [comment]
I didn't get to upload anything. I must have gotten stuck at preview somehow but now I can't edit anything presumably because it goes straight to the preview step.

**Comment by ChaykeeMor** [comment]
https://jigzi.org/asset/edit/resource/0e76f23a-7a17-11ed-aed4-73ec5a2378b3

**Comment by MendyBerger** [comment]
It is the same issue, this cover defaults to the preview page
