### ISSUE TITLE
Mixpanel - What is (empty String) on the JIG graph?

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3454]
Please check why there is an empty string that has such a high count for JIGs in mixpanel? Could it be previewing games that do not yet have a name?

![image](https://user-images.githubusercontent.com/16290361/207296642-d0964fe4-b6b4-4816-9490-0745ed06b574.png)

**Comment by johnnynotsolucky** [comment]
@corinnewo these are "Preview" plays when editing JIGs. I think that they should not be recorded from the app.

**Comment by corinnewo** [comment]
So should we remove that label from the mixpanel events?

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by johnnynotsolucky** [comment]
@corinnewo if you can filter out the empty string from events that would solve it in the interim. Long-term, we'd have to make sure we're not sending the event when a JIG is being previewed.

**Comment by corinnewo** [comment]
We can definitely filter it out on Mixpanel. It also helps knowing why it is showing the empty string! THanks
