### ISSUE TITLE
Split image transformation tasks into a seperate binary

### ISSUE THREAD

**Issue by izik1** [ji-devs/ji-cloud#347]
This offers better scalability on the server side. It makes it easier to go "oh, we need more compute for image transformation" (if we want to) or "oh, we need to spin up more API servers because we're getting _swamped_ with insane numbers of requests". It also makes it impossible for one of the tasks to take up all the resources that are meant for the other task.

They're fundamentally different kinds of tasks with _very_ different resource profiles, the current implementation is a crutch that should be refactored and removed when possible.

**Comment by dakom** [comment]
Yeah - I agree :)

I'm not a huge fan of going super nitty gritty microservices but I do think it makes sense to split our servers where they have very different memory/compute needs.

**Comment by rrcwang** [comment]
![ji-cloud_media_processing_service](https://user-images.githubusercontent.com/15862033/124046291-77b47800-d9c6-11eb-80e8-28e249427252.png)

**Comment by rrcwang** [comment]
## Breaking Changes

### Changes for upload media methods

| method + endpoint | docs link |
| ------------------------- | ------------|
| `PUT /v1/image/{id}/raw` | https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/image/struct.Upload.html |
| `PUT /v1/user/me/image/{id}/raw` | https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/image/user/struct.Upload.html |
| `PUT /v1/animation/{id}/raw` | https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/animation/struct.Upload.html |

* **Requests** now require file `file_size` in bytes.
* **Responses** give the session URI as a `String` to perform a resumable upload to GCS processing bucket.

### Notification for upload completion status:
* FCM Data Message 
  * Topic name is the UUID of the media
  * Data field contains the MediaLibrary, content type, and processed_at time of the media.
**Ex:** for item `/media/global/c0d0aae8-e8eb-11eb-8835-03de51df235e/resized.png` in the media bucket

FCM topic: `c0d0aae8-e8eb-11eb-8835-03de51df235e`

```json
"data": {
    "library": "global",
    "content_type": "image/png",
    "uploaded_at": <TIME>
}
```
