### ISSUE TITLE
Help center icon 

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3484]
Pls add this icon, notice there is a hover state. 
Clicking on it links to the help center page on Jigzi.
(The notification icon- the bell - is not yet implemented, it belongs to the community and may be implemented later on.)

Zeplin:
https://zpl.io/xmo6zNk
https://zpl.io/40q5mW4

Screenshots:
<img width="262" alt="Screen Shot 2022-12-21 at 10 38 15" src="https://user-images.githubusercontent.com/88834002/208859246-ba0c584f-1bb6-4df8-90c8-cc969eba17cb.png">
<img width="348" alt="Screen Shot 2022-12-21 at 10 41 11" src="https://user-images.githubusercontent.com/88834002/208859303-dd8ab98f-45b6-4cb8-a49b-4d672f0e76b0.png">

**Comment by corinnewo** [comment]
The help center is currently housed on the ji site at https://www.jewishinteractive.org/jigzi-help-center/
But we want to have it on Jigzi, within an iframe. See #3482

**Comment by GaliShapira** [comment]
Hi @RickyLB 
Pls see the icon + hover state.

![icon-help](https://user-images.githubusercontent.com/88834002/219340258-16398ad1-fd74-4f1e-b5ee-4b858ce5e938.svg)

![icon-help-hover](https://user-images.githubusercontent.com/88834002/219340249-4df05976-9ec6-4145-be10-52dde72e3bc4.svg)
