### ISSUE TITLE
Search results cards - on JIGs, missing the keywords

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3488]
The keywords are missing from the search result cards for JIGs!
There are keywords on resources and courses , but not on JIGs. Please put in the keywords for the JIGs!

Currently:
JIG:
![missing keywords on jigs](https://user-images.githubusercontent.com/16290361/208908802-068155c3-680c-4d23-be28-d39df8e66a46.JPG)

Resources:
![keywords in resources](https://user-images.githubusercontent.com/16290361/208908868-404e79b5-2163-44ef-9ddf-2774cd4a3f15.JPG)

Courses:

![keywords in courses](https://user-images.githubusercontent.com/16290361/208909163-769a4196-962e-4033-a0cf-477f3199ec98.JPG)

**Comment by RickyLB** [comment]
@corinnewo JIGs already display the keywords in production. 

![Screenshot 2022-12-26 at 8 08 30 PM](https://user-images.githubusercontent.com/76449893/209609663-3b1f0ba7-d5c4-4be6-be32-67656f77cace.png)

**Comment by corinnewo** [comment]
@RickyLB Thanks, I see that now. It seems like all the Ji Tap Library games that were imported from Ji Tap do not have keywords. That field is missing from the Curation page "General Summary".  @MendyBerger Would it be possible to add in that field (same as that in the publish dialog) to the Curation? IF so, I will create a separate ticket for that.

In Curation:
![image](https://user-images.githubusercontent.com/16290361/209914983-0f6dd025-9bfc-4664-928b-01b893fff24c.png)

In publish dialog:

![image](https://user-images.githubusercontent.com/16290361/209915101-3d9c1f17-3b13-49cc-9d84-514f8d08b3d6.png)

**Comment by MendyBerger** [comment]
How should we display keywords once we flatten them? Should we display the whole path?

**Comment by corinnewo** [comment]
I would like the whole path. At the moment, it only shows the final node, which does not really help when it is 'Customs' instead of 'Tu Bishvat Customs'!

**Comment by corinnewo** [comment]
Closing in favor of #3536
