### ISSUE TITLE
Resources - crashes when you duplicate a resource

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3513]
In MY RESOURCES, when I duplicate a resource, it is now crashing. Used to work well.
![image](https://user-images.githubusercontent.com/16290361/210325023-975b1a18-f1f0-4482-a7fe-d9df75033a61.png)

![image](https://user-images.githubusercontent.com/16290361/210325083-c21e2102-42df-4113-9bc7-a0c7f6d0f969.png)

**Comment by MendyBerger** [comment]
Resolved
