### ISSUE TITLE
Text edits in profile settings

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#3518]
Live Text | Should be:
-- | --
My Settings | Account
[button] Edit | [button] Reset
[message after reset button click] We just sent you a reset password email! | Email sent to [account email]
Family name | Last name
Preferred language of communication | Jigzi emails you in: 

<img width="903" alt="Screenshot 2023-01-03 at 8 48 18" src="https://user-images.githubusercontent.com/94056434/210327375-51bc13c1-e710-4127-b580-9e89b8c8809e.png">

Live Text | Should be:
-- | --
Jigzi Filters | Jigzi content filters
A note about our filters: Ji believes in making Jewish education accessible to ALL Jews, of all ages and affiliations. If you would like to see only what Jigzi tags as relevant to you, use these filters to fine-tune your search results. If you would like to see ALL our images, resources and JIGs leave these blank. | A note about our filters: Ji believes in making Jewish education accessible to ALL Jews, of all ages and affiliations. If you would like to see only what Jigzi tags as relevant to you, use these filters to fine-tune your search results. **If you would like to see ALL our images, resources, and JIGs, leave these blank.**
Relevant age groups | Age groups
Relevant subjects | Subjects

<img width="879" alt="Screenshot 2023-01-03 at 8 48 32" src="https://user-images.githubusercontent.com/94056434/210334026-47be9a88-2c23-45b4-b995-f4755808abfa.png">

**Comment by corinnewo** [comment]
@ChaykeeMor We also want to emphasize that if you want to see all content, leave all the filters blank. Can we put that in bold at the top of the section, rather than buried in the paragraph?

**Comment by ChaykeeMor** [comment]
Let's bold the last line.

A note about our filters: Ji believes in making Jewish education accessible to ALL Jews, of all ages and affiliations. If you would like to see only what Jigzi tags as relevant to you, use these filters to fine-tune your search results. **If you would like to see ALL our images, resources and JIGs leave these blank.**

**Comment by MendyBerger** [comment]
Resolved in 18cc9c706
