### ISSUE TITLE
Feedback Jiggling missing

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#3521]
The Blue Gear Jiggling disappears every time user gets to feedback tab.. 

- [x] Even in the case where jiggling has nothing to say...should not disappear.
- [x] We don't have feedback in the json file...which we should rectify.
- [x] also missing in the entire 'answer this' activity and need new json file prepared so I could add tips to this module

https://user-images.githubusercontent.com/94056434/210505914-289c26d3-1da1-4b5d-aa13-0db4dd076370.mov

**Comment by corinnewo** [comment]
We need to add in the sections to the Json file. I'll take a look!
