### ISSUE TITLE
Creating a thumbnail - flow for Resources, Courses and PD Courses

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3522]
In ideation we discussed 2 possibilities. and Mendy says he may have a third to suggest:

### Option 1:

1. Click edit pencil in publish dialog
2. Opens up the thumbnail cover module
3. Change the grid from the JIG grid to a plain grid with no icons around the edge (as thumbnail will not have any of these extras)
4. Delete the Preview step and the preview button on the top right
5. On the Content tab stage, change 'Continue' button in bottom right corner to 'Done'
6. Click **Done** - return to Publish dialog, with the new thumbnail in place

### Option 2:
1. Click edit pencil in publish dialog
2. Opens up the thumbnail cover module
3. Change the grid from the JIG grid to a plain grid with no icons around the edge (as thumbnail will not have any of these extras)
4. Click the Preview step or the preview button on the top right: basically hide the grid and see image without the grid, and have the X on the top right corner "Preview mode". Can't edit at this stage.
5. Click the X button, and you get the same screen as with a JIG - to click DONE or go back and edit 
![image](https://user-images.githubusercontent.com/16290361/210576607-d3315522-aa85-47d7-95cf-86d7e704dd64.png)
6. Click **Done** - return to Publish dialog, with the new thumbnail in place

### Option 3:
Mendy?

**Comment by MendyBerger** [comment]
Resolved in 1b22dbcbc
