### ISSUE TITLE
Grid for thumbnail creation for courses, resources, PD Course

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3523]
Instead of the grid with all the icons and bars that is used to show where JIG player items will be, the grid for the thumbnail does not need to show any extra items, only the grid for aligning items.
@GaliShapira Please attach it here. Thanks!

**Comment by GaliShapira** [comment]
Pls see the gid attached  (SVG + PNG)

![grid_for_courses](https://user-images.githubusercontent.com/88834002/213401244-2f3b7cce-1f03-47bf-941b-01a4c1198ca4.svg)
![grid_for_courses](https://user-images.githubusercontent.com/88834002/213401254-9384cc43-0e35-4a6d-bcd8-d69b0a26a34a.png)

**Comment by corinnewo** [comment]
@GaliShapira Thanks!

**Comment by MendyBerger** [comment]
Resolved

**Comment by corinnewo** [comment]
This grid should **only** be for the creation of thumbnails for courses, resources and pro dev courses, as those covers will never be seen with the player progress bar and other icons.

You have replaced the grid for game creation - so people will not know that there is the player. 

@MendyBerger Please make sure that covers have the plain grid, and JIG creation has the grid with the progress bar and icons.

**Comment by corinnewo** [comment]
Sorry - I saw on sandbox that this is correct!!! Closing the ticket.
