### ISSUE TITLE
Answer it - Add a question

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3541]
I just created an answer it activity.

I selected a text "Find the dog" that I had wrote before as my question. Then, I added a new question, I changed the text of question 2 to "Find the cat" - The question on the canvas wasnt changed. On the player (preview) it was changed to the new question. But I need to see it also when I create on the canvas.

Same question on the canvas for the 2 questions (see on the left panel that I select a different question, sorry its in Hebrew, But I hope its clear, if not I can change)
<img width="882" alt="Screen Shot 2023-01-12 at 0 41 14" src="https://user-images.githubusercontent.com/88834002/211933628-87b2dc98-0ab4-4d60-9bba-d7dd1d5af290.png">:
<img width="884" alt="Screen Shot 2023-01-12 at 0 41 20" src="https://user-images.githubusercontent.com/88834002/211933616-b85200db-249f-48b6-bb8e-4203598d7685.png">

**Comment by corinnewo** [comment]
This will be taken care of when Tyrone does #3085
