### ISSUE TITLE
Answer it - specific feedback - Jiggling text

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3542]
I created an Anwer it activity.
While I was working on the specific feedback, I clicked on the Jiggling, To see if there is more explanation there for the specific feedback, and the text is not relevant for the specific feedback. I think we need a relevant Jiggling text. 
I wondered if someone checked that the Jiggling text is relevant all along the platform.

<img width="1325" alt="Screen Shot 2023-01-12 at 0 41 39" src="https://user-images.githubusercontent.com/88834002/211933875-1ac17353-ad8d-49ad-b7c9-6974219c5273.png">

**Comment by corinnewo** [comment]
Chaykee has been checking the jiggling texts - but I will check too! Thanks

**Comment by corinnewo** [comment]
@johnnynotsolucky How would we add to the JSON the extra tabs of 'Correct' and 'Incorrect'? It is the extra popup for advanced feedback. Please advise!
https://www.dropbox.com/s/vi74csy3f3ehrkq/find-answer.json?dl=0

**Comment by johnnynotsolucky** [comment]
@corinnewo I'll need to add logic into the activity so that the jiggling popup knows to render the correct text. I'll update here when I get to it with what to set exactly.

**Comment by corinnewo** [comment]
@johnnynotsolucky Thanks - I thought it would need you to update the JSON!

**Comment by johnnynotsolucky** [comment]
I have updated find-answer.json to include the Correct and Incorrect tabs for the Jigzi help text. Those just need to be updated with proper copy.

**Comment by corinnewo** [comment]
@ChaykeeMor ready for you!

**Comment by ChaykeeMor** [comment]
Cool if I do it now? Or do I have to wait for the correct/incorrect tabs to exist outside sandbox?

**Comment by corinnewo** [comment]
@johnnynotsolucky ?

**Comment by corinnewo** [comment]
@ChaykeeMor You can go ahead with the texts in sandbox. Thanks
