### ISSUE TITLE
Cannot rename categories

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#355]

**Comment by dakom** [comment]
@izik1 - from looking at google cloud console I see this:

> 2020-11-16 13:24:24.684 UTC [375175]: [3-1] db=jicloud,user=postgres ERROR:  could not serialize access due to concurrent update

**Comment by corinnewo** [comment]
![Categories -error-request payload](https://user-images.githubusercontent.com/16290361/99258557-69dc2900-2821-11eb-8b36-2a62634178c1.PNG)
![categories1 error](https://user-images.githubusercontent.com/16290361/99258573-706aa080-2821-11eb-9e44-5fdad364d192.PNG)
