### ISSUE TITLE
Publish  - autosave all fields in the publish dialogs for JIGs, courses and resources

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3564]
I uploaded a resource, then filled in the name, description, etc, and didn't publish yet. Then went to create a cover. Came back, and all the fields I'd filled in were no longer filled in.

It is also losing the uploaded resource!

Should definitely remember fields when you go out to create the cover.

**Comment by MendyBerger** [comment]
As discussed with @corinnewo, we'll be adding auto-save to all publish pages (jig/resource/course)

**Comment by MendyBerger** [comment]
Resolved
