### ISSUE TITLE
Publish resource- default thumbnail changes to the SHALOM text

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3565]
If I create a new resource, and don't go in and define a thumbnail, the thumbnail in the publish is shown as:
![image](https://user-images.githubusercontent.com/16290361/213417773-65520647-7136-40f1-8fd7-cf242c0c6867.png)

But when you publish, the thumbnail shows in the gallery as:
![image](https://user-images.githubusercontent.com/16290361/213417424-9102c15e-c2b2-49d6-87dd-b84509c5cb85.png)

Surely it should be the same thumbnail as it was in the publish dialog!

**Comment by corinnewo** [comment]
@GaliShapira Did we not speak about a default graphic for the resource? If you have it, please attach it here. Thanks!

**Comment by corinnewo** [comment]
@MendyBerger Instead of making people going into the creator to create a cover, can we program a default background and put the text automatically as the name of the resource, so that there is never the "Shalom" text?

**Comment by GaliShapira** [comment]
I see that the design of the default cover for resource is saved in the Dropbox (here):
<img width="811" alt="Screen Shot 2023-03-14 at 20 27 05" src="https://user-images.githubusercontent.com/88834002/225102753-1944ec6d-0ade-40e8-80da-7069996c4343.png">

SVG:
![default-resource-cover](https://user-images.githubusercontent.com/88834002/225102832-4f5dd5b2-222f-4d18-9234-9c2aeca213d8.svg)

**Comment by corinnewo** [comment]
@GaliShapira If we use this design, then all the resources will look like this! I think that we need to simply change the text of "Shalom" to the name of the resource. We could use this color background.

**Comment by corinnewo** [comment]
Closing in favor of https://github.com/ji-devs/ji-cloud/issues/3793
