### ISSUE TITLE
Legacy player - need a delay once the puzzle is completed so that child can see the full image before proceeding to next slide

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3576]
From Sammy:
Any game with voice whilst dragging that have been exported from jigzi, the voice is cut out once placed in correct position, moving immediately to the next slide. here is an example look at page where dragging the lights of the menorah (screen 5)

[https://jigzi.org/asset/play/jig/7d02f80a-69c6-11ec-ac21-a38e0ff6ca04?direction=l[…]ents=false&drag_assist=false&is_student=false&draft_or_live=live](https://jigzi.org/asset/play/jig/7d02f80a-69c6-11ec-ac21-a38e0ff6ca04?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live)

@dakom Can this be sorted? 
We need to have a delay once the last piece of the puzzle is placed so that you can see the completed puzzle correctly before you get taken to the next screen. Is this part of the legacy player that you built?

**Comment by dakom** [comment]
Haven't looked at the example yet, but on one foot, that sounds more like a bug. It shouldn't move to the next slide until the audio finishes. A delay won't necessarily help (can also add a 1 second delay or so after the audio is finished, for the sake of feeling nicer, but we shouldn't rely on a specific delay time to avoid cutting off the audio)

**Comment by corinnewo** [comment]
In the puzzle activity, the audio cuts off as you place a puzzle piece, which is not great either! But the greater problem here is the fast transition to the next screen, without the user seeing the completed puzzle image.

**Comment by dakom** [comment]
What's it supposed to do when you place a piece? keep playing the old audio and overlap them?

**Comment by corinnewo** [comment]
There must be a delay after the last piece has been placed, after the audio has been playing in full. Perhaps add 3 seconds. Thanks.

**Comment by dakom** [comment]
@corinnewo I believe https://github.com/ji-devs/ji-cloud/pull/3871 fixes this issue. Some notes:

1. It now plays the positive/negative effects in a separate channel which does not cut off the main audio. Let's call this "sidefx" audio, whereas the main recording audio (whether the intro or on an individual puzzle piece") is "clip" audio
2. It now waits for the `clip` audio to finish, before jumping to the next module (whether this clip is the intro or a piece doesn't matter)
3. Additionally, it waits 3 seconds before jumping to the next module. If there is audio playing, then this timer is started _after_ the audio completes. 

Suggested optimization would be to deduct the remaining clip audio from the timer - i.e. if there is 2 seconds of audio remaining, then the end delay would only be 1 second. This data isn't easily available though, so for now it will simply _always_ wait 3 seconds at the end of the puzzle.

Altogether, I believe this addresses the UX issues raised here, both for module #5 (which has an item audio) and module #6 (which does not)

I did not have a test case for a puzzle with no audio clips whatsoever, but logically it should just work as expected (i.e. it will simply wait 3 seconds when the last piece is placed)

Please not that the `sidefx` audio is not counted towards anything, and may be cut off (in practice these are quick clips, and play before the 3 second delay starts, so it's unlikely to be an issue)
