### ISSUE TITLE
Course - cards - Unit count should have number first

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3598]
In sandbox, the unit count does not make sense. Why does it have the number AFTER the word 'Units'? It does not go according to the Zeplin design!

1. Please put the number first, then the word Units (eg 25 Units).
2. If there is 1 unit, then it should say '1 Unit', although if there is only one unit, it should not be a course!
3. In the Zeplin, the number is shown in a larger font.

Currently in Sandbox:
![image](https://user-images.githubusercontent.com/16290361/215076894-23856248-6c2a-4cf7-bffc-271d361afdc8.png)

Zeplin shows this:
![image](https://user-images.githubusercontent.com/16290361/215077239-18fe2053-60a9-48fe-85ef-a6f1a6903228.png)

**Comment by MendyBerger** [comment]
Changed order now it's "x units"
