### ISSUE TITLE
Create a ProDev course 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3610]
See flow in Zeplin, starting here: 
https://zpl.io/ykdz3go

![image](https://user-images.githubusercontent.com/16290361/215688454-4968eb34-8e90-476a-a7ef-ad6764cea5f9.png)

**Comment by RickyLB** [comment]
@corinnewo When updating a unit with another value, should the string in the `Add to course` button change to something along the lines of `Update unit`?

**Comment by corinnewo** [comment]
@RickyLB That's a good idea. If it is going to take time to do, then we don't need it, but it is a nice to have, if you have time! Thanks

**Comment by RickyLB** [comment]
@corinnewo  For the sidebar, should a unit's nameend with an ellipsis if it's too long?
![Screenshot 2023-04-12 at 2 36 48 PM](https://user-images.githubusercontent.com/76449893/231592201-e9a8e76e-cc1a-4071-803d-08a2c00a7d57.png)

**Comment by corinnewo** [comment]
@RickyLB Yes, please add the ellipsis if it is too long.
