### ISSUE TITLE
Create the ProDev course player

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3612]
Starts off similar to the regular courses: https://zpl.io/NwqqgpQ
Then once you click 'Begin course', the player is specific to the ProDev course: Zeplin starts here: https://zpl.io/JEwZEPK

![image](https://user-images.githubusercontent.com/16290361/215690053-831d007b-7b2a-45ff-bd25-631cbba348d9.png)

![image](https://user-images.githubusercontent.com/16290361/215690016-175371fe-93ae-498e-bf66-0699bc5bf928.png)

**Comment by GaliShapira** [comment]
The player itself is different than the Jigzi regular course.
On the regular course when playing you see our regular player of JIGs.
On the ProDev these are not JIGs and not kids, the design is different: the panel is different and with different features.

**Comment by MendyBerger** [comment]
@RickyLB I don't think the element should be shared between course and pro-dev. Feel free to clone course, but I don't think you should share.
Feel free to push back if you disagree
