### ISSUE TITLE
URGENT! Mobile and iPad - clicking the card turns it over and reverses it - can't tap play!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3631]
on live version, tapping a game to see its card back now reverses the card. Reverses the card image and covers the PLAY button.  We once had that before!

Also, were there not supposed to be 3 cards across, not 2?

![IMG_7019](https://user-images.githubusercontent.com/16290361/216565486-2b87c619-5f9b-45a4-8b36-9ed66b55b777.PNG)

**Comment by MendyBerger** [comment]
Resolved
