### ISSUE TITLE
In player info - need to list the courses that this JIG is a part of - currently says 'coming soon'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3639]
If this JIG is part of any courses, then the course names should be listed, as links that can be clicked and the course can be opened.
If this JIG is NOT part of any courses, then hide the heading 'Courses'.

![image](https://user-images.githubusercontent.com/16290361/216944965-35bffed7-c4d3-4e2f-810d-069787960ef1.png)

**Comment by MendyBerger** [comment]
Blocked in #3649
