### ISSUE TITLE
Legacy games - soundboard - highlight should not remain once the audio has played

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3641]
In listen and learn in legacy games, the blue highlight remains on screen, even though something else has been clicked and is playing.
Would it be possible to make the highlight disappear after the audio has played? In this way, only one highlight would be on screen at a time.

https://jigzi.org/asset/play/jig/e2e6edac-69bc-11ec-bb37-07593d686ec5?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

![image](https://user-images.githubusercontent.com/16290361/216976576-15e86e7e-abd1-4879-b688-adffd8a3a9a4.png)

**Comment by corinnewo** [comment]
Hi - this is the last ticket that was labeled 'Legacy'. We have fixed this in the non-legacy games. But in Soundboard migration games, the highlight still remains on screen. Any way you can fix this?

**Comment by dakom** [comment]
Sure, I can try... not sure when, but please feel free to nudge me as a reminder if I haven't fixed within, say a week

**Comment by dakom** [comment]
Opened a PR at https://github.com/ji-devs/ji-cloud/pull/3962 - from testing soundboard it works, but @corinnewo  please see Slack for more details
