### ISSUE TITLE
Transfer legacy games

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#3648]
We'll add the ability for the admin to transfer (legacy) jigs from one user to another. The user will NOT be able to edit those legacy jigs.
We might enable editing those jigs temporarily for one user.

**Comment by corinnewo** [comment]
I have made the list of IML games that were imported from Legacy: https://docs.google.com/spreadsheets/d/1Oas6xs4dAUMaFeL-rGfuuzHx0L9UNCr7HT20ocn_4Rs/edit?usp=sharing

Has the JIG ID and the user ID in JIgzi.
Thanks

**Comment by MendyBerger** [comment]
Blocked on #3687

**Comment by corinnewo** [comment]
I have set up the user in JIgzi:
![image](https://user-images.githubusercontent.com/16290361/225035584-9d6115b0-53f8-4756-9d91-c4942804eee8.png)

**Comment by MendyBerger** [comment]
Done
