### ISSUE TITLE
Community - circles - description -dont show 6 lines.

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3657]
Margin is missing.
If more than 5 lines either add a scroll or enlarge the height of the container.
 @corinnewo what do you think?
 
 <img width="913" alt="Screen Shot 2023-02-08 at 12 55 51" src="https://user-images.githubusercontent.com/88834002/217856148-2a2fd508-a0f9-4817-8e42-03182b8d605d.png">

**Comment by corinnewo** [comment]
@GaliShapira I agree with you regarding the max of 5 lines, then adding a scroll.
What do you mean that a margin is missing? Please give more direction as to how to fix. Thanks!

**Comment by corinnewo** [comment]
no longer relevant
