### ISSUE TITLE
Tooltips on search result icons - only 'Share' appears, need 'Edit' as well

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3664]
At the moment, there is only a tooltip on the share icon. If I am the creator, we need to have the tooltip on the 'Edit' button as well.

![image](https://user-images.githubusercontent.com/16290361/218421605-b6c5533f-27a9-420f-80d2-2b600a6f994e.png)

**Comment by MendyBerger** [comment]
I see the edit button. Are you sure that you're logged in?

**Comment by corinnewo** [comment]
I also see the EDIT button, but there is no tooltip for it! Tooltip is only on SHARE button.

**Comment by MendyBerger** [comment]
Sorry, I didn't read the issue properly
