### ISSUE TITLE
Search results - if name is two lines long, reduce space between rows, increase cell space above

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3666]
If a JIG title (or course/resource) is 2 lines long, then add some cell space above it, so that text is not so close to the image (2 in screen grab) and reduce space between lines (1 in screen grab). If you reduce by same pixels as you add above, then the spacing for the rest should remain unchanged.

![image](https://user-images.githubusercontent.com/16290361/218467302-177f1ffc-5b7c-4df0-9430-d6ad7a5702c3.png)

Should look something like this:
![image](https://user-images.githubusercontent.com/16290361/218468279-dc8dcef1-6a03-4ef2-8ec8-88f47e2211cf.png)

**Comment by MendyBerger** [comment]
Done

**Comment by corinnewo** [comment]
@MendyBerger Thanks - but the first line is still too close to the thumbnail. Can you add 2 pixels above the line, and reduce the space between the lines by 2 pixels?
![image](https://user-images.githubusercontent.com/16290361/229989355-759c9f0a-5152-4b40-bcc6-214253b7c4cf.png)

**Comment by MendyBerger** [comment]
Better now?

**Comment by corinnewo** [comment]
@MendyBerger Yes, much better! Thanks!
