### ISSUE TITLE
thumbnail scroll not working for game 'Stellar'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3667]
In game 'Stellar' (https://jigzi.org/asset/play/jig/caf0b434-69c2-11ec-8e0a-07d8eec7b8a6?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live), the scrolling through the thumbnails is not working - no right arrow.

![image](https://user-images.githubusercontent.com/16290361/218469138-c8b88b41-e61b-4fae-83fe-83907c5b0f7e.png)

**Comment by MendyBerger** [comment]
Resolved
