### ISSUE TITLE
Course creator - center the heading

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3682]
@GaliShapira Please add in your design here. you wanted to change the colour and center the text.
![image](https://user-images.githubusercontent.com/16290361/218941316-f0bb2db9-f5d8-4a4e-8e60-829fb77e40f8.png)

**Comment by GaliShapira** [comment]
Pls see the specs here:
https://zpl.io/3Xk1eyx
<img width="657" alt="Screen Shot 2023-02-16 at 14 06 52" src="https://user-images.githubusercontent.com/88834002/219360904-db89ecc2-bd51-43d0-9326-21741bf834cb.png">

**Comment by MendyBerger** [comment]
Centering would be a quick-fix. Unfortunately this is not

**Comment by corinnewo** [comment]
@MendyBerger Gali agreed that you could simply center the header as well! Please go ahead!

**Comment by MendyBerger** [comment]
Resolved
