### ISSUE TITLE
Course settings - click settings and there is a strange popup!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3684]
Clicking settings on the course creator shows a very strange popup!
![image](https://user-images.githubusercontent.com/16290361/219090198-0aae75a8-f197-4e69-ba73-45e4694651ae.png)

In Zeplin (https://zpl.io/wqQJ4M1) it shows this:
![image](https://user-images.githubusercontent.com/16290361/219090729-383e31fa-367b-4d78-8605-9566f891d8c1.png)

But I seem to remember that we discussed this and took it out as we can not keep track of the progress as students are not logged in. Should we take out the course settings altogether?

**Comment by MendyBerger** [comment]
I guess that a question for ideation?

**Comment by corinnewo** [comment]
I discussed with team - the general consensus is to hide the settings button until we have students that we can keep track of! Please go ahead and hide the settings button!
