### ISSUE TITLE
Phone portrait - show the progress bar 

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3686]
On iPhone, if you are on portrait view, it seems like you are stuck, as you cannot see any arrows.
Please fix so that you can see the progress bar! 

![IMG_5107](https://user-images.githubusercontent.com/16290361/219440247-f6355995-1a12-4148-a075-8b0ffb28027d.PNG)

**Comment by corinnewo** [comment]
Also related to #3365 - to hint that that you should watch landscape preferably!

**Comment by MendyBerger** [comment]
Use https://caniuse.com/viewport-unit-variants
