### ISSUE TITLE
New admin restricted API that allows moving a jig from one user to another

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#3687]

**Comment by RickyLB** [comment]
@MendyBerger Does this endpoint do a batch JIG transfer or single JIG transfer? Will this endpoint be used only once?

**Comment by MendyBerger** [comment]
Don't care if it does a batch transfer or a single one at a time. I.E. it can accept a single jig-id or a vec of jig-ids, whatever works better for you.

It will be use more than once, though I don't expect this to be used very often.
