### ISSUE TITLE
Is rated filter

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#3688]
Please add a "is rated" filter to `JigSearchQuery` and to `ResourceSearchQuery`. Should filter for items that have `rating` in admin data.

**Comment by MendyBerger** [comment]
@RickyLB can you change it to `Option<bool>`?
`true` should only include ones that have a rating (any rating), and `false` should include only the ones that don't have any rating.

**Comment by RickyLB** [comment]
@MendyBerger That can be done
