### ISSUE TITLE
Expand the size of the description box

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#369]
The Image Description box currently shows as a single line of text which requires the user to scroll through it to see the ending as shown here https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f2677ff4e3c3f1fc2c13268

We'd like to update it to look like this view where the user is able to see a greater amount of content without scroll
https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f21806792c08b7f8b385661

**Comment by dani-ji** [comment]
Please follow up with @corinnewo for any further input

**Comment by NaomiLea** [comment]
Made a PR with fix for this.
