### ISSUE TITLE
Very thick border around answer in 'answer this'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3706]
Slide 09: Very strange - the one border shown around the answer is very thick.

https://jigzi.org/asset/play/jig/f2b5c31c-a5c9-11ed-a2cc-3b3a811e33a7?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

![image](https://user-images.githubusercontent.com/16290361/221130304-1acfe0b6-3390-4821-a081-ff39db24290a.png)

Also. when you go to slide 10, you get an empty slide with an error message. How was she able to publish with this message?
![image](https://user-images.githubusercontent.com/16290361/221130734-e937bf32-2519-45fa-a191-79966a7b7c6c.png)

**Comment by johnnynotsolucky** [comment]
@corinnewo the border of the answer is related to resizing of traces themselves - When a trace is resized, the borders thickness changes with it:

https://user-images.githubusercontent.com/4161106/221507208-e1707f51-d82b-4308-9d3e-c113ce5adefd.mov

RE the incomplete activity, I think I need to know what steps were taken to create this JIG so I can attempt to reproduce it. Listen & Learn requires that a use case is selected before it becomes valid, and with brief testing, validation works.

**Comment by corinnewo** [comment]
Wow - never noticed that before, mainly because I probably have not resized traces too much! But I see that you have added a fix to prevent the stroke from scaling too - that's great. Thanks.
