### ISSUE TITLE
Navigational changes for Image Admin

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#372]
- [ ] When a user selects an image on the search result page they should land directly on the image review page as opposed to the image edit page

- [ ] After clicks publish they should be redirected to the /admin/images page

- [ ] Add 'Back to Search Results' on all image edit and review pages which would send the user back to the same results they previously saw

@corinnewo

**Comment by dakom** [comment]
We still need the flow for "add image" though, which should work the way it does currently (no point seeing a summary if no metadata has been added yet)

So there will be two routes:

`admin/image-added/{id}` -> via redirect after uploading a new image
`admin/image-edit/{id}` -> via admin search page

Both of them will share the same codebase, just changes the starting phase

**Comment by dakom** [comment]
> Add 'Back to Search Results' on all image edit and review pages which would send the user back to the same results they previously saw

This is pretty complicated, the search results page wasn't really built for hard linking...

It can be done but just a heads up that it's a significant change

**Comment by dakom** [comment]
the flow here is now a big ball of spaghetti, but I think it works... basically if they're coming from search results, then it'll serialize the state of that search and pass it along to the edit page, which then uses that to drive:

1. a "back to results" button
2. the redirect after publish
3. which section of the image editor it starts out on

if there is no serialized search state, e.g. they came to an edit image page via adding a new image, then there is no "back to search results" and publish will take them to the default search page, and the first section is the "edit metadata" stuff

there's of course a potential possibility of a bug if the search results have changed between navigation, but I don't think that will crash anything, just might be unexpected/weird.

**Comment by dakom** [comment]
Couple more notes: 

1. the serialization in the URL is only used to pass the data along... it's not updated as they change their search options, before navigating away
2. currently it's generating the deep link for each thumbnail in the result. This is potentially slow since it's serializing the json for every thumbnail, but not _too_ bad since it's just a small struct and we limit the number of thumbnails per page anyway
