### ISSUE TITLE
Add link back to jigzi from course player

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3740]
Josh pointed out that if you get the link to share a course and then open in a new window - you don't have the option to close that window with the X that usually appears in top right (because there is nothing to close it down and go back to). But the problem is on this page there is no Jigzi logo/link so no way to get back to main platform.

The solution is to add a Jigzi logo to the course player, with a link to open the Jigzi home page.

@GaliShapira Please suggest where to add in this logo.

![unnamed](https://user-images.githubusercontent.com/16290361/224032654-517426bc-a8a3-4a8b-8a27-c9d2d6e8af96.png)

**Comment by GaliShapira** [comment]
Hi @corinnewo It's the same situation when sharing a link of a JIG.
On the JIG we added the logo but it does not link to the homepage as we didn't want the kids to start navigating. 
Do you want to differentiate it from the JIG? Don't we want the course viewers to stay there?

**Comment by corinnewo** [comment]
@GaliShapira I think that the course is slightly different from a JIG - the Google classroom link opens the student viewer. The regular URL opens the course, and the player is not the student player. At the very least, we need branding on it - there must be a logo on the player, as if you look at it in the screen grab, you have no idea that it is from Jigzi. Let's discuss at ideation with Josh, as he wanted to have a link back to open up the Jigzi site.

**Comment by GaliShapira** [comment]
@corinnewo I believe we dont have a student viewer which is different from the course page. Lets discuss it on the ideation.

**Comment by corinnewo** [comment]
@GaliShapira When a course is shared using the link, there is NO BRANDING and there is NO WAY TO GET TO JIGZI. eg: https://jigzi.org/asset/play/course/f720136c-c4af-11ed-90d9-9fcb9f060997?draft_or_live=live&is_student=false

I know that we have discussed this at ideation - but there are no designs attached here. Please add in your design so that this can be implemented. Thanks!

**Comment by corinnewo** [comment]
See Gali's design: https://zpl.io/ykYON0p

<img width="640" alt="237654680-2bbae97f-93cc-420a-bd28-109525184436" src="https://github.com/ji-devs/ji-cloud/assets/16290361/93b91f72-6b48-4a27-84c2-83761b488926">

Jigzi logo should be a link back to jigzi.org (if not shared to a student)
