### ISSUE TITLE
Search results - Please put  Resources last, change the order of the top sentence too

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3751]
In the search results, please change the order so that resources are listed last.
We also then need to change the wording of the search results, to match the new order.

Regarding order of JIGs and Courses - we will leave JIGs first at the moment, but will do user testing to see what users prefer - courses first or JIGs. So for now, please just put the resources last.

**Comment by MendyBerger** [comment]
Done.

Consider: since the new middle section (courses) doesn't have a background color, it's a bit harder to see to line between the first and second sections.
