### ISSUE TITLE
Publish page and adding a resource: List of types of resources: Add in 'Poster'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3764]
Please add in 'Poster' to the list of resource types in the publish page and also when uploading a resource (alphabetical list, so after **Podcast** in the list):

![image](https://user-images.githubusercontent.com/16290361/225959467-9725f81d-d778-47d8-a3c8-e386a5d344a3.png)

**Comment by MendyBerger** [comment]
Resolved

**Comment by corinnewo** [comment]
Thanks for adding POSTER!

Anat has asked that we add in **Teacher Kit** and **Game**.
The types should be listed alphabetically, so please add these 2 in the correct order. Thanks!
_Teacher Kit would be after Poster.
Game would be after Flashcards._
