### ISSUE TITLE
Circles - edit the description - only displays 2 lines - increase to whole dialog area

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3790]
I tried to edit a description to a circle, and you can only see 2 lines:

![image](https://user-images.githubusercontent.com/16290361/229764045-da4cd312-b973-485e-99d3-9b6aa82521e4.png)

Please increase to more lines, as many as would fit into the dialog.

**Comment by MendyBerger** [comment]
Fixed
