### ISSUE TITLE
In player info - Add in the creator's name, keywords and list of courses

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#3817]
![Screenshot 2023-04-25 at 17 43 29](https://user-images.githubusercontent.com/94056434/234313624-a8130d81-795b-4697-b709-fdbc6a189093.png)

The info button gives very little info. 
- [x] First and most important...MUST DISPLAY CREATOR'S NAME
- [x] Creator's name must be linked to their profile in the community section
- [x] the date created should go above the line opposite creator name
- [x] Why don't we have the keywords? Please list them as in the Zeplin example.
- [x] If no 'Teacher resource' attached, hide that area and heading
- [x] Show courses with the line "This JIG is part of a course." and then link to courses. 
- [x] If not included in any courses, hide that area and heading
- [x] Add a space between the name of the resource and the type of resource

![Screenshot 2023-04-25 at 17 14 15](https://user-images.githubusercontent.com/94056434/234313192-fb8881ac-f0e0-42e2-b044-308ec670baef.png)

Here is the original design please ignore text discrepancies. Go with what's live or ask me: https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/60882cc96ba6862ef6ae5e46

**Comment by RickyLB** [comment]
@corinnewo associated Playlists are listed now. 

![Screenshot 2023-06-26 at 6 18 40 PM](https://github.com/ji-devs/ji-cloud/assets/76449893/f885aeb5-707d-4095-85fd-f532fe8c972e)

**Comment by corinnewo** [comment]
@RickyLB THIS IS AWESOME! Thank you so much!

**Comment by corinnewo** [comment]
@RickyLB There is a typo in the text 'apart'. Please change "a apart" to "part", so that it reads "This JIG is part of the ..."
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/f31947ac-7852-40fc-8e67-1d8ca2fc7650)

**Comment by corinnewo** [comment]
@RickyLB You added a space between the file name and the type of resource. But looking at this, perhaps we ONLY need the type of resource, and the file name is already a tooltip. 
Can you simply list the types, one on a line (as already happens in the playlist info). For example, in the screen capture below, it would just list 'Poster', and then the name of the file is the tool tip.
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/f12de565-b8a8-42ee-a94c-373b1ea7c4ce)

**Comment by RickyLB** [comment]
@corinnewo Keywords have been added!

![Screenshot 2023-07-24 at 1 29 37 PM](https://github.com/ji-devs/ji-cloud/assets/76449893/8a2f3b10-5839-4b1e-86d6-a74c8de7ca80)
