### ISSUE TITLE
Answer this: Add in word (optional) next to the written question

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3821]
So many teachers are adding in text unnecessarily, as they think that it has to be there.
Please add in the word (optional) within the written question box when adding in new questions:
![image](https://user-images.githubusercontent.com/16290361/234550621-7ee0f428-fa3f-423e-bd5a-b2898f5c6942.png)

**Comment by MendyBerger** [comment]
Resolved in 8d5f0327b
