### ISSUE TITLE
Add Content Type field to Jig Table

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#383]
The use case of this is that Creators will be able to define what type of the content this is so that Searchers will be able to filter to the search results by the content type

This is really for LB, just want you to review first to make sure what I've written is correct

Sample types;

Introduction or “Hook"
Lesson Component (Part of a lesson)
Full Lesson
Assessment
Project
Practice
Student Creation

**Comment by dakom** [comment]
It sounds more like "Add Content Type as a row to the Jig Table" ?

(otherwise not sure what table we're adding to, or how these values relate to jigs)

**Comment by dani-ji** [comment]
Correct
