### ISSUE TITLE
Standalone course - close button in JIG within course is missing

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3830]
eg: https://jigzi.org/asset/play/course/98557f28-ea54-11ed-b72a-c73c6580cbc6?draft_or_live=live&is_student=false

Play a JIG within the course - should have an X to close and return to the course. This x is missing when the course is standalone.

![iphone - no x](https://user-images.githubusercontent.com/16290361/236396494-1a784929-ad35-43bc-a09e-9e1f613dfd48.png)

**Comment by MendyBerger** [comment]
Resolved
