### ISSUE TITLE
Create ProDev - fixes to do

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3831]
Please look at Gali's original design here: https://zpl.io/jZEE68Q

1. Add cell space between text "Build your course..." and the white area.
2. Move Video to be the first radio button
3. Change capitalization of "Add Link" to "Add link"
4. Change capitalization of "Add Description" to "Add description"
5. When adding a video, the thumbnail should also show on the panel, otherwise, it is a huge empty space: https://zpl.io/EmEENjl

![image](https://user-images.githubusercontent.com/16290361/236675603-401676e5-cca9-47cd-9b3c-348652c22d2e.png)

**Comment by corinnewo** [comment]
@GaliShapira Please add in any other corrections you would like here.

**Comment by corinnewo** [comment]
@RickyLB Thanks for the changes -please make the default radio button 'Video' and not the "Add link' item.
Are we able to add in the thumbnail of the video into the panel?

**Comment by GaliShapira** [comment]
Its very strange, I remember that I added my comments here and I dont see them... 
I am writing them again here:
1. Make sure to have gaps between the different radio buttons as in the design. 
2. You can keep the color black as you did (in the design its blue... but keep the black)
3. @corinnewo In the design I made icons as well for the nonenglish speakers, do you want to add them? We can make it without.
4. Undeneith the blue area there should be a preview of the resource, if we cant show the preview, can we make the height of the blue field aligned with the description field?

**Comment by corinnewo** [comment]
@RickyLB The only item missing here is the thumbnail of the image or video in the dialog on the right-hand dialog. What is happening with this? thanks!
