### ISSUE TITLE
Default images needed for thumbnails in ProDev player, where no image is available

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3838]
Ricky needs 'thumbnails' for the ProDev player where there are no screen grabs available, like sound files, links and PDF files. Please can you make these with the icons for him? https://zpl.io/NwqqgpQ

Need for:
1. PDF files
2. Audio files
3. Links

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/622d5a46-84ad-4c49-8786-e2f0d8be6fa8)

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/d0c1d24e-21cf-4d1c-8628-dec722e7d4c4)

**Comment by GaliShapira** [comment]
Hi @RickyLB 
Pls see the design:
https://zpl.io/5EdpzOJ

Thumbnails:
[thumbnails svgs.zip](https://github.com/ji-devs/ji-cloud/files/11488916/thumbnails.svgs.zip)

Screenshot:
<img width="959" alt="Screen Shot 2023-05-16 at 17 32 29" src="https://github.com/ji-devs/ji-cloud/assets/88834002/0d01384e-54f4-46ac-823a-f6d0b917222f">

Let me know if you need anything else.

**Comment by corinnewo** [comment]
Also see https://github.com/ji-devs/ji-cloud/issues/3757
