### ISSUE TITLE
Pro Dev Gallery kebabs: Play and Duplicate causing a crash

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3864]
From the gallery, clicking the kebab menu, there is a crash on:

- [x] Play
- [x] Duplicate

The other 2 work well.

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/08b471bc-37b2-4249-a03a-c2bf6c999396)

**Comment by RickyLB** [comment]
@corinnewo Both of Play and Duplicate work now.

**Comment by corinnewo** [comment]
Thank you! That’s great news!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
