### ISSUE TITLE
ProDev player: Fixes left to do

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3865]
- [x] Add in thumbnails for the list, and put play icons aligned to the right (also see #3838)
- [x] Image in player is still not constrained
- [x] There is a double X when you preview the module -please delete one of them!
- [x] When the description is long, need to have the 'Read more' link and open up popup to see whole description. (See https://zpl.io/JEwZEPK and https://zpl.io/RMLGzxe)

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/bb9420a1-0fcc-4128-ad24-67f56b15fe15)

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/4b22f94b-e4da-4472-9804-be1afabe29d3)

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/cbf2cad2-bccf-4f16-83ca-8e2fe680dd4c)

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/04248d96-b291-4c1e-ba51-1658daa14631)

**Comment by corinnewo** [comment]
@MendyBerger The images on sandbox ProDev are still not constrained. I see you marked as done - perhaps sandbox was not updated? Please check. Thanks!

**Comment by RickyLB** [comment]
@corinnewo The double X has been removed

**Comment by corinnewo** [comment]
@RickyLB Brilliant! Thank you!
