### ISSUE TITLE
Embed - Missing small icon

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3866]
@GaliShapira Please put embed.svg in ....ji-cloud-media\ui\entry\jig\modules\small
Thanks!

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/780f61ca-8ac3-4a8c-b031-37d203b38468)

**Comment by GaliShapira** [comment]
@corinnewo Done.
The name of the file is: embed-it

**Comment by corinnewo** [comment]
Thanks! I have renamed to embed.svg to match the programming. I hope that it sorts it out now!
