### ISSUE TITLE
Play playlist on sandbox - not working

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3890]
After PUBLISH, I clicked the Play Playlist button, and all I get is a screen that says 'Share playlist'
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/ce8ce3a2-9aae-4910-a182-b727cf85a556)

Same thing when I click Preview Playlist on the left-hand panel.

**Comment by MendyBerger** [comment]
Resolved in 15811d8bc

**Comment by corinnewo** [comment]
Thanks!
