### ISSUE TITLE
JIG player - panel - the description is too wide!

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3949]
Teacher player, clicking the 'i' button.

I noticed that when the teacher resource in the left-hand panel is a long URL, like a google link, the description is wrapped, and can only be seen with the horizontal scroll. 

Can we force the description to be the maximum width of the panel, and the link can wrap?

![description1](https://github.com/ji-devs/ji-cloud/assets/16290361/40bf17cd-92f4-4aa5-9a73-57359f9f6265)

![description2](https://github.com/ji-devs/ji-cloud/assets/16290361/26329e63-9f62-4cef-b403-c5a3c798fc5e)

**Comment by RickyLB** [comment]
@corinnewo The description and resource name seem to be contained within the info popup. Let me know if this still is the case for you. 


![Screenshot 2023-06-26 at 10 33 22 PM](https://github.com/ji-devs/ji-cloud/assets/76449893/562a49a4-8a00-48e3-a7fb-28abccf91dce)

**Comment by corinnewo** [comment]
@RickyLB I am still getting the horizontal scroll. see JIG https://sandbox.jigzi.org/asset/play/jig/3cb16426-f9ee-11ed-b5a4-d7d0fcdaa3fc?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live


![image](https://github.com/ji-devs/ji-cloud/assets/16290361/bd4a53ee-1ec0-47e0-8951-ed2dfd88cceb)
