### ISSUE TITLE
Player 'i' description - please add autodetect for Hebrew to align right

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3950]
Player 'i' description - please add autodetect for Hebrew to align right. Currently, the Hebrew description is shown aligned left.

![description1](https://github.com/ji-devs/ji-cloud/assets/16290361/613f2bc5-faf7-45f7-a365-938ce87415d8)

**Comment by johnnynotsolucky** [comment]
@corinnewo does it scroll past the popup for all jigs or is that something to do with the content of the description?

**Comment by corinnewo** [comment]
yes- I am sure it is related to the long URL. But the description should not be scrolling , even with a long URL!
