### ISSUE TITLE
Colors have changed for popup buttons (sandbox)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3966]
On sandbox:
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/c474b275-8850-43ca-9c85-965cd1e2204b)

On live: CORRECT!
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/85b3f160-535d-4936-a69b-2445c4624e92)

**Comment by MendyBerger** [comment]
I've changed it to green for now, as we don't have this color in the new button. We'll need to discuss a better solution
