### ISSUE TITLE
Community search does not seem to be working

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3974]
We looked at the person who made the first course, Dvori Mandel. Tried to search for her, and there is no result.
However, she is definitely there. as if you look in the Pincus circle (https://jigzi.org/community/circles/08c446b4-be76-11ed-91aa-57ef3f341236), she is there.

We then tried to find the next person in the Pincus list, Nina Solomon, and no result is returned. However, searching just for 'Solomon' returns 2 results, neither of them is Nina Solomon.

Please will you look into this? Could it be related to #3938?

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/34b4e65e-9405-43e5-8e40-92f2750060e6)

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/8bad4fe2-088c-46eb-a969-c6699762c76c)

**Comment by RickyLB** [comment]
@corinnewo @MendyBerger 

https://github.com/ji-devs/ji-cloud/pull/3986 PR has been added to Sandbox. This will resolve the missing users in Community once deployed to Production.
