### ISSUE TITLE
Login messages are not responsive

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3994]
I tried to **sign up** with my iphone to test what happens. The screens that I got do not fit in the screen:
![IMG_5953](https://github.com/ji-devs/ji-cloud/assets/16290361/54a0afec-2512-4d6d-be94-3bbeaa1d79bb)
![IMG_5954](https://github.com/ji-devs/ji-cloud/assets/16290361/f6f9eedd-f1bc-4c84-8532-7f38d11ddd49)

**Comment by corinnewo** [comment]
@MendyBerger This is the ticket with the 2 instances to make mobile friendly. You only did the one, according to the photo I sent you from Sammy at the conference. Please can you do both? Thanks!

**Comment by MendyBerger** [comment]
Resolved
