### ISSUE TITLE
Pro labels for Jigs, resources, Playlists, images, backgrounds and themes

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3996]
Pls see the labels used on creations and on content. 

Zeplin:
https://zpl.io/Nwy3g69

<img width="477" alt="Screen Shot 2023-07-05 at 14 19 32" src="https://github.com/ji-devs/ji-cloud/assets/88834002/e4be30b6-391a-4e60-a051-54e4b5f66c97">

<img width="314" alt="Screen Shot 2023-07-05 at 14 19 37" src="https://github.com/ji-devs/ji-cloud/assets/88834002/cd611303-9835-4c64-a3c0-dab0054434ac">

<img width="298" alt="Screen Shot 2023-07-05 at 14 19 41" src="https://github.com/ji-devs/ji-cloud/assets/88834002/f5c0a189-14e6-44e2-90eb-5e08eda57471">

**Comment by johnnynotsolucky** [comment]
Closed in #4006, #4009 and #4012
