### ISSUE TITLE
Paywall - what to lock down for each plan (Premium content)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4003]
I am only listing the items that need to be locked down. 

### FREE PLAN
- [x] Can only access **non-premium JIGs**
- [ ] Can only access **non-premium resources**
- [x] Can only access **non-premium playlists**
- [x] Can only access **non-premium courses**
- [x] Cannot create **playlists**
- [x] Can create only **5 JIGs**
- [x] Cannot upload any **resources**
- [x] Cannot create a **course** (pro-dev)
- [x] **Images** limited to non-premium
- [x] **Themes** limited to non-premium
- [x] Cannot **print** **flashcards**, memory game cards, etc (disable the option at the end of the generator activities - should still be visible, and if they click it, should have the popup to select a plan)
- [x] Cannot **print posters** (disable the option at the end of the poster activity - should still be visible, and if they click it, should have the popup to select a plan)
- [ ] **ClassMate** - disable all options: JIGzone, Scoring, My Library (not yet developed)
- [ ] Disable the '**Embed**' option in the sharing menu (if they click, will get popup to select a plan)
- [x] Can't play any **courses** in the community (click play and get popup)
- [x] Can't create a **circle** in the community

### BASIC
- [x] Can create only 5 **JIGs**
- [x] Can create unlimited playlists
- [x] Can only upload 5 **resources**
- [x] Cannot create a **course** (pro-dev)
- [x]  **Images** limited to non-premium
- [x] **Themes** limited to non-premium
- [ ] **ClassMate** - disable all options: JIGzone, Scoring, My Library (not yet developed)
- [ ] Disable the '**Embed**' option in the sharing menu (if they click, will get popup to select a plan)

### PRO
Unlimited access to all premium content

### SCHOOL
Unlimited access to all premium content

**Comment by MendyBerger** [comment]
Since resources are not played within jigzi, it's a bit more challenging to block them
