### ISSUE TITLE
Welcome - take out the extra word 'Family'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4054]
After I have signed up and completed the registration, I get the welcome dialog https://sandbox.jigzi.org/user/welcome.
It seems that there is an extra word there: Family (on the second line). Please remove.
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/3fdfda72-4268-4398-aeca-331360eb9cb1)

**Comment by MendyBerger** [comment]
Resolved
