### ISSUE TITLE
iPad - add in double-tap to edit text

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4079]
On the iPad, you cannot double-tap to edit text. This is expected, so frustrating that it does not work.
Please add it in!

**Comment by corinnewo** [comment]
@MendyBerger Has this been fixed? I have just double-tapped text on my iOS16 iPad, and i was able to edit the text. If it is, please close this ticket. Thanks!

**Comment by MendyBerger** [comment]
I believe this was fixed a while ago.
