### ISSUE TITLE
Clicking the card in the top row should play any sound that is recorded on it.

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4092]
Currently you cannot click the top row of the cards to hear any sound recorded on it. This is limiting and users have asked that this can be added. If there is audio recorded on the card/s in the top row, then clicking the card will play the audio. This is in addition to the dragging or clicking on the lower row.

This will allow interactions like playing a word voiceover, and child needs to find the correct word in the options.

**Comment by johnnynotsolucky** [comment]
Closed with #4127
