### ISSUE TITLE
Add logo and link to all registration pages and plan sign up pages

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4103]
The registration pages, as well as the plan signup pages are all full-screen pages, and once you are there, there is no way to get out of them and back to Jigzi. There must be a Jigzi logo on the top left corner of every stage, and this logo links back to the home page.
Alternatively, all the registration screens should be popups that can simply be closed and you will go back to where you were in Jigzi.

![image](https://github.com/ji-devs/ji-cloud/assets/16290361/6c05b83f-9f70-499c-b668-2af58f68aecc)

**Comment by MendyBerger** [comment]
Resolved in 209c20694
