### ISSUE TITLE
School subscription - open the Google form in new tab and change button to go back to Jigzi

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4104]
When you sign up for a school, the last step on https://sandbox.jigzi.org/user/welcome says "Next Step", which opens the form to send teachers. This should open in a **new tab**, as it currently takes you out of Jigzi totally. Once you have clicked on the "NEXT STEP" button, opened the new tab, can you change the button on the welcome screen to "Back to Jigzi" and it will open up the Jigzi home screen again?

**Comment by MendyBerger** [comment]
Resolved in 8bc6b175e
