### ISSUE TITLE
Login - Eye icon is unresponsive on login page

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#413]
Eye icon is unresponsive for previewing password on login page.
https://jicloud.org/user/signin

See screen recording:
https://www.loom.com/share/da3baec8fee54272a3a7ada4ae16478b

@dani-ji

**Comment by dani-ji** [comment]
@dakom still seems to be a problem for me

**Comment by dakom** [comment]
did you try on sandbox or master?

**Comment by dani-ji** [comment]
Master

**Comment by dakom** [comment]
merged latest changes to master now, should be fixed
