### ISSUE TITLE
Icons for My classes and My courses

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4141]
![nav-icon-Courses](https://github.com/ji-devs/ji-cloud/assets/16290361/45684ec2-2226-46ca-ae14-01235c12f28a)
![nav-icon-Medal](https://github.com/ji-devs/ji-cloud/assets/16290361/febfdb3a-7776-40c5-a187-2a1ffa56e271)

Rochi has made these SVG icons for the pull-down menu.

**Comment by MendyBerger** [comment]
@corinnewo what's the first one for?

**Comment by corinnewo** [comment]
Medal is for classes. 
Other one is for courses - which you are going to hide, but I thought you could at least have the correct icon, so that when we unhide it will be correct!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326
