### ISSUE TITLE
JIG Publish dialog - add toggles for RTL and scoring into the dialog

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4142]
People do not know about the ability to set direction and scoring in the settings of the JIG, and so they miss out. Please add these 2 settings to the publish dialog too. If they have been set in the settings, then that should be the default.

In the publish dialog:
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/98228df1-cbcf-4049-b715-4a4a358bbb70)

In the settings for the JIG:
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/67734b96-67de-4907-a85b-1a5ac873989a)

Make sure that they are similar, ie all toggles are on the same side.
Proposed position:
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/dfc626a5-a1c1-47a6-ab4b-8bdd90a794a7)

**Comment by johnnynotsolucky** [comment]
Closed in #4150
