### ISSUE TITLE
CSV Export scoring - the total score is showing as a date in excel if it is out of a score less than or equal to 12

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#4144]
![image](https://github.com/ji-devs/ji-cloud/assets/16290361/0a65c588-da1e-4546-846d-248d444aebab)

We need to make the last column have an '"' at the start so that it is text -

**Comment by corinnewo** [comment]
We discussed adding a space on either side of the / so that it is text and not a date.

**Comment by MendyBerger** [comment]
Resolved
