### ISSUE TITLE
Sign Up - No Auth

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#421]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Additional context**

**Comment by dakom** [comment]
@esteels can you please fill in the details here? Thanks!

**Comment by esteels** [comment]
@dakom my apologies -- I submitted this one in error/accidentally. I fleshed out the details in issue #422 instead.

I'll close this. Thanks!
