### ISSUE TITLE
Replace module icons

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#466]
once @NaomiLea has put the new ones in https://github.com/ji-devs/ji-cloud/blob/sandbox/frontend/templates/jig/edit/module-selection.html#L34

I need to copy/paste

(eventually we'll have global config json for this sort of thing maybe, but not now...)

**Comment by dani-ji** [comment]
@dakom this looks done, can you please confirm?

**Comment by dakom** [comment]
yep
