### ISSUE TITLE
Web image search - proxy

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#468]
New API for search that serves as a proxy for our web image search

**Comment by dani-ji** [comment]
@dakom @izik1 to clarify the requirement...the image library from the web will be saved to the specific activity it is integrated into and not shown in any further results; so any user who has access to play that activity will see it but it won't be searchable if another user is looking for an image to use in their activity

Per conversation with the CEO they would like to move forward with the integration and figure out the legal compliance/fees etc down the line/in parallel
