### ISSUE TITLE
Categories - Missing header/banner with user information

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#475]
Please add header/banner with user information (profile picture, name, etc.)

Zeplin sketch for reference: https://www.loom.com/i/09999df8e52448e6971383305dd01444 (see top right)

Current Ji Cloud Categories page: https://www.loom.com/i/64ec804c3c0c4d42a2236643e14d2af1 (missing header/banner)

**Comment by dakom** [comment]
Duplicate of #1312
