### ISSUE TITLE
Categories - Correct formatting for active categories

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#477]
Current Ji Cloud Categories page does not show selected/active categories as blue. Additionally, the 3 dots icon does not match the appearance of the one in the Zeplin sketch. Please implement the following changes: 

(1) Make the category line blue when active with **hover over** 

(2) Correct shape of 3 dot icon

Zeplin sketch for anticipated behavior + formatting: 
https://www.loom.com/i/7158e55ff5444404ac25b4742b660e6c

Ji Cloud screen recording for incorrect formatting (missing line = blue, 3 dot icon is incorrect):
https://www.loom.com/share/3e746cb27ea34d08a89a6fe79072d2ed

**Comment by dakom** [comment]
spoke with @corinnewo ... this is actually a lot of effort to fix, so we made a couple small improvements and decided to leave this
