### ISSUE TITLE
General - Lefthand Menu

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#479]
There's a discrepancy between the Ji Cloud lefthand menu and the Zeplin sketch lefthand menu. 

The Ji Cloud lefthand menu reads as follows:
New Image
Search Images
Categories
https://www.loom.com/i/71ae22a50dc94ea0afadcb93330387c0

The Zeplin sketch lefthand menu reads as follows:
Label images
Label JIGS
Edit Categories
https://www.loom.com/i/13b97a86caf7495face9c2a53576a0ff 

Please streamline labels for the lefthand menu.

**Note:** Ji Cloud screenshot is from https://jicloud.org/admin/image-add . If this link is not the correct one for the corresponding Zeplin sketches, please redirect me to the Ji Cloud labeling page. Thanks!

**Comment by dani-ji** [comment]
@corinnewo was this a decision to change the menu or should it be updated to match Zeplin?

**Comment by corinnewo** [comment]
@dani-ji No, there was no decision to rename the side panel. I think that the original Zepelin is better. However, since there is now an option to explicitly add an image, then perhaps we need to include it. 

I would suggest this list (or perhaps our editor/copy write would rename):

- Add images
- Tag images
- Tag JIGs
- Manage categories

**Comment by dakom** [comment]
Tangential Note: our frontend routes are defined [here](https://github.com/ji-devs/ji-cloud/blob/d275d745e995864366384ab81b3f397b17e1047f/frontend/apps/crates/utils/src/routes.rs#L13) and the string correspondance is [here](https://github.com/ji-devs/ji-cloud/blob/d275d745e995864366384ab81b3f397b17e1047f/frontend/apps/crates/utils/src/routes.rs#L101)

Ideally we would define this issue more like `label` -> `route`, with the real route... but it's not a big deal to be thorough with, and it can be a bit too verbose to describe like that so I don't think we need to... just noting it for reference.
