### ISSUE TITLE
Searching image property fields

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#503]
When searching for images in the image admin, the checkbox fields are not queried (example clipart) and therefore don't show in the results

1. Search clipart
2. result is zero matching images even thought there are images that have the clipart checked

https://www.loom.com/share/10889688c93d4ab3b75eae69e73ab545

**Comment by dakom** [comment]
Re-assigned to @izik1 and changed to "feature"

Needs the same solution as categories (duplicates the text for search purposes).

Potentially related to https://github.com/ji-devs/ji-cloud/issues/467
