### ISSUE TITLE
Labeling Images - Hide unexpected classification of sticker vs. canvas

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#510]
Current Ji Cloud "Upload Image" page includes classification for "Sticker" or "Canvas," which is not included in the Zeplin sketch. Please hide this unexpected classification -- unless it is now part of expected functionality.

---

**Current Ji "Upload Image"**
![Labeling_01_A_AddImage_Classification_Ji](https://user-images.githubusercontent.com/74170693/101310998-620b1580-381e-11eb-9cdc-6f9dbebfa1ce.png)

---

**Zeplin Sketch for "Upload Image"**
![Labeling_01_B_AddImage_Classification_Zeplin](https://user-images.githubusercontent.com/74170693/101311010-6800f680-381e-11eb-9e9a-a8303d1cd1ed.png)

**Comment by dakom** [comment]
Yes, this needs to be there and should be reflected in the Zeplin

Api docs page: https://docs.jicloud.org/crate/shared/domain/image/enum.ImageKind.html

**Comment by mehcode** [comment]
I would recommend that the mental model is split and there is a flow for stickers and a flow for canvas'. I imagine its not very helpful to list "all" images either but rather "all canvas'" or "all stickers".

**Comment by dakom** [comment]
Yeah it could be split into a different starting point instead of a radio which would also make it less prone to error. Or maybe even just two big squares - "Upload Sticker" vs. "Upload Canvas (alt. Fullscreen?)"

(after the image is uploaded, it's the same flow and options for tagging)

**Comment by dani-ji** [comment]
@dakom other than this not reflecting in Zeplin, can we close this?

**Comment by dakom** [comment]
yeah... if the zeplin changes mean new ui changes then we can create new issues
