### ISSUE TITLE
Labeling Images - Clarify who has access to edit categories

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#512]
Current Ji Cloud lefthand menu allows all users to access the third section, "Categories". The original Zeplin sketch however indicate that this may only be open or shown for Corinne. The Zeplin Sketch includes a lock icon, and the section is called "Edit Categories" instead of just "Categories". 

Please clarify who should have access to this section. If this section is just for Corinne, please add a lock icon. 

---

**Ji Cloud "Categories" section**
![Labeling_03_A_AddImage_CategoriesAccess_Ji](https://user-images.githubusercontent.com/74170693/101312913-fb3c2b00-3822-11eb-8c9c-28a39f26032e.png)

---

**Zeplin Sketch "Edit Categories" section**

![Labeling_03_B_AddImage_CategoriesAccess_Zeplin](https://user-images.githubusercontent.com/74170693/101312923-042cfc80-3823-11eb-8730-e5a405c6f2c7.png)

**Comment by dakom** [comment]
We need to split this into two unrelated issues:

1. The visual side of showing the lock. This is for @NaomiLea but I believe it was already done...  we may need to restructure it to be more component-based which is a more global thing and not specific to this issue.

2. The programming side of determining if the user has the required scopes _before_ rendering the sidebar, and passing that information along to affect both visibility of the lock and disabling the click. This is for me. I believe the required scope is [ManageCategory](https://docs.jicloud.org/crate/shared/domain/user/enum.UserScope.html)

**Comment by dani-ji** [comment]
@dakom I'm opening an issue for this in Image Admin milestone as it's more of something we didn't implement than a bug (ie a known bug)
