### ISSUE TITLE
Labeling Images - Confirm search filters work properly

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#515]
It's unclear if current Ji Cloud search filters are working correctly. There are 0 results shown for "Show Published" and "Show Saved". "Show All" however displays many results. 
Please confirm that the search filters are working properly.

---

**Ji Cloud "Show All"**

![Labeling_08_D_SearchImage_ShowAllFilters_Zeplin](https://user-images.githubusercontent.com/74170693/101314085-caa9c080-3825-11eb-8937-b4093bbe6361.png)

---

**Ji Cloud "Show Published"**

![Labeling_08_B_SearchImage_ShowPublished_Ji](https://user-images.githubusercontent.com/74170693/101314114-d6958280-3825-11eb-8f0d-5bbc7f2cdfab.png)

---

**Ji Cloud "Show Saved"**

![Labeling_08_C_SearchImage_ShowSaved_Ji](https://user-images.githubusercontent.com/74170693/101314129-deedbd80-3825-11eb-99df-d06932aea793.png)

**Comment by dakom** [comment]
Hmmm this was a known bug before, but it was recently closed: https://github.com/ji-devs/ji-cloud/issues/411

If it's indeed broken, that's the issue to re-open

**Comment by dani-ji** [comment]
@esteels show published works for me, can you please test again

**Comment by esteels** [comment]
@dani-ji tested again, and this time found results for "Show Published" (but not "Show Saved").

---

**Show All:**

![Labeling_08_E_SearchImage_ShowAll_Ji](https://user-images.githubusercontent.com/74170693/101869891-89c7e980-3b4e-11eb-985b-f4228d9d5eea.png)

---

**Show Published:**

![Labeling_08_F_SearchImage_ShowPublished_Ji](https://user-images.githubusercontent.com/74170693/101869905-93e9e800-3b4e-11eb-9507-fe33b5774549.png)

---

**Show Saved:**

![Labeling_08_G_SearchImage_ShowSaved_Ji](https://user-images.githubusercontent.com/74170693/101869935-9c422300-3b4e-11eb-9612-ca14c32071e9.png)

**Comment by dakom** [comment]
Hmmm we can also see this by looking at the total results returned in the request for each type.. @izik1 , should we re-open https://github.com/ji-devs/ji-cloud/issues/411 ?

![chrome_vkcKAU3FtQ](https://user-images.githubusercontent.com/6406986/101870357-1cd24500-3b8a-11eb-92d4-f0385e4c8639.png)
![chrome_wcf7ZQu8sT](https://user-images.githubusercontent.com/6406986/101870361-1d6adb80-3b8a-11eb-9558-b3537126e846.png)
![chrome_PmRxgkG6qj](https://user-images.githubusercontent.com/6406986/101870362-1d6adb80-3b8a-11eb-964e-6492f748a8eb.png)

**Comment by dakom** [comment]
Seems like there is also a bug with the number of pages returned...
