### ISSUE TITLE
Lock / Block Admin sidebar links based on scope

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#516]
Add a backend scope to only allow certain users to manage categories and other users to see a lock next to that screen

For now a UI to edit this scope for each user is not needed

**Comment by dakom** [comment]
This is mainly about the UI right? (it's still on me since it's about dynamically changing that UI at runtime)

afaik the scope already exists and if a user without permission tries to actually edit a category it won't allow them

**Comment by dani-ji** [comment]
Can you check if @esteels is excluded from that scope and if not exclude her.. @esteels once David confirms you're excluded please try to edit/add a category

**Comment by dakom** [comment]
ok I've removed these scopes for the user `esteeellis`

**Comment by esteels** [comment]
@dani-ji @dakom I was unable to edit, add, or expand categories. I was however able to access the category section. Is this intended or will the whole page be locked?

Still need lock icon to match scope; please add. 

![Labeling_23_A_EditCategories_Scopes_Ji](https://user-images.githubusercontent.com/74170693/101870352-6d787c80-3b4f-11eb-9a1d-598c314350bf.png)

**Comment by dakom** [comment]
In terms of the authorization stuff, that's all working correctly.

Re: visual lock - noted and this issue should remain open until that's done

Re: preventing access to the page, even if they navigate to it directly... I need to think about that... more of a note to my future self - there's a nuanced technical decision. On the one hand it might make sense to block them on the page server level. On the other hand, within a local SPA, they can still "navigate" (and the page-level block won't work). I think the right solution here might be to make all local routes check for local credentials first... though I'm not sure how robust it needs to be (e.g. to hit the server every time and get real live status, or just rely on whatever is cached locally). 

This is all about UX though, seems there's no actual security risk.
