### ISSUE TITLE
Re-upload original images

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#521]
Write a cli tool to re-upload the original images... make sure it's the right filename/id mapping!

Should also create new uploads for files that have been added since last time

**Comment by corinnewo** [comment]
@MendyBerger Is this still relevant?

**Comment by MendyBerger** [comment]
Don't understand the issue, @dakom remember what this is about?

**Comment by dakom** [comment]
Wish I could say I did... my best guess is it had to do with the backgrounds Jess created, and we needed to re-upload them (or maybe the stickers) because we changed the transcoding/resizing backend, or target size, or something like that.

This issue was opened a long time ago though, and we even have some utility that seems to kinda do something like that as a one-off.

My guess, fwiw, is this was done and we just forgot to close the issue. Just a guess though, sorry, can't remember for sure.

**Comment by MendyBerger** [comment]
Closing since no one knows what this is about
