### ISSUE TITLE
Labeling Images - Remove redundant image details from first column

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#531]
Image name and image details are currently listed in the first column of image details, and then re-listed in the general Summary section. 

Please match original Zeplin sketches and remove redundant details from the first column of the image details.

Note: This issue was last observed on Dec. 7th, and may have been fixed since then. Working on Ji access issues with @dani-ji.

---

**Ji Cloud with Image Name and Image Description listed in first column and General Summary:**

![Labeling_10_A_LabelImage_ReplaceDelete_Ji](https://user-images.githubusercontent.com/74170693/102004372-16ed7880-3cde-11eb-9b3a-5d4ac54c7df0.png)

---

**Zeplin Sketch with Image Name and Image Description only listed in General Summary:**

![Labeling_10_B_LabelImage_ReplaceDelete_Zeplin](https://user-images.githubusercontent.com/74170693/102004400-4d2af800-3cde-11eb-9e54-87b7195e88cc.png)

**Comment by dakom** [comment]
@corinnewo approved to keep it as-is
