### ISSUE TITLE
Labeling Images - Correct formatting for "Back to search results" 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#533]
Current formatting for "Back to search results" button needs correcting. Please implement the following changes:

- Set button to sentence case (ie only first word capitalized) per text standards. From "Back to Search Results" (incorrect) to "Back to search results" (correct)
- Make sure button is blue
- Make sure button is responsive to hover over
- Add "<" icon
- Set up on top left of page per Zeplin sketch (unless it is intentionally on the right side, in which case please update the Zeplin Sketch)

Note: This issue was last observed on Dec. 7th, and may have been fixed since then. Working on Ji access issues with @dani-ji.

---

**Ji Cloud incorrect version of "Back to search results" button:**

![Labeling_13_A_LabelImage_BackToSearch_Ji](https://user-images.githubusercontent.com/74170693/102004719-2fab5d80-3ce1-11eb-8ef9-ba2ea11f0b64.png)

---

**Zeplin Sketch correct version of "Back to search results" button:** 

![Labeling_13_B_LabelImage_BackToSearch_Zeplin](https://user-images.githubusercontent.com/74170693/102004726-38039880-3ce1-11eb-86e8-93dc28ea4bf7.png)

**Comment by dakom** [comment]
We no longer have this button, user is expected to just use their browser's back button or open the search result in a new tab for editing
