### ISSUE TITLE
Labeling Images - Correct Age Order again

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#536]
When editing "General summary" for image details, ages are not properly ordered again. See #480 for related issue in registration flow. 

Please correct age order for this screen. Per instructions from Corinne, should be:
All ages
Kindergarten
Elementary school
Middle school
High school
University

Note: This issue was last observed on Dec. 7th, and may have been fixed since then. Working on Ji access issues with @dani-ji.

---

**Ji Cloud screen with incorrectly ordered ages:**

![Labeling_17_A_LabelImage_GenSumColumns_Ji](https://user-images.githubusercontent.com/74170693/102005409-967f4580-3ce6-11eb-896d-5899f17c2efa.png)

---

**Zeplin Sketch with correct age order:**

![Labeling_17_B_LabelImage_GenSumColumns_Zeplin](https://user-images.githubusercontent.com/74170693/102005414-9b43f980-3ce6-11eb-8d63-331ca1e65e58.png)

**Comment by dakom** [comment]
This was previously blocked on https://github.com/ji-devs/ji-cloud/issues/375 but can now be fixed with the new `index` column for each meta type
