### ISSUE TITLE
Labeling Images - Correct content for Jewish stream List

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#539]
When editing "General summary" of image details, there are discrepancies in the lists for "Jewish stream" between Zeplin Sketch and Ji Cloud. 

Zeplin Sketch reads as follows:
- All
- No religion
- Reform/Conservative
- Orthodox
- Charedi

![Labeling_21_B_LabelImage_GenSumSearchResults_Zeplin](https://user-images.githubusercontent.com/74170693/102042009-cee25a80-3d9e-11eb-82b0-336aeb7d07ce.png)

Current Ji Cloud reads as follows:
- Show me everything
- No religious content
- Reform/Liberal content
- Orthodox content
- Conservative content
- Israeli secular content
- Charedi content

![Labeling_21_A_LabelImage_GenSumSearchResults_Ji](https://user-images.githubusercontent.com/74170693/102041988-c5f18900-3d9e-11eb-8257-c3000eb6e00b.png)

Please streamline lists to match Zeplin Sketch, with some edits recommended. See below for suggested list: 
- All
- No religion
- Reform
- Conservative
- Orthodox
- Israeli secular
- Charedi

**Comment by dakom** [comment]
See https://github.com/ji-devs/ji-cloud/issues/273
