### ISSUE TITLE
Constraint on ApiResult::Err

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#540]
Currently, we are handling generic errors like Forbidden and InternalError only as variants on each proprietary error type... this doesn't scale well and makes it hard to exit early due to these common errors on the frontend

Rather, [ApiEndpoint::Err](https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/trait.ApiEndpoint.html#associatedtype.Err) should have a constraint such that it must satisfy a trait, let's say `HttpError`, which gives us:

1. A method to get the numeric status code
2. Some couple helper methods for common cases (is_forbidden(), is_internal())

That way, a generic frontend fetch() wrapper can handle these common errors early without needing to be aware of the concrete error type.

We can also have a simple common struct which `impls` HttpError, such as `BasicError`, for the api's that _only_ need to error in these situations and have no proprietary errors otherwise

**Comment by dakom** [comment]
Discussed on Slack - might not be a trait, but rather a concrete type which has a generic inner error

**Comment by izik1** [comment]
Closed in #553
