### ISSUE TITLE
Labeling Images - Pease add "Expand all" and "Collapse all" as hover over interactions for individual categories

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#557]
Current Ji Cloud has "Expand all" / "Collapse all" as static buttons that impact all of the categories when editing categories of a given image. Zeplin Sketches indicate that these should be available **hover over** interactions for **individual** categories.

Please format "Expand all" / "Collapse all" to be hover over interactions that apply to individual categories. 

---

**Current Ji Cloud screens with "Expand all" / "Collapse all" as static buttons on the top of the page:**

![Labeling_29_A_SearchImages_ButtonLabel_Ji](https://user-images.githubusercontent.com/74170693/102720613-6bd35500-42c3-11eb-8995-d7a202362eba.png)

---

**Zeplin Sketch of "Expand all" and "Collapse all" as individual hover over interactions:**

![Labeling_29_B_SearchImages_ButtonLabel_Zeplin](https://user-images.githubusercontent.com/74170693/102720626-7988da80-42c3-11eb-84cc-d6c8a76ca157.png)

![Labeling_28_D_SearchImages_Expand:Collapse_Zeplin](https://user-images.githubusercontent.com/74170693/102720634-83aad900-42c3-11eb-8d4b-10dae8d299dc.png)

**Comment by dakom** [comment]
Zeplin is out of date. Was closed with discussion here: https://github.com/ji-devs/ji-cloud/issues/371

**Comment by esteels** [comment]
Thank you @dakom! I'll close this request then -- much appreciated.
