### ISSUE TITLE
Labeling Images - Avoid crowding when implementing 2 columns of text (?)

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#559]
Zeplin sketches suggest having 2 columns for General Summary and Categories Summary, "In case there is a lot of info". It's not clear to me when this would need implementation and how it would look -- but this may cause more crowding issues for the text. Is this still an expected functionality for the Ji Cloud flow?

Preemptive issue: please avoid crowding when implementing 2 columns of text.

---

**Zeplin Sketch for 2 columns of text:**

![Labeling_32_B_SearchImages_PrePublish_Zeplin](https://user-images.githubusercontent.com/74170693/102721932-ccff2680-42cb-11eb-9902-0ad64e896295.png)

**Comment by dakom** [comment]
agreed - needs brief, closing for now
