### ISSUE TITLE
Jig Editing - Add missing banner

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#560]
Zeplin sketches indicate there should be a Ji Banner on the top left JIG Editing page. 

Please add missing banner to the Ji Cloud screen.

---

**Ji Cloud screen missing banner:**

![JIGs_02_JiBanner_A_Missing_Ji](https://user-images.githubusercontent.com/74170693/102744859-be932800-4328-11eb-8a8b-0495ee5d67dc.png)

---

**Zeplin Sketch with banner:**

![JIGs_02_JiBanner_B_Missing_Zeplin](https://user-images.githubusercontent.com/74170693/102744869-c6eb6300-4328-11eb-8e23-038a814d1a83.png)

**Comment by dakom** [comment]
This is now implemented by having the Jigzi logo which brings them to the homepage, and there they have the full header.

A change would need a UI brief
