### ISSUE TITLE
JIG Editing - Correct behavior for editing project name

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#563]
Zeplin sketch suggests the JIG name field is editable by a double click, and that the icon [in the field] is not clickable (see screenshot below, specifically the instructions on the bottom right of the screen). Current Ji Screen has icon outside of field, and the field is editable with one click instead of double click.

Please correct Ji Cloud field interaction to respond to double click + have the edit icon in the field itself.

---

**Zeplin Sketch with instructions for project name field:**

![JIGs_05_ProjectName_B_Editing_Zeplin](https://user-images.githubusercontent.com/74170693/102745856-f7340100-432a-11eb-9e7a-4f50af1bd5ca.png)

---

**Ji Screen with incorrectly placed icon and behavior:**

![JIGs_05_ProjectName_A_Editing_Ji](https://user-images.githubusercontent.com/74170693/102745852-f307e380-432a-11eb-9d28-e24d45111fc2.png)

**Comment by dakom** [comment]
@dani-ji note that this applies to two different domains - the interaction part is on me (click icon and double-click field for edit) while the icon placement is @NaomiLea
