### ISSUE TITLE
JIG Editing - Show two states (regular and selected) for activities in the lefthand bar

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#564]
Zeplin Sketches indicate that the activities in the lefthand bar should have two states: regular (white) and selected (light grey with a blue line). See screenshot below with special attention to the instructions at the bottom right. Currently only the "Cover" activity displays selected activities. 

Please implement 2 states for all activities in the lefthand bar --  regular and selected.

---

**Zeplin Sketch with instructions for 2 states:**

![JIGs_06_TwoStates_B_Unresponsive_Zeplin](https://user-images.githubusercontent.com/74170693/102746152-abce2280-432b-11eb-836f-9c5081a42d2f.png)

---

**Ji Cloud screen:**

![JIGs_06_TwoStates_A_Unresponsive_Ji](https://user-images.githubusercontent.com/74170693/102746114-91944480-432b-11eb-934f-a3876585b575.png)

**Comment by dakom** [comment]
The Zeplin reference here is a bit misleading I think - none of the modules in the left sidebar should be selected while in this mode. Rather, selecting a module will redirect to that module's app editing page.

For example, selecting "Cover" will effectively change the main right area to be "design a cover page"
