### ISSUE TITLE
JIG Editing - Remove unnecessary "clipboard" note

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#566]
The Ji Cloud screen displays the following unnecessary notification: "The activity was copied to your clipboard". This does not seem to be a default display / not in response to any clear interaction, and this text is not included in the original Zeplin Sketches.

Please remove the unnecessary "clipboard" notification from the Ji Cloud sreen.

---

**Ji Cloud Screen with unnecessary note (highlighted):**

![JIGs_08_CopiedClipboard_A_Note_Ji](https://user-images.githubusercontent.com/74170693/102746746-dd93b900-432c-11eb-94fa-4ebb220310c5.png)

---

**Original Zeplin sketch with no notification:** 

![JIGs_08_CopiedClipboard_B_Note_Zeplin](https://user-images.githubusercontent.com/74170693/102746740-da98c880-432c-11eb-8097-c69d97bef34a.png)

**Comment by dakom** [comment]
Note that this one is on me, not @NaomiLea (though it will also resolve itself as we move to be more component-based, since the previous system more often tended toward _hiding_ elements until they were needed, and the new system will be more about _showing_ elements only as they are needed)

**Comment by esteels** [comment]
Adding additional screenshot from Zeplin indicating when the "copied to clipboard" notification should be visible (ie after copied is selected from 3 dots menu): 

![JIGs_08_CopiedClipboard_C_Note_Zeplin](https://user-images.githubusercontent.com/74170693/103186784-ec7bed80-488f-11eb-8ec8-41bb1a7459c7.png)
