### ISSUE TITLE
JIG Editing - Add missing "Print" option in menu

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#569]
Current Ji Screen is missing "Print" option for three dots menu. 

Please add print option.

---

**Original Zeplin Sketch with Print option:**

![JIGs_12_OptionMenu_B_Print_Zeplin](https://user-images.githubusercontent.com/74170693/102749769-93153b00-4332-11eb-9e37-2603798596da.png)

---

**Current Ji Cloud Screen missing Print option:**

![JIGs_12_OptionMenu_A_Print_Ji](https://user-images.githubusercontent.com/74170693/102749776-97d9ef00-4332-11eb-8752-e129819b7ea4.png)

**Comment by dakom** [comment]
@dani-ji I thought we concluded that print would only be an option inside of specific modules, not from the outside here, both for technical reasons and UX.

For example, it doesn't make sense for many eventual module types (video, various games, etc.)
