### ISSUE TITLE
JIG Editing - Set scrollbar to respond to hover over

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#580]
Original Zeplin sketch indicates scrollbar should respond to mouse hover over. Current Ji Cloud screen does **not** respond to hover over, although it does become visible when activated. See loom recording: https://www.loom.com/share/23cee71e147848c2be901fdb0f698b22

---

**Original Zeplin Sketch** 

![JIGs_10_ScrollBar_A_HoverOver_Zeplin](https://user-images.githubusercontent.com/74170693/103120611-7df81f00-4646-11eb-9d64-832b22fca33d.png)

**Comment by dakom** [comment]
this just follows the native browser's scrollbar implementation
