### ISSUE TITLE
JIG Editing - Correct behaviors for cover / ending sections in activity list

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#583]
Zeplin sketch lists the following properties for the cover and ending sections:
- display "selected" properties on hover over (ie mark as selected with grey fill and blue line)
- open "tool tip" that reads "Click to design"

Current Ji Cloud screen does not reflect these behaviors. See loom recording: https://www.loom.com/share/c8fb3ec4e17449bc857589f19c2635a3

Please correct behaviors for cover / ending sections. 

---

**Zeplin Sketch with cover/ending behavior details:**

![JIGs_16_CoverEnding_A_Behavior_Zeplin](https://user-images.githubusercontent.com/74170693/103121505-70dd2f00-464a-11eb-9650-e8ea2ac2ad80.png)

**Comment by dakom** [comment]
Outdated design
