### ISSUE TITLE
JIG Editing - Correct activity icon behavior for hover

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#585]
Zeplin sketches outline the following 2 behaviors for activity icons when mouse hovers over it:

- the icon is changed to hover state
- the icon is draggable. A cursor of drag (open hand)

The current Ji Cloud screens do NOT include the icon changing to a hover state, although they DO include the open hand drag cursor. See Loom recording: https://www.loom.com/share/1fc0e2d01adf4694ac31c2c2f714534e

Please correct the activity icon behavior by changing the icon appearance to hover state when mouse hovers over it.

---

**Zeplin Sketch for anticipated interaction:**

![JIGs_17_ActivityHover_A_IconsBehavior_Zeplin](https://user-images.githubusercontent.com/74170693/103181832-97ca7980-4873-11eb-8e9b-887296b03a99.png)

---

**Zeplin Sketch for hover state specs:**

![JIGs_17_ActivityHover_B_IconsBehavior_Zeplin](https://user-images.githubusercontent.com/74170693/103181833-99943d00-4873-11eb-8536-8831390a405c.png)

---

**Ji Cloud Screen with incorrectly sized activity icon:** 

![JIGs_17_ActivityHover_C_IconsBehavior_Ji](https://user-images.githubusercontent.com/74170693/103181834-99943d00-4873-11eb-804d-7f299e96826a.png)

**Comment by NaomiLea** [comment]
This design has changed and can be closed no? @dani-ji
