### ISSUE TITLE
JIG Editing - Correct activity icon behavior for grabbing and dragging

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#586]
Zeplin sketch describes anticipated activity icon behavior for grabbing and dragging:
- cursor of drag (hand closed)
- when the icon is dragged, there is a tray shade in the icon's place.

In the current Ji Cloud screens, neither of these behaviors are implemented. See Loom recording: https://www.loom.com/share/b1e88217d6264016b6a36fa8daa36a89

Please correct activity icon behavior for grabbing and dragging with a closed hand cursor, and with an empty tray.

---

**Zeplin sketch with anticipated behavior:**

![JIGs_18_ActivityGrabbed_A_IconsBehavior_Zeplin](https://user-images.githubusercontent.com/74170693/103182236-e5e17c00-4877-11eb-9a71-cf26b427da24.png)

**Comment by dani-ji** [comment]
@dakom I believe to the conclusion the 'empty tray' is not reasonably feasible correct? But the cursor should be changing

**Comment by dakom** [comment]
yeah, I guess it's more a UX decision, but you can add poster multiple times for example so I don't think it's supposed to disappear from the options.
