### ISSUE TITLE
Labeling Images - Fix unresponsive "Upload Image" button 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#603]
I'm testing the "Upload Image" button, and unfortunately it does not seem to be responsive. See Loom recording here: https://www.loom.com/share/af8ad74bdb9a4ce094e28ce7a45bed7f 

Please fix "Upload Image" button. If there are errors with the upload process, please add error notifications as well.

---

**Zeplin Sketch of Upload Image button:**

![Labeling_35_B_UploadImage_Unresponsive_Zeplin](https://user-images.githubusercontent.com/74170693/103427195-43820b00-4b8d-11eb-977e-4e5e759e5af2.png)

**Comment by dakom** [comment]
This is probably due to the changes we made on the backend for media types in general (e.g. https://github.com/ji-devs/ji-cloud/issues/548)

It's a genuine bug, but will probably be fixed very easily once we get back into the frontend app development on the Rust side

**Comment by dakom** [comment]
@dani-ji I went ahead and assigned this to myself (but didn't remove you, feel free to remove yourself)

**Comment by dakom** [comment]
@esteels - I'd say all bets are off for anything having to do with images until we can resolve this (currently waiting on html/css stuff, I'd guess sometime mid/late next week)

**Comment by esteels** [comment]
excellent, thank you @dakom! I'll keep an eye on it.
