### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#605]
TBD

**Comment by izik1** [comment]
I think this is finished on the backend "initially", per discussion in slack.
The result of this is that:
* the frontend has access to `/v1/search/key` which generates a key to access Algolia (currently expires in 15 minutes. If needed that can be adjusted or made configurable)
* an query suggestions index needs to be created (see [Creating a Query Suggestions index](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/query-suggestions/how-to/creating-a-query-suggestions-index/js/))
* The frontend then uses the key it generated to query that index, parse the results and display queries

The only thing that might throw a wrench in this is #593, which is being worked on

**Comment by dani-ji** [comment]
I believe this is set up now
