### ISSUE TITLE
QA Login and Signup 

### ISSUE THREAD

**Issue by NaomiLea** [ji-devs/ji-cloud#608]
Check the login and signup pages. 
Things that can only be checked after the implementation and should be disregarded at this state is
1. Error and helpmessages
2. Inputfield changes at different states
3. Password strength changes (the green line is a placeholder and the word strong will not always be there)
4. Icons displaying in the input fields 
5. The 

The right design should look like this 
https://zpl.io/b6Xzrvy

But it should follow this flow
https://zpl.io/bPevo9p

All pages can be found in Storybook Full Pages Login

**Comment by dakom** [comment]
@NaomiLea these things should be in storybook - ideally via controls, but separate stories is ok too

I also noticed that some of the controls that are there are ineffective (like `Instruction` on `Login Change Email`)

**Comment by dani-ji** [comment]
@esteels I believe this can be closed?

**Comment by esteels** [comment]
@dani-ji closing QA for Registration/Login/Sign Up.
