### ISSUE TITLE
Login Change Email (Storybook) - Add link for "If you need our help..."

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#611]
Zeplin sketches include a line "If you did our help, kindly contact us in: Info@JI.com" (there are a few spelling / grammatical corrections needed for this line). See screenshot below + link to [corresponding Zeplin Screen ](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f6236ab6e8ac3a485981abd)

Storybook screen does not have this line. 

Please make the following adjustments:
(1) Add line
(2) Correct grammar to read the following: "If you need our help, kindly contact us at: Info@JI.com" 

---

**Original Zeplin Sketches with line:**

![Registration_22_A_ChangeEmail_HelpContact_Zeplin](https://user-images.githubusercontent.com/74170693/103940811-f9080d80-50fb-11eb-80ed-764f87cb5190.png)

---

**Storybook Screen without line:**

![Registration_22_B_ChangeEmail_HelpContact_SB](https://user-images.githubusercontent.com/74170693/103940888-176e0900-50fc-11eb-9112-c1afbfb51b4c.png)

**Comment by corinnewo** [comment]
Please correct the email address to info@jewishinteractive.org. The email address is incorrect!

Sent from my iPhone

Corinne Ossendryver
CPO, Jewish Interactive 
(+27) 079-8865326

**Comment by esteels** [comment]
@NaomiLea, looks good. Thanks!

**Comment by esteels** [comment]
@NaomiLea reopening for minor text edit.

Please change text to "at" instead of "on":

"If you need our help, kindly contact us at:"

**Comment by NaomiLea** [comment]
fixed :)

**Comment by chayaml** [comment]
Line added with corrected edit

**SB Screen:**
![Screen Shot 2021-02-10 at 2 04 14 PM](https://user-images.githubusercontent.com/78186896/107559359-fe002700-6ba9-11eb-865c-034cfc321829.png)
