### ISSUE TITLE
Login Change Email (Storybook) - Reconcile missing Zeplin text

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#612]
[Zeplin sketch](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f6236ab6e8ac3a485981abd) includes this text:

"This is the email that you filled in, You can change it now"

This text is missing from the Storybook screen. 

Please make the following adjustments:
(1) Add missing text if it is meant to be there
(2) Add field to show email
(3) Correct punctuation to "This is the email that you filled in. You can change it now."

---

**Original Zeplin Sketch with text:**

![Registration_24_A_ChangeEmail_ThisIsEmail_Zeplin](https://user-images.githubusercontent.com/74170693/103941927-94e64900-50fd-11eb-8353-9b90d3662ac9.png)

---

**Storybook screen without the text:**

![Registration_24_B_ChangeEmail_ThisIsEmail_SB](https://user-images.githubusercontent.com/74170693/103941973-a7608280-50fd-11eb-8352-2b4d964bcdc1.png)

**Comment by NaomiLea** [comment]
This has been fixed. Please check on Monday when merged

**Comment by esteels** [comment]
@NaomiLea, looks good. Thanks!

@dani-ji, I opened a new request on [Monday.com](https://jii.monday.com/boards/707048115/pulses/966294733) to address the wording per email.
