### ISSUE TITLE
Registration Complete - update UI

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#613]
[Zeplin sketch](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f6236aa1eab76a5fcb27752) includes an animation placeholder. 

Current Storybook screen does not have placeholder.

Please add animation placeholder to screen.

---

**Zeplin sketch with placeholder:**

![Registration_26_B_Confirmationl_AnimationPlaceholder_Zeplin](https://user-images.githubusercontent.com/74170693/103942270-25248e00-50fe-11eb-9322-7c918e4a57c5.png)
 
---

**Storybook screen without placeholder:**

![Registration_26_A_Confirmationl_AnimationPlaceholder_SB](https://user-images.githubusercontent.com/74170693/103942329-39688b00-50fe-11eb-9113-f1ee8c5e37af.png)

**Comment by dani-ji** [comment]
Animation placeholder won't be added but leaving open to make sure we remember to come back to add the animation once it has been created

**Comment by dakom** [comment]
Note this is https://jigzi.org/user/register-complete - for right now it's just missing the static image placeholder

Also should be "Jigzi" instead of "Ji"
