### ISSUE TITLE
Login Sign Up Four (Storybook) - Reword line for "It might had got to the promotion or spam’s folders" 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#616]
Previous edits/issues to Login screens resulted in rewording of line for "It might had got to the promotion or spam’s folders...". Neither the Zeplin old design pages nor the current Storybook screen reflect these changes, but the previous Ji Cloud screens do (see screenshots below).

Please reword this line to, "It may have been filtered into the promotion or spam folders" 

---

**Previous Ji Cloud version:**

![Registration_33_A_SignUpFour_WonkyGrammar_Ji](https://user-images.githubusercontent.com/74170693/103962642-6f6d3580-5125-11eb-96e1-fe26b1ece413.png)

---

**Incorrect Storybook version:** 

![Registration_33_B_SignUpFour_WonkyGrammar_SB](https://user-images.githubusercontent.com/74170693/103962643-7005cc00-5125-11eb-94ec-b41192e1aaf3.png)

---

**Incorrect Zeplin version:**

![Registration_33_C_SignUpFour_WonkyGrammar_Zeplin](https://user-images.githubusercontent.com/74170693/103962644-7005cc00-5125-11eb-9399-a271190a8175.png)

**Comment by NaomiLea** [comment]
This has been fixed. Please check on Monday when it has been merged

**Comment by esteels** [comment]
Looks good @NaomiLea . Thanks!
