### ISSUE TITLE
Login Sign Up Four (Storybook) - Add notification for "We have just sent you another email" 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#617]
[Zeplin sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f6236996e8ac3a485981aa5) include a notification when users send another email. It's unclear to me if current Storybook screen has this notification or not. 

If the notification is erroneously missing, please make the following following edits:
- add notification
- suggested rewording to "We just sent you another email" to match screen title (ie remove the word "just")

---

**Zeplin Sketch for notification:**

![Registration_34_B_SignUpFour_PleaseSendAgainButton_Zeplin](https://user-images.githubusercontent.com/74170693/103963382-1b635080-5127-11eb-80a4-b23747c7ccd3.png)

**Comment by NaomiLea** [comment]
This has been fixed but needs implementation.

**Comment by esteels** [comment]
@NaomiLea, thanks! @dani-ji, closing request.
