### ISSUE TITLE
Login Sign Up One (Storybook) - Change "Family Name" to "Last Name"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#619]
Previous edits/issues to Login screens resulted in change of "Family Name" to "Last Name". Neither the Zeplin old design pages nor the current Storybook screen reflect these changes, but the previous Ji Cloud screens do (see screenshots below).

Please change "Family Name" to "Last Name"

---

**Previous Ji Cloud screen with Last Name:**
![Registration_35_C_SignUpOne_LastName_Ji](https://user-images.githubusercontent.com/74170693/103963619-bbb97500-5127-11eb-8cff-b2df4903e5ea.png)

---

**Current Storybook screen with Family Name:**
![Registration_35_A_SignUpOne_LastName_SB](https://user-images.githubusercontent.com/74170693/103963617-bb20de80-5127-11eb-800c-b7ecc9247928.png)

---

**Zeplin Sketch with Family Name:**
![Registration_35_B_SignUpOne_LastName_Zeplin](https://user-images.githubusercontent.com/74170693/103963618-bb20de80-5127-11eb-96d6-34968c50c93c.png)

**Comment by NaomiLea** [comment]
This has been fixed. Just need it to merge (please check on monday)

**Comment by esteels** [comment]
Looks good @NaomiLea . Thanks!
