### ISSUE TITLE
Login, Many Screens (Storybook) - Reformat line for "Already have an account? Login"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#620]
Previous edits/issues to Login screens resulted in reformatting of line for "Already have an account...". Neither the Zeplin old design pages nor the current Storybook screen reflect these changes, but the previous Ji Cloud screens do (see screenshots below).

Please reformat the line in the following ways:
(1) Add Login -- "Already have an account? Login"
(2) Adjust coloring so that "Already have an account?" is regular text, and "Login" is blue/hyperlinked text

These two edits apply to many screens, such as the following:
- Sign Up Start
- Sign Up One
- Sign Up Two **NOTE:** [Zeplin sketch](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f62350d5851c3018f4e8aab) for this screen does NOT feature this text, so it may not be necessary in the SB screen at all. If it is not needed on this screen, please remove the text for "Already have an account?". 

---

**Previous Ji Cloud Screen reflecting this reformatted text:**

![Registration_36_C_SignUpOne_LoginButton_Ji](https://user-images.githubusercontent.com/74170693/103964063-819ca300-5128-11eb-9b11-8467ed428da0.png)

---

**Storybook link, without updated text formatting:**

![Registration_36_A_SignUpOne_LoginButton_SB](https://user-images.githubusercontent.com/74170693/103964059-81040c80-5128-11eb-8d59-b4c870045904.png)

---

Zeplin link, without updated text formatting:

![Registration_36_B_SignUpOne_LoginButton_Zeplin](https://user-images.githubusercontent.com/74170693/103964061-81040c80-5128-11eb-8ef6-a743c86e8a43.png)

**Comment by NaomiLea** [comment]
This can be tested

**Comment by esteels** [comment]
@NaomiLea , looks good. Thanks! 

Sign Up Start -- looks good
Sign Up One -- display blocked by error message (will follow up to confirm this looks good)
Sign Up Two -- looks good
