### ISSUE TITLE
Login Sign Up Four (Storybook) - Suggested correction for punctuation

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#624]
Text on [Storybook Sign up Four](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-four) reads "I didn’t receive an email, Please send again". This is consistent with [Zeplin sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f62369c2e32467af3e0bbd7), but it does not seem correct to me.

**Suggested correction:** "I didn’t receive an email, please send again" (ie lowercase p)

---

**Storybook Screen of "Please send again":**

![Registration_47_A_SignUpOne_PleaseSend_SB](https://user-images.githubusercontent.com/74170693/103975692-c46b7480-5142-11eb-8788-58fa3bd94762.png)

---

**Zeplin Sketches of "Please send again":**

![Registration_47_B_SignUpOne_Location_Zeplin](https://user-images.githubusercontent.com/74170693/103975693-c5040b00-5142-11eb-8e2f-a55663dcd431.png)

**Comment by NaomiLea** [comment]
This has been fixed, just needs merging. Please check again on Monday

**Comment by esteels** [comment]
Looks good @NaomiLea . Thanks!
