### ISSUE TITLE
Login Sign Up Three (Storybook) - Confirm lists for content streams

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#625]
Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-three) does not match the [Zeplin sketch](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5f6234ff1142517b9a42f468) for content streams.  

Zeplin list is as follows:

- Show me everything
- No religious content
- Reform content
- Conservative content
- Orthodox content
- Charedi content
- Israeli Secular content

Please confirm and reconcile correct list for content streams and correct as necessary. 

---

**Storybook screen for list of content streams:** 

![Registration_46_A_SignUpOne_ContentStreams_SB](https://user-images.githubusercontent.com/74170693/103976303-66d82780-5144-11eb-86bd-694362ac86fc.png)

---

**Zeplin screen for list of content streams:**

![Registration_46_C_SignUpOne_ContentStreams_Zeplin](https://user-images.githubusercontent.com/74170693/103976538-00073e00-5145-11eb-94dc-d53da47955bc.png)

**Comment by NaomiLea** [comment]
This has been fixed just need to be merged. Please confirm on monday

**Comment by esteels** [comment]
Looks good @NaomiLea . Thanks!
