### ISSUE TITLE
General, Many Screens - Confirm criteria for Headings and Subheadings for cases

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#627]
[Text Standards for Ji-2](https://docs.google.com/document/d/1VQ6dnxJGvr3YRHYOScsXrh00McEj6fmhwSFlSl7YBvs/edit?usp=sharing) specifies case details for Headings and subheadings. 

**Headings:**

- Title Case: All words with a capital letter

**Subheadings:**

- Sentence case
- Eg: Image description, etc.

The criteria for establishing Headings vs. Subheadings is unclear to me. Is the control field that's labeled "title" considered a Heading or Subheading? Based on sentence case formatting in Zeplin and Storybook, it appears to be a Subheading -- but this strikes me as a counterintuitive classification. See sample screenshot from [Sign Up Two](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-two):

![Registration_49_A_SignUpOne_Title_SB](https://user-images.githubusercontent.com/74170693/103980815-9724c380-514e-11eb-9c8c-f9335aaf8e25.png)

If the "title"s are Subheadings, no changes are needed.
If the "title"s are Headings, the text needs to be corrected to title case in the following instances: 

**- Login Change Email:** "Change Email Account"
**- Confirmation:** "Welcome to JI Family"
**- Login Forgot Password:** "Create a New Password"
**- Login Full One:** NA / no changes needed
**- Sign Up Four:** "We Just Sent You an Email"
**- Sign Up One:** "Sign Up - Step 1"
**-Sign Up Start:** "Sign Up"
**- Sign Up Three:** "Sign up - step 3"
**- Sign Up Two:** "Sign Up - Step 2"
**- User Info:** NA / no changes needed

(@corinnewo, this is a follow-up to our email conversation. Many thanks for all of your guidance!)

**Comment by NaomiLea** [comment]
This has been fixed. Just need to check once merged. (Monday)

**Comment by esteels** [comment]
Looks good @NaomiLea. Thanks!
