### ISSUE TITLE
Login Full One (Storybook) - Confirm Google assets preview correctly 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#628]
Image for Google Sign In is not displaying properly for me on any of the Storybook screens. Is there something wrong with the asset, or is it just not previewing for me/on my computer? 

![Registration_29_A_LoginFullOne_GoogleImage_SB](https://user-images.githubusercontent.com/74170693/103982111-dce28b80-5150-11eb-9a63-dafe3c403cec.png)

Please confirm that the google asset previews correctly. If this is an issue on my end, please let me know how I can fix it.

**Comment by dani-ji** [comment]
appears to be resolved
