### ISSUE TITLE
QA Image labelling

### ISSUE THREAD

**Issue by NaomiLea** [ji-devs/ji-cloud#634]
https://zpl.io/2ZlAPMl

Please bare in mind the the tree doesnt look 100% right. This will be fixed once implementation is done.

**Comment by dani-ji** [comment]
@NaomiLea where is the page in Storybook?

**Comment by dakom** [comment]
We were having back-and-forth to fix up some showstopping issues outside of the code review mechanism. It's fixed enough now (as in, just within the last half hour) to let the PR through for visual QA - but still needs more work before it can be implemented on the Rust side.

Will merge it now
