### ISSUE TITLE
Login Confirmation (Storybook) -- Correct controls

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#644]
Manual QA test of some controls produces no noticeable changes to the Storybook screen.

Please correct the following controls on the [Login Confirmation Screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--confirmation):
- bold (true/false)
- italics (true/false) 

---

**Storybook screenshot of controls:**

![Registration_54_A_LoginConfirmation_Controls_SB](https://user-images.githubusercontent.com/74170693/104547994-da26e100-55fd-11eb-9b74-6eb382fc34fa.png)

**Comment by esteels** [comment]
Updated controls page: 

![Registration_54_B_LoginConfirmation_Controls_SB](https://user-images.githubusercontent.com/74170693/104853626-214bf500-58d0-11eb-9945-008a2c77b557.png)

**Comment by dakom** [comment]
The updated image looks right to me. 

Unfortunately, I don't know off the top of me head of a way to tell storybook "don't even give an option to view controls for this page if there aren't any", so we'll just have to deal with that ugly yellow bar for now :/
