### ISSUE TITLE
Login Forgot Password (Storybook) -- Correct controls

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#645]
Manual QA test of some controls produces no noticeable changes to the Storybook screen.

Please correct the following controls on the [Login Forgot Password Screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--login-forgot-password):
- helpertext
- errormessage
- instruction (true/false)
- error (true/false)
- visible password (true/false) -- password does NOT become visible

See loom recording: https://www.loom.com/share/938ba555db1f4eea8e11e8a85c9cc980

---

**Storybook screenshot of controls:**

![Registration_55_A_LoginForgotPassword_Controls_SB](https://user-images.githubusercontent.com/74170693/104548227-5d483700-55fe-11eb-8e73-28010140869e.png)

**Comment by NaomiLea** [comment]
@dani-ji controls not needed on this page
