### ISSUE TITLE
Login Full One (Storybook) -- Correct controls

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#646]
Manual QA test of some controls produces no noticeable changes to the Storybook screen.

Please correct the following controls on the [Login Full One Screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--login-full-one):

- helpertext 
- errormessage
- instruction (True/False)
- error (TrueF/alse)
- visiblepassword (true/false) 

---

**Storybook screenshot of controls:**

![Registration_56_A_LoginFullOne_Controls_SB](https://user-images.githubusercontent.com/74170693/104549034-06dbf800-5600-11eb-9bc5-e7623721e500.png)

**Comment by NaomiLea** [comment]
@dani-ji controls not needed on this page
