### ISSUE TITLE
Login Sign Up Four (Storybook) -- Correct controls 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#647]
I cannot access controls on [Sign Up Four screen.](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-four)

Please correct and/or direct me toward controls I can test.

---

**Storybook screenshot of controls:**

![Registration_57_A_SignUpFour_Controls_SB](https://user-images.githubusercontent.com/74170693/104549259-8073e600-5600-11eb-81a8-2ef8fee9e504.png)

**Comment by dani-ji** [comment]
@NaomiLea don't believe controls are needed on page so closing
