### ISSUE TITLE
Login Sign Up Start (Storybook) -- Correct controls

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#649]
Manual QA test of some controls produces no noticeable changes to the Storybook screen.

Please correct the following controls on the [Sign Up Start](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-start) Screen:

- helpertext -- nothing displays
- errormessage -- nothing displays 
- instruction (true/false) -- no change
- error (true/false) -- no change
- imghidden (true/false)	-- no change
- visiblepassword (true/false) -- icon changes, but password visibility does NOT change

---

**Storybook screenshot of controls:**

![Registration_59_A_SignUpStart_Controls_SB](https://user-images.githubusercontent.com/74170693/104549958-cf6e4b00-5601-11eb-82f1-9dbd67a7403d.png)

**Comment by NaomiLea** [comment]
@dani-ji controls not needed on this page
