### ISSUE TITLE
Login Sign Up Three (Storybook) -- Correct controls

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#650]
I cannot access controls on [Sign Up Three](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-three) screen.

Please correct and/or direct me toward controls I can test.

---

**Storybook screenshot of controls:**

![Registration_60_A_SignUpThree_Controls_SB](https://user-images.githubusercontent.com/74170693/104550173-41469480-5602-11eb-8558-32de6bb350ba.png)

**Comment by dani-ji** [comment]
Controls not needed on this page
