### ISSUE TITLE
Login Sign Up Two (Storybook) -- Correct controls 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#651]
Manual QA test of some controls produces no noticeable changes to the Storybook screen.

Please correct the following controls on the [Sign Up Two Screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-two):

helpertext -- nothing displays
errormessage -- nothing displays
instruction (true/false) -- no change
error (true/false) -- no change
imghidden (true/false) -- no change

---

**Storybook screenshot of controls:**

![Registration_61_A_SignUpTwo_Controls_SB](https://user-images.githubusercontent.com/74170693/104550475-f5e0b600-5602-11eb-87db-40f3412eb756.png)

**Comment by NaomiLea** [comment]
@dani-ji controls not needed on this page
