### ISSUE TITLE
Login User Info (Storybook) -- Correct controls

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#652]
I cannot access controls on [Unit Info](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--user-info) screen.

Please correct and/or direct me toward controls I can test.

---

**Storybook screenshot of controls:**

![Registration_62_A_UserInfo_Controls_SB](https://user-images.githubusercontent.com/74170693/104550613-3b9d7e80-5603-11eb-9111-3bd621c710ab.png)

**Comment by dani-ji** [comment]
Controls not needed on this page
