### ISSUE TITLE
green bar should be controllable 

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#660]
green bar should be controllable (however you choose - percentage, radio, etc.): https://storybook.sandbox.jicloud.org/?path=/story/full-pages-login--sign-up-start

**Comment by dakom** [comment]
@dani-ji seems this might not be in Zeplin and needs a reference

**Comment by dakom** [comment]
With the Zeplin reference in mind, I'd suggest a refactor of the `text-input` element. It should be split into two separate elements:

1. `text-input` - pretty much as it is right now, with the password stuff stripped out (e.g. there's no `mode` at all)
2. `password-input` - should be like `text-input` is now, with the following changes:
    1. `mode` should be changed to `reveal` and should be a boolean with default of `false`
    2. `strength` property defined as `0 | 1 | 2 | 3 `
    3. the `strength` property should affect both the color bar _and_ the hint message
    4. therefore the hint message isn't controllable from the outside - everything is from `strength` (like `error` and `errorwrapper`)

**Comment by dakom** [comment]
my mistake - the elements should not be split because we need password _without_ the strength indicator elsewhere (e.g. login)

everything else applies though (having a password-strength element and controlling it on the registration page)

**Comment by NaomiLea** [comment]
This has been fixed
