### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#667]
I don't see where to pull it from... ~~will refactor things tomm probably so these urls might not be valid but:~~ (*edit:* going to wait to refactor until after this is fixed):

* here it says "undefined" and label control doesn't do anything: https://storybook.sandbox.jicloud.org/?path=/story/dropdown--selected-dropdown

* here there's no actual dropdown: https://storybook.sandbox.jicloud.org/?path=/story/input-text--dropdown

if dropdown is meant to be only a component, not an element - that's fine, but it does need an example in storybook with the actual dropdown part to toggle off and on

**Comment by dani-ji** [comment]
@NaomiLea Please look at this ASAP
