### ISSUE TITLE
QA Publish (Publish Full One) - Add heading/title "Settings and JIG Info." in top left corner

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#682]
[Zeplin sketches](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a4bbb02ce93c385bd68b) include heading/title in top left corner: "Settings and JIG Info." Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) does not feature this text.

Please add heading/title "Settings and JIG Info." in top left corner.

---

**Zeplin Sketch (with orange heading/title in top left corner):**

![Publish_05_A_PublishFullOne_HeadingTopLeft_Zeplin](https://user-images.githubusercontent.com/74170693/104874421-f0e07700-5920-11eb-88c8-e50c44c1919e.png)

---

**Storybook Screen (missing orange heading/title in top left corner):**

![Publish_05_B_PublishFullOne_HeadingTopLeft_SB](https://user-images.githubusercontent.com/74170693/104874422-f0e07700-5920-11eb-88e0-3a519d782b9f.png)

**Comment by NaomiLea** [comment]
This was there before too, but please check again to confirm

**Comment by esteels** [comment]
@NaomiLea Still missing in my preview:

![Publish_05_C_PublishFullOne_HeadingTopLeft_SB_Round2](https://user-images.githubusercontent.com/74170693/105453805-d246ec80-5c4e-11eb-9b0b-bd5b579c0b8a.png)

**Comment by chayaml** [comment]
Settings and JIG info added in Storybook 

![Publish fullone](https://user-images.githubusercontent.com/78186896/106483098-28e8cd80-647c-11eb-91e7-401a1f1a0ea6.png)
