### ISSUE TITLE
QA Publish (Publish Full One) - Change language from "Add Curriculum" to "Add Lesson Plan" 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#684]
[New Zeplin sketches](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a4bbb02ce93c385bd68b) feature the phrase, "Add Lesson Plan" underneath "Additional resources (Optional). Current [Storybook screens](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) feature "Add Curriculum" instead (as found in earlier versions of Zeplin sketches).

Please updated language to "Add Lesson Plan".

---

**Zeplin Sketch (with "Add Lesson Plan"):**

![Publish_06_A_PublishFullOne_HoverOverAdditionalResources_Zeplin](https://user-images.githubusercontent.com/74170693/104875029-508b5200-5922-11eb-9672-1ff536871b80.png)

---

**Storybook Screen (with "Add Curriculum"):**

![Publish_06_B_PublishFullOne_HoverOverAdditionalResources_SB](https://user-images.githubusercontent.com/74170693/104875031-5123e880-5922-11eb-89c8-afa79291b01d.png)

**Comment by NaomiLea** [comment]
This has been fixed according to Corinnes instructions.

**Comment by NaomiLea** [comment]
Waiting for https://github.com/ji-devs/ji-cloud/pull/735 to be merged. So please check that this is done before you check this again
