### ISSUE TITLE
QA Publish (Publish Full One) - Correct spelling of "Teaching"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#685]
[Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) contains minor spelling error with "Teachig Goals".

Please correct spelling to "Teaching Goals".

---

**Storybook Teaching Goals field:**

![Publish_09_A_PublishFullOne_SpellingTeaching_SB](https://user-images.githubusercontent.com/74170693/104875288-f17a0d00-5922-11eb-97a3-a60ff06a1859.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by dani-ji** [comment]
resolved
