### ISSUE TITLE
QA Publish (Publish Full One) - Confirm color of "Categories" button

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#687]
[Zeplin sketches](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a1570c56693dee495b9c) indicate light blue color for "Categories" buttons/labels + darker blue text. Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) displays a blue color that seems slightly darker than the Zeplin sketches + black text. 

Please confirm "Categories" color button color and correct if needed.

---

**Zeplin Sketch (with color specifications):**

![Publish_14_A_PublishFullOne_CategoriesColor_Zeplin](https://user-images.githubusercontent.com/74170693/104875845-5124e800-5924-11eb-8339-b967a488e3bc.png)

---

**Storybook Screen (with darker button + black text):**

![Publish_14_B_PublishFullOne_CategoriesColor_SB](https://user-images.githubusercontent.com/74170693/104875846-5124e800-5924-11eb-97eb-753f81d6d515.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by esteels** [comment]
@NaomiLea looks good based on this link: https://storybook.sandbox.jicloud.org/?path=/story/core-pills--pill-close 

Thanks!
