### ISSUE TITLE
QA Publish (Publish Full Two) - Show three idle buttons

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#690]
[Zeplin Sketches](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a1570c56693dee495b9c) indicate 3 buttons:

- share the JIG
- create a new JIG
- play the JIG

Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-two) only displays one button since the dropdown menu obscures the other two buttons.

Please make sure all three buttons are there/please show all three buttons.

---

**NEW DESIGN Zeplin Sketch:**

![Publish_20_A_PublishFullTwo_ThreeButtons_Zeplin](https://user-images.githubusercontent.com/74170693/104876888-921dfc00-5926-11eb-8471-055cfd13e12f.png)

---

**OLD DESIGN Zeplin Sketch:**

![Publish_20_B_PublishFullTwo_ThreeButtons_Zeplin](https://user-images.githubusercontent.com/74170693/104876890-92b69280-5926-11eb-9804-49beafd7a079.png)

---

**Storybook Screen:**

![Publish_20_C_PublishFullTwo_ThreeButtons_SB](https://user-images.githubusercontent.com/74170693/104876891-92b69280-5926-11eb-9de4-3f21be2194bc.png)

**Comment by NaomiLea** [comment]
Fixed just waiting for merge

**Comment by chayaml** [comment]
All three buttons show when switching "Embedclosed" control from "False" to "True"

**SB Screen:**
![Screen Shot 2021-02-10 at 2 49 52 PM](https://user-images.githubusercontent.com/78186896/107563726-6c93b380-6baf-11eb-9345-4369fcbe0866.png)
