### ISSUE TITLE
QA Publish (Publish Full Two) - Ensure distinction between idle/hover/selected for buttons

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#692]
[OLD Zeplin sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da2118090f84a30790b7) show distinction between idle/hover/[selected](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da211ca70f44c6fe7c28) states of three buttons. [NEW Zeplin sketch](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a1570c56693dee495b9c) does not include the specs in this case, and current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-two) does not reflect this distinction. 

Please ensure and display distinction between idle/hover/selected for buttons. 

@dani-ji please let me know if the correct specs for new design are listed in a Zeplin doc for future reference/for more precise revisions. 

---

**OLD Zeplin Sketch (hover + idle):**

![Publish_22_A_PublishFullTwo_ButtonStateHover_Zeplin](https://user-images.githubusercontent.com/74170693/104878925-d90df080-592a-11eb-853e-af58dac2b056.png)

**OLD Zeplin Sketch (selected):**

![Publish_22_B_PublishFullTwo_ButtonStateSelected_Zeplin](https://user-images.githubusercontent.com/74170693/104878927-d90df080-592a-11eb-97c1-94f08657fe35.png)

**NEW Zeplin Sketch (with undefined idle/hover/selected specs):**

![Publish_22_C_PublishFullTwo_ButtonStateUndefined_Zeplin](https://user-images.githubusercontent.com/74170693/104878928-d9a68700-592a-11eb-870b-0c1b13f6fd86.png)

**Storybook Screen:**

![Publish_22_D_PublishFullTwo_ButtonStateUnchanged_SB](https://user-images.githubusercontent.com/74170693/104878929-d9a68700-592a-11eb-9a23-c94cbfbf2c8d.png)

**Comment by NaomiLea** [comment]
Blocked zeplin isnt displaying the different states for these buttons @dani-ji

**Comment by dakom** [comment]
closed until there is an updated brief
