### ISSUE TITLE
QA Publish (Publish Full Two) - Correct hover for icons on dropdown list

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#693]
[Zeplin sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da21b8608c2f2ca0c081) indicate that icons + text reflect hover state. Current [Storybook Screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-two) only shows the text reflecting a hover state. 

Please correct the hover state to include icons on the dropdown list in hover response. 

---

**Zeplin Sketch (with icon included in hover state):**

![Publish_23_A_PublishFullTwo_DropDownStateHover_Zeplin](https://user-images.githubusercontent.com/74170693/104879426-d6f86180-592b-11eb-932d-115aab5fe2b5.png)

---

**Storybook Screen (with icon missing hover state):**

![Publish_23_B_PublishFullTwo_DropDownStateHover_SB](https://user-images.githubusercontent.com/74170693/104879428-d6f86180-592b-11eb-85c6-3ae23bd4b55a.png)

**Comment by dakom** [comment]
this isn't in the current UI brief: https://zpl.io/aX7XXoM
