### ISSUE TITLE
QA Publish (Publish Full Two) - Add notification banners after text copied

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#695]
[Zeplin Sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da22b8608c2f2ca0c156) indicate that there should be a notification banner after a string (or [code](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da2318090f84a3079135)) is copied to the clipboard. Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-two) does not seem to include this notification in the screen interactions or controls. 

Please add notification banner after text is copied to the clipboard.

---

**Zeplin Sketch:**

![Publish_25_A_PublishFullTwo_DropDownNotification_Zeplin](https://user-images.githubusercontent.com/74170693/104880346-62bebd80-592d-11eb-89e4-196c8df37ee1.png)

---

**Storybook Screen:**

![Publish_25_B_PublishFullTwo_DropDownNotification_SB](https://user-images.githubusercontent.com/74170693/104880347-63575400-592d-11eb-90c6-7eacab6ea9f0.png)

**Comment by NaomiLea** [comment]
Pkease add pictures again, cant see them

**Comment by NaomiLea** [comment]
This have been fixed . Just waiting for merging PR
