### ISSUE TITLE
QA Publish (Publish Full One) - Confirm default/initial number of elements under "Additional resources (Optional)"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#697]
[Zeplin sketches](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a1570c56693dee495b9c) indicate 4 elements beneath "Additional resources (Optional)", while current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) displays only 2. 

Please confirm the default/initial number of elements under "Additional resources (Optional)" and correct as needed (seems like 4).

---

**Zeplin Sketch (with 4 elements):**

![Publish_29_A_PublishFullOne_DefaultAdditionals_Zeplin](https://user-images.githubusercontent.com/74170693/104881391-39069600-592f-11eb-9518-4b977e78259c.png)

---

**Storybook Screen (with 2 elements):**

![Publish_29_B_PublishFullOne_DefaultAdditionals_SB](https://user-images.githubusercontent.com/74170693/104881393-39069600-592f-11eb-9415-fa4ee932e357.png)

**Comment by NaomiLea** [comment]
Fixes

**Comment by dani-ji** [comment]
@NaomiLea @esteels related to the above, please see comment in Zeplin 

```
@aagalish Where is the page showing the types of additional resources? They were not all Lesson Plans

Add lesson plan
Add curriculum
Add activity ideas
Add link
```

@corinnewo please clarify if they will be updated in Zeplinn and hence the issue should not be closed
