### ISSUE TITLE
Incorrect Border Radius on Google Button

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#724]
Zeplin has 14px radius and SB has 4px

![Screen Shot 2021-01-20 at 1 53 55 PM](https://user-images.githubusercontent.com/73904351/105221338-f90a0380-5b26-11eb-864d-edb277a57c4e.png)
![Screen Shot 2021-01-20 at 1 53 47 PM](https://user-images.githubusercontent.com/73904351/105221340-f9a29a00-5b26-11eb-80ad-b8fc530f9fc2.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by dani-ji** [comment]
@NaomiLea good in SB, waiting to close until reflects in live version
