### ISSUE TITLE
Missing Placeholder Text in Email/Password fields

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#725]
Zeplin has placeholder text
Type your username
Type your password

![Screen Shot 2021-01-20 at 1 55 04 PM](https://user-images.githubusercontent.com/73904351/105221587-4dad7e80-5b27-11eb-8216-2dc690ed15f9.png)
![Screen Shot 2021-01-20 at 1 55 17 PM](https://user-images.githubusercontent.com/73904351/105221589-4e461500-5b27-11eb-9c36-bfd359de98ab.png)

**Comment by NaomiLea** [comment]
fixed

**Comment by dani-ji** [comment]
@corinnewo as we are using Email instead of Username (technical reasons...) should the placeholder text be "Type your email" as opposed to the current "Type your username"
