### ISSUE TITLE
HR is different color

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#726]
HR in Zeplin is #d3dde9 in SB is #4a4a4a;
![Screen Shot 2021-01-20 at 1 59 06 PM](https://user-images.githubusercontent.com/73904351/105221861-b0067f00-5b27-11eb-8733-72f58fe95748.png)
![Uploading Screen Shot 2021-01-20 at 1.58.59 PM.png…]()

**Comment by NaomiLea** [comment]
Fixed

**Comment by dani-ji** [comment]
Resolved in SB, waiting to close until resolved in live version
