### ISSUE TITLE
Missing padding on top and below 'Forgot your Password'

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#727]
![Screen Shot 2021-01-20 at 2 00 03 PM](https://user-images.githubusercontent.com/73904351/105222154-14294300-5b28-11eb-8f0b-ab208d6adebb.png)
![Screen Shot 2021-01-20 at 2 00 09 PM](https://user-images.githubusercontent.com/73904351/105222156-14294300-5b28-11eb-8449-57bebf0a1877.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by dani-ji** [comment]
resolved in SB; waiting to close until reflects in live version
