### ISSUE TITLE
Inconsistent text  

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#729]
In Zeplin Don’t have an account yet? is blue in SB is black with a blue ‘Register’ after it
![Screen Shot 2021-01-20 at 2 04 20 PM](https://user-images.githubusercontent.com/73904351/105222519-974a9900-5b28-11eb-96ce-5e9297bfdddd.png)
![Screen Shot 2021-01-20 at 2 04 36 PM](https://user-images.githubusercontent.com/73904351/105222520-974a9900-5b28-11eb-85c2-4eeff41e8fcd.png)

**Comment by NaomiLea** [comment]
fixed

**Comment by dani-ji** [comment]
resolved in SB; waiting to close until reflects in live version
