### ISSUE TITLE
TBD - ditch Firebase for auth

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#736]
The firebase layer was a nice way to quickly get up and running when we had a bigger backlog on the backend, but it also introduces some funky problems, such as:

1. if the user exists in firebase but not our DB, it gets weird
2. relying on firebase for some transactional emails and flows where we might want to have more control (e.g. reset password for subaccounts down the line)
3. we want our own password strength validation, and firebase has its own - conflicts there are awkward
4. perhaps YAGNI, but third-party integrations that might not follow an oauth spec perfectly or have problems integrating through firebase (e.g. various school's LMS's)

**Comment by izik1** [comment]
I think this can be closed now?
