### ISSUE TITLE
Publish Full One - cursor:pointer over Additional Resources

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#737]
https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one

Please change to cursor:pointer for hover over Additional Resources

![Publish_30_A_PublishFullOne_CursorAdditionalResources_SB](https://user-images.githubusercontent.com/74170693/105622714-a4de7800-5de1-11eb-9d70-05551ccb19b0.png)

**Comment by NaomiLea** [comment]
Fixed - make sure no outstanding PR before checking

**Comment by esteels** [comment]
Looks great, thank you @NaomiLea
