### ISSUE TITLE
Publish Full One - cursor:pointer over dropdown chevron

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#738]
https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one

Please change to cursor:pointer for hover over dropdown chevron

![Publish_31_A_PublishFullOne_CursorDropDown_SB](https://user-images.githubusercontent.com/74170693/105622739-dd7e5180-5de1-11eb-972c-aee33ccb9bd5.png)

**Comment by NaomiLea** [comment]
Fixed - check no open PR before checking this

**Comment by esteels** [comment]
Still looks like default arrow cursor on my screen. Please change to cursor:pointer over dropdown menu.

**Comment by NaomiLea** [comment]
Fixed
