### ISSUE TITLE
Publish Full One - cursor:pointer over category tags

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#739]
https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one

Please change to cursor:pointer for hover over category tags

![Publish_32_A_PublishFullOne_CursorDeleteOnPill_SB](https://user-images.githubusercontent.com/74170693/105622767-0ef71d00-5de2-11eb-853c-72aed5e40d68.png)

**Comment by NaomiLea** [comment]
Fixed - make sure no PR are open before checking this.

**Comment by esteels** [comment]
@NaomiLea looks like cursor:text. Please change to cursor:pointer.

**Comment by dakom** [comment]
duplicate of https://github.com/ji-devs/ji-cloud/issues/1317
