### ISSUE TITLE
Publish Full One - Correct size of delete icon

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#740]
Current delete icon for category tags looks much smaller than in Zeplin. Please resize.  

Zeplin is 16 px x 16 px for pills that have height of 24 px.

![Publish_34_A_PublishFullOne_DeleteButton_Zeplin](https://user-images.githubusercontent.com/74170693/105622793-5b425d00-5de2-11eb-9064-1905e10c24b0.png)

![Publish_34_B_PublishFullOne_DeleteButton_Zeplin](https://user-images.githubusercontent.com/74170693/105622819-9e9ccb80-5de2-11eb-89cb-4c4d6ac6c023.png)

On SB, it appears to be 16 px x 16 px for a pill that's 32 px tall ? Still looks very small.

![Publish_34_F_PublishFullOne_DeleteButton_SB](https://user-images.githubusercontent.com/74170693/105622906-40241d00-5de3-11eb-92bc-c030f83bd095.png)
![Publish_34_G_PublishFullOne_DeleteButton_SB](https://user-images.githubusercontent.com/74170693/105622908-40bcb380-5de3-11eb-8dfb-2205e8c3263b.png)
![Publish_34_H_PublishFullOne_DeleteButton_SB](https://user-images.githubusercontent.com/74170693/105622935-7f526e00-5de3-11eb-81c4-d13e2323bdfc.png)

**Comment by NaomiLea** [comment]
Fixed - same as other bugs, make sure no PR are open before checking this.

**Comment by esteels** [comment]
Looks great, thank you! Resolved.
