### ISSUE TITLE
Publish Full One - Format text + controls for Error message

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#741]
Current SB placeholder text reads "hello"; please update text to Zeplin error message:
"Please fill the missing fields"

Please also add controls for unfinished fields to be marked red when publish is clicked prematurely 

![Publish_35_A_PublishFullOne_ErrorMessage_SB](https://user-images.githubusercontent.com/74170693/105623114-2d124c80-5de5-11eb-93d3-ab4c40bf1eae.png)
![Publish_35_B_PublishFullOne_ErrorMessage_Zeplin](https://user-images.githubusercontent.com/74170693/105623115-2daae300-5de5-11eb-8fc5-86907857d37b.png)

**Comment by NaomiLea** [comment]
the input fields will only show error messages after implementation. To test if error works it will be checked on the main component for the inputs that were already checked for login.

**Comment by NaomiLea** [comment]
This is finished but awaiting merge. Please check sure there are no waiting PR before this is checked
