### ISSUE TITLE
Offline strings tool

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#746]
Rough comments, from Zoom meeting:

Frontend utility, built in Rust, in `frontend/build-utils/string-generator`

It reads local JSON and generates a series of `strings.rs` and `strings.ts` files

The JSON example below would create `user/strings.ts`, `core/strings.ts`, `user/strings.rs`, `core/strings.rs`

Additionally, the rust folders may need a `mod.rs` with:

```
mod strings;
pub use strings::*;
```

```
// STEP 1 - DEFINE STRINGS IN CONFIG FILE 
{
    "USER": {
        "LOGIN": {
            "PLACEHOLDER": "Enter your email address"
        }
    },

    "CORE": {
        "BUTTONS": {
            "SUBMIT": "Submit"
        }
    }
}

//STEP 2 - UTILITY BUILDS strings.ts and strings.rs (in their respective folders)

//Example strings.ts:
export const USER_LOGIN_PLACEHOLDER = "Enter your email address";
export const CORE_BUTTONS_SUBMIT = "Submit";

//Example strings.rs:
pub const USER_LOGIN_PLACEHOLDER:&'static str = "Enter your email address";
pub const CORE_BUTTONS_SUBMIT:&'static str = "Submit";

//STEP 3 (not really a _step_)

//Typescript usage:

import {USER_LOGIN_PLACEHOLDER, CORE_BUTTONS_SUBMIT} from "strings";
console.log(USER_LOGIN_PLACEHOLDER); // "Enter your email address"
console.log(CORE_BUTTONS_SUBMIT); // "Submit"

//Rust usage:

use strings::{USER_LOGIN_PLACEHOLDER, CORE_BUTTONS_SUBMIT};

log::info!("{}", USER_LOGIN_PLACEHOLDER); // "Enter your email address"
log::info!("{}", CORE_BUTTONS_SUBMIT); // "Submit"
```

**Comment by MendyBerger** [comment]
Ok, so here is a rundown of what I was able to achieve today.

As directed by @dakom I created the template-builder in build-utils as a starting point.
I added transform functionality from json to typescript and rust.
I did not hook it into the broader pipeline yet, all it does for now is take a json file located within the directory and outputs to files in the same directory.

I pushed the changes to a clone on my account `/MendyBerger/ji-cloud/tree/strings-builder`.
To run open strings-builder and run `cargo run -- --remote-target=local` .

**Comment by dakom** [comment]
You're working on it in your `strings-builder` branch right? i.e. https://github.com/MendyBerger/ji-cloud/tree/strings-builder/frontend/build-utils/strings-builder

Off to a good start :) I'm going to close this issue and instead open a milestone so we can create more granular issues (cc @dani-ji )

**Comment by MendyBerger** [comment]
@dakom correct, `strings-builder` branch, forgot to mention it in my comment yesterday
