### ISSUE TITLE
Email Change Page - Add padding between text and Email box

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#748]
Zeplin sketch includes padding/space between text, "This is the email that you filled in. You can change it now." and "Email" box. Current SB screen is missing this padding. 
https://storybook.sandbox.jicloud.org/?path=/story/entry-user-email-pages--email-change

Please add padding between text and Email box.

![Registration_67_A_EmailChange_MissingPadding_SB](https://user-images.githubusercontent.com/74170693/105944476-617a4880-6031-11eb-8018-691076d2996f.png)

![Registration_67_B_EmailChange_MissingPadding_Zeplin](https://user-images.githubusercontent.com/74170693/105944480-617a4880-6031-11eb-9aea-bf6bec9dfbc1.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by chayaml** [comment]
Thanks!
**SB Screen**

![Screen Shot 2021-02-10 at 2 18 58 PM](https://user-images.githubusercontent.com/78186896/107560200-115fc200-6bab-11eb-9a88-abc0783e6ce8.png)
