### ISSUE TITLE
Email Send Page - Correct sequence and padding of text, button, and linked text

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#749]
Zeplin sketch displays the following three things with sufficient padding between them.

**(1) Text:** (slightly different wording from Zeplin; words approved by @corinnewo)
Open the email and click on the Verification button
It may have been filtered into the promotion or spam folders

**(2) Button:**
We have just sent you another email

**(3) Linked text:**
Change email account

Current SB shows incorrect order (text, linked text, and button) and is missing padding. 

Please correct sequence and padding of text, button, and linked text

---

**Zeplin**
![Registration_70_B_EmailChange_Padding_Zeplin](https://user-images.githubusercontent.com/74170693/105944679-d057a180-6031-11eb-9930-54170ee9e90a.png)

**SB**
![Registration_70_A_EmailChange_Padding_SB](https://user-images.githubusercontent.com/74170693/105944677-cfbf0b00-6031-11eb-9209-768fdcec1eea.png)

**Comment by dakom** [comment]
closing since UI brief is outdated and only in old zeplin
