### ISSUE TITLE
Reset Page - Add padding between button and text 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#750]
Zeplin sketch includes padding/space between button ("Set Password") and text ("You’ll be logged in automatically after this"). Current SB screen is missing this padding.
https://storybook.sandbox.jicloud.org/?path=/story/entry-user-password-pages--reset 

Please add padding between button and text.

---

**Zeplin**
![Registration_74_B_Reset_Padding_Zeplin](https://user-images.githubusercontent.com/74170693/105945536-72c45480-6033-11eb-8f6e-c0351fa59d61.png)

**SB:**
![Registration_74_A_Reset_Padding_SB](https://user-images.githubusercontent.com/74170693/105945554-7eb01680-6033-11eb-9bed-48865e769fd0.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by chayaml** [comment]
Thanks! @NaomiLea 

**SB Screen:**
![Screen Shot 2021-02-11 at 9 37 01 AM](https://user-images.githubusercontent.com/78186896/107650706-c1d1d280-6c4c-11eb-9a8b-c8ab076af68d.png)
