### ISSUE TITLE
Reset Page - Change to lowercase for "password" and add padding before passwordStrength bar

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#751]
Zeplin sketch includes lowercase for "password" in "Enter new Password" field; Zeplin sketches also indicate padding between field and passwordStrength bar. **Note:** passwordStrength bar appears on top of the filed in older version.
Current SB screen displays incorrect capital letter for "Password" and is missing padding between field and passwordStrength
https://storybook.sandbox.jicloud.org/?path=/story/entry-user-email-pages--email-change

Change to lowercase for "password" and add padding before passwordStrength bar

---

**SB with incorrect capital letter and missing padding before passwordStrength bar:**
![Registration_74_D_Reset_Padding_SB](https://user-images.githubusercontent.com/74170693/105946186-c4211380-6034-11eb-9bb5-1d0c3a028f3a.png)

**Zeplin with padding between passwordStrength bar and field:**
![Registration_74_C_Reset_Padding_Zeplin](https://user-images.githubusercontent.com/74170693/105946055-760c1000-6034-11eb-9f2e-1078347d350b.png)

**Comment by NaomiLea** [comment]
Fixed (also moved it above the input field according to the design

**Comment by chayaml** [comment]
My screen still displays incorrect capital letter for "Password." Please change to lowercase for "password."
Padding and placing looks good!

**SB Screen:**
![Screen Shot 2021-02-11 at 8 33 58 AM](https://user-images.githubusercontent.com/78186896/107643814-a19e1580-6c44-11eb-930d-c7ced8b9c58c.png)
