### ISSUE TITLE
Landing (Register Complete)Page - Add padding between text and button

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#752]
Zeplin sketch includes padding/space between text, "You can now create, play, and share your content. We are here to help you in whatever you need." and "Go to JI home" button. Current SB screen is missing this padding.
https://storybook.sandbox.jicloud.org/?path=/story/entry-user-register-complete-pages--landing

Please add padding between text and button.

---

**Zeplin:**
![Registration_76_B_Landing2_Padding_Zeplin](https://user-images.githubusercontent.com/74170693/105947137-963cce80-6036-11eb-8431-21deaac537c6.png)

**SB:**
![Registration_76_A_Landing2_Padding_SB](https://user-images.githubusercontent.com/74170693/105947136-963cce80-6036-11eb-9514-b0de8e52f99d.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by chayaml** [comment]
**SB Screen:**
![Screen Shot 2021-02-11 at 9 24 29 AM](https://user-images.githubusercontent.com/78186896/107649004-fe9cca00-6c4a-11eb-81c8-747ff62b811f.png)
