### ISSUE TITLE
Separate json for each entry

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#753]
The initial spec was something like this:

**strings.json**
```
{
    "USER": {
        "LOGIN": {
            "PLACEHOLDER": "Enter your email address"
        }
    },

    "CORE": {
        "BUTTONS": {
            "SUBMIT": "Submit"
        }
    }
}
```

Instead, I think it should be like this:

**user.json**
```
{
    "LOGIN": {
        "PLACEHOLDER": "Enter your email address"
    }
}
```

**core.json**
```
{
    "BUTTONS": {
        "SUBMIT": "Submit"
    }
}
```

The reason is that building an entry wouldn't require loading the entire JSON

**Comment by MendyBerger** [comment]
Update in https://github.com/MendyBerger/ji-cloud/commit/49c2c1b81a69907e3da8aab4d54e0287684cb718
