### ISSUE TITLE
lowercase keys -> uppercase const

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#754]
The initial spec defined lookups like this:

```
{
    "LOGIN": {
        "PLACEHOLDER": "Enter your email address"
    }
}
```

The concept was more to illustrate the point that they keys get concatenated, but we shouldn't need to worry about the casing. 

Suggestion:

1. the keys in the JSON should be lowercase by convention
2. it shouldn't really matter, the tool should convert them to uppercase before concatenation

**Comment by MendyBerger** [comment]
Updated in https://github.com/MendyBerger/ji-cloud/commit/f59d6ad56adc4f5a3e08f324b8c005cef97d463c
