### ISSUE TITLE
Labeling Images (Confirmation) - Confirm display of "+" icon for Upload image button

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#776]
Zeplin sketches show a"+" icon for the Upload image button, but the icon is not displaying on my SB screen. (A similar issue was reported for #628).

Please confirm the "+" icon is displaying correctly for Upload image button, and/or tell me how I can fix this on my end.

---

**Zeplin Sketch (with "+" icon):**

![Labeling2_003_A_Confirmation_UploadButton_Zeplin](https://user-images.githubusercontent.com/74170693/106395935-ee772600-63d2-11eb-8281-fecffd0b7984.png)

SB Screen ("+" does not display properly for me): 

![Labeling2_003_B_Confirmation_UploadButton_SB](https://user-images.githubusercontent.com/74170693/106395936-ef0fbc80-63d2-11eb-81aa-c54115b8c37a.png)

**Comment by NaomiLea** [comment]
This has been fixed

**Comment by esteels** [comment]
Looks good, thank you @NaomiLea
