### ISSUE TITLE
Labeling Images (Image Label Full 1) - Correct placement + formatting of Replace | Delete buttons

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#777]
Zeplin sketches show "Replace | Delete" buttons right aligned with bottom of image. Current SB screen shows "Replace Delete" buttons to the right of the image at the bottom. 

Please do the following:
(1) Set the buttons to right align beneath the image
(2) Add "|" between the buttons so they read "Replace | Delete"

---

**Zeplin Sketch (with correct button placement and format):**

![Labeling2_004_005_A_ImageLabelFull1_ReplaceDelete_Zeplin](https://user-images.githubusercontent.com/74170693/106396053-a573a180-63d3-11eb-919e-065aef0c9455.png)

**SB Screen (with incorrect button placement and format):**

![Labeling2_004_005_B_ImageLabelFull1_ReplaceDelete_SB](https://user-images.githubusercontent.com/74170693/106396054-a60c3800-63d3-11eb-89cc-cccb7ebd6546.png)

**Comment by NaomiLea** [comment]
This isnt a bug. The image is simply not as wide as the space for the image. The text cant be controlled based on the width of the image itself.

**Comment by chayaml** [comment]
Closed

"|" Line added between "Replace | Delete"

**SB Screen:**
![Screen Shot 2021-02-08 at 9 45 26 AM](https://user-images.githubusercontent.com/78186896/107235200-6e644800-69f2-11eb-8ac4-97aff80c57f2.png)
