### ISSUE TITLE
Labeling Images (Image Label Full 1) - Add horizontal line before "Premium image" checkbox

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#778]
Zeplin Sketches include a horizontal grey line beneath the "Replace | Delete" buttons above the "Premium image" checkbox. Current SB screen is missing this line.

Please add horizontal grey line beneath the "Replace | Delete" buttons above the "Premium image" checkbox.

---

**Zeplin Sketch (with horizontal grey line):**

![Labeling2_006_007_008_A_ImageLabelFull1_Features_Zeplin](https://user-images.githubusercontent.com/74170693/106396131-0ef3b000-63d4-11eb-9b41-89d7c5ab0d2e.png)

**SB Screen (missing horizontal grey line):**

![Labeling2_006_007_008_B_ImageLabelFull1_Features_SB](https://user-images.githubusercontent.com/74170693/106396166-495d4d00-63d4-11eb-9808-1b5d8236a9cd.png)

**Comment by NaomiLea** [comment]
This has been fixed

**Comment by chayaml** [comment]
Closed

Horizontal grey line and vertical padding added to elements.

**SB Screen:**
![Screen Shot 2021-02-08 at 9 37 06 AM](https://user-images.githubusercontent.com/78186896/107234082-49230a00-69f1-11eb-962a-3a492a215701.png)
