### ISSUE TITLE
Labeling Images (Image Label Full 1) - Add/Confirm appropriate padding between elements 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#779]
Zeplin Sketches indicate padding between various elements; current SB screen has inconsistent padding. 

- "Replace | Delete" buttons  **// confirm padding above and below**
- Horizontal grey line **// per #778**
- "Premium image" checkbox **// ensure padding below, currently looks crowded**
- "Image name" (subheading) 
- Text input field **// ensure padding below, see second Zeplin screenshot**
- Horizontal grey line
- "Image description" (subheading)
- Text input field **// ensure padding below, see second Zeplin screenshot**
- Horizontal grey line **// there's a grey line way way at the bottom - is that meant to be under the text input field?** 

Please add/confirm padding between  elements as listed above. 

---

**Zeplin Sketch (general overview):**

![Labeling2_006_007_008_A_ImageLabelFull1_Features_Zeplin](https://user-images.githubusercontent.com/74170693/106397136-e078d380-63d9-11eb-8ff4-8dfeba713987.png)

**Zeplin Sketch (showing padding between text input field and grey line):**

![Labeling2_006_007_008_C_ImageLabelFull1_Features_Zeplin](https://user-images.githubusercontent.com/74170693/106397138-e078d380-63d9-11eb-889f-6a20455a7a84.png)

**SB Screen (missing appropriate padding):**

![Labeling2_006_007_008_E_ImageLabelFull1_Features_SB](https://user-images.githubusercontent.com/74170693/106397477-a7d9f980-63db-11eb-8413-4cb87014aaef.png)

**Comment by dakom** [comment]
discussed with @corinnewo , leaving as-is for now
