### ISSUE TITLE
Labeling Images (Image Label Full 1) - Add search icon

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#780]
Zeplin sketch includes search icon for "To be used for". Current SB screen is missing icon.

Please add icon.

---

**Zeplin Sketch (with search icon):**

![Labeling2_013_A_ImageLabelFull1_SearchIcon_Zeplin](https://user-images.githubusercontent.com/74170693/106398940-d065f180-63e3-11eb-85ac-e55feb1f8967.png)

**SB Screen (missing search icon):**

![Labeling2_013_B_ImageLabelFull1_SearchIcon_SB](https://user-images.githubusercontent.com/74170693/106398942-d1971e80-63e3-11eb-9ff1-a5ded3268237.png)

**Comment by NaomiLea** [comment]
@dani-ji according to @dakom message on slack this was decided to be removed. Can this be confirmed please?

**Comment by esteels** [comment]
Relatedly, if this filter is removed, seems like it would not be needed in General Summary?

See Image Label Full 3.

**SB:**

![Labeling2_021_B_ImageLabelFull3_ImageDesc_SB](https://user-images.githubusercontent.com/74170693/107265919-d460c780-6a12-11eb-8b1e-d4d898e0cfa6.png)

**Zeplin:**

![Labeling2_021_A_ImageLabelFull3_ImageDesc_Zeplin](https://user-images.githubusercontent.com/74170693/107265842-bdba7080-6a12-11eb-8978-a87e6ffb2e3a.png)
