### ISSUE TITLE
Labeling Images (Image Label Full 1) - Correct text formatting for "Image name"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#781]
Zeplin sketches indicate same paragraph styles for "Image name" and "Image description" text input fields. SB text seems to be behaving differently (/incorrectly?) under "Image name".

Please correct text formatting for text input field under "Image name":
- wrap text
- make sure letters are not compressed (looks like there's some kerning going on?)
- confirm text is same size as for "Image description" 

--- 

**Zeplin Sketch (for "Image name"):**

![Labeling2_020_A_ImageLabelFull1_TextInput_Zeplin](https://user-images.githubusercontent.com/74170693/106399550-4ae44080-63e7-11eb-9b30-ae015e0afc7f.png)

**Zeplin Sketch (for "Image description"):**

![Labeling2_020_B_ImageLabelFull1_TextInput_Zeplin](https://user-images.githubusercontent.com/74170693/106399551-4ae44080-63e7-11eb-838e-5f97cb386216.png)

**SB Screen (with incorrect formatting for "Image name" text input field):**

![Labeling2_006_007_008_E_ImageLabelFull1_Features_SB](https://user-images.githubusercontent.com/74170693/106399555-4fa8f480-63e7-11eb-8206-6ef75444f64b.png)

**SB Screen (with cursor as text, small?):**

![Labeling2_009_A_ImageLabelFull1_TextSize_SB](https://user-images.githubusercontent.com/74170693/106399620-cf36c380-63e7-11eb-8d6f-2e3ab01d9f55.png)

**SB Screen (with cursor as text, normal?):**

![Labeling2_009_B_ImageLabelFull1_TextSize_SB](https://user-images.githubusercontent.com/74170693/106399621-cfcf5a00-63e7-11eb-9b00-2fe5b20207a9.png)

**Comment by dakom** [comment]
discussed with @corinnewo , not doing for now (image admin as a whole needs UI revamp)
