### ISSUE TITLE
Labeling Images (Image Label Full 1) - Ensure responsive lists

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#782]
Text in SB lists compresses and overlaps when the window is too narrow. 

Please ensure responsive lists that leave more space between text with narrow screens.

![Labeling2_010_A_ImageLabelFull1_ResponsiveText_SB](https://user-images.githubusercontent.com/74170693/106399735-7582c900-63e8-11eb-81e4-254d310e91f0.png)

**Comment by NaomiLea** [comment]
Fixed

**Comment by chayaml** [comment]
Thanks!

**SB Screen:**
![Screen Shot 2021-02-11 at 8 50 05 AM](https://user-images.githubusercontent.com/78186896/107645157-5be24c80-6c46-11eb-8066-e93e38d322da.png)
