### ISSUE TITLE
Labeling Images (Image Label Full 1) - Correctly format "To be used only for"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#783]
Original Zeplin sketches outline very different interaction than is currently displaying on SB. Additionally, SB text seems to have same formatting issues noted in #781.

This issue may have been addressed in previous rounds of QA, but unfortunately I can't recall the take away. 

If applicable, please do the following:

(1) correctly format interaction for "To be used only for" (select from dropdown menu, display, etc)
(2) make sure text previews correctly:

- wrap text
- make sure letters are not compressed (looks like there's some kerning going on?)
- confirm text is same size as for "Image description"

---

**SB Screen (with incorrectly formatted text):**

![Labeling2_012_A_ImageLabelFull1_ToBeUsed_SB](https://user-images.githubusercontent.com/74170693/106399978-c6df8800-63e9-11eb-9044-db3ca02690bf.png)

**Zeplin Sketch 1**

![Labeling2_012_B_ImageLabelFull1_ToBeUsed_Zeplin1](https://user-images.githubusercontent.com/74170693/106399980-c6df8800-63e9-11eb-9a10-15d71337fff5.png)

**Zeplin Sketch 2:**

![Labeling2_012_C_ImageLabelFull1_ToBeUsed_Zepline2](https://user-images.githubusercontent.com/74170693/106399981-c6df8800-63e9-11eb-80b1-ad1b92f72990.png)

**Zeplin Sketch 3:**

![Labeling2_012_D_ImageLabelFull1_ToBeUsed_Zeplin3](https://user-images.githubusercontent.com/74170693/106399982-c7781e80-63e9-11eb-9c5e-6d2db5d09cd5.png)

**Comment by NaomiLea** [comment]
@dani-ji I was told this has been removed. Please confirm?

**Comment by dakom** [comment]
This has been removed for now
