### ISSUE TITLE
Labeling Images (Image Label Full 3) - Remove Image name + Image description under image for Full 3

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#797]
Zeplin sketches do not include Image name + Image description beneath the image for Full 3 (last step before publish). current SB screen does include these fields beneath the image. 

Please remove Image name + Image description beneath image on page Image Label Full 3.

---

**Zeplin (w/o Image name + Image description under image):**

![Labeling2_021_A_ImageLabelFull3_ImageDesc_Zeplin](https://user-images.githubusercontent.com/74170693/107266443-87312580-6a13-11eb-99fa-6ac9c4aea4c3.png)

**SB (incorrectly w/ Image name + Image description under image):**

![Labeling2_021_B_ImageLabelFull3_ImageDesc_SB](https://user-images.githubusercontent.com/74170693/107266455-8c8e7000-6a13-11eb-8917-78b2b4fe46b8.png)

**Comment by dakom** [comment]
It is meant to be there so that they can change it at any time
