### ISSUE TITLE
Labeling Images (Image Label Full 2) -- General corrections to Categories/tree interactions

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#798]
Per email with @NaomiLea, just submitting one request for now; to be revisited after implementation.

Tracking details for correction, beginning with this list below:

- Only one section should be open/green at a time. Other sections should reflect inactive state.
- Confirm expand/collapse buttons work as expected
- Make sure check boxes line up with elements correctly
- Ensure controls are testable

**Correct Zeplin screen:**

![Labeling2_018_A_ImageLabelFull2_CategoriesGreen_Zeplin](https://user-images.githubusercontent.com/74170693/107268439-20613b80-6a16-11eb-9dcd-878dfa225d84.png)

**Screenshots from SB Screens, Image Label Full 2:**

![Labeling2_018_C_ImageLabelFull2_CategoriesGreen_SB](https://user-images.githubusercontent.com/74170693/107268535-44248180-6a16-11eb-85f4-5c19b9f54019.png)

![Labeling2_018_C_ImageLabelFull2_CategoriesGreenControls_SB](https://user-images.githubusercontent.com/74170693/107268536-44248180-6a16-11eb-849a-19dea9d2fb70.png)

**Screenshots from SB Screens, Dropdown Tree 2:**

![Labeling2_018_D_ImageLabelFull2_CategoriesGreenControls_SB](https://user-images.githubusercontent.com/74170693/107268537-44248180-6a16-11eb-9102-d3c906eb51ce.png)

**Comment by dakom** [comment]
This seems outdated
