### ISSUE TITLE
Registration (Step 2) -- Please add field for School/Organization

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#807]
Original Zeplin sketch includes field for School/Organization. Current SB screen is missing this field. Please add field for School/Organization.

---

**Original Zeplin Sketch with School/Organization:**

![Registration_77_A_Step2_SchoolOrganization_Zeplin](https://user-images.githubusercontent.com/74170693/107608053-d55b4a00-6c08-11eb-8a95-732da1cae44d.png)

**Current SB Screen (missing School/Organization):**

![Registration_77_B_Step2_SchoolOrganization_SB](https://user-images.githubusercontent.com/74170693/107608056-d5f3e080-6c08-11eb-93aa-721610f15f84.png)

**Comment by dakom** [comment]
The Zeplin is outdated here

**Comment by dani-ji** [comment]
Reopened as #814 with more detail
