### ISSUE TITLE
remove duplicate data in GetAuthUrl request

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#823]
According to the [current docs](https://docs.sandbox.jicloud.org/crate/shared/api/endpoints/session/struct.GetOAuthUrl.html#impl-ApiEndpoint) it requires replacing the string in the url, as well as providing a tuple of `(GetOAuthUrlServiceKind::Google, GetOAuthUrlKind::Register)` in the request.

Should only need it once (either place is fine)

**Comment by izik1** [comment]
That's a problem with the docs for the shared crate, the endpoint only checks the path
