### ISSUE TITLE
jig editor: module menu for "use content as"

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#830]
"available on any module that has an "associated kind". Does not require being a duplicate first (at this level at least, we don't even track the history of duplicates at all and have no knowledge of it. we may change that in the future for analytics but that will be even deeper history and has no relevance here). imho the ui should reflect this and simply say "change module kind" or something like that" -David

@corinnewo please confirm if you would like to stick to the current format in Zeplin or update to David's suggestion

**Comment by corinnewo** [comment]
David and I discussed this and came to an acceptable conclusion, which Gali is going to implement. She agreed with it.
I will update the flowcharts too.

Decision:
- Regular right-click menu will have DUPLICATE item, which will clone the current module
- Advanced menu, if the module is one of the set (memory, flashcards, matching, 1of3), then there will be an item DUPLICATE CONTENT AS... 
- If you click this item, a secondary part will open up, listing the 3 possibilities.
- Duplicating the content as... will mean creating a module of the type chosen, eg flashcards, and populating it with the content from the original module, eg memory game. The theme should remain the same, but any instructions or play settings will need to be redefined, as they need to relate to the functionality if the new game.

**Comment by corinnewo** [comment]
Implemented
