### ISSUE TITLE
Remove cover / end page from Jig struct

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#835]
Rather, we'll just treat the first and last modules as special on the frontend (e.g. disallow deleting via the UI, decorate differently, etc.)

**Comment by dani-ji** [comment]
@corinnewo  did you sign off on this change

**Comment by dakom** [comment]
This isn't a change to the spec, it's only a change to implementation.

**Comment by dakom** [comment]
In other words, the spec says that there is always a cover page.

Currently, that's implemented as a separate part of the Jig struct.

It's cleaner for various reasons to instead implement that as a logical constraint with the following rules under the hood:

1. Newly created JIG's must first create a new module of `ModuleKind::Cover`
2. The new jig then has its `modules` list with only that ID
3. The UI disallows re-ordering or deleting the first module in a jig. We can also prevent this at the API-level to be extra safe.

Not creating all those issues as part of this one though, since the _structure_ of the JIG is separate from the process of creating a new one.

**Comment by dakom** [comment]
That said, @dani-ji you are correct that the spec _has_ changed in regard to end page. It used to be a design screen like cover page and that's no longer the case (whether it's a Publish module?? or something else has yet to be decided, but and ending design screen has been removed according to latest approved Zeplin.)

**Comment by izik1** [comment]
Closed in #839
