### ISSUE TITLE
Data structures for locale

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#836]
```rust
pub type Section = String;

pub struct Bundle {
    id: Uuid,
    name: String,
}

pub struct ItemKind {
    id: Uuid,
    name: String,
}

pub enum EntryStatus {
    Approved,
    Discuss,
    OnHold,
}

pub struct Entry {
    pub id: u32, // not sure yet if auto incremented 
    pub bundle_id: Uuid,
    pub section: Option<Section>,
    pub item_kind_id: Option<Uuid>,
    pub english: String,
    pub hebrew: String,
    pub status: EntryStatus,
    pub zeplin_reference: Option<url::Url>,
    pub comments: String,
    pub in_app: bool,
    pub in_element: bool,
    pub in_mock: bool,
}
```

For `Entry` I need regular CRUD, and a GET that allows filtering by `bundle` (allow multiple).

For `Bundle` and `ItemKind` I just need GET (get all) for now

Let me know if you need anything else.

**Comment by izik1** [comment]
what does getting with filtering by bundle mean? Bundle ID? Either bundle ID or name? If name, does name have to be an exact match?
Is it the frontend that specifies Entry IDs?

```rust
pub in_app: bool,
pub in_element: bool,
pub in_mock: bool,

```
Would it be correct to assume that any combination of these are possible?
What happens if a particular `Entry` doesn't have an English or Hebrew version at some point in time?

> For `Bundle` and `ItemKind` I just need GET (get all) for now
Will creation and upkeep of these be handled by @dakom or yourself for now?

**Comment by MendyBerger** [comment]
I suppose @dakom would be better in answering these questions

**Comment by dakom** [comment]
> what does getting with filtering by bundle mean?

Bundle ID only, but ability to get several at a time, like `Vec<BundleId>`

> Is it the frontend that specifies Entry IDs?

@corinnewo (CC @dani-ji to keep in the loop). Can you please give final confirmation on what the IDs should be for each row on the table? Here are the options on the table (yes, terrible pun intended):

1. auto-incrementing integer. Advantage: simplest to implement and not too bad to reason about. Easier to communicate too, esp in the context of translations where English ids might not be as easy for everyone. Disadvantage: requires looking up the ID in the tool to know what it's for.

2. string id. advantage: human-readable. Disadvantage: requires coming up with unique English names for every string (or at least, unique within a bundle). Also, if we _really_ care about performance, would need some additional engineering on the frontend side to deal with hashing the strings into numerical ids, interning, and other headaches. we probably don't need that performance though.

Note that we could decide to scope these per-bundle or globally... but it's probably wiser to just keep the ids globally unique.

> Would it be correct to assume that any combination of these are possible?

Yes

> What happens if a particular Entry doesn't have an English or Hebrew version at some point in time?

This isn't an error on the database side. When it comes to creating the FTL bundles, it'll probably be ok as long as there's English, but we haven't gotten to that yet.

**Comment by dakom** [comment]
@izik1 for convenience, the work-in-progress live UI is here: https://sandbox.jicloud.org/admin/locale

**Comment by izik1** [comment]
> This isn't an error on the database side. When it comes to creating the FTL bundles, it'll probably be ok as long as there's English, but we haven't gotten to that yet.

Does this mean it should be `Option<String>` instead?

**Comment by dakom** [comment]
yes, `english`, `hebrew`, and `comments` should all be `Option<String>`

**Comment by dani-ji** [comment]
@izik1 the conclusion from @corinnewo is for it be auto incrementing integers 

One important note, if a string is deleted the numbers should continue to increment from the last number not use that deleted ID again
