### ISSUE TITLE
Return to previous screen after Publish

### ISSUE THREAD

**Issue by dani-ji** [ji-devs/ji-cloud#870]
In the previous version, after a user would Publish an image the user would be returned to the search result page with the view they had previously been filtered to

@chayaml is requesting this feature to be reimplemented

**Comment by dakom** [comment]
Discussed with @corinnewo  - since the back button _does_ work in this case, and the user can also just open the image to edit in a new tab, there isn't a need to have a round-trip button in the UI (nor to persist the last search state across routes)
