### ISSUE TITLE
Recent images list

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#910]
Depends on #909 

Image search widget needs to:

1. Load the recent images when first mounted
2. Provide a hook for imperatively updating that list, without having to re-load (or, alternatively, force a re-load)

**Comment by MendyBerger** [comment]
https://zpl.io/2pw9Or8

**Comment by MendyBerger** [comment]
@dakom is point 2 still relevant? I don't quite understand it

**Comment by dakom** [comment]
Nope, I think it was just an internal implementation note and based on an older codebase. Closing the issue :)
