### ISSUE TITLE
Dual list - limit character input

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#916]
overflow with ellipses?

**Comment by dakom** [comment]
@corinnewo - I'm not sure which way to do this:

1. actually limit the number of characters, so they won't show up on the cards. In this case we can't/shouldn't show ellipses because there isn't any more text
2. don't limit the number of characters, everything beyond the ellipses will show on the cards

**Comment by corinnewo** [comment]
@dakom I think that we should not allow them to add in more characters at all once they reach the limit, as all the text must appear on the cards.  The limit will depend on the size of the font, and maximum number of letters that fit comfortably on the card.

**Comment by dakom** [comment]
@corinnewo - by "characters" we mean what a human would consider a character as opposed to the computer, right?

For example, in Hebrew with nikkud, the letter and the nikkud are technically separate characters from the computer's perspective, but they take up the same space as a single letter.

It's a complicated problem to count the number of "characters from a human's perspective", though there are third-party libraries. I'll use https://crates.io/crates/unicode-segmentation and hope it's good enough...

**Comment by dakom** [comment]
So for example, considering `בְּרֵאשִׁ֖ית בָּרָ֣א`

* native character length: 39
* unicode character length: 20
* grapheme cluster length: 10

So going with the grapheme cluster length, calculated via that crate mentioned above

**Comment by corinnewo** [comment]
The example you give would be 10 character spaces, according to what I consider a character. The nikud is over the actual letter, so should not be considered as it does not add extra width to the text. So we would go with 'grapheme cluster length'.

**Comment by dakom** [comment]
ok great. Also - doesn't this apply to all text inputs here? i.e. same for the single-list (duplicate and lettering) as well as the card itself?

**Comment by dakom** [comment]
Editing on the card itself though is a bit different, since there is more vertical than horizontal space, so the limits are not really about the number of characters...

maybe we should let them do what they want on the cards, since they can see the changes and make their own decision by looking at it?

**Comment by corinnewo** [comment]
There should still be a limit of characters on the cards, though. If the characters exceed the space on the card, they should not be allowed to add more.

**Comment by dakom** [comment]
So we'll have two systems:

1. Sidebar text inputs - just limits by number of characters ("graphemes"). The exact number will be determined by some table, but we're saying 30 characters for now.

2. The cards... only solution I can think of is solving it iteratively by running calculations on every text input:

1. Graphically measure the resulting text box
2. If it overflows, remove a character (which requires getting it via the byte offset at the previous grapheme index)
3. Go to 1 until it stops overflowing

**Comment by dakom** [comment]
for the cards, it's a lot simpler to avoid the whole grapheme stuff, and anyway it's graphics based so really as long as it removes characters until it fits it _should_ equate to the same thing - and in fact there could be a better UX if it constrains a nikkud only that pushes it over the limit
