### ISSUE TITLE
Provide font-family, font-size, font-weight, and color lookup table for cards

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#917]
It's a function of the following parameters:
  * theme
  * mode
  * number of characters
  * if card is left vs. right

The font-family will also require a web font file to load.

**Comment by dani-ji** [comment]
@corinnewo I believe we need Gali for this, correct?

**Comment by corinnewo** [comment]
I have sent Gali a file to fill out - https://docs.google.com/document/d/1GaBgd6NfCaWJOmMfAnSrL21X0XSFXl8H0BgX6GbYXs0/edit?usp=sharing
