### ISSUE TITLE
Clarify parameterization of 2-column input

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#925]
It seems both columns operate the same way, and so this is really a question of parameterization of any given column within the 2-column input.

At a glance the options are:

1. Header text
2. Input height (as textarea rows?)
3. Input font info (size and color)
4. Placeholder font info (size and color)

These will be used, at least, for:

1. riddles
2. begins-with
3. opposites
4. synonymns
5. translate

**Comment by corinnewo** [comment]
@dakom I am not sure what you mean about the Input font info (size and color) and placeholder font info (size and color). What is the difference apart from the color?

**Comment by corinnewo** [comment]
[1lists.docx](https://github.com/ji-devs/ji-cloud/files/6298162/1lists.docx)

**Comment by dakom** [comment]
Hmm yeah it seems there isn't much variety and we don't really need a table, just a few basic rules... is this right?

* color is always Dark_Gray_6, placeholder is Dark_Gray_4
* font-family is always Heebo-regular
* size is always 24px, except for Riddles where it's 16px
* height is always 1 row, except for Riddles where it's 2

The header names will be via a lookup, though eventually those will be moved to Localization anyway
