### ISSUE TITLE
Vertical center the "Edit words on cards" in sidebar

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#927]
Ran into some CSS issues with this...  see for example: https://zpl.io/aX6m06p

**Comment by MendyBerger** [comment]
Problem was that two ancestors of `step1-sidebar-empty` didn't take full height so even if it would have taken it's full height it wouldn't be vertically centered .

The two elements are:

1. `module-sidebar-body`.
2. In `module-sidebar` there was an extra wrapper `div.content`, I removed it.

**Comment by dakom** [comment]
I think it's technically fixed since it looks right in the regular modes, but looks incorrect in `Words and Images`, probably due to a problem in the container CSS
