### ISSUE TITLE
Jig Metadata

### ISSUE THREAD

**Issue by dakom** [ji-devs/ji-cloud#967]
Zeplin reference: https://zpl.io/bJoQWOx

Search-related fields:

* name
* description
* language
* age
* goal
* categories

Additional resources are currently being discussed... potential security hazard for us to host user-uploaded files (CC @dani-ji @corinnewo )

**Comment by dakom** [comment]
Note this metadata should comes along for the ride with Browse/Search requests, i.e. it should be part of `https://docs.sandbox.jicloud.org/crate/shared/domain/jig/struct.Jig.html`

**Comment by dani-ji** [comment]
@corinnewo how are new "Teaching Goals" added to the dropdown? Are they fairly static and once created once won't require UI to edit?

**Comment by izik1** [comment]
Closed in #1023
