### ISSUE TITLE
Missing parts from #985

### ISSUE THREAD

**Issue by MendyBerger** [ji-devs/ji-cloud#986]
I added jig gallery in #985 but there are still some missing parts 

- selecting a template doesn't do anything.
- Some metadata in recent is missing, blocked by #967.
- Search not implemented, blocked by #969.
- Styling of "Show all my JIGs" and "search" not fully like spec'd, I'll need to discuss with @dakom.

**Comment by dakom** [comment]
Closing as an all-encompassing issue, specific issues should be re-opened as needed
