### ISSUE TITLE
Settings - Instructions are not saving

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#996]
Written instructions and the recording are not being saved - they play in the preview, but when I go back to settings, they are not there.

**Comment by dakom** [comment]
yes this is a genuine bug... I think a regression from this commit: https://github.com/ji-devs/ji-cloud/commit/17690fea9e8c26aff9eadcd9edaf6cc28fc8fd62

**Comment by dakom** [comment]
I suspect it is saving, but it isn't restoring the save in the editor
