### ISSUE TITLE
When inputting words, the DONE button is below the fold

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#998]
When putting in list of words, the DONE button is right at the bottom, and you have to know to scroll down to the end to continue. This is a usability issue.

 Discussed with Gali, and she suggested:
1. Reduce the number of lines displayed
2. Insert scroll into the line area, instead of along the right hand side of the whole wizard panel.
3. Put the DONE button above the fold, just like the continue is always above the fold on the right hand side.

Currently:
![done button](https://user-images.githubusercontent.com/16290361/116404168-ab401e00-a82e-11eb-9506-7369d2676a61.png)
Suggestion:
![done1 button](https://user-images.githubusercontent.com/16290361/116404349-d75b9f00-a82e-11eb-9bb0-52c47890f700.png)

**Comment by dakom** [comment]
there is no "fold" on the web. it depends on the size of their browser and the cutoff will be different on different screens.

We can put reduce the height and put a scollbar on the text input but there will still be times where the area will be small, in which case there will then be 2 scrollbars and the `Done` button will still be hidden.

**Comment by dani-ji** [comment]
Per Corrine by default 10-11 rows should display with a scroll within the text input; there may still be off cases where this exceeds screen size but should work for most screens

**Comment by dakom** [comment]
Discussed more with @corinnewo, perhaps the button should be at the top or some other solution which definitively works for all screens.

Re-assigning to her and @GaliShapira for further discussion

**Comment by MendyBerger** [comment]
Resolved in e8d17d55b97c83d57978997be0694f5f83e056b4

**Comment by corinnewo** [comment]
I still have to scroll down to see the done button. Please make the list area shorter, with the scroll bar that you have added within the list area. The DONE button must be visible. 

![image](https://user-images.githubusercontent.com/16290361/133003100-3f710a33-8baf-4a88-961c-743b66cdabd4.png)

**Comment by GaliShapira** [comment]
@MendyBerger Hi Mendy, from the screenshot it looks like the horizontal gaps between the wizard to the title "Add your words" , from the title to the keyboards icons, from the keyboards icons to the list are very big, can you compare to the Zeplin specs?
